(define (read-to-eof port)
  (let ((value (read port)))
    (if (eof-object? value) value (read-to-eof port))))

(define eof-port (open-input-file "reader_data.txt"))
(define eof-value (read-to-eof eof-port))

(define pair-value (cons 1 2))
(define string-value (string-append "same"))
(define vector-value (vector 1 2))
(define bytevector-value (bytevector 1 2))
(define procedure-value (lambda (x) x))
(define record-type-value (struct 'record '(value)))
(define record-value (record-type-value 1))
(define port-value (open-input-file "reader_data.txt"))

(define representatives
  (list 1 #t #\a '() eof-value pair-value procedure-value car 'symbol string-value vector-value
        bytevector-value port-value record-type-value record-value))

(define (different-from-all? value rest)
  (if (null? rest)
      #t
      (and (not (eq? value (car rest)))
           (not (eqv? value (car rest)))
           (not (equal? value (car rest)))
           (different-from-all? value (cdr rest)))))

(define (all-types-distinct? values)
  (if (null? values)
      #t
      (and (different-from-all? (car values) (cdr values))
           (all-types-distinct? (cdr values)))))

($check (all-types-distinct? representatives))

($check (eq? 12 12))
($check (eqv? 12 12))
($check (equal? 12 12))
($check (not (eq? 12 13)))
($check (not (eqv? 12 13)))
($check (not (equal? 12 13)))
($check (not (eq? 0 -0)))
($check (eqv? 0 -0))
($check (equal? 0 -0))

($check (eq? #t #t))
($check (eqv? #t #t))
($check (equal? #t #t))
($check (eq? #f #f))
($check (eqv? #f #f))
($check (equal? #f #f))
($check (not (eq? #t #f)))
($check (not (eqv? #t #f)))
($check (not (equal? #t #f)))

($check (eq? #\a #\a))
($check (eqv? #\a #\a))
($check (equal? #\a #\a))
($check (not (eq? #\a #\b)))
($check (not (eqv? #\a #\b)))
($check (not (equal? #\a #\b)))

($check (eq? '() '()))
($check (eqv? '() '()))
($check (equal? '() '()))

($check (eq? eof-value (read eof-port)))
($check (eqv? eof-value (read eof-port)))
($check (equal? eof-value (read eof-port)))

($check (eq? 'same 'same))
($check (eqv? 'same (string->symbol "same")))
($check (equal? 'same (string->symbol "same")))
($check (not (eq? 'same 'different)))
($check (not (eqv? 'same 'different)))
($check (not (equal? 'same 'different)))

(define pair-alias pair-value)
(define equal-pair (cons 1 2))
(define unequal-pair (cons 1 3))
($check (eq? pair-value pair-alias))
($check (eqv? pair-value pair-alias))
($check (equal? pair-value pair-alias))
($check (not (eq? pair-value equal-pair)))
($check (not (eqv? pair-value equal-pair)))
($check (equal? pair-value equal-pair))
($check (not (equal? pair-value unequal-pair)))
($check (not (equal? '(1 2) '(1 2 3))))
($check (not (equal? '(1 2 3) '(1 2))))
($check (equal? '((1 . 2) #(3 "four")) '((1 . 2) #(3 "four"))))
($check (not (equal? '((1 . 2) #(3 "four")) '((1 . 2) #(3 "five")))))

(define string-alias string-value)
(define equal-string (string-append "sa" "me"))
(define unequal-string (string-append "different"))
($check (eq? string-value string-alias))
($check (eqv? string-value string-alias))
($check (equal? string-value string-alias))
($check (not (eq? string-value equal-string)))
($check (not (eqv? string-value equal-string)))
($check (equal? string-value equal-string))
($check (not (equal? string-value unequal-string)))
(define empty-string-1 (string-append ""))
(define empty-string-2 (string-append ""))
($check (not (eq? empty-string-1 empty-string-2)))
($check (not (eqv? empty-string-1 empty-string-2)))
($check (equal? empty-string-1 empty-string-2))

(define vector-alias vector-value)
(define equal-vector (vector 1 2))
(define unequal-vector (vector 1 3))
($check (eq? vector-value vector-alias))
($check (eqv? vector-value vector-alias))
($check (equal? vector-value vector-alias))
($check (not (eq? vector-value equal-vector)))
($check (not (eqv? vector-value equal-vector)))
($check (equal? vector-value equal-vector))
($check (not (equal? vector-value unequal-vector)))
($check (not (equal? (vector 1) (vector 1 2))))
($check (not (equal? (vector 1 2) (vector 1))))
($check (equal? (vector (vector 1) '(2)) (vector (vector 1) '(2))))
($check (not (equal? (vector (vector 1) '(2)) (vector (vector 1) '(3)))))
(define empty-vector-1 (vector))
(define empty-vector-2 (vector))
($check (not (eq? empty-vector-1 empty-vector-2)))
($check (not (eqv? empty-vector-1 empty-vector-2)))
($check (equal? empty-vector-1 empty-vector-2))

(define bytevector-alias bytevector-value)
(define equal-bytevector (bytevector 1 2))
(define unequal-bytevector (bytevector 1 3))
($check (eq? bytevector-value bytevector-alias))
($check (eqv? bytevector-value bytevector-alias))
($check (equal? bytevector-value bytevector-alias))
($check (not (eq? bytevector-value equal-bytevector)))
($check (not (eqv? bytevector-value equal-bytevector)))
($check (equal? bytevector-value equal-bytevector))
($check (not (equal? bytevector-value unequal-bytevector)))
($check (not (equal? (bytevector 1) (bytevector 1 2))))
($check (not (equal? (bytevector 1 2) (bytevector 1))))
(define empty-bytevector-1 (bytevector))
(define empty-bytevector-2 (bytevector))
($check (not (eq? empty-bytevector-1 empty-bytevector-2)))
($check (not (eqv? empty-bytevector-1 empty-bytevector-2)))
($check (equal? empty-bytevector-1 empty-bytevector-2))

(define procedure-alias procedure-value)
($check (eq? procedure-value procedure-alias))
($check (eqv? procedure-value procedure-alias))
($check (equal? procedure-value procedure-alias))

(define (make-reader value)
  (lambda () value))

(define reader-1 (make-reader 1))
(define reader-2 (make-reader 2))
($check (not (eq? reader-1 reader-2)))
($check (not (eqv? reader-1 reader-2)))
($check (not (equal? reader-1 reader-2)))

(define (make-identity)
  (lambda (value) value))

(define identity-1 (make-identity))
(define identity-2 (make-identity))
($check (or (not (eq? identity-1 identity-2)) (eqv? identity-1 identity-2)))
($check (eq? (eqv? identity-1 identity-2) (equal? identity-1 identity-2)))

($check (eq? car car))
($check (eqv? car car))
($check (equal? car car))
($check (not (eq? car cdr)))
($check (not (eqv? car cdr)))
($check (not (equal? car cdr)))

(define record-type-alias record-type-value)
(define other-record-type (struct 'record '(value)))
($check (eq? record-type-value record-type-alias))
($check (eqv? record-type-value record-type-alias))
($check (equal? record-type-value record-type-alias))
($check (not (eq? record-type-value other-record-type)))
($check (not (eqv? record-type-value other-record-type)))
($check (not (equal? record-type-value other-record-type)))

(define record-alias record-value)
(define equal-looking-record (record-type-value 1))
($check (eq? record-value record-alias))
($check (eqv? record-value record-alias))
($check (equal? record-value record-alias))
($check (not (eq? record-value equal-looking-record)))
($check (not (eqv? record-value equal-looking-record)))
($check (not (equal? record-value equal-looking-record)))

(define port-alias port-value)
(define other-port (open-input-file "reader_data.txt"))
($check (eq? port-value port-alias))
($check (eqv? port-value port-alias))
($check (equal? port-value port-alias))
($check (not (eq? port-value other-port)))
($check (not (eqv? port-value other-port)))
($check (not (equal? port-value other-port)))

(define mutable-pair (cons 1 2))
(define mutable-pair-alias mutable-pair)
(define pair-before-mutation (cons 1 2))
($check (equal? mutable-pair pair-before-mutation))
(set-car! mutable-pair 3)
($check (eq? mutable-pair mutable-pair-alias))
($check (eqv? mutable-pair mutable-pair-alias))
($check (equal? mutable-pair mutable-pair-alias))
($check (not (equal? mutable-pair pair-before-mutation)))

(define mutable-string (string-append "ab"))
(define mutable-string-alias mutable-string)
(define string-before-mutation (string-append "ab"))
($check (equal? mutable-string string-before-mutation))
(string-set! mutable-string 0 #\z)
($check (eq? mutable-string mutable-string-alias))
($check (eqv? mutable-string mutable-string-alias))
($check (equal? mutable-string mutable-string-alias))
($check (not (equal? mutable-string string-before-mutation)))

(define mutable-vector (vector 1 2))
(define mutable-vector-alias mutable-vector)
(define vector-before-mutation (vector 1 2))
($check (equal? mutable-vector vector-before-mutation))
(vector-set! mutable-vector 0 3)
($check (eq? mutable-vector mutable-vector-alias))
($check (eqv? mutable-vector mutable-vector-alias))
($check (equal? mutable-vector mutable-vector-alias))
($check (not (equal? mutable-vector vector-before-mutation)))

(define mutable-bytevector (bytevector 1 2))
(define mutable-bytevector-alias mutable-bytevector)
(define bytevector-before-mutation (bytevector 1 2))
($check (equal? mutable-bytevector bytevector-before-mutation))
(bytevector-u8-set! mutable-bytevector 0 3)
($check (eq? mutable-bytevector mutable-bytevector-alias))
($check (eqv? mutable-bytevector mutable-bytevector-alias))
($check (equal? mutable-bytevector mutable-bytevector-alias))
($check (not (equal? mutable-bytevector bytevector-before-mutation)))

(define law-values
  (list 0 -0 1 #t #f #\a #\b '() eof-value 'same 'different pair-value pair-alias equal-pair
        string-value string-alias equal-string vector-value vector-alias equal-vector bytevector-value
        bytevector-alias equal-bytevector procedure-value procedure-alias reader-1 reader-2 identity-1
        identity-2 car cdr record-type-value record-type-alias other-record-type record-value record-alias
        equal-looking-record port-value port-alias other-port))

(define (predicate-laws-for-pair? a b)
  (and (eq? (eq? a b) (eq? b a))
       (eq? (eqv? a b) (eqv? b a))
       (eq? (equal? a b) (equal? b a))
       (or (not (eq? a b)) (eqv? a b))
       (or (not (eqv? a b)) (equal? a b))))

(define (predicate-laws-against? value values)
  (if (null? values)
      #t
      (and (predicate-laws-for-pair? value (car values))
           (predicate-laws-against? value (cdr values)))))

(define (predicate-laws? values)
  (if (null? values)
      #t
      (and (eq? (car values) (car values))
           (eqv? (car values) (car values))
           (equal? (car values) (car values))
           (predicate-laws-against? (car values) law-values)
           (predicate-laws? (cdr values)))))

(define (transitive-with-third? predicate a b values)
  (if (null? values)
      #t
      (and (or (not (and (predicate a b) (predicate b (car values))))
               (predicate a (car values)))
           (transitive-with-third? predicate a b (cdr values)))))

(define (transitive-with-second? predicate value values)
  (if (null? values)
      #t
      (and (transitive-with-third? predicate value (car values) law-values)
           (transitive-with-second? predicate value (cdr values)))))

(define (transitive? predicate values)
  (if (null? values)
      #t
      (and (transitive-with-second? predicate (car values) law-values)
           (transitive? predicate (cdr values)))))

($check (predicate-laws? law-values))
($check (transitive? eq? law-values))
($check (transitive? eqv? law-values))
($check (transitive? equal? law-values))

(close-input-port eof-port)
(close-input-port port-value)
(close-input-port other-port)
