(define cursor (%iter (vector 10 20 30)))
($check (= 10 (%iter-next! cursor (value) value)))
($check (= 21 (%iter-next! cursor (value) (+ value 1))))
($check (= 30 (%iter-next! cursor (value) value 'exhausted)))
($check (eq? 'exhausted (%iter-next! cursor (value) value 'exhausted)))
(%iter-next! (%iter (vector)) (value) value)

($check (= 33 (%iter-next! (%iter (vector 33)) (value) value)))

(define (cursor-first cursor)
  (%iter-next! cursor (value) value 'empty))
($check (= 34 (cursor-first (%iter (vector 34)))))
($check (eq? 'empty (cursor-first (%iter (vector)))))

(define growing-vector (vector 1 2))
(define growing-cursor (%iter growing-vector))
($check (= 1 (%iter-next! growing-cursor (value) value)))
(vector-push! growing-vector 3)
($check (= 2 (%iter-next! growing-cursor (value) value)))
($check (= 3 (%iter-next! growing-cursor (value) value)))
($check (eq? 'done (%iter-next! growing-cursor (value) value 'done)))

(define replaced-vector (vector 10 20))
(define replaced-cursor (%iter replaced-vector))
($check (= 10 (%iter-next! replaced-cursor (value) value)))
(setf! replaced-vector 1 21)
($check (= 21 (%iter-next! replaced-cursor (value) value)))

(define removed-visited-vector (vector 30 40 50))
(define removed-visited-cursor (%iter removed-visited-vector))
($check (= 30 (%iter-next! removed-visited-cursor (value) value)))
($check (= 30 (vector-pop-first! removed-visited-vector)))
($check (= 40 (%iter-next! removed-visited-cursor (value) value)))

(define removed-next-vector (vector 60 70))
(define removed-next-cursor (%iter removed-next-vector))
($check (= 60 (%iter-next! removed-next-cursor (value) value)))
($check (= 70 (vector-pop! removed-next-vector)))
($check (eq? 'done (%iter-next! removed-next-cursor (value) value 'done)))

(define replaced-tail-vector (vector 80))
(define replaced-tail-cursor (%iter replaced-tail-vector))
($check (= 80 (%iter-next! replaced-tail-cursor (value) value)))
($check (= 80 (vector-pop! replaced-tail-vector)))
(vector-push! replaced-tail-vector 81)
($check (= 81 (%iter-next! replaced-tail-cursor (value) value)))

(define shared-vector (vector 90 100 110))
(define shared-cursor-a (%iter shared-vector))
(define shared-cursor-b (%iter shared-vector))
($check (= 90 (%iter-next! shared-cursor-a (value) value)))
(vector-pop-first! shared-vector)
($check (= 100 (%iter-next! shared-cursor-a (value) value)))
($check (= 100 (%iter-next! shared-cursor-b (value) value)))
($check (= 110 (%iter-next! shared-cursor-a (value) value)))
($check (eq? 'done (%iter-next! shared-cursor-a (value) value 'done)))
($check (= 110 (%iter-next! shared-cursor-b (value) value)))
($check (eq? 'done (%iter-next! shared-cursor-b (value) value 'done)))

(define equal-cursor-target (vector 1 2))
(define equal-cursor-a (%iter equal-cursor-target))
(define equal-cursor-b (%iter equal-cursor-target))
(define equal-cursor-other (%iter (vector 1 2)))
($check (equal? equal-cursor-a equal-cursor-b))
($check (not (equal? equal-cursor-a equal-cursor-other)))
(%iter-next! equal-cursor-a (value) value)
($check (not (equal? equal-cursor-a equal-cursor-b)))
(%iter-next! equal-cursor-b (value) value)
($check (equal? equal-cursor-a equal-cursor-b))
(%iter-next! equal-cursor-a (value) value)
(%iter-next! equal-cursor-b (value) value)
($check (equal? equal-cursor-a equal-cursor-b))
($check (eq? 'done (%iter-next! equal-cursor-a (value) value 'done)))
($check (not (equal? equal-cursor-a equal-cursor-b)))
($check (eq? 'done (%iter-next! equal-cursor-b (value) value 'done)))
($check (equal? equal-cursor-a equal-cursor-b))

(define outer 'outer)
(define scope-cursor (%iter (vector 'inner)))
($check (eq? 'inner (%iter-next! scope-cursor (outer) outer)))
($check (eq? 'outer outer))
($check (eq? 'outer (%iter-next! (%iter (vector)) (outer) outer outer)))

(define (capture-values values)
  (let ((cursor (%iter values)))
    (let loop ((result '()))
      (%iter-next! cursor (value)
        (loop (cons (lambda () value) result))
        result))))
(define captured-values (capture-values (vector 1 2 3)))
($check (= 3 ((first captured-values))))
($check (= 2 ((second captured-values))))
($check (= 1 ((third captured-values))))

(define capture-cursor (%iter (vector 40 50)))
(define captured (%iter-next! capture-cursor (value) (lambda () value)))
($check (= 40 (captured)))
(define mutated
  (%iter-next! capture-cursor (value)
    (begin
      (set! value (+ value 1))
      (lambda () value))))
($check (= 51 (mutated)))

(define (sum-cursor cursor total)
  (%iter-next! cursor (value)
    (sum-cursor cursor (+ total value))
    total))
($check (= 15 (sum-cursor (%iter (vector 1 2 3 4 5)) 0)))

(define outer-cursor (%iter (vector 1 2)))
(define inner-cursor (%iter (vector 10 20)))
($check
  (= 11
     (%iter-next! outer-cursor (outer-value)
       (%iter-next! inner-cursor (inner-value)
         (+ outer-value inner-value)))))

(define retained-cursor (%iter (vector 42)))
(let loop ((i 0))
  (if (< i 10000)
      (begin
        (vector i i i i i i i i)
        (loop (+ i 1)))))
($check (= 42 (%iter-next! retained-cursor (value) value)))
