(define cursor (%iter (vector 10 20 30)))
($check (= 10 (%if/next! ((value) cursor) value)))
($check (= 21 (%if/next! ((value) cursor) (+ value 1))))
($check (= 30 (%if/next! ((value) cursor) value 'exhausted)))
($check (eq? 'exhausted (%if/next! ((value) cursor) value 'exhausted)))
(%if/next! ((value) (%iter (vector))) value)

($check (= 33 (%if/next! ((value) (%iter (vector 33))) value)))

(define (cursor-first cursor)
  (%if/next! ((value) cursor) value 'empty))
($check (= 34 (cursor-first (%iter (vector 34)))))
($check (eq? 'empty (cursor-first (%iter (vector)))))

(define growing-vector (vector 1 2))
(define growing-cursor (%iter growing-vector))
($check (= 1 (%if/next! ((value) growing-cursor) value)))
(vector-push! growing-vector 3)
($check (= 2 (%if/next! ((value) growing-cursor) value)))
($check (= 3 (%if/next! ((value) growing-cursor) value)))
($check (eq? 'done (%if/next! ((value) growing-cursor) value 'done)))

(define replaced-vector (vector 10 20))
(define replaced-cursor (%iter replaced-vector))
($check (= 10 (%if/next! ((value) replaced-cursor) value)))
(setf! replaced-vector 1 21)
($check (= 21 (%if/next! ((value) replaced-cursor) value)))

(define removed-visited-vector (vector 30 40 50))
(define removed-visited-cursor (%iter removed-visited-vector))
($check (= 30 (%if/next! ((value) removed-visited-cursor) value)))
($check (= 30 (vector-pop-first! removed-visited-vector)))
($check (= 40 (%if/next! ((value) removed-visited-cursor) value)))

(define removed-next-vector (vector 60 70))
(define removed-next-cursor (%iter removed-next-vector))
($check (= 60 (%if/next! ((value) removed-next-cursor) value)))
($check (= 70 (vector-pop! removed-next-vector)))
($check (eq? 'done (%if/next! ((value) removed-next-cursor) value 'done)))

(define replaced-tail-vector (vector 80))
(define replaced-tail-cursor (%iter replaced-tail-vector))
($check (= 80 (%if/next! ((value) replaced-tail-cursor) value)))
($check (= 80 (vector-pop! replaced-tail-vector)))
(vector-push! replaced-tail-vector 81)
($check (= 81 (%if/next! ((value) replaced-tail-cursor) value)))

(define shared-vector (vector 90 100 110))
(define shared-cursor-a (%iter shared-vector))
(define shared-cursor-b (%iter shared-vector))
($check (= 90 (%if/next! ((value) shared-cursor-a) value)))
(vector-pop-first! shared-vector)
($check (= 100 (%if/next! ((value) shared-cursor-a) value)))
($check (= 100 (%if/next! ((value) shared-cursor-b) value)))
($check (= 110 (%if/next! ((value) shared-cursor-a) value)))
($check (eq? 'done (%if/next! ((value) shared-cursor-a) value 'done)))
($check (= 110 (%if/next! ((value) shared-cursor-b) value)))
($check (eq? 'done (%if/next! ((value) shared-cursor-b) value 'done)))

(define equal-cursor-target (vector 1 2))
(define equal-cursor-a (%iter equal-cursor-target))
(define equal-cursor-b (%iter equal-cursor-target))
(define equal-cursor-other (%iter (vector 1 2)))
($check (equal? equal-cursor-a equal-cursor-b))
($check (not (equal? equal-cursor-a equal-cursor-other)))
(%if/next! ((value) equal-cursor-a) value)
($check (not (equal? equal-cursor-a equal-cursor-b)))
(%if/next! ((value) equal-cursor-b) value)
($check (equal? equal-cursor-a equal-cursor-b))
(%if/next! ((value) equal-cursor-a) value)
(%if/next! ((value) equal-cursor-b) value)
($check (equal? equal-cursor-a equal-cursor-b))
($check (eq? 'done (%if/next! ((value) equal-cursor-a) value 'done)))
($check (not (equal? equal-cursor-a equal-cursor-b)))
($check (eq? 'done (%if/next! ((value) equal-cursor-b) value 'done)))
($check (equal? equal-cursor-a equal-cursor-b))

(define outer 'outer)
(define scope-cursor (%iter (vector 'inner)))
($check (eq? 'inner (%if/next! ((outer) scope-cursor) outer)))
($check (eq? 'outer outer))
($check (eq? 'outer (%if/next! ((outer) (%iter (vector))) outer outer)))

(define (capture-values values)
  (let ((cursor (%iter values)))
    (let loop ((result '()))
      (%if/next! ((value) cursor) (loop (cons (lambda () value) result)) result))))
(define captured-values (capture-values (vector 1 2 3)))
($check (= 3 ((first captured-values))))
($check (= 2 ((second captured-values))))
($check (= 1 ((third captured-values))))

(define capture-cursor (%iter (vector 40 50)))
(define captured (%if/next! ((value) capture-cursor) (lambda () value)))
($check (= 40 (captured)))
(define mutated
  (%if/next! ((value) capture-cursor) (begin
      (set! value (+ value 1))
      (lambda () value))))
($check (= 51 (mutated)))

(define (sum-cursor cursor total)
  (%if/next! ((value) cursor) (sum-cursor cursor (+ total value)) total))
($check (= 15 (sum-cursor (%iter (vector 1 2 3 4 5)) 0)))

(define outer-cursor (%iter (vector 1 2)))
(define inner-cursor (%iter (vector 10 20)))
($check
  (= 11
     (%if/next! ((outer-value) outer-cursor) (%if/next! ((inner-value) inner-cursor) (+ outer-value inner-value)))))

(define retained-cursor (%iter (vector 42)))
(let loop ((i 0))
  (if (< i 10000)
      (begin
        (vector i i i i i i i i)
        (loop (+ i 1)))))
($check (= 42 (%if/next! ((value) retained-cursor) value)))

(define (cursor-entries cursor)
  (%if/next! ((key value) cursor) (cons (cons key value) (cursor-entries cursor)) '()))
(define (entry-value entries key)
  (cdr (assoc key entries)))

(define empty-map-cursor (%iter (hashmap)))
($check (null? (cursor-entries empty-map-cursor)))
(define one-map-entries (cursor-entries (%iter (hashmap 'one 1))))
($check (= 1 (length one-map-entries)))
($check (= 1 (entry-value one-map-entries 'one)))
(define many-map-entries (cursor-entries (%iter (hashmap 'a 1 'b 2 'c 3))))
($check (= 3 (length many-map-entries)))
($check (= 1 (entry-value many-map-entries 'a)))
($check (= 2 (entry-value many-map-entries 'b)))
($check (= 3 (entry-value many-map-entries 'c)))

(define inserted-before-map (hashmap 'a 1))
(define inserted-before-cursor (%iter inserted-before-map))
(setf! inserted-before-map 'b 2)
(define inserted-before-entries (cursor-entries inserted-before-cursor))
($check (= 2 (length inserted-before-entries)))
($check (= 1 (entry-value inserted-before-entries 'a)))
($check (= 2 (entry-value inserted-before-entries 'b)))

(define inserted-between-map (hashmap 'a 1))
(define inserted-between-cursor (%iter inserted-between-map))
($check (= 1 (%if/next! ((key value) inserted-between-cursor) value)))
(setf! inserted-between-map 'b 2)
($check (= 2 (%if/next! ((key value) inserted-between-cursor) value)))
($check (eq? 'done (%if/next! ((key value) inserted-between-cursor) value 'done)))

(define replaced-before-map (hashmap 'a 1))
(define replaced-before-cursor (%iter replaced-before-map))
(setf! replaced-before-map 'a 2)
($check (= 2 (%if/next! ((key value) replaced-before-cursor) value)))
(define replaced-after-map (hashmap 'a 3))
(define replaced-after-cursor (%iter replaced-after-map))
($check (= 3 (%if/next! ((key value) replaced-after-cursor) value)))
(setf! replaced-after-map 'a 4)
($check (eq? 'done (%if/next! ((key value) replaced-after-cursor) value 'done)))

(define removed-before-map (hashmap 'a 1))
(define removed-before-cursor (%iter removed-before-map))
(hashmap-unset! removed-before-map 'a)
($check (eq? 'done (%if/next! ((key value) removed-before-cursor) value 'done)))
(hashmap-unset! removed-before-map 'missing)
(define removed-after-map (hashmap 'a 1))
(define removed-after-cursor (%iter removed-after-map))
($check (= 1 (%if/next! ((key value) removed-after-cursor) value)))
(hashmap-unset! removed-after-map 'a)
($check (eq? 'done (%if/next! ((key value) removed-after-cursor) value 'done)))

(define reinserted-map (hashmap 'a 1))
(define reinserted-cursor (%iter reinserted-map))
($check (= 1 (%if/next! ((key value) reinserted-cursor) value)))
(hashmap-unset! reinserted-map 'a)
(setf! reinserted-map 'a 2)
($check (= 2 (%if/next! ((key value) reinserted-cursor) value)))
($check (eq? 'done (%if/next! ((key value) reinserted-cursor) value 'done)))

(define shared-map (hashmap 'a 1))
(define shared-map-cursor-a (%iter shared-map))
(define shared-map-cursor-b (%iter shared-map))
($check (= 1 (%if/next! ((key value) shared-map-cursor-a) value)))
(setf! shared-map 'b 2)
(setf! shared-map 'c 3)
(hashmap-unset! shared-map 'b)
(define shared-map-rest-a (cursor-entries shared-map-cursor-a))
(define shared-map-rest-b (cursor-entries shared-map-cursor-b))
($check (= 1 (length shared-map-rest-a)))
($check (= 3 (entry-value shared-map-rest-a 'c)))
($check (= 2 (length shared-map-rest-b)))
($check (= 1 (entry-value shared-map-rest-b 'a)))
($check (= 3 (entry-value shared-map-rest-b 'c)))

(define tombstone-map (hashmap))
(let loop ((i 0))
  (if (< i 130)
      (begin
        (setf! tombstone-map i (* i 2))
        (loop (+ i 1)))))
(hashmap-unset! tombstone-map 0)
(hashmap-unset! tombstone-map 64)
(hashmap-unset! tombstone-map 129)
(define tombstone-entries (cursor-entries (%iter tombstone-map)))
($check (= 127 (length tombstone-entries)))
($check (not (assoc 0 tombstone-entries)))
($check (not (assoc 64 tombstone-entries)))
($check (not (assoc 129 tombstone-entries)))
($check (= 126 (entry-value tombstone-entries 63)))
($check (= 130 (entry-value tombstone-entries 65)))

(define wrapped-map (hashmap))
(let loop ((i 0))
  (if (< i 128)
      (begin
        (setf! wrapped-map i i)
        (loop (+ i 1)))))
(let loop ((i 0))
  (if (< i 96)
      (begin
        (hashmap-unset! wrapped-map i)
        (loop (+ i 1)))))
(hashmap-unset! wrapped-map 127)
(let loop ((i 128))
  (if (< i 400)
      (begin
        (setf! wrapped-map i i)
        (loop (+ i 1)))))
(define wrapped-entries (cursor-entries (%iter wrapped-map)))
($check (= 303 (length wrapped-entries)))
($check (= 96 (entry-value wrapped-entries 96)))
($check (= 126 (entry-value wrapped-entries 126)))
($check (= 128 (entry-value wrapped-entries 128)))
($check (= 399 (entry-value wrapped-entries 399)))
($check (not (assoc 95 wrapped-entries)))
($check (not (assoc 127 wrapped-entries)))

(define rehashed-map (hashmap 0 0))
(define rehashed-cursor (%iter rehashed-map))
($check (= 0 (%if/next! ((key value) rehashed-cursor) value)))
(let loop ((i 1))
  (if (< i 1000)
      (begin
        (setf! rehashed-map i (* i i))
        (loop (+ i 1)))))
(define rehashed-entries (cursor-entries rehashed-cursor))
($check (= 999 (length rehashed-entries)))
($check (= (* 999 999) (entry-value rehashed-entries 999)))

(define retained-map-cursor
  (let ((map (hashmap (tuple 'key) (vector 7 8 9))))
    (%iter map)))
(let loop ((i 0))
  (if (< i 10000)
      (begin
        (vector i i i i i i i i)
        (loop (+ i 1)))))
($check
  (equal? (list (tuple 'key) (vector 7 8 9))
          (%if/next! ((key value) retained-map-cursor) (list key value))))

(define cursor-gc-map (hashmap 'alive 1))
(define cursor-gc-retained
  (let ((discarded (%iter cursor-gc-map)))
    (%iter cursor-gc-map)))
(let loop ((i 0))
  (if (< i 10000)
      (begin
        (vector i i i i i i i i)
        (loop (+ i 1)))))
($check (= 1 (%if/next! ((key value) cursor-gc-retained) value)))

(define equal-map-target (hashmap 'a 1))
(define equal-map-cursor-a (%iter equal-map-target))
(define equal-map-cursor-b (%iter equal-map-target))
($check (equal? equal-map-cursor-a equal-map-cursor-b))
(%if/next! ((key value) equal-map-cursor-a) value)
($check (not (equal? equal-map-cursor-a equal-map-cursor-b)))
(%if/next! ((key value) equal-map-cursor-b) value)
($check (equal? equal-map-cursor-a equal-map-cursor-b))
($check (eq? 'done (%if/next! ((key value) equal-map-cursor-a) value 'done)))
($check (not (equal? equal-map-cursor-a equal-map-cursor-b)))
($check (eq? 'done (%if/next! ((key value) equal-map-cursor-b) value 'done)))
($check (equal? equal-map-cursor-a equal-map-cursor-b))

(define (cursor-values cursor)
  (%if/next! ((value) cursor) (cons value (cursor-values cursor)) '()))

(define (values-hashset values)
  (let ((set (hashset)))
    (let add ((values values))
      (if (null? values)
          set
          (begin
            (setf! set (car values) #t)
            (add (cdr values)))))))

($check (null? (cursor-values (%iter (hashset)))))
(define one-set-values (cursor-values (%iter (hashset 'one))))
($check (= 1 (length one-set-values)))
($check (equal? (hashset 'one) (values-hashset one-set-values)))
(define many-set-values (cursor-values (%iter (hashset 'a 'b 'c))))
($check (= 3 (length many-set-values)))
($check (equal? (hashset 'a 'b 'c) (values-hashset many-set-values)))

(define inserted-before-set (hashset 'a))
(define inserted-before-set-cursor (%iter inserted-before-set))
(setf! inserted-before-set 'b #t)
(define inserted-before-values (cursor-values inserted-before-set-cursor))
($check (= 2 (length inserted-before-values)))
($check (equal? inserted-before-set (values-hashset inserted-before-values)))

(define inserted-between-set (hashset 'a))
(define inserted-between-set-cursor (%iter inserted-between-set))
($check (eq? 'a (%if/next! ((value) inserted-between-set-cursor) value)))
(setf! inserted-between-set 'b #t)
($check (eq? 'b (%if/next! ((value) inserted-between-set-cursor) value)))
($check (eq? 'done (%if/next! ((value) inserted-between-set-cursor) value 'done)))

(define duplicate-set (hashset 'a))
(define duplicate-set-cursor (%iter duplicate-set))
(setf! duplicate-set 'a #t)
($check (eq? 'a (%if/next! ((value) duplicate-set-cursor) value)))
(setf! duplicate-set 'a #t)
($check (eq? 'done (%if/next! ((value) duplicate-set-cursor) value 'done)))

(define removed-before-set (hashset 'a))
(define removed-before-set-cursor (%iter removed-before-set))
(hashset-unset! removed-before-set 'a)
($check (eq? 'done (%if/next! ((value) removed-before-set-cursor) value 'done)))
(hashset-unset! removed-before-set 'missing)
(define removed-after-set (hashset 'a))
(define removed-after-set-cursor (%iter removed-after-set))
($check (eq? 'a (%if/next! ((value) removed-after-set-cursor) value)))
(hashset-unset! removed-after-set 'a)
($check (eq? 'done (%if/next! ((value) removed-after-set-cursor) value 'done)))

(define reinserted-set (hashset 'a))
(define reinserted-set-cursor (%iter reinserted-set))
($check (eq? 'a (%if/next! ((value) reinserted-set-cursor) value)))
(hashset-unset! reinserted-set 'a)
(setf! reinserted-set 'a #t)
($check (eq? 'a (%if/next! ((value) reinserted-set-cursor) value)))
($check (eq? 'done (%if/next! ((value) reinserted-set-cursor) value 'done)))

(define shared-set (hashset 'a))
(define shared-set-cursor-a (%iter shared-set))
(define shared-set-cursor-b (%iter shared-set))
($check (eq? 'a (%if/next! ((value) shared-set-cursor-a) value)))
(setf! shared-set 'b #t)
(setf! shared-set 'c #t)
(hashset-unset! shared-set 'b)
(define shared-set-rest-a (cursor-values shared-set-cursor-a))
(define shared-set-rest-b (cursor-values shared-set-cursor-b))
($check (= 1 (length shared-set-rest-a)))
($check (eq? 'c (car shared-set-rest-a)))
($check (= 2 (length shared-set-rest-b)))
($check (ref shared-set (car shared-set-rest-b)))
($check (ref shared-set (car (cdr shared-set-rest-b))))

(define tombstone-set (hashset))
(let loop ((i 0))
  (if (< i 130)
      (begin
        (setf! tombstone-set i #t)
        (loop (+ i 1)))))
(hashset-unset! tombstone-set 0)
(hashset-unset! tombstone-set 64)
(hashset-unset! tombstone-set 129)
(define tombstone-values (cursor-values (%iter tombstone-set)))
($check (= 127 (length tombstone-values)))
($check (not (ref tombstone-set 0)))
($check (not (ref tombstone-set 64)))
($check (not (ref tombstone-set 129)))
($check (ref tombstone-set 63))
($check (ref tombstone-set 65))

(define wrapped-set (hashset))
(let loop ((i 0))
  (if (< i 128)
      (begin
        (setf! wrapped-set i #t)
        (loop (+ i 1)))))
(let loop ((i 0))
  (if (< i 96)
      (begin
        (hashset-unset! wrapped-set i)
        (loop (+ i 1)))))
(hashset-unset! wrapped-set 127)
(let loop ((i 128))
  (if (< i 400)
      (begin
        (setf! wrapped-set i #t)
        (loop (+ i 1)))))
(define wrapped-values (cursor-values (%iter wrapped-set)))
($check (= 303 (length wrapped-values)))
($check (ref wrapped-set 96))
($check (ref wrapped-set 126))
($check (ref wrapped-set 128))
($check (ref wrapped-set 399))
($check (not (ref wrapped-set 95)))
($check (not (ref wrapped-set 127)))

(define rehashed-set (hashset 0))
(define rehashed-set-cursor (%iter rehashed-set))
($check (= 0 (%if/next! ((value) rehashed-set-cursor) value)))
(let loop ((i 1))
  (if (< i 1000)
      (begin
        (setf! rehashed-set i #t)
        (loop (+ i 1)))))
(define rehashed-values (cursor-values rehashed-set-cursor))
($check (= 999 (length rehashed-values)))
($check (ref rehashed-set 999))

(define retained-set-cursor
  (let ((set (hashset (tuple 'key (tuple "nested" 7)))))
    (%iter set)))
(let loop ((i 0))
  (if (< i 10000)
      (begin
        (vector i i i i i i i i)
        (loop (+ i 1)))))
($check (equal? (tuple 'key (tuple "nested" 7))
                (%if/next! ((value) retained-set-cursor) value)))

(define cursor-gc-set (hashset 'alive))
(define cursor-gc-set-retained
  (let ((discarded (%iter cursor-gc-set)))
    (%iter cursor-gc-set)))
(let loop ((i 0))
  (if (< i 10000)
      (begin
        (vector i i i i i i i i)
        (loop (+ i 1)))))
($check (eq? 'alive (%if/next! ((value) cursor-gc-set-retained) value)))

(define equal-set-target (hashset 'a))
(define equal-set-cursor-a (%iter equal-set-target))
(define equal-set-cursor-b (%iter equal-set-target))
($check (equal? equal-set-cursor-a equal-set-cursor-b))
(%if/next! ((value) equal-set-cursor-a) value)
($check (not (equal? equal-set-cursor-a equal-set-cursor-b)))
(%if/next! ((value) equal-set-cursor-b) value)
($check (equal? equal-set-cursor-a equal-set-cursor-b))
($check (eq? 'done (%if/next! ((value) equal-set-cursor-a) value 'done)))
($check (not (equal? equal-set-cursor-a equal-set-cursor-b)))
($check (eq? 'done (%if/next! ((value) equal-set-cursor-b) value 'done)))
($check (equal? equal-set-cursor-a equal-set-cursor-b))

;;; generic iteration surface: `%iter`, `%if/next!`, two-output protocol, `coro/next`

($check (= 10 (%if/next! ((v) (%iter (vector 10 20))) v 'none)))

(define public-vector-cursor (%iter (vector 5 6)))
($check (= 5 (%if/next! ((v) public-vector-cursor) v)))
($check (= 6 (%if/next! ((v) public-vector-cursor) v)))
($check (eq? 'done (%if/next! ((v) public-vector-cursor) v 'done)))

(define shared-step-cursor (%iter (vector 1 2)))
($check (= 1 (%if/next! ((v) shared-step-cursor) v)))
($check (= 2 (%if/next! ((v) shared-step-cursor) v)))

(define vector-pairs (%iter (vector 10 20 30)))
($check (equal? (cons 0 10) (%if/next! ((k v) vector-pairs) (cons k v))))
($check (equal? (cons 1 20) (%if/next! ((k v) vector-pairs) (cons k v))))
($check (equal? (cons 2 30) (%if/next! ((k v) vector-pairs) (cons k v))))
($check (eq? 'done (%if/next! ((k v) vector-pairs) (cons k v) 'done)))

(define set-pairs (%iter (hashset 'only)))
($check (%if/next! ((k v) set-pairs) (and (eq? k 'only) (eq? v 'only)) #f))
($check (eq? 'done (%if/next! ((k v) set-pairs) v 'done)))

(define map-values (%iter (hashmap 'a 7)))
($check (= 7 (%if/next! ((v) map-values) v)))
($check (eq? 'done (%if/next! ((v) map-values) v 'done)))

(define map-pairs (%iter (hashmap 'a 7)))
($check (equal? (cons 'a 7) (%if/next! ((k v) map-pairs) (cons k v))))
($check (eq? 'done (%if/next! ((k v) map-pairs) (cons k v) 'done)))

(define coro-one (let/coro yield () (yield 1) (yield 2) 3))
($check (= 1 (%if/next! ((v) coro-one) v)))
($check (= 2 (%if/next! ((v) coro-one) v)))
($check (= 3 (%if/next! ((v) coro-one) v)))
($check (eq? 'done (%if/next! ((v) coro-one) v 'done)))

(define coro-two (let/coro yield () (yield 10) 20))
($check (= 10 (%if/next! ((k v) coro-two) v)))
($check (= 20 (%if/next! ((k v) coro-two) v)))
($check (eq? 'done (%if/next! ((k v) coro-two) v 'done)))

(define coro-next-target (let/coro yield () (yield 1) (yield 2) 3))
($check (= 1 (coro/next coro-next-target 'done)))
($check (= 2 (coro/next coro-next-target 'done)))
($check (= 3 (coro/next coro-next-target 'done)))
($check (eq? 'done (coro/next coro-next-target 'done)))
