#!/bin/sh

file=$1
shift
JET=${JET:-../build/jet}

if [ -z "$JET_TEST_DIAGNOSTICS" ]
then
    "$JET" run $file $@ > /dev/null 2>&1
    exit $?
fi

diagnostics=$("$JET" run $file $@ 2>&1 > /dev/null)
status=$?
if [ -n "$diagnostics" ]
then
    printf '%s\n' "$diagnostics" >&2
fi
case $diagnostics in
    *Sanitizer*) exit 1 ;;
esac
exit $status
