(define plus-requested (option "--plus" #f))
(define plus-available
  (if (eq? demo-action 'play) (= (ref demo-data 5) 1) plus-requested))
(define plus-enabled plus-available)
(define plus-key #f)

(define plus-turn-speed (option "--turn-speed" 62.5))
(define plus-walk-speed (option "--walk-speed" 52.5))

(define PLUS_LIGHT_RADIUS 6)
(define PLUS_LIGHT_LEVELS 8)
(define PLUS_CHANDELIER_LEVELS 9)
(define PLUS_LIGHT_STEP 16)
(define PLUS_AMBIENT_DEPTH 96)
(define PLUS_DISTANCE_DEPTH 32)
(define PLUS_LEVEL_MIN -64)
(define PLUS_LEVEL_MAX 240)
(define PLUS_LEVEL_COUNT (+ 1 (- PLUS_LEVEL_MAX PLUS_LEVEL_MIN)))
(define PLUS_SHADE_STEP 4)
(define PLUS_SHADE_COUNT (+ 1 (/ (- PLUS_LEVEL_COUNT 1) PLUS_SHADE_STEP)))
(define PLUS_EMISSIVE_LUMA 48)
(define PLUS_FLASH_LEVELS 32)
(define PLUS_FLASH_TICS 8)
(define PLUS_FLASH_COUNT 4)
(define PLUS_AO_WIDTH (/ TILEGLOBAL 40))
(define PLUS_AO_STEP 4)
(define PLUS_DITHER_CONTRAST 0.25)
(define PLUS_CORNER_DEPTH 3)
(define PLUS_AO_DEPTHS (vector 0 1 PLUS_CORNER_DEPTH))
(define plus-ao-shades #f)
(define plus-corner-shades #f)
(define plus-palette-slots #(5 80 81 82 83 84 85 86 87 166 167 168 169 170 176 177 178 181 255))
(define PLUS_SHADOW_DEPTH 48)

(define plus-boundaries (make-vector (vector-length wallheight) 0))
(define plus-planex (make-vector (vector-length wallheight) 0))
(define plus-planey (make-vector (vector-length wallheight) 0))
(define plus-shades
  (let ((identity (make-bytevector 256 0)))
    (let colors ((color 0))
      (when (< color 256)
        (setf! identity color color)
        (colors (+ color 1))))
    (make-vector PLUS_SHADE_COUNT identity)))
(define plus-emissive (make-bytevector 256 0))
(define plus-luma (make-bytevector 256 0))
(define plus-sprites (make-vector 0 #f))
(define plus-feet (make-vector 0 #f))
(define plus-mounts (make-vector (+ SPR_STAT_0 19) #f))
(define plus-lightmap (make-vector (* MAPSIZE MAPSIZE) 0))
(define plus-light-base (make-vector (* MAPSIZE MAPSIZE) 0))
(define plus-light-paths (make-vector (* MAPSIZE MAPSIZE) '()))
(define plus-light-watch (make-vector MAXDOORS '()))
(define plus-light-positions (make-vector MAXDOORS -1))
(define plus-light-dirty (make-bytevector (* MAPSIZE MAPSIZE) 0))
(define plus-light-queue (make-vector (* MAPSIZE MAPSIZE) 0))
(define plus-light-count 0)
(define plus-light-samples (make-vector 4 0))
(define plus-light-cells (make-vector (* MAPSIZE MAPSIZE 4) 0))
; Cell bits run left to right, then top to bottom.
(define plus-light-masks (make-bytevector (* MAPSIZE MAPSIZE) 0))
(define plus-flashmaps
  (let ((maps (make-vector PLUS_FLASH_COUNT #f)))
    (let slots ((slot 0))
      (when (< slot PLUS_FLASH_COUNT)
        (setf! maps slot (make-bytevector (* MAPSIZE MAPSIZE) 0))
        (slots (+ slot 1))))
    maps))
(define plus-neighbors #(#(-1 0) #(1 0) #(0 -1) #(0 1)))
(define plus-flash-starts (make-vector PLUS_FLASH_COUNT -1))
(define plus-flash-next 0)
(define plus-flash-time #f)
(define plus-flash-active #f)
(define plus-flash-epoch 0)
(define plus-flash-remaining (make-vector PLUS_FLASH_COUNT 0))
(define plus-flash-epochs (make-vector (* MAPSIZE MAPSIZE) -1))
(define plus-flash-levels (make-bytevector (* MAPSIZE MAPSIZE) 0))

(define (plus-shade level)
  (truncate (/ (+ (- level PLUS_LEVEL_MIN) (/ PLUS_SHADE_STEP 2)) PLUS_SHADE_STEP)))

(define (plus-color color level)
  (if plus-enabled (ref plus-shades (plus-shade level) color) color))

(define (plus-sprite-color color shade emissive)
  (ref (if (and emissive (= (ref plus-emissive color) 1)) emissive shade) color))

(define (plus-distance-level extent range)
  (if plus-enabled
      (let ((distance (- range (min extent range))))
        (truncate (/ (* PLUS_DISTANCE_DEPTH distance distance distance distance)
                     (* range range range range))))
      0))

(define (plus-light-index tilex tiley)
  (+ (* tiley MAPSIZE) tilex))

(define (plus-update-flashes)
  (when plus-enabled
    (unless (and plus-flash-time (= plus-flash-time TimeCount))
      (set! plus-flash-active #f)
      (let slots ((slot 0))
        (when (< slot PLUS_FLASH_COUNT)
          (let* ((start (ref plus-flash-starts slot))
                 (remaining (if (or (< start 0) (> start TimeCount))
                                0
                                (max 0 (- PLUS_FLASH_TICS (- TimeCount start))))))
            (setf! plus-flash-remaining slot remaining)
            (when (> remaining 0) (set! plus-flash-active #t)))
          (slots (+ slot 1))))
      (set! plus-flash-epoch (+ plus-flash-epoch 1))
      (set! plus-flash-time TimeCount))))

(define (plus-flash-level spot)
  (if (= (ref plus-flash-epochs spot) plus-flash-epoch)
      (ref plus-flash-levels spot)
      (let* ((flash (let slots ((slot 0) (brightest 0))
                      (if (= slot PLUS_FLASH_COUNT)
                          brightest
                          (let ((level (truncate (/ (* (ref plus-flashmaps slot spot)
                                                        (ref plus-flash-remaining slot))
                                                     PLUS_FLASH_TICS))))
                            (slots (+ slot 1) (max brightest level))))))
             (bright (if (= flash 0) 0
                         (min 4 (max 1 (truncate (/ (* 4 flash) PLUS_FLASH_LEVELS)))))))
        (setf! plus-flash-levels spot bright)
        (setf! plus-flash-epochs spot plus-flash-epoch)
        bright)))

(define (plus-light-level level worldx worldy)
  (if plus-enabled
      (let* ((tilex (/ worldx TILEGLOBAL))
             (tiley (/ worldy TILEGLOBAL))
             (samplex (max 0 (min (- MAPSIZE 1) (- tilex 0.5))))
             (sampley (max 0 (min (- MAPSIZE 1) (- tiley 0.5))))
             (left (floor samplex))
             (top (floor sampley))
             (spot (plus-light-index left top))
             (cell (* 4 spot))
             (mask (ref plus-light-masks spot))
             (fractionx (- samplex left))
             (fractiony (- sampley top))
             (upper (+ (ref plus-light-cells cell) (* fractionx (ref plus-light-cells (+ cell 1)))))
             (lower (+ (ref plus-light-cells (+ cell 2)) (* fractionx (ref plus-light-cells (+ cell 3)))))
             (light (cond ((= mask 0) (+ upper (* fractiony (- lower upper))))
                          ((= mask 9) (if (< (+ fractionx fractiony) 1) upper lower))
                          ((= mask 6) (if (> fractionx fractiony) upper lower))
                          (else
                           (let* ((horizontal (if (or (= mask 7) (= mask 13)) fractionx (- 1 fractionx)))
                                  (vertical (if (or (= mask 7) (= mask 11)) fractiony (- 1 fractiony)))
                                  (weight (- 1 (* horizontal vertical))))
                             (if (> weight 0)
                                 (/ (+ upper (* fractiony (- lower upper))) weight)
                                 (/ (+ (* 2 (ref plus-light-cells cell)) (ref plus-light-cells (+ cell 1))
                                       (* 2 (ref plus-light-cells (+ cell 2))) (ref plus-light-cells (+ cell 3)))
                                    3))))))
             (dark (- (+ PLUS_AMBIENT_DEPTH level) (* PLUS_LIGHT_STEP light)))
             (bright (if plus-flash-active
                         (plus-flash-level
                           (plus-light-index (max 0 (min (- MAPSIZE 1) (floor tilex)))
                                             (max 0 (min (- MAPSIZE 1) (floor tiley)))))
                         0)))
        (max PLUS_LEVEL_MIN (- dark (* 16 bright))))
      0))

(define (plus-ceiling-light? shape)
  (or (= shape (+ SPR_STAT_0 4)) (= shape (+ SPR_STAT_0 14))))

(define (plus-light-emission shape)
  (cond ((= shape (+ SPR_STAT_0 3)) 1)
        ((plus-ceiling-light? shape) 2)
        (else 0)))

(define (plus-light-shape? shape)
  (> (plus-light-emission shape) 0))

(define (plus-light-factor level)
  (- 1 (/ level (if (< level 0) 120 PLUS_LEVEL_MAX))))

(define (plus-build-table factor)
  (let ((table (make-bytevector 256 0)))
    (let colors ((color 0))
      (when (< color 256)
        (let* ((red (min 63 (round (* (ref gamepal (* color 3)) factor))))
               (green (min 63 (round (* (ref gamepal (+ (* color 3) 1)) factor))))
               (blue (min 63 (round (* (ref gamepal (+ (* color 3) 2)) factor))))
               (best (let search ((index 0) (bestdist -1) (bestindex 0))
                       (if (= index 256)
                           bestindex
                           (let ((dred (- red (ref gamepal (* index 3))))
                                 (dgreen (- green (ref gamepal (+ (* index 3) 1))))
                                 (dblue (- blue (ref gamepal (+ (* index 3) 2)))))
                             (let ((dist (+ (* dred dred) (* dgreen dgreen) (* dblue dblue))))
                               (if (or (< bestdist 0) (< dist bestdist))
                                   (search (+ index 1) dist index)
                                   (search (+ index 1) bestdist bestindex))))))))
          (setf! table color best))
        (colors (+ color 1))))
    table))

(define (plus-linear channel)
  (let ((value (/ channel 63)))
    (if (<= value 0.04045)
        (/ value 12.92)
        (expt (/ (+ value 0.055) 1.055) 2.4))))

(define (plus-channel-value value)
  (* 63 (if (<= value 0.0031308)
            (* value 12.92)
            (- (* 1.055 (expt value (/ 1 2.4))) 0.055))))

(define (plus-channel value)
  (round (plus-channel-value value)))

(define (plus-target color light depth channel)
  (let* ((red (plus-linear (min 63 (* (ref gamepal (* color 3)) light))))
         (green (plus-linear (min 63 (* (ref gamepal (+ (* color 3) 1)) light))))
         (blue (plus-linear (min 63 (* (ref gamepal (+ (* color 3) 2)) light))))
         (luminance (+ (* 0.2126 red) (* 0.7152 green) (* 0.0722 blue)))
         (lightness (if (<= luminance (/ 216 24389))
                        (* luminance (/ 24389 27))
                        (- (* 116 (expt luminance (/ 1 3))) 16)))
         (step (min PLUS_AO_STEP (/ lightness 6)))
         (target (- lightness (* depth step)))
         (level (if (<= target 8)
                    (* target (/ 27 24389))
                    (expt (/ (+ target 16) 116) 3)))
         (factor (if (= luminance 0) 0 (/ level luminance))))
    (vector (channel (* red factor))
            (channel (* green factor))
            (channel (* blue factor)))))

(define (plus-ao-target color light depth)
  (plus-target color light depth plus-channel))

(define (plus-palette-error target index)
  (let ((red (- (ref target 0) (ref gamepal (* index 3))))
        (green (- (ref target 1) (ref gamepal (+ (* index 3) 1))))
        (blue (- (ref target 2) (ref gamepal (+ (* index 3) 2)))))
    (+ (* red red) (* green green) (* blue blue))))

(define (plus-nearest-color target)
  (let search ((index 1) (best 0) (error (plus-palette-error target 0)))
    (if (= index 256)
        best
        (let ((distance (plus-palette-error target index)))
          (if (< distance error)
              (search (+ index 1) index distance)
              (search (+ index 1) best error))))))

(define (plus-surface-colors)
  (if (= mapon -1)
      (vector FLOOR)
      (let ((ceiling (ceiling-color)))
        (if (= ceiling FLOOR) (vector FLOOR) (vector FLOOR ceiling)))))

(define (plus-palette-distance first second)
  (let ((red (- (ref gamepal (* first 3)) (ref gamepal (* second 3))))
        (green (- (ref gamepal (+ (* first 3) 1)) (ref gamepal (+ (* second 3) 1))))
        (blue (- (ref gamepal (+ (* first 3) 2)) (ref gamepal (+ (* second 3) 2)))))
    (+ (* red red) (* green green) (* blue blue))))

(define (plus-palette-sample target)
  (let* ((pair (plus-dither-pair target))
         (first (ref pair 0))
         (second (ref pair 1))
         (mix (ref pair 2))
         (first-error (plus-palette-error target first))
         (second-error (plus-palette-error target second))
         (nearest (if (or (< first-error second-error)
                          (and (= first-error second-error) (< first second))) first second))
         (distance (plus-palette-distance first second))
         (pixel-error (+ (* (- 1 mix) first-error) (* mix second-error)))
         (variance (* mix (- 1 mix) distance))
         (limit (+ distance (/ (max 0 (- pixel-error variance)) PLUS_DITHER_CONTRAST))))
    (vector nearest (min first-error second-error) limit pixel-error)))

(define (plus-build-palette)
  (let* ((surfaces (plus-surface-colors))
         (ramp (* PLUS_LEVEL_COUNT (vector-length PLUS_AO_DEPTHS)))
         (count (* (vector-length surfaces) ramp))
         (targets (make-vector count #f))
         (colors (make-vector count #f))
         (samples (make-vector count #f))
         (weights (make-vector count 0)))
    (let slots ((slot 0))
      (when (< slot (vector-length plus-palette-slots))
        (let channels ((channel 0))
          (when (< channel 3)
            (setf! gamepal (+ (* (ref plus-palette-slots slot) 3) channel) (ref gamepal channel))
            (channels (+ channel 1))))
        (slots (+ slot 1))))

    (let prepare ((index 0))
      (when (< index count)
        (let* ((shade (remainder index PLUS_LEVEL_COUNT))
               (layer (remainder (quotient index PLUS_LEVEL_COUNT) (vector-length PLUS_AO_DEPTHS)))
               (depth (ref PLUS_AO_DEPTHS layer))
               (color (ref surfaces (quotient index ramp)))
               (target (plus-target color (plus-light-factor (+ shade PLUS_LEVEL_MIN))
                                    depth plus-channel-value))
               (rounded (vector (round (ref target 0)) (round (ref target 1)) (round (ref target 2)))))
          (unless (= (plus-palette-error rounded (plus-nearest-color rounded)) 0)
            (let ((brightness (/ (+ (* 54 (ref target 0)) (* 183 (ref target 1))
                                     (* 19 (ref target 2))) 256)))
              (setf! targets index target)
              (setf! colors index rounded)
              (setf! samples index (plus-palette-sample target))
              (setf! weights index (/ 1 (sqrt (+ brightness 8)))))))
        (prepare (+ index 1))))

    (let slots ((slot 0))
      (when (< slot (vector-length plus-palette-slots))
        (let ((best (let search ((index 0) (best #f) (error 0))
                      (cond ((= index count) best)
                            ((not (ref samples index)) (search (+ index 1) best error))
                            (else
                              (let ((score (* (ref weights index) (ref samples index 3))))
                                (if (or (not best) (> score error))
                                    (search (+ index 1) index score)
                                    (search (+ index 1) best error))))))))
          (when best
            (let ((target (ref colors best))
                  (color (ref plus-palette-slots slot)))
              (let channels ((channel 0))
                (when (< channel 3)
                  (setf! gamepal (+ (* color 3) channel) (ref target channel))
                  (channels (+ channel 1))))
              (let update ((index 0))
                (when (< index count)
                  (let ((sample (ref samples index)))
                    (when sample
                      (cond ((= (plus-palette-error (ref colors index) color) 0)
                             (setf! samples index #f))
                            ((or (<= (plus-palette-error (ref targets index) color) (ref sample 1))
                                 (<= (plus-palette-distance color (ref sample 0)) (ref sample 2)))
                             (setf! samples index (plus-palette-sample (ref targets index)))))))
                  (update (+ index 1)))))
            (slots (+ slot 1))))))))

(define (plus-build-ao-colors depth)
  (let ((table (make-bytevector 256 0)))
    (let colors ((color 0))
      (when (< color 256)
        (setf! table color (plus-nearest-color (plus-ao-target color 1 depth)))
        (colors (+ color 1))))
    table))

(define (plus-build-ao-shades depth)
  (let ((dark (plus-build-ao-colors depth))
        (shades (make-vector PLUS_SHADE_COUNT 0)))
    (let levels ((level 0))
      (when (< level PLUS_SHADE_COUNT)
        (let ((table (make-bytevector 256 0))
              (lit (ref plus-shades level)))
          (let colors ((color 0))
            (when (< color 256)
              (setf! table color (ref dark (ref lit color)))
              (colors (+ color 1))))
          (setf! shades level table))
        (levels (+ level 1))))
    shades))

(define (plus-build-ao)
  (set! plus-ao-shades (plus-build-ao-shades (ref PLUS_AO_DEPTHS 1)))
  (set! plus-corner-shades (plus-build-ao-shades (ref PLUS_AO_DEPTHS 2))))

(define (plus-build-shades)
  (when plus-available (plus-build-palette))
  (let ((identity (make-bytevector 256 0)))
    (let loop ((index 0))
      (when (< index 256)
        (let ((luma (truncate (/ (+ (* 54 (ref gamepal (* index 3)))
                                      (* 183 (ref gamepal (+ (* index 3) 1)))
                                      (* 19 (ref gamepal (+ (* index 3) 2))))
                                   256))))
          (setf! identity index index)
          (setf! plus-luma index luma)
          (setf! plus-emissive index (if (>= luma PLUS_EMISSIVE_LUMA) 1 0)))
        (loop (+ index 1))))
    (setf! plus-shades (plus-shade 0) identity))
  (let shades ((shade 0))
    (when (< shade PLUS_SHADE_COUNT)
      (let ((level (+ (* shade PLUS_SHADE_STEP) PLUS_LEVEL_MIN)))
        (unless (= level 0)
          (setf! plus-shades shade (plus-build-table (plus-light-factor level)))))
      (shades (+ shade 1))))
  (plus-build-ao)
  (when plus-available (plus-build-dither)))

(define (plus-door-tile? tile)
  (and (>= tile 128) (< tile 192)))

(define (plus-door-passes? position limit)
  (or (= position 65535) (> position limit)))

(define (plus-light-space? tile)
  (or (= tile 0) (plus-door-tile? tile)))

(define (plus-light-passable? tilex tiley)
  (and (>= tilex 0) (< tilex MAPSIZE) (>= tiley 0) (< tiley MAPSIZE)
       (let ((tile (tileat tilex tiley)))
         (or (= tile 0)
             (and (plus-door-tile? tile)
                  (plus-door-passes? (ref doorposition (bitwise-and tile 127)) (/ TILEGLOBAL 2)))))))

(define (plus-box-distance worldx worldy left top right bottom)
  (let ((dx (max 0 (- left worldx) (- worldx right)))
        (dy (max 0 (- top worldy) (- worldy bottom))))
    (+ (* dx dx) (* dy dy))))

(define (plus-wall-distance worldx worldy tilex tiley)
  (let ((tile (tileat tilex tiley))
        (limit (* PLUS_AO_WIDTH PLUS_AO_WIDTH)))
    (cond
      ((= tile 0) limit)
      ((and (> pwallstate 0)
            (or (and (= tilex pwallx) (= tiley pwally))
                (and (= tilex (+ pwallx (dir-dx pwalldir)))
                     (= tiley (+ pwally (dir-dy pwalldir))))))
       (let ((left (+ (* pwallx TILEGLOBAL) (* pwallpos 1024 (dir-dx pwalldir))))
             (top (+ (* pwally TILEGLOBAL) (* pwallpos 1024 (dir-dy pwalldir)))))
         (plus-box-distance worldx worldy left top (+ left TILEGLOBAL) (+ top TILEGLOBAL))))
      ((plus-door-tile? tile)
       (let* ((door (bitwise-and tile 127))
              (position (ref doorposition door))
              (left (* tilex TILEGLOBAL))
              (top (* tiley TILEGLOBAL)))
         (if (= position 65535)
             limit
             (if (ref doorvertical door)
                 (plus-box-distance worldx worldy (+ left 32768) (+ top position)
                                    (+ left 32768) (+ top TILEGLOBAL))
                 (plus-box-distance worldx worldy (+ left position) (+ top 32768)
                                    (+ left TILEGLOBAL) (+ top 32768))))))
      (else
       (plus-box-distance worldx worldy (* tilex TILEGLOBAL) (* tiley TILEGLOBAL)
                          (* (+ tilex 1) TILEGLOBAL) (* (+ tiley 1) TILEGLOBAL))))))

(define (plus-ao-distance worldx worldy)
  (let ((left (max 0 (arithmetic-shift (- worldx PLUS_AO_WIDTH) -16)))
        (right (min (- MAPSIZE 1) (arithmetic-shift (+ worldx PLUS_AO_WIDTH) -16)))
        (top (max 0 (arithmetic-shift (- worldy PLUS_AO_WIDTH) -16)))
        (bottom (min (- MAPSIZE 1) (arithmetic-shift (+ worldy PLUS_AO_WIDTH) -16))))
    (let columns ((tilex left) (distance (* PLUS_AO_WIDTH PLUS_AO_WIDTH)))
      (if (or (> tilex right) (= distance 0))
          distance
          (columns (+ tilex 1)
                   (let rows ((tiley top) (nearest distance))
                     (if (or (> tiley bottom) (= nearest 0))
                         nearest
                         (rows (+ tiley 1)
                               (min nearest (plus-wall-distance worldx worldy tilex tiley))))))))))

(define (plus-corner-wall? tilex tiley)
  (and (>= tilex 0) (< tilex MAPSIZE) (>= tiley 0) (< tiley MAPSIZE)
       (let ((tile (tileat tilex tiley)))
         (and (> tile 0) (< tile 128)))
       (not (and (> pwallstate 0)
                 (= tilex (+ pwallx (dir-dx pwalldir)))
                 (= tiley (+ pwally (dir-dy pwalldir)))))))

(define (plus-corner? worldx worldy)
  (let* ((tilex (arithmetic-shift worldx -16))
         (tiley (arithmetic-shift worldy -16))
         (offsetx (- worldx (* tilex TILEGLOBAL)))
         (offsety (- worldy (* tiley TILEGLOBAL)))
         (dx (min offsetx (- TILEGLOBAL offsetx)))
         (dy (min offsety (- TILEGLOBAL offsety))))
    (and (>= tilex 0) (< tilex MAPSIZE) (>= tiley 0) (< tiley MAPSIZE)
         (>= dx 0) (< dx PLUS_AO_WIDTH) (>= dy 0) (< dy PLUS_AO_WIDTH)
         (< (+ (* dx dx) (* dy dy)) (* PLUS_AO_WIDTH PLUS_AO_WIDTH))
         (= (tileat tilex tiley) 0)
         (plus-corner-wall? (+ tilex (if (< offsetx (/ TILEGLOBAL 2)) -1 1)) tiley)
         (plus-corner-wall? tilex (+ tiley (if (< offsety (/ TILEGLOBAL 2)) -1 1))))))

(define (plus-ao-layer worldx worldy edge)
  (cond ((< (plus-ao-distance worldx worldy) (* PLUS_AO_WIDTH PLUS_AO_WIDTH))
         (if (plus-corner? worldx worldy) 2 1))
        (edge 1)
        (else 0)))

(define (plus-ao level worldx worldy edge)
  (if plus-enabled
      (let ((shade (plus-shade level))
            (layer (plus-ao-layer worldx worldy edge)))
        (cond ((= layer 2) (ref plus-corner-shades shade))
              ((= layer 1) (ref plus-ao-shades shade))
              (else (ref plus-shades shade))))
      (ref plus-shades (plus-shade 0))))

(define (plus-check-keys)
  (when plus-requested
    (let ((pressed (and (or (ref Keyboard sc_LShift) (ref Keyboard sc_RShift))
                        (ref Keyboard sc_P))))
      (when (and pressed (not plus-key))
        (set! plus-enabled (not plus-enabled)))
      (set! plus-key pressed))))

(define (plus-door-limit fromx fromy tox toy tilex tiley door)
  (let* ((vertical (ref doorvertical door))
         (delta (if vertical (- tox fromx) (- toy fromy))))
    (if (= delta 0)
        65535
        (let* ((fraction (/ (if vertical (- tilex fromx) (- tiley fromy)) delta))
               (offset (+ 0.5 (if vertical (- fromy tiley) (- fromx tilex))
                          (* fraction (if vertical (- toy fromy) (- tox fromx))))))
          (and (>= fraction 0) (<= fraction 1) (>= offset 0) (< offset 1) (* offset TILEGLOBAL))))))

(define (plus-trace-light fromx fromy tox toy)
  (let ((dx (abs (- tox fromx)))
        (dy (abs (- toy fromy)))
        (stepx (if (< fromx tox) 1 -1))
        (stepy (if (< fromy toy) 1 -1)))
    (let ray ((tilex fromx) (tiley fromy) (crossx dy) (crossy dx) (doors '()))
      (let ((tile (tileat tilex tiley)))
        (and (plus-light-space? tile)
             (let* ((door (and (plus-door-tile? tile) (bitwise-and tile 127)))
                    (limit (and door (plus-door-limit fromx fromy tox toy tilex tiley door)))
                    (path (if limit (cons (tuple door limit) doors) doors)))
               (cond ((and (= tilex tox) (= tiley toy)) path)
                     ((< crossx crossy) (ray (+ tilex stepx) tiley (+ crossx (* 2 dy)) crossy path))
                     ((> crossx crossy) (ray tilex (+ tiley stepy) crossx (+ crossy (* 2 dx)) path))
                     (else
                      (and (plus-light-space? (tileat (+ tilex stepx) tiley))
                           (plus-light-space? (tileat tilex (+ tiley stepy)))
                           (ray (+ tilex stepx) (+ tiley stepy)
                                (+ crossx (* 2 dy)) (+ crossy (* 2 dx)) path))))))))))

(define (plus-path-open? doors)
  (or (null? doors)
      (let ((door (car doors)))
        (and (plus-door-passes? (ref doorposition (ref door 0)) (ref door 1))
             (plus-path-open? (cdr doors))))))

(define (plus-light-value spot)
  (let scan ((paths (ref plus-light-paths spot)) (light (ref plus-light-base spot)))
    (if (null? paths)
        light
        (let* ((path (car paths))
               (level (ref path 0)))
          (scan (cdr paths) (if (and (> level light) (plus-path-open? (ref path 1))) level light))))))

(define (plus-build-light lightx lighty radius levels)
  (let ((left (max 0 (- lightx radius)))
        (right (min (- MAPSIZE 1) (+ lightx radius)))
        (top (max 0 (- lighty radius)))
        (bottom (min (- MAPSIZE 1) (+ lighty radius)))
        (limit (* radius radius))
        (falloff (/ levels radius)))
    (let rows ((tiley top))
      (when (<= tiley bottom)
        (let columns ((tilex left))
          (when (<= tilex right)
            (let* ((dx (- tilex lightx))
                   (dy (- tiley lighty))
                   (distance (+ (* dx dx) (* dy dy))))
              (when (and (< distance limit) (plus-light-space? (tileat tilex tiley)))
                (let ((doors (plus-trace-light lightx lighty tilex tiley)))
                  (when doors
                    (let ((spot (plus-light-index tilex tiley))
                          (level (- levels (* falloff (sqrt distance)))))
                      (if (null? doors)
                          (setf! plus-light-base spot (max level (ref plus-light-base spot)))
                          (setf! plus-light-paths spot (cons (tuple level doors) (ref plus-light-paths spot)))))))))
            (columns (+ tilex 1))))
        (rows (+ tiley 1))))))

(define (plus-clear-map map)
  (let clear ((index 0))
    (when (< index (* MAPSIZE MAPSIZE))
      (setf! map index 0)
      (clear (+ index 1)))))

(define (plus-cell-value samples mask corner)
  (if (> (bitwise-and mask (arithmetic-shift 1 corner)) 0)
      (ref samples corner)
      (let* ((across (bitwise-xor corner 1))
             (along (bitwise-xor corner 2))
             (diagonal (bitwise-xor corner 3))
             (horizontal (and (> (bitwise-and mask (arithmetic-shift 1 across)) 0) (ref samples across)))
             (vertical (and (> (bitwise-and mask (arithmetic-shift 1 along)) 0) (ref samples along))))
        (cond ((and horizontal vertical) (/ (+ horizontal vertical) 2))
              (horizontal horizontal)
              (vertical vertical)
              ((> (bitwise-and mask (arithmetic-shift 1 diagonal)) 0) (ref samples diagonal))
              (else 0)))))

(define (plus-build-light-cell spot)
  (let* ((samples plus-light-samples)
         (left (remainder spot MAPSIZE))
         (top (quotient spot MAPSIZE))
         (right (min (- MAPSIZE 1) (+ left 1)))
         (bottom (min (- MAPSIZE 1) (+ top 1)))
         (cell (* 4 spot))
         (mask (+ (if (plus-light-passable? left top) 1 0)
                  (if (plus-light-passable? right top) 2 0)
                  (if (plus-light-passable? left bottom) 4 0)
                  (if (plus-light-passable? right bottom) 8 0))))
    (setf! samples 0 (ref plus-lightmap (plus-light-index left top)))
    (setf! samples 1 (ref plus-lightmap (plus-light-index right top)))
    (setf! samples 2 (ref plus-lightmap (plus-light-index left bottom)))
    (setf! samples 3 (ref plus-lightmap (plus-light-index right bottom)))
    (let* ((masked (if (or (= mask 6) (= mask 7) (= mask 9) (= mask 11) (= mask 13) (= mask 14)) mask 0))
           (upper (cond ((= masked 6) (ref samples 1))
                        ((> masked 0) (ref samples 0))
                        (else (plus-cell-value samples mask 0))))
           (lower (cond ((= masked 9) (ref samples 3))
                        ((> masked 0) (ref samples 2))
                        (else (plus-cell-value samples mask 2))))
           (upper-right (cond ((or (= masked 6) (= masked 9)) upper)
                              ((> masked 0) (ref samples 1))
                              (else (plus-cell-value samples mask 1))))
           (lower-right (cond ((or (= masked 6) (= masked 9)) lower)
                              ((> masked 0) (ref samples 3))
                              (else (plus-cell-value samples mask 3)))))
      (setf! plus-light-masks spot masked)
      (setf! plus-light-cells cell upper)
      (setf! plus-light-cells (+ cell 1) (- upper-right upper))
      (setf! plus-light-cells (+ cell 2) lower)
      (setf! plus-light-cells (+ cell 3) (- lower-right lower)))))

(define (plus-build-light-cells)
  (let cells ((spot 0))
    (when (< spot (* MAPSIZE MAPSIZE))
      (plus-build-light-cell spot)
      (cells (+ spot 1)))))

(define (plus-build-lights)
  (plus-clear-map plus-light-base)
  (plus-clear-map plus-light-dirty)
  (set! plus-light-count 0)
  (let doors ((door 0))
    (when (< door MAXDOORS)
      (setf! plus-light-watch door '())
      (setf! plus-light-positions door (ref doorposition door))
      (doors (+ door 1))))
  (let clear ((spot 0))
    (when (< spot (* MAPSIZE MAPSIZE))
      (setf! plus-light-paths spot '())
      (clear (+ spot 1))))
  (let lights ((index 0))
    (when (< index statcount)
      (when (plus-light-shape? (ref stat-shape index))
        (plus-build-light (ref stat-tilex index) (ref stat-tiley index) PLUS_LIGHT_RADIUS
                          (if (= (ref stat-shape index) (+ SPR_STAT_0 4))
                              PLUS_CHANDELIER_LEVELS PLUS_LIGHT_LEVELS)))
      (lights (+ index 1))))
  (let points ((spot 0))
    (when (< spot (* MAPSIZE MAPSIZE))
      (setf! plus-light-paths spot
             (let keep ((paths (ref plus-light-paths spot)) (kept '()))
               (if (null? paths)
                   kept
                   (let ((path (car paths)))
                     (if (<= (ref path 0) (ref plus-light-base spot))
                         (keep (cdr paths) kept)
                         (begin
                           (let watch ((doors (ref path 1)))
                             (when (pair? doors)
                               (let* ((requirement (car doors))
                                      (door (ref requirement 0)))
                                 (setf! plus-light-watch door
                                        (cons (tuple (ref requirement 1) spot) (ref plus-light-watch door))))
                               (watch (cdr doors))))
                           (keep (cdr paths) (cons path kept))))))))
      (setf! plus-lightmap spot (plus-light-value spot))
      (points (+ spot 1))))
  (plus-build-light-cells))

(define (plus-dirty-light spot flags)
  (let ((current (ref plus-light-dirty spot)))
    (when (= current 0)
      (setf! plus-light-queue plus-light-count spot)
      (set! plus-light-count (+ plus-light-count 1)))
    (setf! plus-light-dirty spot (bitwise-ior current flags))))

(define (plus-dirty-cells spot)
  (plus-dirty-light spot 2)
  (when (> (remainder spot MAPSIZE) 0)
    (plus-dirty-light (- spot 1) 2))
  (when (>= spot MAPSIZE)
    (plus-dirty-light (- spot MAPSIZE) 2)
    (when (> (remainder spot MAPSIZE) 0)
      (plus-dirty-light (- spot MAPSIZE 1) 2))))

(define (plus-update-lights)
  (when plus-enabled
    (let doors ((door 0))
      (when (< door doornum)
        (let ((position (ref doorposition door))
              (previous (ref plus-light-positions door)))
          (unless (= position previous)
            (let watch ((entries (ref plus-light-watch door)))
              (when (pair? entries)
                (let* ((entry (car entries))
                       (limit (ref entry 0)))
                  (unless (eq? (plus-door-passes? previous limit) (plus-door-passes? position limit))
                    (plus-dirty-light (ref entry 1) 1)))
                (watch (cdr entries))))
            (unless (eq? (plus-door-passes? previous (/ TILEGLOBAL 2))
                         (plus-door-passes? position (/ TILEGLOBAL 2)))
              (plus-dirty-cells (plus-light-index (ref doortilex door) (ref doortiley door))))
            (setf! plus-light-positions door position)))
        (doors (+ door 1))))
    (let points ((head 0))
      (when (< head plus-light-count)
        (let ((spot (ref plus-light-queue head)))
          (when (> (bitwise-and (ref plus-light-dirty spot) 1) 0)
            (let ((light (plus-light-value spot)))
              (unless (= light (ref plus-lightmap spot))
                (setf! plus-lightmap spot light)
                (plus-dirty-cells spot)))))
        (points (+ head 1))))
    (let cells ((head 0))
      (when (< head plus-light-count)
        (let ((spot (ref plus-light-queue head)))
          (when (> (bitwise-and (ref plus-light-dirty spot) 2) 0)
            (plus-build-light-cell spot))
          (setf! plus-light-dirty spot 0))
        (cells (+ head 1))))
    (set! plus-light-count 0)))

(define (plus-flash-at tilex tiley)
  (when plus-enabled
    (let ((flashmap (ref plus-flashmaps plus-flash-next))
          (queue (make-vector (* MAPSIZE MAPSIZE) 0))
          (distance (make-bytevector (* MAPSIZE MAPSIZE) 255))
          (tail 1))
      (plus-clear-map flashmap)
      (setf! queue 0 (plus-light-index tilex tiley))
      (setf! distance (plus-light-index tilex tiley) 0)
      (let flood ((head 0) (maxd 0))
        (if (< head tail)
            (let* ((spot (ref queue head))
                   (tx (remainder spot MAPSIZE))
                   (ty (quotient spot MAPSIZE))
                   (steps (ref distance spot)))
              (let visit ((direction 0))
                (when (< direction 4)
                  (let* ((offset (ref plus-neighbors direction))
                         (nextx (+ tx (ref offset 0)))
                         (nexty (+ ty (ref offset 1))))
                    (when (plus-light-passable? nextx nexty)
                      (let ((next (plus-light-index nextx nexty)))
                        (when (> (ref distance next) (+ steps 1))
                          (setf! distance next (+ steps 1))
                          (setf! queue tail next)
                          (set! tail (+ tail 1)))))
                    (visit (+ direction 1)))))
              (flood (+ head 1) (max maxd steps)))
            (let stamp ((index 0))
              (if (< index tail)
                  (let* ((spot (ref queue index))
                         (tx (remainder spot MAPSIZE))
                         (ty (quotient spot MAPSIZE))
                         (steps (ref distance spot))
                         (level (if (= maxd 0)
                                    PLUS_FLASH_LEVELS
                                    (max 1 (- PLUS_FLASH_LEVELS
                                              (truncate (/ (* PLUS_FLASH_LEVELS steps) maxd)))))))
                    (setf! flashmap spot level)
                    (let walls ((direction 0))
                      (when (< direction 4)
                        (let* ((offset (ref plus-neighbors direction))
                               (nextx (+ tx (ref offset 0)))
                               (nexty (+ ty (ref offset 1))))
                          (when (and (>= nextx 0) (< nextx MAPSIZE) (>= nexty 0) (< nexty MAPSIZE)
                                     (not (= (tileat nextx nexty) 0)))
                            (let ((next (plus-light-index nextx nexty)))
                              (when (> level (ref flashmap next))
                                (setf! flashmap next level)))))
                        (walls (+ direction 1))))
                    (stamp (+ index 1)))
                  (begin
                    (setf! plus-flash-starts plus-flash-next TimeCount)
                    (set! plus-flash-time #f)
                    (set! plus-flash-next (remainder (+ plus-flash-next 1) PLUS_FLASH_COUNT))))))))))

(define (plus-enemy-shape? shape)
  (or (and (>= shape SPR_GRD_S_1) (< shape SPR_HYPO1))
      (and (>= shape SPR_FAKE_W1) (< shape SPR_FIRE1))
      (and (>= shape SPR_FAKE_DIE1) (< shape SPR_ROCKET_1))
      (and (>= shape SPR_GRETEL_W1) (<= shape SPR_FAT_DEAD))))

(define (plus-ceiling-shape? shape)
  (or (plus-ceiling-light? shape)
      (= shape (+ SPR_STAT_0 17)) (= shape (+ SPR_STAT_0 18))))

(define (plus-crop-sprite shape)
  (let* ((source (PM_GetPage (+ PMSpriteStart shape)))
         (page (bytevector-copy source 0 (bytevector-length source)))
         (limit (* 32 2))
         (left (readu16 page 0))
         (right (readu16 page 2)))
    (let columns ((column left))
      (when (<= column right)
        (let posts ((offset (readu16 page (+ 4 (* (- column left) 2)))))
          (let ((end (readu16 page offset)))
            (when (> end 0)
              (let ((start (readu16 page (+ offset 4))))
                (setf! page offset (if (>= start limit) 0 (min end limit)))
                (setf! page (+ offset 1) 0)
                (when (< start limit) (posts (+ offset 6)))))))
        (columns (+ column 1))))
    page))

(define (plus-build-sprites)
  (set! plus-sprites (make-vector (- PMSoundStart PMSpriteStart) #f))
  (let shapes ((shape 0))
    (when (< shape (vector-length plus-sprites))
      (when (and (plus-ceiling-light? shape) (PM_HasPage (+ PMSpriteStart shape)))
        (setf! plus-sprites shape (plus-crop-sprite shape)))
      (shapes (+ shape 1)))))

(define (plus-shape-bounds shape start end)
  (let* ((page (PM_GetPage (+ PMSpriteStart shape)))
         (left (readu16 page 0))
         (right (readu16 page 2))
         (first 64)
         (last -1))
    (let columns ((column left))
      (when (<= column right)
        (let posts ((offset (readu16 page (+ 4 (* (- column left) 2)))))
          (let ((bottom (readu16 page offset)))
            (when (> bottom 0)
              (when (and (> bottom (* start 2)) (< (readu16 page (+ offset 4)) (* end 2)))
                (set! first (min first column))
                (set! last (max last column)))
              (posts (+ offset 6)))))
        (columns (+ column 1))))
    (and (<= first last) (tuple first (+ last 1)))))

(define (plus-body-bounds shape)
  (or (plus-shape-bounds shape 60 64)
      (let* ((page (PM_GetPage (+ PMSpriteStart shape)))
             (left (readu16 page 0))
             (right (readu16 page 2))
             (bottom 0))
        (let columns ((column left))
          (when (<= column right)
            (let posts ((offset (readu16 page (+ 4 (* (- column left) 2)))))
              (let ((end (readu16 page offset)))
                (when (> end 0)
                  (set! bottom (max bottom (quotient end 2)))
                  (posts (+ offset 6)))))
            (columns (+ column 1))))
        (and (> bottom 0) (plus-shape-bounds shape (max 0 (- bottom 4)) bottom)))))

(define (plus-build-feet)
  (set! plus-feet (make-vector (- PMSoundStart PMSpriteStart) #f))
  (let shapes ((shape 0))
    (when (< shape (vector-length plus-feet))
      (when (and (plus-enemy-shape? shape) (PM_HasPage (+ PMSpriteStart shape)))
        (setf! plus-feet shape (plus-body-bounds shape)))
      (shapes (+ shape 1)))))

(define (plus-build-mounts)
  (let shapes ((shape SPR_STAT_0))
    (when (< shape (vector-length plus-mounts))
      (when (and (plus-ceiling-shape? shape) (PM_HasPage (+ PMSpriteStart shape)))
        (setf! plus-mounts shape (plus-shape-bounds shape 0 3)))
      (shapes (+ shape 1)))))

(define (plus-shadow index bounds ceiling?)
  (let* ((height (ref vis-height index))
         (scale (truncate (/ height 8))))
    (when (and (> scale 0) (<= scale maxscale))
      (let* ((rows (* scale 2))
             (center (ref vis-x index))
             (padding (if ceiling? 2 1))
             (contact (and ceiling? (< rows 64)))
             (start (/ (* (- (ref bounds 0) padding) rows) 64))
             (end (/ (* (+ (ref bounds 1) padding) rows) 64))
             (left (+ center (- (if contact (floor start) (truncate start)) scale)))
             (right (+ center (- (if contact (ceiling end) (truncate end)) scale)))
             (bottom (+ (truncate (/ (- viewheight rows) 2)) rows -1))
             (depth (max 1 (truncate (/ rows 64))))
             (limit (+ bottom depth (if (and ceiling? (or contact (>= rows 64))) 1 0)))
             (level (plus-light-level 0 (* (+ (ref vis-tilex index) 0.5) TILEGLOBAL)
                                        (* (+ (ref vis-tiley index) 0.5) TILEGLOBAL)))
             (color (if ceiling?
                        (ref plus-ao-shades (plus-shade level) (ceiling-color))
                        (plus-color FLOOR (min PLUS_LEVEL_MAX (+ level PLUS_SHADOW_DEPTH)))))
             (luma (ref plus-luma color)))
        (let scan ((row (max (arithmetic-shift viewheight -1) (- bottom depth))))
          (when (and (< row limit) (< row viewheight))
            (let* ((inset (truncate (/ (* (- right left) (abs (- row bottom))) (* depth 4))))
                   (end (min viewwidth (- right inset))))
              (let columns ((column (max 0 (+ left inset))))
                (when (< column end)
                  (when (and (< (ref wallheight column) height)
                             (>= row (+ (arithmetic-shift viewheight -1) (ref plus-boundaries column))))
                    (let* ((screenrow (if ceiling? (- viewheight 1 row) row))
                           (pixel (+ (* (+ viewtop screenrow) screenwidth) viewleft column)))
                      (when (> (ref plus-luma (ref framebuffer pixel)) luma)
                        (setf! framebuffer pixel color))))
                  (columns (+ column 1)))))
            (scan (+ row 1))))))))

(define (plus-draw-shadows)
  (when plus-enabled
    (let sprites ((index 0))
      (when (< index viscount)
        (let* ((shape (ref vis-shape index))
               (feet (and (>= shape 0) (< shape (vector-length plus-feet)) (ref plus-feet shape))))
          (cond (feet (plus-shadow index feet #f))
                ((plus-ceiling-shape? shape)
                 (let ((mount (ref plus-mounts shape)))
                   (when mount (plus-shadow index mount #t))))))
        (sprites (+ index 1))))))

(define (plus-palette-loaded)
  (when plus-available (plus-build-shades)))

(define (plus-startup)
  (when plus-available
    (plus-build-sprites)
    (plus-build-feet)
    (plus-build-mounts)))

(define (plus-level-loaded)
  (when plus-available
    (plus-build-shades)
    (InitRedShifts)
    (unless screenfaded (VL_SetPalette gamepal))
    (let reset ((slot 0))
      (when (< slot PLUS_FLASH_COUNT)
        (plus-clear-map (ref plus-flashmaps slot))
        (setf! plus-flash-starts slot -1)
        (reset (+ slot 1))))
    (set! plus-flash-next 0)
    (set! plus-flash-time #f)
    (plus-build-lights)))

(define (plus-build-planes)
  (let* ((stepx (/ viewsin 2))
         (stepy (/ viewcos 2))
         (forwardx (* scale stepy))
         (forwardy (- (* scale stepx)))
         (center (/ (- viewwidth 1) 2)))
    (let columns ((column 0))
      (when (< column viewwidth)
        (let ((offset (- column center)))
          (setf! plus-boundaries column (arithmetic-shift (scale-rows (ref wallheight column)) -1))
          (setf! plus-planex column (+ forwardx (* offset stepx)))
          (setf! plus-planey column (+ forwardy (* offset stepy))))
        (columns (+ column 1))))))

(define plus-dither (make-vector 256 #f))
(define plus-pattern
  (let ((pattern
          #(200 94 175 234 98 23 194 115 145 181 19 61 250 89 151 7
            168 37 72 122 52 170 132 77 50 245 106 203 163 21 231 123
            249 137 219 5 207 254 41 224 166 29 131 80 36 183 102 51
            26 83 189 155 108 86 147 1 211 68 191 237 144 218 70 197
            112 226 20 56 180 30 192 119 96 152 12 110 59 3 130 162
            45 146 100 246 126 74 239 58 230 177 46 223 169 255 90 209
            241 64 164 201 9 215 160 16 134 82 202 125 99 34 179 17
            120 185 35 79 141 48 105 188 38 247 24 63 150 199 76 142
            93 4 236 116 173 251 88 220 154 113 167 228 14 244 49 221
            193 156 217 55 205 13 128 28 75 54 190 92 133 109 159 25
            124 71 101 27 149 67 176 233 208 138 6 216 44 187 84 235
            39 178 136 242 95 196 117 47 158 104 252 73 172 11 206 62
            253 8 214 43 165 0 248 85 18 184 32 121 148 232 107 143
            87 195 118 81 227 127 57 204 135 222 97 238 53 78 22 171
            33 153 60 186 31 157 103 174 40 66 161 2 198 182 129 225
            111 243 15 140 210 69 240 10 229 91 212 139 114 42 213 65)))
    (let thresholds ((index 0))
      (when (< index (vector-length pattern))
        (setf! pattern index (/ (+ 0.5 (ref pattern index)) (vector-length pattern)))
        (thresholds (+ index 1))))
    pattern))

(define (plus-dither-pair target)
  (let* ((first (plus-nearest-color target))
         (red (ref gamepal (* first 3)))
         (green (ref gamepal (+ (* first 3) 1)))
         (blue (ref gamepal (+ (* first 3) 2)))
         (error-red (- (ref target 0) red))
         (error-green (- (ref target 1) green))
         (error-blue (- (ref target 2) blue)))
    (let search ((index 0) (second first) (mix 0) (error #f))
      (if (= index 256)
          (let ((first-brightness (+ (* 54 red) (* 183 green) (* 19 blue)))
                (second-brightness (+ (* 54 (ref gamepal (* second 3)))
                                      (* 183 (ref gamepal (+ (* second 3) 1)))
                                      (* 19 (ref gamepal (+ (* second 3) 2))))))
            (if (or (> first-brightness second-brightness)
                    (and (= first-brightness second-brightness) (> first second)))
                (vector second first (- 1 mix))
                (vector first second mix)))
          (let* ((delta-red (- (ref gamepal (* index 3)) red))
                 (delta-green (- (ref gamepal (+ (* index 3) 1)) green))
                 (delta-blue (- (ref gamepal (+ (* index 3) 2)) blue))
                 (distance (+ (* delta-red delta-red) (* delta-green delta-green)
                              (* delta-blue delta-blue)))
                 (weight (if (= distance 0) 0
                             (max 0 (min 1 (/ (+ (* error-red delta-red) (* error-green delta-green)
                                                (* error-blue delta-blue)) distance)))))
                 (residual-red (- error-red (* weight delta-red)))
                 (residual-green (- error-green (* weight delta-green)))
                 (residual-blue (- error-blue (* weight delta-blue)))
                 (score (+ (* residual-red residual-red) (* residual-green residual-green)
                           (* residual-blue residual-blue) (* PLUS_DITHER_CONTRAST distance))))
            (if (and (> weight 0) (or (not error) (< score error)))
                (search (+ index 1) index weight score)
                (search (+ index 1) second mix error)))))))

(define (plus-build-dither)
  (let ((colors (plus-surface-colors)))
    (let surfaces ((index 0))
      (when (< index (vector-length colors))
        (let ((color (ref colors index))
              (tables (make-vector (vector-length PLUS_AO_DEPTHS) #f)))
          (let layers ((layer 0))
            (when (< layer (vector-length PLUS_AO_DEPTHS))
              (let ((table (make-vector PLUS_LEVEL_COUNT #f)))
                (let shades ((shade 0))
                  (when (< shade PLUS_LEVEL_COUNT)
                    (setf! table shade
                           (plus-dither-pair
                             (plus-target color (plus-light-factor (+ shade PLUS_LEVEL_MIN))
                                          (ref PLUS_AO_DEPTHS layer) plus-channel-value)))
                    (shades (+ shade 1))))
                (setf! tables layer table))
              (layers (+ layer 1))))
          (setf! plus-dither color tables))
        (surfaces (+ index 1))))))

(define (plus-plane-color shades layer shade threshold)
  (let ((pair (ref shades layer shade)))
    (ref pair (if (< threshold (ref pair 2)) 1 0))))

(define (plus-draw-planes)
  (when plus-enabled
    (plus-build-planes)
    (let ((halfh (arithmetic-shift viewheight -1))
          (ceiling (ref plus-dither (ceiling-color)))
          (floor (ref plus-dither FLOOR)))
      (let rows ((height 1))
        (when (< height halfh)
          (let* ((projection (/ 1 (+ height 0.5)))
                 (top (- halfh 1 height))
                 (bottom (+ halfh height))
                 (top-offset (+ (* (+ viewtop top) screenwidth) viewleft))
                 (bottom-offset (+ (* (+ viewtop bottom) screenwidth) viewleft))
                 (top-pattern (* (bitwise-and top 15) 16))
                 (bottom-pattern (* (bitwise-and bottom 15) 16)))
            (let columns ((column 0))
              (when (< column viewwidth)
                (let ((boundary (ref plus-boundaries column)))
                  (when (>= height boundary)
                    (let* ((worldx (+ viewx (* (ref plus-planex column) projection)))
                           (worldy (+ viewy (* (ref plus-planey column) projection)))
                           (level (plus-light-level 0 worldx worldy))
                           (shade (max 0 (min (- PLUS_LEVEL_COUNT 1) (round (- level PLUS_LEVEL_MIN)))))
                           (layer (plus-ao-layer worldx worldy (= height boundary)))
                           (phase (bitwise-and column 15)))
                      (setf! framebuffer (+ top-offset column)
                             (plus-plane-color ceiling layer shade
                                               (ref plus-pattern (+ top-pattern phase))))
                      (setf! framebuffer (+ bottom-offset column)
                             (plus-plane-color floor layer shade
                                               (ref plus-pattern (+ bottom-pattern phase)))))))
                (columns (+ column 1)))))
          (rows (+ height 1)))))))

(define (plus-door-edge column height)
  (when plus-enabled
    (let* ((rows (scale-rows height))
           (top (truncate (/ (- viewheight rows) 2)))
           (start (max top 0))
           (end (min viewheight (+ top (quotient (+ rows 63) 64)))))
      (when (and (>= rows 4) (< start end))
        (let* ((pixel (+ (* (+ viewtop start) screenwidth) viewleft column))
               (color (ref framebuffer pixel))
               (shade (plus-color color 48)))
          (when (< (ref plus-luma shade) (ref plus-luma color))
            (let pixels ((row start) (pixel pixel))
              (when (< row end)
                (setf! framebuffer pixel shade)
                (pixels (+ row 1) (+ pixel screenwidth))))))))))
