;;; WL_ACT1.C — door motion

(define (InitStaticList)
  (set! statcount 0))

(define (SpawnStatic tilex tiley type)
  (let ((item (ref statinfo-type type)))
    (setf! stat-tilex statcount tilex)
    (setf! stat-tiley statcount tiley)
    (setf! stat-shape statcount (+ SPR_STAT_0 (ref statinfo-pic type)))
    (setf! stat-flags statcount (if (<= item block) 0 FL_BONUS))
    (setf! stat-item statcount item)
    (when (= item block)
      (actorat-set! tilex tiley MAXACTORS))
    (when (and (treasure-item item) (not loadedgame))
      (set! treasuretotal (+ treasuretotal 1)))
    (set! statcount (+ statcount 1))
    (when (= statcount MAXSTATS)
      (Quit "Too many static objects!\n"))))

(define (PlaceItemType itemtype tilex tiley)
  (let ((type (let scan ((index 0))
                (cond ((= index (vector-length statinfo-type)) -1)
                      ((= (ref statinfo-type index) itemtype) index)
                      (else (scan (+ index 1)))))))
    (when (= type -1)
      (Quit "PlaceItemType: couldn't find type!"))
    (let ((spot (let scan ((index 0))
                  (cond ((= index statcount)
                         (if (= statcount MAXSTATS)
                             -1
                             (begin (set! statcount (+ statcount 1)) index)))
                        ((= (ref stat-shape index) -1) index)
                        (else (scan (+ index 1)))))))
      (when (>= spot 0)
        (setf! stat-shape spot (+ SPR_STAT_0 (ref statinfo-pic type)))
        (setf! stat-tilex spot tilex)
        (setf! stat-tiley spot tiley)
        (setf! stat-flags spot FL_BONUS)
        (setf! stat-item spot itemtype)))))

(define OPENTICS 300)
(define PUSHABLETILE 98)
(define EXITTILE 99)
(define ELEVATORTILE 21)
(define ALTELEVATORTILE 107)

(define di_north 0)
(define di_east 1)
(define di_south 2)
(define di_west 3)

(define dr_normal 0)
(define dr_lock1 1)
(define dr_lock4 4)
(define dr_elevator 5)

(define (dir-dx dir)
  (cond ((= dir di_east) 1) ((= dir di_west) -1) (else 0)))

(define (dir-dy dir)
  (cond ((= dir di_south) 1) ((= dir di_north) -1) (else 0)))

(define dr_open 0)
(define dr_closed 1)
(define dr_opening 2)
(define dr_closing 3)

(define dooraction (make-vector MAXDOORS 1))
(define doorticcount (make-vector MAXDOORS 0))

(define areaconnect (make-vector (* NUMAREAS NUMAREAS) 0))
(define areabyplayer (make-vector NUMAREAS #f))

(define (areabyplayer-at area) (ref areabyplayer area))

(define (connected area other) (ref areaconnect (+ (* area NUMAREAS) other)))

(define (connect! area other delta)
  (setf! areaconnect (+ (* area NUMAREAS) other) (+ (connected area other) delta))
  (setf! areaconnect (+ (* other NUMAREAS) area) (+ (connected other area) delta)))

(define (RecursiveConnect area)
  (let loop ((other 0))
    (when (< other NUMAREAS)
      (when (and (> (connected area other) 0) (not (ref areabyplayer other)))
        (setf! areabyplayer other #t)
        (RecursiveConnect other))
      (loop (+ other 1)))))

(define (clear-areabyplayer)
  (let loop ((area 0))
    (when (< area NUMAREAS)
      (setf! areabyplayer area #f)
      (loop (+ area 1)))))

(define (InitDoorList)
  (clear-areabyplayer)
  (let loop ((index 0))
    (when (< index (vector-length areaconnect))
      (setf! areaconnect index 0)
      (loop (+ index 1))))
  (set! doornum 0))

(define (SpawnDoor tilex tiley vertical lock)
  (when (= doornum MAXDOORS)
    (Quit "64+ doors on level!"))
  (setf! doorposition doornum 0)
  (setf! doorlock doornum lock)
  (setf! doorvertical doornum vertical)
  (setf! doortilex doornum tilex)
  (setf! doortiley doornum tiley)
  (setf! dooraction doornum dr_closed)
  (actorat-set! tilex tiley (bitwise-ior doornum 128))
  (tileset! tilex tiley (bitwise-ior doornum 128))
  (if vertical
      (begin
        (areaset! tilex tiley (areaat (- tilex 1) tiley))
        (tileset! tilex (- tiley 1) (bitwise-ior (tileat tilex (- tiley 1)) 64))
        (tileset! tilex (+ tiley 1) (bitwise-ior (tileat tilex (+ tiley 1)) 64)))
      (begin
        (areaset! tilex tiley (areaat tilex (- tiley 1)))
        (tileset! (- tilex 1) tiley (bitwise-ior (tileat (- tilex 1) tiley) 64))
        (tileset! (+ tilex 1) tiley (bitwise-ior (tileat (+ tilex 1) tiley) 64))))
  (set! doornum (+ doornum 1)))

(define (InitAreas)
  (clear-areabyplayer)
  (setf! areabyplayer player-areanumber #t))

(define (ConnectAreas)
  (clear-areabyplayer)
  (setf! areabyplayer player-areanumber #t)
  (RecursiveConnect player-areanumber))

(define (DoorAreas door delta)
  (let ((tilex (ref doortilex door))
        (tiley (ref doortiley door)))
    (if (ref doorvertical door)
        (connect! (areaat (+ tilex 1) tiley) (areaat (- tilex 1) tiley) delta)
        (connect! (areaat tilex (- tiley 1)) (areaat tilex (+ tiley 1)) delta)))
  (ConnectAreas))

(define (OpenDoor door)
  (if (= (ref dooraction door) dr_open)
      (setf! doorticcount door 0)
      (setf! dooraction door dr_opening)))

(define (actor-crosses-x? index tilex side)
  (and (>= index 0) (< index actorcount)
       (= (tileof (+ (ref actor-x index) (* side MINDIST))) tilex)))

(define (actor-crosses-y? index tiley side)
  (and (>= index 0) (< index actorcount)
       (= (tileof (+ (ref actor-y index) (* side MINDIST))) tiley)))

(define (door-blocked? door)
  (let ((tilex (ref doortilex door))
        (tiley (ref doortiley door)))
    (or (>= (actorat-at tilex tiley) 0)
        (and (= player-tilex tilex) (= player-tiley tiley))
        (if (ref doorvertical door)
            (or (and (= player-tiley tiley)
                     (or (= (tileof (+ player-x MINDIST)) tilex)
                         (= (tileof (- player-x MINDIST)) tilex)))
                (actor-crosses-x? (actorat-at (- tilex 1) tiley) tilex 1)
                (actor-crosses-x? (actorat-at (+ tilex 1) tiley) tilex -1))
            (or (and (= player-tilex tilex)
                     (or (= (tileof (+ player-y MINDIST)) tiley)
                         (= (tileof (- player-y MINDIST)) tiley)))
                (actor-crosses-y? (actorat-at tilex (- tiley 1)) tiley 1)
                (actor-crosses-y? (actorat-at tilex (+ tiley 1)) tiley -1))))))

(define (CloseDoor door)
  (unless (door-blocked? door)
    (let ((tilex (ref doortilex door))
          (tiley (ref doortiley door)))
      (when (ref areabyplayer (areaat tilex tiley))
        (PlaySoundLocTile CLOSEDOORSND tilex tiley))
      (setf! dooraction door dr_closing)
      (actorat-set! tilex tiley (bitwise-ior door 128)))))

(define (OperateDoor door)
  (let ((lock (ref doorlock door)))
    (if (and (>= lock dr_lock1) (<= lock dr_lock4)
             (= 0 (bitwise-and keys (arithmetic-shift 1 (- lock dr_lock1)))))
        (SD_PlaySound NOWAYSND)
      (let ((action (ref dooraction door)))
        (cond ((or (= action dr_closed) (= action dr_closing))
               (OpenDoor door))
              ((or (= action dr_open) (= action dr_opening))
               (CloseDoor door)))))))

(define (DoorOpen door tics)
  (setf! doorticcount door (+ (ref doorticcount door) tics))
  (when (>= (ref doorticcount door) OPENTICS)
    (CloseDoor door)))

(define (DoorOpening door tics)
  (when (= (ref doorposition door) 0)
    (DoorAreas door 1)
    (let ((tilex (ref doortilex door))
          (tiley (ref doortiley door)))
      (when (ref areabyplayer
                 (if (ref doorvertical door)
                     (areaat (+ tilex 1) tiley)
                     (areaat tilex (- tiley 1))))
        (PlaySoundLocTile OPENDOORSND tilex tiley))))
  (let ((position (+ (ref doorposition door) (* tics 1024))))
    (if (>= position 65535)
        (begin
          (setf! doorposition door 65535)
          (setf! doorticcount door 0)
          (setf! dooraction door dr_open)
          (actorat-set! (ref doortilex door) (ref doortiley door) -1))
        (setf! doorposition door position))))

(define (DoorClosing door tics)
  (let ((tilex (ref doortilex door))
        (tiley (ref doortiley door)))
    (if (or (not (= (actorat-at tilex tiley) (bitwise-ior door 128)))
            (and (= player-tilex tilex) (= player-tiley tiley)))
        (OpenDoor door)
        (let ((position (- (ref doorposition door) (* tics 1024))))
          (if (<= position 0)
              (begin
                (setf! doorposition door 0)
                (setf! dooraction door dr_closed)
                (DoorAreas door -1))
              (setf! doorposition door position))))))

(define secretcount 0)
(define pwallstate 0)
(define pwallpos 0)
(define pwallx 0)
(define pwally 0)
(define pwalldir 0)

(define (PushWall checkx checky dir)
  (when (= pwallstate 0)
    (let ((oldtile (tileat checkx checky))
          (aheadx (+ checkx (dir-dx dir)))
          (aheady (+ checky (dir-dy dir))))
      (when (> oldtile 0)
        (if (>= (actorat-at aheadx aheady) 0)
            (SD_PlaySound NOWAYSND)
          (begin
            (actorat-set! aheadx aheady oldtile)
            (tileset! aheadx aheady oldtile)
            (set! secretcount (+ secretcount 1))
            (set! pwallx checkx)
            (set! pwally checky)
            (set! pwalldir dir)
            (set! pwallstate 1)
            (set! pwallpos 0)
            (tileset! checkx checky (bitwise-ior oldtile 192))
            (let ((info (ref mapsegs 1))
                  (offset (* (+ (* checky MAPSIZE) checkx) 2)))
              (setf! info offset 0)
              (setf! info (+ offset 1) 0))
            (SD_PlaySound PUSHWALLSND)))))))

(define (pwall-advance oldtile)
  (let ((nextx (+ pwallx (dir-dx pwalldir)))
        (nexty (+ pwally (dir-dy pwalldir))))
    (set! pwallx nextx)
    (set! pwally nexty)
    (let ((aheadx (+ nextx (dir-dx pwalldir)))
          (aheady (+ nexty (dir-dy pwalldir))))
      (if (>= (actorat-at aheadx aheady) 0)
          (set! pwallstate 0)
          (begin
            (actorat-set! aheadx aheady oldtile)
            (tileset! aheadx aheady oldtile)
            (tileset! nextx nexty (bitwise-ior oldtile 192)))))))

(define (MovePWalls tics)
  (unless (= pwallstate 0)
    (let ((oldblock (truncate (/ pwallstate 128))))
      (set! pwallstate (+ pwallstate tics))
      (unless (= (truncate (/ pwallstate 128)) oldblock)
        (let ((oldtile (bitwise-and (tileat pwallx pwally) 63)))
          (tileset! pwallx pwally 0)
          (actorat-set! pwallx pwally -1)
          (areaset! pwallx pwally (areaat player-tilex player-tiley))
          (if (> pwallstate 256)
              (set! pwallstate 0)
              (pwall-advance oldtile)))))
    (unless (= pwallstate 0)
      (set! pwallpos (bitwise-and (truncate (/ pwallstate 2)) 63)))))

(define (MoveDoors tics)
  (unless victoryflag
    (let loop ((door 0))
      (when (< door doornum)
        (let ((action (ref dooraction door)))
          (cond ((= action dr_open) (DoorOpen door tics))
                ((= action dr_opening) (DoorOpening door tics))
                ((= action dr_closing) (DoorClosing door tics))))
        (loop (+ door 1))))))
