(include "ID_CA.ss")
(include "ID_PM.ss")
(include "WL_DRAW.ss")
(include "ID_VH.ss")
(include "WL_SPRITE.ss")
(include "WL_AGENT.ss")
(include "WL_ACT1.ss")
(include "WL_ACT2.ss")
(include "ID_SD.ss")
(include "ID_MM.ss")
(include "ID_US_1.ss")
(include "WL_STATE.ss")
(include "ID_IN.ss")
(include "WL_GAME.ss")
(include "WL_INTER.ss")
(include "WL_TEXT.ss")
(include "WL_MENU.ss")
(include "WL_MAIN.ss")
(include "ID_VL.ss")
(InitGame)
(set! demoplayback #t)
(CA_CacheMap 0)
(SetupGameLevel)
(define FRAMES 200)
(let loop ((frame 0))
  (when (< frame FRAMES)
    (set! player-angle (- 360 (- 360 (+ 0 (* 0 frame)))))
    (WallRefresh)
    (loop (+ frame 1))))
(displayn (list 'frames FRAMES 'centerheight (ref wallheight 160)))
