(include "ID_CA.ss")
(include "ID_PM.ss")
(include "WL_DRAW.ss")
(include "ID_VH.ss")
(include "WL_SPRITE.ss")
(include "WL_AGENT.ss")
(include "WL_ACT1.ss")
(include "WL_ACT2.ss")
(include "ID_SD.ss")
(include "ID_MM.ss")
(include "ID_US_1.ss")
(include "WL_STATE.ss")
(include "ID_IN.ss")
(include "WL_GAME.ss")
(include "WL_INTER.ss")
(include "WL_TEXT.ss")
(include "WL_MENU.ss")
(include "WL_MAIN.ss")
(include "ID_VL.ss")

(InitGame)
(set! demoplayback #t)
(CA_CacheMap 0)
(SetupGameLevel)
(set! player-tilex (tileof player-x))
(set! player-tiley (tileof player-y))

(define FRAMES 200)
(define WALLS-ONLY #f)

(define visible-total 0)

(set! player-x (+ (* 30 TILEGLOBAL) 32768))
(set! player-y (+ (* 60 TILEGLOBAL) 32768))
(Thrust 0 0)

(let loop ((frame 0))
  (when (< frame FRAMES)
    (Turn 2)
    (MoveDoors 1)
    (spotvis-clear)
    (WallRefresh)
    (unless WALLS-ONLY
      (set! visible-total (+ visible-total (DrawScaleds))))
    (loop (+ frame 1))))

(displayn (list 'frames FRAMES 'tile player-tilex player-tiley 'sprite-pixels sprite-pixels 'visible-total visible-total))
