(include "ID_CA.ss")
(include "ID_PM.ss")
(include "WL_DRAW.ss")
(include "ID_VH.ss")
(include "WL_SPRITE.ss")
(include "WL_AGENT.ss")
(include "WL_ACT1.ss")
(include "WL_ACT2.ss")
(include "ID_SD.ss")
(include "ID_MM.ss")
(include "ID_US_1.ss")
(include "WL_STATE.ss")
(include "ID_IN.ss")
(include "WL_GAME.ss")
(include "WL_INTER.ss")
(include "WL_TEXT.ss")
(include "WL_MENU.ss")
(include "WL_MAIN.ss")
(include "ID_VL.ss")
(InitGame)
(set! demoplayback #t)
(CA_CacheMap 0)
(SetupGameLevel)
(set! player-x (+ (* 30 TILEGLOBAL) 32768))
(set! player-y (+ (* 60 TILEGLOBAL) 32768))
(Thrust 0 0)
(let frames ((frame 0))
  (when (< frame 60)
    (Turn 6)
    (spotvis-clear)
    (WallRefresh)
    (let loop ((index 0))
      (when (< index actorcount)
        (when (actor-visible index)
          (let ((transformed (TransformActor index)))
            (let ((screenx (car transformed)) (height (car (cdr transformed))))
              (when (> height 0)
                (let ((page (+ PMSpriteStart (ref (ref actor-state index) 'shapenum))))
                  (displayn (list 'frame frame 'actor index
                                  'tile (ref actor-tilex index) (ref actor-tiley index)
                                  'screenx screenx 'height height
                                  'wallheight (if (and (>= screenx 0) (< screenx viewwidth))
                                                  (ref wallheight screenx) 'offscreen)
                                  'page page 'pagelen (ref pagelengths page)
                                  'left (readu16 (PM_GetPage page) 0)
                                  'right (readu16 (PM_GetPage page) 2))))))))
        (loop (+ index 1))))
    (frames (+ frame 1))))
