(include "ID_CA.ss")
(include "ID_PM.ss")
(include "WL_DRAW.ss")
(include "ID_VH.ss")
(include "WL_SPRITE.ss")
(include "WL_AGENT.ss")
(include "WL_ACT1.ss")
(include "WL_ACT2.ss")
(include "ID_SD.ss")
(include "ID_MM.ss")
(include "ID_US_1.ss")
(include "WL_STATE.ss")
(include "ID_IN.ss")
(include "WL_GAME.ss")
(include "WL_INTER.ss")
(include "WL_TEXT.ss")
(include "WL_MENU.ss")
(include "WL_MAIN.ss")
(include "ID_VL.ss")
(InitGame)
(set! demoplayback #t)
(CA_CacheMap 0)
(SetupGameLevel)
(set! player-tilex (tileof player-x))
(set! player-tiley (tileof player-y))
(define (count-marks)
  (let loop ((index 0) (total 0))
    (if (= index (* MAPSIZE MAPSIZE))
        total
        (loop (+ index 1) (+ total (ref spotvis index))))))
(define (marked-statics)
  (let loop ((index 0) (total 0))
    (if (= index statcount)
        total
        (loop (+ index 1)
              (+ total (spotvis-at (ref stat-tilex index) (ref stat-tiley index)))))))
(let loop ((frame 0))
  (when (< frame 20)
    (Turn 3)
    (ControlMovement 0 -25)
    (spotvis-clear)
    (WallRefresh)
    (let ((marks (count-marks)) (statics (marked-statics)))
      (displayn (list 'frame frame 'tile player-tilex player-tiley 'angle player-angle
                      'marks marks 'marked-statics statics 'drawn (DrawScaleds))))
    (loop (+ frame 1))))
(displayn (list 'nearest-statics
  (let loop ((index 0) (best 9999) (bx -1) (by -1))
    (if (= index statcount)
        (list best bx by)
        (let ((dx (- (ref stat-tilex index) player-tilex))
              (dy (- (ref stat-tiley index) player-tiley)))
          (let ((distance (+ (* dx dx) (* dy dy))))
            (if (< distance best)
                (loop (+ index 1) distance (ref stat-tilex index) (ref stat-tiley index))
                (loop (+ index 1) best bx by))))))))
