(include "ID_CA.ss")
(include "ID_PM.ss")
(include "WL_DRAW.ss")
(include "ID_VH.ss")
(include "WL_SPRITE.ss")
(include "WL_AGENT.ss")
(include "WL_ACT1.ss")
(include "WL_ACT2.ss")
(include "ID_SD.ss")
(include "ID_MM.ss")
(include "ID_US_1.ss")
(include "WL_STATE.ss")
(include "ID_IN.ss")
(include "WL_GAME.ss")
(include "WL_INTER.ss")
(include "WL_TEXT.ss")
(include "WL_MENU.ss")
(include "WL_MAIN.ss")
(include "ID_VL.ss")
(InitGame)
(set! demoplayback #t)
(CA_CacheMap 0)
(SetupGameLevel)
(define TWOPI 6.28318530717959)

(define (cast-hit pixx)
  (let ((angl (+ (* player-angle 10) (ref pixelangle pixx))))
    (let ((angle (cond ((< angl 0) (+ angl FINEANGLES))
                       ((>= angl ANG360) (- angl FINEANGLES))
                       (else angl))))
      (let ((xtilestep 0) (ytilestep 0) (xstep 0) (ystep 0) (xpartial 0) (ypartial 0))
        (cond
          ((< angle ANG90)
           (set! xtilestep 1) (set! ytilestep -1)
           (set! xstep (ref finetangent (- (- ANG90 1) angle)))
           (set! ystep (- (ref finetangent angle)))
           (set! xpartial xpartialup) (set! ypartial ypartialdown))
          ((< angle ANG180)
           (set! xtilestep -1) (set! ytilestep -1)
           (set! xstep (- (ref finetangent (- angle ANG90))))
           (set! ystep (- (ref finetangent (- (- ANG180 1) angle))))
           (set! xpartial xpartialdown) (set! ypartial ypartialdown))
          ((< angle ANG270)
           (set! xtilestep -1) (set! ytilestep 1)
           (set! xstep (- (ref finetangent (- (- ANG270 1) angle))))
           (set! ystep (ref finetangent (- angle ANG180)))
           (set! xpartial xpartialdown) (set! ypartial ypartialup))
          (else
           (set! xtilestep 1) (set! ytilestep 1)
           (set! xstep (ref finetangent (- angle ANG270)))
           (set! ystep (- (ref finetangent (- (- ANG360 1) angle))))
           (set! xpartial xpartialup) (set! ypartial ypartialup)))
        (let loop ((xtile (+ focaltx xtilestep))
                   (ytile (+ focalty ytilestep))
                   (xintercept (+ (FixedByFrac xstep ypartial) viewx))
                   (yintercept (+ (FixedByFrac ystep xpartial) viewy))
                   (steps 0))
          (if (> steps 200)
              (list 'none)
              (let ((yinttile (tileof yintercept)) (xinttile (tileof xintercept)))
                (if (if (= ytilestep -1) (<= yinttile ytile) (>= yinttile ytile))
                    (let ((tile (if (and (>= xinttile 0) (< xinttile MAPSIZE) (>= ytile 0) (< ytile MAPSIZE)) (tileat xinttile ytile) 1)))
                      (if (> tile 0)
                          (list 'horiz xinttile ytile tile (/ xintercept 65536.0) (* ytile 1.0))
                          (loop xtile (+ ytile ytilestep) (+ xintercept xstep) yintercept (+ steps 1))))
                    (let ((tile (if (and (>= xtile 0) (< xtile MAPSIZE) (>= yinttile 0) (< yinttile MAPSIZE)) (tileat xtile yinttile) 1)))
                      (if (> tile 0)
                          (list 'vert xtile yinttile tile (* xtile 1.0) (/ yintercept 65536.0))
                          (loop (+ xtile xtilestep) ytile xintercept (+ yintercept ystep) (+ steps 1))))))))))))

(define (march-hit pixx)
  (let ((angle (/ (* (+ (* player-angle 10) (ref pixelangle pixx)) TWOPI) 3600)))
    (let ((dx (cos angle)) (dy (- (sin angle))) (vx (/ viewx 65536.0)) (vy (/ viewy 65536.0)))
      (let loop ((distance 0.0))
        (if (> distance 64.0)
            (list 'none)
            (let ((x (+ vx (* dx distance))) (y (+ vy (* dy distance))))
              (let ((tx (truncate x)) (ty (truncate y)))
                (if (or (< tx 0) (>= tx 64) (< ty 0) (>= ty 64) (> (tileat tx ty) 0))
                    (list 'hit tx ty (tileat tx ty) x y distance)
                    (loop (+ distance 0.0005))))))))))

(set! viewsin (ref sintable player-angle))
(set! viewcos (ref costable player-angle))
(set! viewx (- player-x (FixedByFrac focallength viewcos)))
(set! viewy (+ player-y (FixedByFrac focallength viewsin)))
(set! focaltx (tileof viewx))
(set! focalty (tileof viewy))
(set! xpartialdown (- viewx (* focaltx TILEGLOBAL)))
(set! xpartialup (- TILEGLOBAL xpartialdown))
(set! ypartialdown (- viewy (* focalty TILEGLOBAL)))
(set! ypartialup (- TILEGLOBAL ypartialdown))
(WallRefresh)

(for-each (lambda (pixx)
            (displayn (list 'pixx pixx 'angle (+ (* player-angle 10) (ref pixelangle pixx))))
            (displayn (list '  cast (cast-hit pixx) 'height (ref wallheight pixx)))
            (displayn (list '  march (march-hit pixx))))
          (list 319 318 280 200 40 0))
