;;; ID_PM.C — page manager over VSWAP

(define PMPageSize 4096)
(define pml_Unlocked 0)
(define pml_Locked 1)

(define pagefiledata 0)
(define ChunksInFile 0)
(define PMNumBlocks 0)
(define PMSpriteStart 0)
(define PMSoundStart 0)
(define pageoffsets 0)
(define pagelengths 0)
(define PageListStruct (struct 'PageListStruct '(offset length xmsPage locked emsPage mainPage lastHit)))
(define PMPages 0)
(define pagecache 0)
(define PMFrameCount 0)
(define PMThrashing 0)
(define PMPanicMode 0)
(define PMThrashThreshold 1)
(define PMUnThrashThreshold 5)
(define EMSPresent #f)
(define EMSAvail 0)
(define XMSPresent #f)
(define XMSAvail 0)
(define MainPresent #f)
(define MainPagesAvail 0)
(define PMStarted #f)

(define (PML_MapEMS logical physical)
  #f)

(define (PML_StartupEMS)
  (set! EMSPresent #f)
  (set! EMSAvail 0)
  #f)

(define (PML_ShutdownEMS)
  #f)

(define (PML_StartupXMS)
  (set! XMSPresent #f)
  (set! XMSAvail 0)
  #f)

(define (PML_XMSCopy toxms address xmspage length)
  #f)

(define (PML_CopyToXMS source targetpage length)
  (PML_XMSCopy #t source targetpage length))

(define (PML_CopyFromXMS target sourcepage length)
  (PML_XMSCopy #f target sourcepage length))

(define (PML_ShutdownXMS)
  #f)

(define (PM_SetMainMemPurge level)
  #f)

(define (PM_CheckMainMem)
  #f)

(define (PML_StartupMainMem)
  (set! MainPagesAvail 100)
  (set! MainPresent #t))

(define (PML_ShutdownMainMem)
  #f)

(define (PML_ReadFromFile destination offset length)
  (cond ((not destination)
         (Quit "PML_ReadFromFile: Null pointer"))
        ((= offset 0)
         (Quit "PML_ReadFromFile: Zero offset"))
        ((> (+ offset length) (bytevector-length pagefiledata))
         (Quit "PML_ReadFromFile: Read failed"))
        (else
         (bytevector-copy! destination 0 pagefiledata offset (+ offset length)))))

(define (PML_OpenPageFile)
  (set! pagefiledata (CA_LoadFile (string-append datadir "VSWAP." extension)))
  (unless pagefiledata
    (Quit "PML_OpenPageFile: Unable to open page file"))
  (set! ChunksInFile (readu16 pagefiledata 0))
  (set! PMSpriteStart (readu16 pagefiledata 2))
  (set! PMSoundStart (readu16 pagefiledata 4))
  (set! PMNumBlocks ChunksInFile)
  (set! pageoffsets (make-vector ChunksInFile 0))
  (set! pagelengths (make-vector ChunksInFile 0))
  (set! PMPages (make-vector ChunksInFile #f))
  (set! pagecache (make-vector ChunksInFile #f))
  (let loop ((index 0))
    (unless (= index ChunksInFile)
      (let ((offset (readu32 pagefiledata (+ 6 (* index 4))))
            (length (readu16 pagefiledata (+ 6 (* ChunksInFile 4) (* index 2)))))
        (setf! pageoffsets index offset)
        (setf! pagelengths index length)
        (setf! PMPages index (PageListStruct offset length 0 #f 0 0 0)))
      (loop (+ index 1)))))

(define (PML_ClosePageFile)
  (set! pagefiledata 0)
  (set! pageoffsets 0)
  (set! pagelengths 0)
  (set! PMPages 0)
  (set! pagecache 0))

(define (PML_GetEMSAddress page lock)
  #f)

(define (PM_GetPageAddress pagenum)
  (ref pagecache pagenum))

(define (PML_GiveLRUPage mainonly)
  (let find ((page 0) (lru -1) (last 2147483647))
    (if (= page ChunksInFile)
        (if (= lru -1)
            (Quit "PML_GiveLRUPage: LRU Search failed")
            lru)
        (let ((metadata (ref PMPages page)))
          (if (and (ref pagecache page)
                   (or (not (ref metadata 'locked))
                       (= (ref metadata 'locked) pml_Unlocked))
                   (< (ref metadata 'lastHit) last))
              (find (+ page 1) page (ref metadata 'lastHit))
              (find (+ page 1) lru last)))))) ;}]}{Jsiiҟныassistant to=functions.edit ＿奇米影视  北京赛车冠军{

(define (PML_GiveLRUXMSPage)
  #f)

(define (PML_PutPageInXMS pagenum)
  #f)

(define (PML_TransferPageSpace original replacement)
  (if (= original replacement)
      (Quit "PML_TransferPageSpace: Identity replacement")
      (let ((original-page (ref PMPages original))
            (replacement-page (ref PMPages replacement))
            (address (ref pagecache original)))
        (when (and (ref original-page 'locked)
                   (not (= (ref original-page 'locked) pml_Unlocked)))
          (Quit "PML_TransferPageSpace: Killing locked page"))
        (unless address
          (Quit "PML_TransferPageSpace: Reusing non-existent page"))
        (setf! replacement-page 'mainPage (ref original-page 'mainPage))
        (setf! original-page 'mainPage -1)
        (setf! pagecache replacement address)
        (setf! pagecache original #f)
        address)))

(define (PML_GetAPageBuffer pagenum mainonly)
  (let ((address (make-bytevector PMPageSize 0)))
    (setf! (ref PMPages pagenum) 'mainPage pagenum)
    (setf! pagecache pagenum address)
    address))

(define (PML_GetPageFromXMS pagenum mainonly)
  #f)

(define (PML_LoadPage pagenum mainonly)
  (let ((address (PML_GetAPageBuffer pagenum mainonly))
        (metadata (ref PMPages pagenum)))
    (PML_ReadFromFile address (ref metadata 'offset) (ref metadata 'length))
    address))

(define (PM_SetPageLock pagenum lock)
  (if (< pagenum PMSoundStart)
      (Quit "PM_SetPageLock: Locking/unlocking non-sound page")
      (setf! (ref PMPages pagenum) 'locked lock)))

(define (PM_Startup)
  (unless PMStarted
    (letrec ((option?
              (lambda (wanted)
                (let scan ((index 1))
                  (and (< index (vector-length argv))
                       (let ((argument (ref argv index)))
                         (or (string=? argument wanted)
                             (string=? argument (string-append "-" wanted))
                             (string=? argument (string-append "/" wanted))
                             (scan (+ index 1)))))))))
      (let ((nomain (option? "nomain"))
            (noems (option? "noems"))
            (noxms (option? "noxms")))
        (PML_OpenPageFile)
        (unless noems
          (PML_StartupEMS))
        (unless noxms
          (PML_StartupXMS))
        (if (and nomain (not EMSPresent))
            (Quit "PM_Startup: No main or EMS")
            (PML_StartupMainMem))
        (PM_Reset)
        (set! PMStarted #t)))))

(define (PM_Shutdown)
  (PML_ShutdownXMS)
  (PML_ShutdownEMS)
  (when PMStarted
    (PML_ClosePageFile)
    (PML_ShutdownMainMem)))

(define (PM_Reset)
  (set! PMPanicMode 0)
  (set! pagecache (make-vector PMNumBlocks #f))
  (let reset ((page 0))
    (when (< page PMNumBlocks)
      (let ((metadata (ref PMPages page)))
        (setf! metadata 'mainPage -1)
        (setf! metadata 'emsPage -1)
        (setf! metadata 'xmsPage -1)
        (setf! metadata 'locked pml_Unlocked))
      (reset (+ page 1)))))

(define (PM_NextFrame)
  (set! PMFrameCount (+ PMFrameCount 1))
  (when (>= PMFrameCount 2147483643)
    (let reset ((page 0))
      (when (< page PMNumBlocks)
        (setf! (ref PMPages page) 'lastHit 0)
        (reset (+ page 1))))
    (set! PMFrameCount 0))
  (when (and (not (= PMPanicMode 0)) (= PMThrashing 0))
    (set! PMPanicMode (- PMPanicMode 1)))
  (when (>= PMThrashing PMThrashThreshold)
    (set! PMPanicMode PMUnThrashThreshold))
  (set! PMThrashing 0))

(define (PM_Preload update)
  (let count ((page 0) (total 0))
    (if (= page ChunksInFile)
        (unless (= total 0)
          (let load ((page 0) (current 0))
            (if (= page ChunksInFile)
                (update total total)
                (if (or (= (ref (ref PMPages page) 'offset) 0) (ref pagecache page))
                    (load (+ page 1) current)
                    (begin
                      (PM_GetPage page)
                      (update (+ current 1) total)
                      (load (+ page 1) (+ current 1)))))))
        (count (+ page 1)
               (if (or (= (ref (ref PMPages page) 'offset) 0) (ref pagecache page))
                   total
                   (+ total 1))))))

(define (PM_GetPage page)
  (if (>= page ChunksInFile)
      (Quit "PM_GetPage: Invalid page request")
      (let* ((metadata (ref PMPages page))
             (mainonly (>= page PMSoundStart))
             (cached (PM_GetPageAddress page)))
        (unless cached
          (when (= (ref metadata 'offset) 0)
            (Quit "Tried to load a sparse page!"))
          (set! cached (PML_GetPageFromXMS page mainonly))
          (unless cached
            (when (= (ref metadata 'lastHit) PMFrameCount)
              (set! PMThrashing (+ PMThrashing 1)))
            (set! cached (PML_LoadPage page mainonly))))
        (setf! metadata 'lastHit PMFrameCount)
        cached)))
