;;; ID_VH.C — pic and font drawing into the framebuffer

(define STARTFONT 1)
(define STARTFONTM 3)
(define STARTPICS 3)
(define STARTTILE8 135)
(define STARTTILE8M 136)

(define fontnumber 0)
(define fontcolor 15)
(define px 0)
(define py 0)

(define fonts (make-vector 2 0))
(define mfonts (make-vector 2 0))
(define tile8s 0)
(define tile8ms 0)

(define (font-height font) (readu16 font 0))
(define (font-location font ch) (readu16 font (+ 2 (* ch 2))))
(define (font-width font ch) (ref font (+ 514 ch)))

(define (VH_Plot x y color)
  (when (and (>= x 0) (< x screenwidth) (>= y 0) (< y screenheight))
    (setf! framebuffer (+ (* y screenwidth) x) color)))

;; ID_VH.C dirty-block state (16x16 pixel blocks).  This is distinct from
;; framebuffer RAM and is consumed by VW_UpdateScreen.
(define UPDATEWIDE (quotient (+ screenwidth 15) 16))
(define UPDATEHIGH (quotient (+ screenheight 15) 16))
(define update (make-bytevector (* UPDATEWIDE UPDATEHIGH) 0))

(define (VW_MarkUpdateBlock x1 y1 x2 y2)
  (let ((xt1 (max 0 (arithmetic-shift x1 -4)))
        (yt1 (max 0 (arithmetic-shift y1 -4)))
        (xt2 (min (- UPDATEWIDE 1) (arithmetic-shift x2 -4)))
        (yt2 (min (- UPDATEHIGH 1) (arithmetic-shift y2 -4))))
    (if (or (>= xt1 UPDATEWIDE) (>= yt1 UPDATEHIGH) (< xt2 0) (< yt2 0))
        #f
        (begin
          (let rows ((row yt1))
            (when (<= row yt2)
              (let columns ((column xt1))
                (when (<= column xt2)
                  (setf! update (+ (* row UPDATEWIDE) column) 1)
                  (columns (+ column 1))))
              (rows (+ row 1))))
          #t))))

;; ID_VH.C: VWB_DrawTile8 -> LatchDrawChar.  Tile data was copied into the
;; latch by LoadLatchMem, so this must use that RAM rather than redraw source.
(define (VWB_DrawTile8 x y tile)
  (when (VW_MarkUpdateBlock x y (+ x 7) (+ y 7))
    (VL_LatchToScreen (+ (ref latchpics 0) (* tile 16)) 2 8 x y)))

(define (VWB_DrawTile8M x y tile)
  (when (VW_MarkUpdateBlock x y (+ x 7) (+ y 7))
    (when (eqv? tile8ms 0)
      (set! tile8ms (CA_CacheGrChunk STARTTILE8M)))
    (let planes ((plane 0))
      (when (< plane 4)
        (let rows ((row 0))
          (when (< row 8)
            (let pairs ((pair 0))
              (when (< pair 2)
                (VH_Plot (+ x (* pair 4) plane) (+ y row)
                         (ref tile8ms (+ (* tile 64) (* plane 16) (* row 2) pair)))
                (pairs (+ pair 1))))
            (rows (+ row 1))))
        (planes (+ plane 1))))))

(define (VWB_DrawPic x y chunknum)
  (let* ((left (bitwise-and x -8))
         (pic (ref pictable (- chunknum STARTPICS)))
         (width (ref pic 'width))
         (height (ref pic 'height)))
    (when (VW_MarkUpdateBlock left y (+ left width -1) (+ y height -1))
      (VH_DrawPicAt left y chunknum))))

(define (VWB_Bar x y width height color)
  (when (VW_MarkUpdateBlock x y (+ x width) (+ y height -1))
    (let rows ((row 0))
      (when (< row height)
        (let cols ((column 0))
          (when (< column width)
            (VH_Plot (+ x column) (+ y row) color)
            (cols (+ column 1))))
        (rows (+ row 1))))))

(define (VWB_Hlin x1 x2 y color)
  (when (VW_MarkUpdateBlock x1 y x2 y)
    (let loop ((x x1))
      (when (<= x x2)
        (VH_Plot x y color)
        (loop (+ x 1))))))

(define (VWB_Vlin y1 y2 x color)
  (when (VW_MarkUpdateBlock x y1 x y2)
    (let loop ((y y1))
      (when (<= y y2)
        (VH_Plot x y color)
        (loop (+ y 1))))))

(define (VWB_Plot x y color)
  (when (VW_MarkUpdateBlock x y x y)
    (VH_Plot x y color)))

;; ID_VH.C: copy every marked 16x16 block from the draw page to the display
;; page, then consume the mark.
(define (VW_UpdateScreen)
  (let blocks ((index 0))
    (when (< index (* UPDATEWIDE UPDATEHIGH))
      (when (not (= (ref update index) 0))
        (let ((left (* (remainder index UPDATEWIDE) 16))
              (top (* (quotient index UPDATEWIDE) 16)))
          (let rows ((y top))
            (when (< y (min (+ top 16) screenheight))
              (let columns ((x left))
                (when (< x (min (+ left 16) screenwidth))
                  (setf! displayframebuffer (+ (* y screenwidth) x)
                         (ref framebuffer (+ (* y screenwidth) x)))
                  (columns (+ x 1))))
              (rows (+ y 1))))
          (setf! update index 0)))
      (blocks (+ index 1)))))

(define (VH_DrawPicAt left y chunknum)
  (let ((pic (ref pictable (- chunknum STARTPICS)))
        (source (CA_CacheGrChunk chunknum)))
    (let ((width (ref pic 'width))
          (height (ref pic 'height)))
      (let ((span (truncate (/ width 4))))
        (let planes ((plane 0))
          (when (< plane 4)
            (let rows ((row 0))
              (when (< row height)
                (let cols ((col 0))
                  (when (< col span)
                    (VH_Plot (+ left (* col 4) plane)
                             (+ y row)
                             (ref source (+ (* plane span height) (* row span) col)))
                    (cols (+ col 1))))
                (rows (+ row 1))))
            (planes (+ plane 1))))))))

;; ID_VH.C latch layout.  These offsets are VGA byte offsets, not linear
;; framebuffer pixel indices.
(define FREESTART (* 80 208 3))
(define NUMTILE8 72)
(define LATCHPICS_LUMP_START 91)
(define LATCHPICS_LUMP_END 134)
(define latchpics (make-vector 100 0))
(define freelatch FREESTART)

(define (LatchDrawPic x y picnum)
  (let ((pic (ref pictable (- picnum STARTPICS))))
    (VL_LatchToScreen (ref latchpics (+ 2 (- picnum LATCHPICS_LUMP_START)))
                      (truncate (/ (ref pic 'width) 4))
                      (ref pic 'height) (* x 8) y)))

;; ID_VH.C: LoadLatchMem.  Populate the latch planes before any latch draw;
;; retain the per-tile and per-picture transfer sequence and offsets.
(define (LoadLatchMem)
  (setf! latchpics 0 freelatch)
  (let ((tiles (CA_CacheGrChunk STARTTILE8)))
    (let tiles-loop ((tile 0) (dest freelatch))
      (if (= tile NUMTILE8)
          (set! freelatch dest)
          (begin
            (VL_MemToLatch (bytevector-copy tiles (* tile 64) (* (+ tile 1) 64)) 8 8 dest)
            (tiles-loop (+ tile 1) (+ dest 16))))))
  (let pics-loop ((picnum LATCHPICS_LUMP_START) (dest freelatch))
    (if (> picnum LATCHPICS_LUMP_END)
        (set! freelatch dest)
        (let* ((pic (ref pictable (- picnum STARTPICS)))
               (width (ref pic 'width))
               (height (ref pic 'height)))
          (setf! latchpics (+ 2 (- picnum LATCHPICS_LUMP_START)) dest)
          (VL_MemToLatch (CA_CacheGrChunk picnum) width height dest)
          (pics-loop (+ picnum 1) (+ dest (* (truncate (/ width 4)) height)))))))

(define (VWB_DrawPic x y chunknum)
  (let* ((left (bitwise-and x -8))
         (pic (ref pictable (- chunknum STARTPICS)))
         (width (ref pic 'width))
         (height (ref pic 'height)))
    (when (VW_MarkUpdateBlock left y (+ left width -1) (+ y height -1))
      (VH_DrawPicAt left y chunknum))))

(define (VH_Font)
  (let ((chunk (+ STARTFONT fontnumber)))
    (when (eqv? (ref fonts fontnumber) 0)
      (setf! fonts fontnumber (CA_CacheGrChunk chunk)))
    (ref fonts fontnumber)))

(define (VH_MFont)
  (let ((chunk (+ STARTFONTM fontnumber)))
    (when (eqv? (ref mfonts fontnumber) 0)
      (setf! mfonts fontnumber (CA_CacheGrChunk chunk)))
    (ref mfonts fontnumber)))

(define (VW_DrawPropChar font ch)
  (let ((width (font-width font ch))
        (height (font-height font))
        (location (font-location font ch)))
    (let cols ((col 0))
      (when (< col width)
        (let rows ((row 0))
          (when (< row height)
            (unless (= 0 (ref font (+ location (* row width) col)))
              (VH_Plot (+ px col) (+ py row) fontcolor))
            (rows (+ row 1))))
        (cols (+ col 1))))
    (set! px (+ px width))))

(define (VW_DrawPropString text)
  (let ((font (VH_Font)))
    (let loop ((index 0))
      (when (< index (string-length text))
        (VW_DrawPropChar font (char->integer (string-ref text index)))
        (loop (+ index 1))))))

(define (VWB_DrawPropString text)
  (let ((x px)
        (height (font-height (VH_Font))))
    (VW_DrawPropString text)
    (VW_MarkUpdateBlock x py (- px 1) (+ py height -1))))

(define (VL_MungePic source width height)
  (unless (= (remainder width 4) 0)
    (Quit "VL_MungePic: Not divisable by 4!"))
  (let ((copy (bytevector-copy source 0 (* width height)))
        (plane-width (quotient width 4)))
    (let planes ((plane 0) (dest 0))
      (if (< plane 4)
          (let rows ((row 0) (dest dest))
            (if (< row height)
                (let cols ((column 0) (dest dest))
                  (if (< column plane-width)
                      (begin
                        (setf! source dest (ref copy (+ (* row width) (* column 4) plane)))
                        (cols (+ column 1) (+ dest 1)))
                      (rows (+ row 1) dest)))
                (planes (+ plane 1) dest)))
          source))))

(define (VW_DrawColorPropString text)
  (let ((font (VH_Font)))
    (let chars ((index 0))
      (when (< index (string-length text))
        (let* ((ch (char->integer (string-ref text index)))
               (width (font-width font ch))
               (height (font-height font))
               (location (font-location font ch))
               (offset (if (even? height) 1 0)))
          (let cols ((col 0))
            (when (< col width)
              (let rows ((row 0))
                (when (< row height)
                  (unless (= 0 (ref font (+ location (* row width) col)))
                    (VH_Plot (+ px col) (+ py row)
                             (modulo (+ fontcolor (truncate (/ (+ row offset) 2))) 256)))
                  (rows (+ row 1))))
              (cols (+ col 1))))
          (set! px (+ px width)))
        (chars (+ index 1))))))

;; The DOS code drew the bar into the hidden page that FizzleFade then copied from. There is one
;; framebuffer here, so the bar goes into a snapshot of it.
(define (fizzle-source left top width height color)
  (let ((source (bytevector-copy framebuffer 0 (bytevector-length framebuffer))))
    (let rows ((row 0))
      (when (< row height)
        (let cols ((col 0))
          (when (< col width)
            (setf! source (+ (* (+ top row) screenwidth) left col) color)
            (cols (+ col 1))))
        (rows (+ row 1))))
    source))

;; ID_VH.C:471-547. The DOS routine copied one pixel per step from a hidden page to the
;; display; here source is a framebuffer-sized snapshot copied into the framebuffer. The pixel
;; order is the same 17-bit shift register, and one frame passes per pixperframe pixels.
(define (FizzleFade source left top width height frames abortable)
  (let ((pixperframe (truncate (/ 64000 frames))))
    (IN_StartAck)
    (let per-frame ((rndval 1))
      (if (and abortable (IN_CheckAck))
          #t
          (let pixels ((count 0) (rndval rndval))
            (if (>= count pixperframe)
                (begin (VL_WaitVBL 1) (per-frame rndval))
                (let ((y (bitwise-and (- (bitwise-and rndval 255) 1) 255))
                      (x (bitwise-and (arithmetic-shift rndval -8) 65535))
                      (next (let ((shifted (arithmetic-shift rndval -1)))
                              (if (= 1 (bitwise-and rndval 1))
                                  (bitwise-xor shifted 73728)
                                  shifted))))
                  (when (and (<= x width) (<= y height))
                    (let ((offset (+ (* (+ top y) screenwidth) left x)))
                      (when (< offset (bytevector-length framebuffer))
                        (setf! framebuffer offset (ref source offset)))))
                  (if (= next 1)
                      #f
                      (pixels (+ count 1) next)))))))))

(define (VWL_MeasureString text font)
  (let loop ((index 0) (total 0))
    (if (= index (string-length text))
        (list total (font-height font))
        (loop (+ index 1)
              (+ total (font-width font (char->integer (string-ref text index))))))))

(define (VW_MeasurePropString text)
  (VWL_MeasureString text (VH_Font)))

(define (VW_MeasureMPropString text)
  (VWL_MeasureString text (VH_MFont)))
