;;; ID_VL.C — palette and framebuffer output

(define PALETTEBYTES 768)
(define GAMEPALOBJ "GAMEPAL.OBJ")

(define gamepal 0)
(define curpal (make-bytevector PALETTEBYTES 0))
;; The displayed VGA page is separate from the page currently being drawn.
(define displayframebuffer (make-bytevector (* screenwidth screenheight) 0))
(define screenfaded #f)
(define fastpalette #f)
(define bordercolor 0)
(define splitScreenLine 0)
(define linewidth 80)
(define ylookup (make-vector 200 0))

;; Set by the entry point to a procedure that shows the current frame; headless scripts leave it #f.
(define vl-vbl #f)

(define (VL_Startup)
  #f)

(define (VL_Shutdown)
  (VL_SetTextMode))

(define (VL_SetTextMode)
  #f)

(define (VL_SetVGAPlaneMode)
  (VL_DePlaneVGA)
  (VL_SetLineWidth 40))

(define (VL_ClearVideo color)
  (let loop ((index 0))
    (when (< index (bytevector-length framebuffer))
      (setf! framebuffer index color)
      (loop (+ index 1)))))

(define (VL_DePlaneVGA)
  (VL_ClearVideo 0))

(define (VL_SetLineWidth width)
  (set! linewidth (* width 2))
  (let loop ((row 0) (offset 0))
    (when (< row (vector-length ylookup))
      (setf! ylookup row offset)
      (loop (+ row 1) (+ offset linewidth)))))

(define (VL_WaitVBL count)
  (when vl-vbl
    (vl-vbl count)))

(define (VL_SetSplitScreen linenum)
  (VL_WaitVBL 1)
  (set! splitScreenLine linenum))

(define (object-name? object offset count name)
  (if (< count (string-length name))
      #f
      (let characters ((index 0))
        (if (= index (string-length name))
            (let spaces ((index index))
              (if (= index count)
                  #t
                  (and (= (ref object (+ offset index)) 32)
                       (spaces (+ index 1)))))
            (and (= (ref object (+ offset index))
                    (char->integer (string-ref name index)))
                 (characters (+ index 1)))))))

(define (gamepal-object? object)
  (if (< (bytevector-length object) 4)
      #f
      (let* ((length (readu16 object 1))
             (end (+ 3 length)))
        (and (= (ref object 0) #x80)
             (>= length 2)
             (<= end (bytevector-length object))
             (= length (+ (ref object 3) 2))
             (object-name? object 4 (ref object 3) "GAMEPAL.BIN")))))

(define (gamepal-from-object object)
  (if (not (gamepal-object? object))
      #f
      (let records ((offset 0))
        (if (>= offset (bytevector-length object))
            #f
            (if (< (- (bytevector-length object) offset) 3)
                #f
                (let* ((length (readu16 object (+ offset 1)))
                       (end (+ offset 3 length)))
                  (if (or (< length 1) (> end (bytevector-length object)))
                      #f
                      (if (and (= (ref object offset) #xa0)
                               (= (- length 4) PALETTEBYTES)
                               (= (ref object (+ offset 3)) 1)
                               (= (ref object (+ offset 4)) 0)
                               (= (ref object (+ offset 5)) 0))
                          (bytevector-copy object (+ offset 6) (- end 1))
                          (records end)))))))))

(define (VL_LoadPalette)
  (let* ((path (string-append datadir GAMEPALOBJ))
         (object (CA_LoadFile path)))
    (unless object
      (Quit (string-append "Can't open " path ". Copy WOLFSRC/OBJ/GAMEPAL.OBJ from the Wolf3D source release here.")))
    (let ((palette (gamepal-from-object object)))
      (unless palette
        (Quit (string-append path " is not a supported GAMEPAL.OBJ")))
      (set! gamepal palette)
      (plus-palette-loaded)
      (VL_SetPalette palette))))

(define (VL_SetColor color red green blue)
  (let ((offset (* color 3)))
    (setf! curpal offset red)
    (setf! curpal (+ offset 1) green)
    (setf! curpal (+ offset 2) blue)
    (dos:set-palette curpal)))


(define (VL_GetColor color)
  (let ((offset (* color 3)))
    (tuple (ref curpal offset)
           (ref curpal (+ offset 1))
           (ref curpal (+ offset 2)))))

(define (VL_SetPalette palette)
  (let loop ((index 0))
    (when (< index PALETTEBYTES)
      (setf! curpal index (ref palette index))
      (loop (+ index 1))))
  (dos:set-palette curpal))

(define (VL_GetPalette palette)
  (let loop ((index 0))
    (when (< index PALETTEBYTES)
      (setf! palette index (ref curpal index))
      (loop (+ index 1)))))

(define (VL_FillPalette red green blue)
  (let ((filled (make-bytevector PALETTEBYTES 0)))
    (let loop ((color 0))
      (when (< color 256)
        (setf! filled (* color 3) red)
        (setf! filled (+ (* color 3) 1) green)
        (setf! filled (+ (* color 3) 2) blue)
        (loop (+ color 1))))
    (VL_SetPalette filled)))

(define (VL_FadeOut start end red green blue steps)
  (VL_WaitVBL 1)
  (let ((original (bytevector-copy curpal 0 PALETTEBYTES))
        (faded (bytevector-copy curpal 0 PALETTEBYTES)))
    (let frames ((frame 0))
      (when (< frame steps)
        (let colors ((color start))
          (when (<= color end)
            (let ((offset (* color 3)))
              (setf! faded offset (+ (ref original offset)
                                     (truncate (/ (* (- red (ref original offset)) frame) steps))) )
              (setf! faded (+ offset 1) (+ (ref original (+ offset 1))
                                           (truncate (/ (* (- green (ref original (+ offset 1))) frame) steps))))
              (setf! faded (+ offset 2) (+ (ref original (+ offset 2))
                                           (truncate (/ (* (- blue (ref original (+ offset 2))) frame) steps)))))
            (colors (+ color 1))))
        (VL_WaitVBL 1)
        (VL_SetPalette faded)
        (frames (+ frame 1)))))
  (VL_FillPalette red green blue)
  (set! screenfaded #t))

(define (VL_FadeIn start end palette steps)
  (VL_WaitVBL 1)
  (let ((original (bytevector-copy curpal 0 PALETTEBYTES))
        (faded (bytevector-copy curpal 0 PALETTEBYTES))
        (first (* start 3))
        (last (+ (* end 3) 2)))
    (let frames ((frame 0))
      (when (< frame steps)
        (let bytes ((index first))
          (when (<= index last)
            (setf! faded index (+ (ref original index)
                                  (truncate (/ (* (- (ref palette index) (ref original index)) frame) steps))))
            (bytes (+ index 1))))
        (VL_WaitVBL 1)
        (VL_SetPalette faded)
        (frames (+ frame 1)))))
  (VL_SetPalette palette)
  (set! screenfaded #f))

(define (VL_TestPaletteSet)
  (let ((palette1 (make-bytevector PALETTEBYTES 0))
        (palette2 (make-bytevector PALETTEBYTES 0)))
    (let loop ((index 0))
      (when (< index PALETTEBYTES)
        (setf! palette1 index (remainder index 256))
        (loop (+ index 1))))
    (set! fastpalette #t)
    (VL_SetPalette palette1)
    (VL_GetPalette palette2)
    (unless (equal? palette1 palette2)
      (set! fastpalette #f))))

(define (VL_ColorBorder color)
  (set! bordercolor color))

(define (VL_Plot x y color)
  (setf! framebuffer (+ (* y screenwidth) x) color))

(define (VL_Hlin x y width color)
  (let loop ((column 0))
    (when (< column width)
      (VL_Plot (+ x column) y color)
      (loop (+ column 1)))))

(define (VL_Vlin x y height color)
  (let loop ((row 0))
    (when (< row height)
      (VL_Plot x (+ y row) color)
      (loop (+ row 1)))))

(define (VL_Bar x y width height color)
  (let loop ((row 0))
    (when (< row height)
      (VL_Hlin x (+ y row) width color)
      (loop (+ row 1)))))

;; Four 64 KiB VGA planes retain the latch RAM used by ID_VH.C.  The visible
;; framebuffer is deliberately separate: these transfers must not be replaced
;; by direct picture drawing.
(define LATCHPLANEWORDS 65536)
(define latch-planes
  (vector (make-bytevector LATCHPLANEWORDS 0)
          (make-bytevector LATCHPLANEWORDS 0)
          (make-bytevector LATCHPLANEWORDS 0)
          (make-bytevector LATCHPLANEWORDS 0)))

;; ID_VL.C: VL_MemToLatch.  Source is four contiguous planar runs; destination
;; is the same VGA offset in each selected plane.
(define (VL_MemToLatch source width height dest)
  (let ((count (* (truncate (/ (+ width 3) 4)) height)))
    (let planes ((plane 0))
      (when (< plane 4)
        (let bytes ((index 0))
          (when (< index count)
            (setf! (ref latch-planes plane) (+ dest index)
                   (ref source (+ (* plane count) index)))
            (bytes (+ index 1))))
        (planes (+ plane 1))))))

;; ID_VL.C: VL_MemToScreen. Source is four contiguous planar runs; plane
;; zero begins at x's VGA plane, so each successive run advances one pixel.
(define (VL_MemToScreen source width height x y)
  (let* ((bytes-wide (quotient width 4))
         (count (* bytes-wide height)))
    (let planes ((plane 0))
      (when (< plane 4)
        (let rows ((row 0))
          (when (< row height)
            (let bytes ((byte 0))
              (when (< byte bytes-wide)
                (VL_Plot (+ x (* byte 4) plane) (+ y row)
                         (ref source (+ (* plane count) (* row bytes-wide) byte)))
                (bytes (+ byte 1))))
            (rows (+ row 1))))
        (planes (+ plane 1))))))

;; ID_VL.C names this a masked transfer, but its mask initialization is
;; commented out; its data-copy loop is the same four-plane transfer.
(define (VL_MaskedToScreen source width height x y)
  (VL_MemToScreen source width height x y))

;; ID_VL.C: VL_LatchToScreen, VGA write mode 1 expressed over the linear
;; framebuffer: each latched planar byte supplies its corresponding pixel.
(define (VL_LatchToScreen source width height x y)
  (let rows ((row 0))
    (when (< row height)
      (let bytes ((byte 0))
        (when (< byte width)
          (let planes ((plane 0))
            (when (< plane 4)
              (let ((px (+ x (* byte 4) plane))
                    (py (+ y row)))
                (when (and (>= px 0) (< px screenwidth) (>= py 0) (< py screenheight))
                  (setf! framebuffer (+ (* py screenwidth) px)
                         (ref (ref latch-planes plane) (+ source (* row width) byte)))))
              (planes (+ plane 1))))
          (bytes (+ byte 1))))
      (rows (+ row 1)))))

(define (VL_ScreenToScreen source dest width height)
  (let ((copy (bytevector-copy framebuffer 0 (bytevector-length framebuffer)))
        (source-y (quotient source linewidth))
        (source-x (* (remainder source linewidth) 4))
        (dest-y (quotient dest linewidth))
        (dest-x (* (remainder dest linewidth) 4)))
    (let rows ((row 0))
      (when (< row height)
        (let columns ((column 0))
          (when (< column (* width 4))
            (setf! framebuffer
                   (+ (* (+ dest-y row) screenwidth) dest-x column)
                   (ref copy (+ (* (+ source-y row) screenwidth) source-x column)))
            (columns (+ column 1))))
        (rows (+ row 1))))))

(define (VL_SizeTile8String text)
  (list (* 8 (string-length text)) 8))

(define (VL_DrawLatch8String text tile8 printx printy)
  (let chars ((index 0))
    (when (< index (string-length text))
      (VL_LatchToScreen (+ tile8 (* (char->integer (string-ref text index)) 16))
                        2 8 (+ printx (* index 8)) printy)
      (chars (+ index 1)))))

(define (VL_DrawTile8String text tile8 printx printy)
  (let chars ((index 0))
    (when (< index (string-length text))
      (let ((base (* (char->integer (string-ref text index)) 64)))
        (let planes ((plane 0))
          (when (< plane 4)
            (let rows ((row 0))
              (when (< row 8)
                (let pairs ((pair 0))
                  (when (< pair 2)
                    (VL_Plot (+ printx (* index 8) (* pair 4) plane)
                             (+ printy row)
                             (ref tile8 (+ base (* plane 16) (* row 2) pair)))
                    (pairs (+ pair 1))))
                (rows (+ row 1))))
            (planes (+ plane 1)))))
      (chars (+ index 1)))))

(define (VL_MaskedToScreen source width height x y)
  (VL_MemToScreen source width height x y))

(define (VL_MemToScreen source width height x y)
  (let ((plane-width (quotient width 4)))
    (let planes ((plane 0))
      (when (< plane 4)
        (let rows ((row 0))
          (when (< row height)
            (let columns ((column 0))
              (when (< column plane-width)
                (VL_Plot (+ x (* column 4) plane)
                         (+ y row)
                         (ref source (+ (* plane plane-width height) (* row plane-width) column)))
                (columns (+ column 1))))
            (rows (+ row 1))))
        (planes (+ plane 1))))))

(define (VL_SetColor color red green blue)
  (setf! curpal (* color 3) red)
  (setf! curpal (+ (* color 3) 1) green)
  (setf! curpal (+ (* color 3) 2) blue)
  (dos:set-palette curpal))

(define (VL_GetColor color)
  (list (ref curpal (* color 3))
        (ref curpal (+ (* color 3) 1))
        (ref curpal (+ (* color 3) 2))))

(define (VL_FadeOut start end red green blue steps)
  (let ((palette1 (make-bytevector PALETTEBYTES 0))
        (palette2 (make-bytevector PALETTEBYTES 0))
        (target (vector red green blue)))
    (VL_WaitVBL 1)
    (VL_GetPalette palette1)
    (VL_GetPalette palette2)
    (let steploop ((step 0))
      (when (< step steps)
        (let colors ((color start))
          (when (<= color end)
            (let channels ((channel 0))
              (when (< channel 3)
                (let* ((slot (+ (* color 3) channel))
                       (orig (ref palette1 slot))
                       (delta (- (ref target channel) orig)))
                  (setf! palette2 slot (+ orig (truncate (/ (* delta step) steps)))))
                (channels (+ channel 1))))
            (colors (+ color 1))))
        (VL_WaitVBL 1)
        (VL_SetPalette palette2)
        (steploop (+ step 1)))))
  (VL_FillPalette red green blue)
  (set! screenfaded #t))

(define (VL_FadeIn start end palette steps)
  (let ((palette1 (make-bytevector PALETTEBYTES 0))
        (palette2 (make-bytevector PALETTEBYTES 0)))
    (VL_WaitVBL 1)
    (VL_GetPalette palette1)
    (VL_GetPalette palette2)
    (let ((first (* start 3))
          (last (+ (* end 3) 2)))
      (let steploop ((step 0))
        (when (< step steps)
          (let slots ((slot first))
            (when (<= slot last)
              (let ((delta (- (ref palette slot) (ref palette1 slot))))
                (setf! palette2 slot (+ (ref palette1 slot) (truncate (/ (* delta step) steps)))))
              (slots (+ slot 1))))
          (VL_WaitVBL 1)
          (VL_SetPalette palette2)
          (steploop (+ step 1))))))
  (VL_SetPalette palette)
  (set! screenfaded #f))

(define (palette-red index) (* 4 (ref gamepal (* index 3))))
(define (palette-green index) (* 4 (ref gamepal (+ (* index 3) 1))))
(define (palette-blue index) (* 4 (ref gamepal (+ (* index 3) 2))))

(define (VL_WritePPM path buffer width height)
  (let ((out (open-output-file path)))
    (display "P6\n" out)
    (display width out)
    (display " " out)
    (display height out)
    (display "\n255\n" out)
    (let ((row (make-bytevector (* width 3) 0)))
      (let rows ((y 0))
        (when (< y height)
          (let cols ((x 0))
            (when (< x width)
              (let ((value (ref buffer (+ (* y width) x))))
                (setf! row (* x 3) (palette-red value))
                (setf! row (+ (* x 3) 1) (palette-green value))
                (setf! row (+ (* x 3) 2) (palette-blue value)))
              (cols (+ x 1))))
          (write-bytes row out)
          (rows (+ y 1)))))
    (close-output-port out)))
