(define plus-enabled
  (let scan ((index 0))
    (if (= index (vector-length argv))
        #f
        (or (string=? (ref argv index) "--plus") (scan (+ index 1))))))

(define PLUS_LIGHT_RADIUS 6)
(define PLUS_LIGHT_LEVELS 8)
(define PLUS_EMISSIVE_LUMA 48)
(define PLUS_FLASH_LEVELS 32)
(define PLUS_FLASH_TICS 8)
(define PLUS_FLASH_COUNT 4)
(define PLUS_AO_RANGE 21)
(define PLUS_AO_DEPTH 48)

(define plus-shades (make-vector 20 0))
(define plus-emissive (make-bytevector 256 0))
(define plus-lightmap (make-bytevector (* MAPSIZE MAPSIZE) 0))
(define plus-flashmaps
  (vector (make-bytevector (* MAPSIZE MAPSIZE) 0)
          (make-bytevector (* MAPSIZE MAPSIZE) 0)
          (make-bytevector (* MAPSIZE MAPSIZE) 0)
          (make-bytevector (* MAPSIZE MAPSIZE) 0)))
(define plus-flash-starts (make-vector PLUS_FLASH_COUNT -1))
(define plus-flash-next 0)
(define plus-aomap (make-bytevector (* MAPSIZE MAPSIZE) 0))

(define (plus-color color level)
  (if plus-enabled (ref (ref plus-shades (+ level 4)) color) color))

(include "plus-noise.ss")

(define (plus-dither level16 x y)
  (let* ((level (- (truncate (/ (+ level16 64) 16)) 4))
         (frac (- level16 (* 16 level)))
         (noise (ref plus-noise (+ (* (bitwise-and y 63) 64) (bitwise-and x 63)))))
    (if (> frac noise)
        (+ level 1)
        level)))

(define (plus-sprite-color color level16 emission x y)
  (if (and (> emission 0) (= (ref plus-emissive color) 1))
      (if (= emission 1) (plus-color color (plus-dither (truncate (/ level16 2)) x y)) color)
      (plus-color color (plus-dither level16 x y))))

(define (plus-distance-level extent range)
  (if plus-enabled
      (let ((distance (- range (min extent range))))
        (truncate (/ (* 240 distance distance distance distance) (* range range range range))))
      0))

(define (plus-light-index tilex tiley)
  (+ (* tiley MAPSIZE) tilex))

(define (plus-light-level level tilex tiley)
  (if plus-enabled
      (let* ((spot (plus-light-index tilex tiley))
             (flash (let slots ((slot 0) (brightest 0))
                      (if (= slot PLUS_FLASH_COUNT)
                          brightest
                          (let* ((remaining
                                  (if (> (ref plus-flash-starts slot) TimeCount)
                                      0
                                      (max 0 (- PLUS_FLASH_TICS (- TimeCount (ref plus-flash-starts slot))))))
                                 (level (truncate
                                         (/ (* (ref (ref plus-flashmaps slot) spot) remaining)
                                            PLUS_FLASH_TICS))))
                            (slots (+ slot 1) (max brightest level))))))
             (dark (truncate (/ (* level (- 15 (ref plus-lightmap spot))) 15)))
             (bright (if (= flash 0)
                         0
                         (min 4 (max 1 (truncate (/ (* 4 flash) PLUS_FLASH_LEVELS)))))))
        (max -64 (- dark (* 16 bright))))
      0))

(define (plus-light-emission shape)
  (cond ((= shape (+ SPR_STAT_0 3)) 1)
        ((or (= shape (+ SPR_STAT_0 4)) (= shape (+ SPR_STAT_0 14))) 2)
        (else 0)))

(define (plus-light-shape? shape)
  (> (plus-light-emission shape) 0))

(define (plus-build-table factor)
  (let ((table (make-bytevector 256 0)))
    (let colors ((color 0))
      (when (< color 256)
        (let* ((red (min 63 (truncate (/ (* (ref gamepal (* color 3)) factor) 15))))
               (green (min 63 (truncate (/ (* (ref gamepal (+ (* color 3) 1)) factor) 15))))
               (blue (min 63 (truncate (/ (* (ref gamepal (+ (* color 3) 2)) factor) 15))))
               (best (let search ((index 0) (bestdist -1) (bestindex 0))
                       (if (= index 256)
                           bestindex
                           (let ((dred (- red (ref gamepal (* index 3))))
                                 (dgreen (- green (ref gamepal (+ (* index 3) 1))))
                                 (dblue (- blue (ref gamepal (+ (* index 3) 2)))))
                             (let ((dist (+ (* dred dred) (* dgreen dgreen) (* dblue dblue))))
                               (if (or (< bestdist 0) (< dist bestdist))
                                   (search (+ index 1) dist index)
                                   (search (+ index 1) bestdist bestindex))))))))
          (setf! table color best))
        (colors (+ color 1))))
    table))

(define (plus-build-shades)
  (let ((identity (make-bytevector 256 0)))
    (let loop ((index 0))
      (when (< index 256)
        (let ((luma (truncate (/ (+ (* 54 (ref gamepal (* index 3)))
                                      (* 183 (ref gamepal (+ (* index 3) 1)))
                                      (* 19 (ref gamepal (+ (* index 3) 2))))
                                   256))))
          (setf! identity index index)
          (setf! plus-emissive index (if (>= luma PLUS_EMISSIVE_LUMA) 1 0)))
        (loop (+ index 1))))
    (setf! plus-shades 4 identity))
  (let bright ((level 1))
    (when (<= level 4)
      (setf! plus-shades (- 4 level) (plus-build-table (+ 15 (* level 2))))
      (bright (+ level 1))))
  (let dark ((level 1))
    (when (< level 16)
      (setf! plus-shades (+ level 4) (plus-build-table (- 15 level)))
      (dark (+ level 1)))))

(define (plus-light-passable? tilex tiley)
  (and (>= tilex 0) (< tilex MAPSIZE) (>= tiley 0) (< tiley MAPSIZE) (< (tileat tilex tiley) 128)))

(define (plus-ao-edge distance)
  (if (< distance PLUS_AO_RANGE)
      (truncate (/ (* PLUS_AO_DEPTH (- PLUS_AO_RANGE distance)) PLUS_AO_RANGE))
      0))

(define (plus-ao level16 xf yf)
  (if plus-enabled
      (let ((mask (ref plus-aomap (plus-light-index (bitwise-and (arithmetic-shift xf -16) 63)
                                                    (bitwise-and (arithmetic-shift yf -16) 63)))))
        (if (= mask 0)
            level16
            (if (= mask 255)
                (min 240 (+ level16 PLUS_AO_DEPTH))
                (let* ((fx (bitwise-and (arithmetic-shift xf -10) 63))
                   (fy (bitwise-and (arithmetic-shift yf -10) 63))
                   (shadow 0)
                   (shadow (if (> (bitwise-and mask 1) 0) (max shadow (plus-ao-edge fx)) shadow))
                   (shadow (if (> (bitwise-and mask 2) 0) (max shadow (plus-ao-edge (- 63 fx))) shadow))
                   (shadow (if (> (bitwise-and mask 4) 0) (max shadow (plus-ao-edge fy)) shadow))
                   (shadow (if (> (bitwise-and mask 8) 0) (max shadow (plus-ao-edge (- 63 fy))) shadow))
                   (shadow (if (> (bitwise-and mask 16) 0)
                               (max shadow (plus-ao-edge (max fx fy))) shadow))
                   (shadow (if (> (bitwise-and mask 32) 0)
                               (max shadow (plus-ao-edge (max (- 63 fx) fy))) shadow))
                   (shadow (if (> (bitwise-and mask 64) 0)
                               (max shadow (plus-ao-edge (max fx (- 63 fy)))) shadow))
                   (shadow (if (> (bitwise-and mask 128) 0)
                               (max shadow (plus-ao-edge (max (- 63 fx) (- 63 fy)))) shadow)))
                    (min 240 (+ level16 shadow))))))
      level16))

(define (plus-ao-solid? tilex tiley)
  (and (>= tilex 0) (< tilex MAPSIZE) (>= tiley 0) (< tiley MAPSIZE)
       (> (tileat tilex tiley) 0) (< (tileat tilex tiley) 128)))

(define (plus-build-ao)
  (let tiles ((tiley 0))
    (when (< tiley MAPSIZE)
      (let row ((tilex 0))
        (when (< tilex MAPSIZE)
          (setf! plus-aomap (plus-light-index tilex tiley)
                 (if (plus-ao-solid? tilex tiley)
                     255
                     (let* ((west (plus-ao-solid? (- tilex 1) tiley))
                            (east (plus-ao-solid? (+ tilex 1) tiley))
                            (north (plus-ao-solid? tilex (- tiley 1)))
                            (south (plus-ao-solid? tilex (+ tiley 1)))
                            (nw (and (not west) (not north)
                                     (plus-ao-solid? (- tilex 1) (- tiley 1))))
                            (ne (and (not east) (not north)
                                     (plus-ao-solid? (+ tilex 1) (- tiley 1))))
                            (sw (and (not west) (not south)
                                     (plus-ao-solid? (- tilex 1) (+ tiley 1))))
                            (se (and (not east) (not south)
                                     (plus-ao-solid? (+ tilex 1) (+ tiley 1)))))
                       (+ (if west 1 0) (if east 2 0) (if north 4 0) (if south 8 0)
                          (if nw 16 0) (if ne 32 0) (if sw 64 0) (if se 128 0)))))
          (row (+ tilex 1))))
      (tiles (+ tiley 1)))))

(define (plus-spread-light target lightx lighty radius levels)
  (let ((queue (make-vector (* MAPSIZE MAPSIZE) 0))
        (distance (make-bytevector (* MAPSIZE MAPSIZE) 255))
        (tail 1))
    (setf! queue 0 (plus-light-index lightx lighty))
    (setf! distance (plus-light-index lightx lighty) 0)
    (let flood ((head 0))
      (when (< head tail)
        (let* ((spot (ref queue head))
               (tilex (remainder spot MAPSIZE))
               (tiley (quotient spot MAPSIZE))
               (steps (ref distance spot))
               (level (- levels (truncate (/ (* levels steps) radius)))))
          (when (> level (ref target spot))
            (setf! target spot level))
          (when (< steps radius)
            (let visit ((neighbors (list (tuple (- tilex 1) tiley) (tuple (+ tilex 1) tiley)
                                          (tuple tilex (- tiley 1)) (tuple tilex (+ tiley 1)))))
              (when (pair? neighbors)
                (let* ((neighbor (car neighbors))
                       (nextx (ref neighbor 0))
                       (nexty (ref neighbor 1)))
                  (when (and (>= nextx 0) (< nextx MAPSIZE) (>= nexty 0) (< nexty MAPSIZE))
                    (let ((next (plus-light-index nextx nexty)))
                      (let ((nextlevel (- levels (truncate (/ (* levels (+ steps 1)) radius)))))
                        (when (> nextlevel (ref target next))
                          (setf! target next nextlevel)))
                      (when (< (tileat nextx nexty) 128)
                        (when (> (ref distance next) (+ steps 1))
                          (setf! distance next (+ steps 1))
                          (setf! queue tail next)
                          (set! tail (+ tail 1))))))
                  (visit (cdr neighbors)))))
          (flood (+ head 1))))))))

(define (plus-build-lights)
  (let clear ((index 0))
    (when (< index (* MAPSIZE MAPSIZE))
      (setf! plus-lightmap index 0)
      (clear (+ index 1))))
  (let lights ((index 0))
    (when (< index statcount)
      (when (plus-light-shape? (ref stat-shape index))
        (plus-spread-light plus-lightmap (ref stat-tilex index) (ref stat-tiley index)
                           PLUS_LIGHT_RADIUS PLUS_LIGHT_LEVELS))
      (lights (+ index 1)))))

(define (plus-flash-at tilex tiley)
  (when plus-enabled
    (let ((flashmap (ref plus-flashmaps plus-flash-next))
          (queue (make-vector (* MAPSIZE MAPSIZE) 0))
          (distance (make-bytevector (* MAPSIZE MAPSIZE) 255))
          (tail 1))
      (let clear ((index 0))
        (when (< index (* MAPSIZE MAPSIZE))
          (setf! flashmap index 0)
          (clear (+ index 1))))
      (setf! queue 0 (plus-light-index tilex tiley))
      (setf! distance (plus-light-index tilex tiley) 0)
      (let flood ((head 0) (maxd 0))
        (if (< head tail)
            (let* ((spot (ref queue head))
                   (tx (remainder spot MAPSIZE))
                   (ty (quotient spot MAPSIZE))
                   (steps (ref distance spot)))
              (let visit ((neighbors (list (tuple (- tx 1) ty) (tuple (+ tx 1) ty)
                                           (tuple tx (- ty 1)) (tuple tx (+ ty 1)))))
                (when (pair? neighbors)
                  (let* ((neighbor (car neighbors))
                         (nextx (ref neighbor 0))
                         (nexty (ref neighbor 1)))
                    (when (plus-light-passable? nextx nexty)
                      (let ((next (plus-light-index nextx nexty)))
                        (when (> (ref distance next) (+ steps 1))
                          (setf! distance next (+ steps 1))
                          (setf! queue tail next)
                          (set! tail (+ tail 1)))))
                    (visit (cdr neighbors)))))
              (flood (+ head 1) (max maxd steps)))
            (let stamp ((index 0))
              (if (< index tail)
                  (let* ((spot (ref queue index))
                         (tx (remainder spot MAPSIZE))
                         (ty (quotient spot MAPSIZE))
                         (steps (ref distance spot))
                         (level (if (= maxd 0)
                                    PLUS_FLASH_LEVELS
                                    (max 1 (- PLUS_FLASH_LEVELS
                                              (truncate (/ (* PLUS_FLASH_LEVELS steps) maxd)))))))
                    (setf! flashmap spot level)
                    (let walls ((neighbors (list (tuple (- tx 1) ty) (tuple (+ tx 1) ty)
                                                 (tuple tx (- ty 1)) (tuple tx (+ ty 1)))))
                      (when (pair? neighbors)
                        (let* ((neighbor (car neighbors))
                               (nextx (ref neighbor 0))
                               (nexty (ref neighbor 1)))
                          (when (and (>= nextx 0) (< nextx MAPSIZE) (>= nexty 0) (< nexty MAPSIZE)
                                     (>= (tileat nextx nexty) 128))
                            (let ((next (plus-light-index nextx nexty)))
                              (when (> level (ref flashmap next))
                                (setf! flashmap next level)))))
                        (walls (cdr neighbors))))
                    (stamp (+ index 1)))
                  (begin
                    (setf! plus-flash-starts plus-flash-next TimeCount)
                    (set! plus-flash-next (remainder (+ plus-flash-next 1) PLUS_FLASH_COUNT))))))))))

(define (plus-palette-loaded)
  (when plus-enabled (plus-build-shades)))

(define (plus-level-loaded)
  (when plus-enabled
    (let reset ((slot 0))
      (when (< slot PLUS_FLASH_COUNT)
        (let ((flashmap (ref plus-flashmaps slot)))
          (let clear ((index 0))
            (when (< index (* MAPSIZE MAPSIZE))
              (setf! flashmap index 0)
              (clear (+ index 1)))))
        (setf! plus-flash-starts slot -1)
        (reset (+ slot 1))))
    (set! plus-flash-next 0)
    (plus-build-lights)
    (plus-build-ao)))

(define (plus-draw-planes)
  (when plus-enabled
    (let ((halfh (arithmetic-shift viewheight -1))
          (ceilcolor (ceiling-color))
          (centercol (arithmetic-shift viewwidth -1)))
      (let rows ((h 1))
        (when (< h halfh)
          (let* ((level 0)
                 (length (truncate (/ (* 32768 scale) h)))
                 (xstep (truncate (/ (* viewsin 2) h)))
                 (ystep (truncate (/ (* viewcos 2) h)))
                 (startx (+ viewx (FixedMul length viewcos)))
                 (starty (- viewy (FixedMul length viewsin)))
                 (top (- halfh 1 h))
                 (bottom (+ halfh h)))
            (when (and (>= top 0) (< bottom viewheight))
              (let columns ((x 0))
                (when (< x viewwidth)
                  (when (>= h (arithmetic-shift (scale-rows (ref wallheight x)) -1))
                    (let* ((prestep (- centercol x))
                           (xf (- startx (arithmetic-shift (* xstep prestep) -2)))
                           (yf (- starty (arithmetic-shift (* ystep prestep) -2)))
                           (lit (plus-ao (plus-light-level level
                                                           (bitwise-and (arithmetic-shift xf -16) 63)
                                                           (bitwise-and (arithmetic-shift yf -16) 63))
                                         xf yf)))
                      (setf! framebuffer (+ (* (+ viewtop top) screenwidth) viewleft x)
                             (plus-color ceilcolor (plus-dither lit (arithmetic-shift xf -10) (arithmetic-shift yf -10))))
                      (setf! framebuffer (+ (* (+ viewtop bottom) screenwidth) viewleft x)
                             (plus-color FLOOR (plus-dither lit (arithmetic-shift xf -10) (arithmetic-shift yf -10))))))
                  (columns (+ x 1))))))
          (rows (+ h 1)))))))
