(include "ID_CA.ss")
(include "ID_PM.ss")
(include "WL_DRAW.ss")
(include "ID_VH.ss")
(include "WL_SPRITE.ss")
(include "WL_AGENT.ss")
(include "WL_ACT1.ss")
(include "WL_ACT2.ss")
(include "ID_SD.ss")
(include "ID_MM.ss")
(include "ID_US_1.ss")
(include "WL_STATE.ss")
(include "ID_IN.ss")
(include "WL_GAME.ss")
(include "WL_INTER.ss")
(include "WL_TEXT.ss")
(include "WL_MENU.ss")
(include "WL_MAIN.ss")
(include "ID_VL.ss")
(InitGame)
(set! demoplayback #t)
(CA_CacheMap 0)
(SetupGameLevel)
(WallRefresh)
(define TWOPI 6.28318530717959)
(define (march-height pixx step)
  (let ((angle (/ (* (+ (* player-angle 10) (ref pixelangle pixx)) TWOPI) 3600)))
    (let ((dx (cos angle)) (dy (- (sin angle)))
          (vx (/ viewx 65536)) (vy (/ viewy 65536)))
      (let loop ((distance 0.0))
        (if (> distance 64.0)
            0
            (let ((x (+ vx (* dx distance))) (y (+ vy (* dy distance))))
              (let ((tx (truncate x)) (ty (truncate y)))
                (if (or (< tx 0) (>= tx 64) (< ty 0) (>= ty 64) (> (tileat tx ty) 0))
                    (let ((perp (* distance (cos (/ (* (ref pixelangle pixx) TWOPI) 3600)))))
                      (truncate (/ heightnumerator (truncate (/ (* perp 65536) 256)))))
                    (loop (+ distance step))))))))))
(define (sweep step)
  (let loop ((pixx 0) (bad 0) (worst 0) (worstcol -1))
    (if (= pixx 320)
        (begin (displayn (list 'step step 'columns-over-2 bad 'worst worst 'at worstcol)))
        (let ((diff (abs (- (ref wallheight pixx) (march-height pixx step)))))
          (loop (+ pixx 1)
                (if (> diff 2) (+ bad 1) bad)
                (if (> diff worst) diff worst)
                (if (> diff worst) pixx worstcol))))))
(sweep 0.002)
(sweep 0.0002)
(displayn (list 'col280 'cast (ref wallheight 280) 'm002 (march-height 280 0.002) 'm00002 (march-height 280 0.0002)))
