;;; WL_AGENT.C — player movement

(define PLAYERSIZE MINDIST)
(define MOVESCALE 150)
(define BACKMOVESCALE 100)
(define ANGLESCALE 20)

(define anglefrac 0)
(define thrustspeed 0)
(define funnyticount 0)
(define playerxmove 0)
(define playerymove 0)
(define RUNSPEED 6000)

(define gd_baby 0)
(define gd_easy 1)
(define gd_medium 2)
(define gd_hard 3)
(define difficulty gd_hard)
(define godmode #f)
(define noclip #f)
(define health 100)
(define ex_stillplaying 0)
(define ex_completed 1)
(define ex_died 2)
(define ex_warped 3)
(define ex_resetgame 4)
(define ex_loadedgame 5)
(define ex_victorious 6)
(define ex_abort 7)
(define ex_demodone 8)
(define ex_secretlevel 9)
(define playstate ex_stillplaying)
(define victoryflag #f)
(define deathcam-active #f)
(define LastAttacker -1)
(define killerobj -1)
(define gotgatgun 0)
(define killx 0)
(define killy 0)

(define (TakeDamage points attacker)
  (set! LastAttacker attacker)
  (unless victoryflag
    (let ((scaled (if (= difficulty gd_baby) (arithmetic-shift points -2) points)))
      (unless godmode
        (set! health (- health scaled)))
      (when (<= health 0)
        (set! health 0)
        (set! playstate ex_died)
        (set! killerobj attacker))
      (StartDamageFlash scaled)
      (set! gotgatgun 0)
      (DrawHealth)
      (DrawFace))))

(define wp_knife 0)
(define wp_pistol 1)
(define wp_machinegun 2)
(define wp_chaingun 3)

(define STARTAMMO 8)

(define weapon wp_pistol)
(define bestweapon wp_pistol)
(define chosenweapon wp_pistol)
(define ammo STARTAMMO)
(define attackframe 0)
(define attackcount 0)
(define weaponframe 0)
(define player-attacking #f)

(define shootdelta (truncate (/ viewwidth 10)))

(define attackinfo
  (vector 6 0 1  6 2 2  6 0 3  6 -1 4
          6 0 1  6 1 2  6 0 3  6 -1 4
          6 0 1  6 1 2  6 3 3  6 -1 4
          6 0 1  6 1 2  6 4 3  6 -1 4))

(define (atk-field which frame field)
  (ref attackinfo (+ (* which 12) (* frame 3) field)))

(define (atk-tics which frame) (atk-field which frame 0))
(define (atk-attack which frame) (atk-field which frame 1))
(define (atk-frame which frame) (atk-field which frame 2))

(define EXTRAPOINTS 40000)

(define score 0)
(define nextextra EXTRAPOINTS)
(define lives 3)
(define keys 0)

(define STATUSLINES 40)
(define STATUSBARPIC 86)
(define KNIFEPIC 91)
(define NOKEYPIC 95)
(define GOLDKEYPIC 96)
(define SILVERKEYPIC 97)
(define N_BLANKPIC 98)
(define N_0PIC 99)
(define FACE1APIC 109)
(define FACE8APIC 130)
(define GOTGATLINGPIC 131)
(define MUTANTBJPIC 132)

(define FACETICS 70)
(define facecount 0)
(define faceframe 0)

(define (StatusDrawPic x y picnum)
  (VH_DrawPicAt (* x 8) (+ (- screenheight STATUSLINES) y) picnum))

(define (LatchNumber x y width number)
  (let ((text (number->string number)))
    (let ((length (string-length text)))
      (let pad ((column x) (room width))
        (if (> room length)
            (begin
              (StatusDrawPic column y N_BLANKPIC)
              (pad (+ column 1) (- room 1)))
            (let digits ((index (if (<= length room) 0 (- length room)))
                         (column column))
              (when (< index length)
                (StatusDrawPic column y
                               (+ N_0PIC (- (char->integer (string-ref text index))
                                            (char->integer #\0))))
                (digits (+ index 1) (+ column 1)))))))))

(define (DrawFace)
  (if (> health 0)
      (StatusDrawPic 17 4 (+ FACE1APIC (* 3 (truncate (/ (- 100 health) 16))) faceframe))
      (if (= (ref actor-class LastAttacker) needleobj)
          (StatusDrawPic 17 4 MUTANTBJPIC)
          (StatusDrawPic 17 4 FACE8APIC))))

(define (UpdateFace tics)
  (unless (eqv? (SD_SoundPlaying) GETGATLINGSND)
    (update-face-frame tics)))

(define (update-face-frame tics)
  (set! facecount (+ facecount tics))
  (when (> facecount (US_RndT))
    (set! faceframe (arithmetic-shift (US_RndT) -6))
    (when (= faceframe 3)
      (set! faceframe 1))
    (set! facecount 0)
    (DrawFace)))

(define (DrawHealth)
  (LatchNumber 21 16 3 health))

(define (DrawLives)
  (LatchNumber 14 16 1 lives))

(define (DrawLevel)
  (LatchNumber 2 16 2 (+ mapon 1)))

(define (DrawAmmo)
  (LatchNumber 27 16 2 ammo))

(define (DrawScore)
  (LatchNumber 6 16 6 score))

(define (DrawWeapon)
  (StatusDrawPic 32 8 (+ KNIFEPIC weapon)))

(define (DrawKeys)
  (if (> (bitwise-and keys 1) 0)
      (StatusDrawPic 30 4 GOLDKEYPIC)
      (StatusDrawPic 30 4 NOKEYPIC))
  (if (> (bitwise-and keys 2) 0)
      (StatusDrawPic 30 20 SILVERKEYPIC)
      (StatusDrawPic 30 20 NOKEYPIC)))

(define (HealSelf points)
  (set! health (+ health points))
  (when (> health 100)
    (set! health 100))
  (DrawHealth)
  (set! gotgatgun 0)
  (DrawFace))

(define (GiveExtraMan)
  (when (< lives 9)
    (set! lives (+ lives 1)))
  (DrawLives)
  (SD_PlaySound BONUS1UPSND))

(define (GivePoints points)
  (set! score (+ score points))
  (let loop ()
    (when (>= score nextextra)
      (set! nextextra (+ nextextra EXTRAPOINTS))
      (GiveExtraMan)
      (loop)))
  (DrawScore))

(define (GiveAmmo count)
  (when (and (= ammo 0) (= attackframe 0))
    (set! weapon chosenweapon)
    (DrawWeapon))
  (set! ammo (+ ammo count))
  (when (> ammo 99)
    (set! ammo 99))
  (DrawAmmo))

(define (GiveWeapon which)
  (GiveAmmo 6)
  (when (< bestweapon which)
    (set! bestweapon which)
    (set! weapon which)
    (set! chosenweapon which))
  (DrawWeapon))

(define (GiveKey key)
  (set! keys (bitwise-ior keys (arithmetic-shift 1 key)))
  (DrawKeys))

(define (GetBonus index)
  (let ((item (ref stat-item index)))
    (let ((taken
           (cond
             ((= item bo_firstaid)
              (and (< health 100) (begin (SD_PlaySound HEALTH2SND) (HealSelf 25) #t)))
             ((and (>= item bo_key1) (<= item bo_key4))
              (GiveKey (- item bo_key1))
              (SD_PlaySound GETKEYSND)
              #t)
             ((= item bo_cross)
              (SD_PlaySound BONUS1SND)
              (GivePoints 100)
              (set! treasurecount (+ treasurecount 1))
              #t)
             ((= item bo_chalice)
              (SD_PlaySound BONUS2SND)
              (GivePoints 500)
              (set! treasurecount (+ treasurecount 1))
              #t)
             ((= item bo_bible)
              (SD_PlaySound BONUS3SND)
              (GivePoints 1000)
              (set! treasurecount (+ treasurecount 1))
              #t)
             ((= item bo_crown)
              (SD_PlaySound BONUS4SND)
              (GivePoints 5000)
              (set! treasurecount (+ treasurecount 1))
              #t)
             ((= item bo_clip)
              (and (< ammo 99) (begin (SD_PlaySound GETAMMOSND) (GiveAmmo 8) #t)))
             ((= item bo_clip2)
              (and (< ammo 99) (begin (SD_PlaySound GETAMMOSND) (GiveAmmo 4) #t)))
             ((= item bo_machinegun)
              (SD_PlaySound GETMACHINESND)
              (GiveWeapon wp_machinegun)
              #t)
             ((= item bo_chaingun)
              (SD_PlaySound GETGATLINGSND)
              (GiveWeapon wp_chaingun)
              (StatusDrawPic 17 4 GOTGATLINGPIC)
              (set! facecount 0)
              (set! gotgatgun 1)
              #t)
             ((= item bo_fullheal)
              (SD_PlaySound BONUS1UPSND)
              (HealSelf 99)
              (GiveAmmo 25)
              (GiveExtraMan)
              (set! treasurecount (+ treasurecount 1))
              #t)
             ((= item bo_food)
              (and (< health 100) (begin (SD_PlaySound HEALTH1SND) (HealSelf 10) #t)))
             ((= item bo_alpo)
              (and (< health 100) (begin (SD_PlaySound HEALTH1SND) (HealSelf 4) #t)))
             ((= item bo_gibs)
              (and (<= health 10) (begin (SD_PlaySound SLURPIESND) (HealSelf 1) #t)))
             ((= item bo_spear)
              (set! spearflag #t)
              (set! spearx player-x)
              (set! speary player-y)
              (set! spearangle player-angle)
              (set! playstate ex_completed)
              #t)
             (else #f))))
      (when taken
        (StartBonusFlash)
        (setf! stat-shape index -1)))))

(define (CheckWeaponChange)
  (when (> ammo 0)
    (let loop ((which wp_knife))
      (when (<= which bestweapon)
        (if (ref buttonstate (+ bt_readyknife which))
            (begin
              (set! weapon which)
              (set! chosenweapon which)
              (DrawWeapon))
            (loop (+ which 1)))))))

(define (Cmd_Use)
  (let ((facing (cond ((or (< player-angle (/ ANGLES 8)) (> player-angle (* 7 (/ ANGLES 8))))
                       di_east)
                      ((< player-angle (* 3 (/ ANGLES 8))) di_north)
                      ((< player-angle (* 5 (/ ANGLES 8))) di_west)
                      (else di_south))))
    (let ((checkx (+ player-tilex (dir-dx facing)))
          (checky (+ player-tiley (dir-dy facing)))
          (elevatorok (or (= facing di_east) (= facing di_west))))
      (let ((doortile (tileat checkx checky)))
        (cond
          ((= (maptile 1 (+ (* checky MAPSIZE) checkx)) PUSHABLETILE)
           (PushWall checkx checky facing))
          ((and (not (ref buttonheld bt_use)) (= doortile ELEVATORTILE) elevatorok)
           (setf! buttonheld bt_use #t)
           (tileset! checkx checky (+ doortile 1))
           (set! playstate
                 (if (= (maptile 0 (+ (* player-tiley MAPSIZE) player-tilex)) ALTELEVATORTILE)
                     ex_secretlevel
                     ex_completed))
           (SD_PlaySound LEVELDONESND)
           (SD_WaitSoundDone))
          ((and (not (ref buttonheld bt_use)) (= (bitwise-and doortile 192) 128))
           (setf! buttonheld bt_use #t)
           (OperateDoor (bitwise-and doortile 127)))
          (else
           (SD_PlaySound DONOTHINGSND)))))))

(define (SpawnPlayer tilex tiley dir)
  (set! deathcam-active #f)
  (set! player-tilex tilex)
  (set! player-tiley tiley)
  (set! player-areanumber (areaat tilex tiley))
  (set! player-x (+ (* tilex TILEGLOBAL) 32768))
  (set! player-y (+ (* tiley TILEGLOBAL) 32768))
  (set! player-angle (let ((angle (* (- 1 dir) 90)))
                       (if (< angle 0) (+ angle ANGLES) angle)))
  (Thrust 0 0)
  (InitAreas))

(define (T_Player controlx controly tics)
  (if victoryflag
      (VictorySpin tics)
      (begin
        (UpdateFace tics)
        (CheckWeaponChange)
        (when (ref buttonstate bt_use)
          (Cmd_Use))
        (when (and (ref buttonstate bt_attack) (not (ref buttonheld bt_attack)))
          (Cmd_Fire))
        (ControlMovement controlx controly))))

(define (VictorySpin tics)
  (cond ((> player-angle 270)
         (set! player-angle (max (- player-angle (* tics 3)) 270)))
        ((< player-angle 270)
         (set! player-angle (min (+ player-angle (* tics 3)) 270))))
  (let ((desty (- (* (- player-tiley 5) TILEGLOBAL) 12288)))
    (when (> player-y desty)
      (set! player-y (max (- player-y (* tics 4096)) desty)))))

(define (VictoryTile)
  (unless spear-mode
    (SpawnBJVictory))
  (set! victoryflag #t))

(define (Cmd_Fire)
  (setf! buttonheld bt_attack #t)
  (set! weaponframe 0)
  (set! player-attacking #t)
  (set! attackframe 0)
  (set! attackcount (atk-tics weapon attackframe))
  (set! weaponframe (atk-frame weapon attackframe)))

(define (shootable-target index)
  (let ((flags (ref actor-flags index)))
    (and (> (bitwise-and flags FL_SHOOTABLE) 0)
         (> (bitwise-and flags FL_VISABLE) 0)
         (< (abs (- (ref actor-viewx index) centerx)) shootdelta))))

(define (closest-target)
  (let loop ((index 0) (best -1) (dist 2147483647) (order 2147483647))
    (if (= index actorcount)
        (list best dist)
        (let ((candidate-dist (ref actor-transx index))
              (candidate-order (ref actor-order index)))
          (if (and (shootable-target index)
                   (or (< candidate-dist dist)
                       (and (= candidate-dist dist) (< candidate-order order))))
              (loop (+ index 1) index candidate-dist candidate-order)
              (loop (+ index 1) best dist order))))))

(define (KnifeAttack)
  (SD_PlaySound ATKKNIFESND)
  (let ((found (closest-target)))
    (let ((closest (car found))
          (dist (car (cdr found))))
      (when (and (>= closest 0) (<= dist 98304))
        (DamageActor closest (arithmetic-shift (US_RndT) -4))))))

(define (GunAttack)
  (cond ((= weapon wp_pistol) (SD_PlaySound ATKPISTOLSND))
        ((= weapon wp_machinegun) (SD_PlaySound ATKMACHINEGUNSND))
        ((= weapon wp_chaingun) (SD_PlaySound ATKGATLINGSND)))
  (set! madenoise #t)
  (plus-flash-at player-tilex player-tiley)
  (let ((closest (car (closest-target))))
    (when (and (>= closest 0) (CheckLine closest))
      (let ((dx (abs (- (ref actor-tilex closest) player-tilex)))
            (dy (abs (- (ref actor-tiley closest) player-tiley))))
        (let ((dist (if (> dx dy) dx dy)))
          (cond ((< dist 2) (DamageActor closest (truncate (/ (US_RndT) 4))))
                ((< dist 4) (DamageActor closest (truncate (/ (US_RndT) 6))))
                ((>= (truncate (/ (US_RndT) 12)) dist)
                 (DamageActor closest (truncate (/ (US_RndT) 6))))))))))

(define (fire-gun)
  (if (= ammo 0)
      (set! attackframe (+ attackframe 1))
      (begin
        (GunAttack)
        (set! ammo (- ammo 1))
        (DrawAmmo))))

(define (attack-step)
  (let ((kind (atk-attack weapon attackframe))
        (frametics (atk-tics weapon attackframe)))
    (if (= kind -1)
        (begin
          (set! player-attacking #f)
          ;; WL_AGENT.C:1349-1363, the weapon is redrawn only when it changed
          (if (= ammo 0)
              (begin (set! weapon wp_knife) (DrawWeapon))
              (unless (= weapon chosenweapon)
                (set! weapon chosenweapon)
                (DrawWeapon)))
          (set! attackframe 0)
          (set! weaponframe 0)
          #f)
        (begin
          (cond ((= kind 1) (fire-gun))
                ((= kind 2) (KnifeAttack))
                ((= kind 3)
                 (when (and (> ammo 0) (ref buttonstate bt_attack))
                   (set! attackframe (- attackframe 2))))
                ((= kind 4)
                 (when (> ammo 0)
                   (when (ref buttonstate bt_attack)
                     (set! attackframe (- attackframe 2)))
                   (fire-gun))))
          (set! attackcount (+ attackcount frametics))
          (set! attackframe (+ attackframe 1))
          (set! weaponframe (atk-frame weapon attackframe))
          #t))))

(define (T_Attack controlx controly tics)
  (UpdateFace tics)
  (if victoryflag
      (VictorySpin tics)
      (begin
        (when (and (ref buttonstate bt_use) (not (ref buttonheld bt_use)))
          (setf! buttonstate bt_use #f))
        (when (and (ref buttonstate bt_attack) (not (ref buttonheld bt_attack)))
          (setf! buttonstate bt_attack #f))
        (ControlMovement controlx controly)
        (unless victoryflag
          (set! attackcount (- attackcount tics))
          (let loop ()
            (when (and (<= attackcount 0) (attack-step))
              (loop)))))))

(define (solid-at x y)
  (if (or (< x 0) (>= x MAPSIZE) (< y 0) (>= y MAPSIZE))
      #t
      (let ((tile (tileat x y)))
        (cond ((= tile 0) #f)
              ((and (>= tile 128) (< tile 192))
               (< (ref doorposition (bitwise-and tile 127)) 65535))
              ((= tile (bitwise-and tile 64)) #f)
              (else #t)))))

(define (wall-clear x y xl yl xh yh)
  (let rows ((ty yl))
    (if (> ty yh)
        #t
        (let cols ((tx xl))
          (cond ((> tx xh) (rows (+ ty 1)))
                ((or (solid-at tx ty) (= (actorat-at tx ty) MAXACTORS)) #f)
                (else (cols (+ tx 1))))))))

(define (actor-clear x y xl yl xh yh)
  (let rows ((ty (if (> yl 0) (- yl 1) yl)))
    (if (> ty (if (< yh (- MAPSIZE 1)) (+ yh 1) yh))
        #t
        (let cols ((tx (if (> xl 0) (- xl 1) xl)))
          (if (> tx (if (< xh (- MAPSIZE 1)) (+ xh 1) xh))
              (rows (+ ty 1))
              (let ((other (actorat-at tx ty)))
                (if (and (>= other 0) (< other MAXACTORS)
                             (> (bitwise-and (ref actor-flags other) FL_SHOOTABLE) 0)
                             (<= (abs (- x (ref actor-x other))) MINACTORDIST)
                             (<= (abs (- y (ref actor-y other))) MINACTORDIST))
                    #f
                    (cols (+ tx 1)))))))))

(define (TryMove x y)
  (let ((xl (tileof (- x PLAYERSIZE)))
        (yl (tileof (- y PLAYERSIZE)))
        (xh (tileof (+ x PLAYERSIZE)))
        (yh (tileof (+ y PLAYERSIZE))))
    (and (wall-clear x y xl yl xh yh)
         (actor-clear x y xl yl xh yh))))

(define (ClipMove xmove ymove)
  (let ((basex player-x) (basey player-y))
    (set! player-x (+ basex xmove))
    (set! player-y (+ basey ymove))
    (unless (or (TryMove player-x player-y)
                (and noclip
                     (> player-x (* 2 TILEGLOBAL))
                     (> player-y (* 2 TILEGLOBAL))
                     (< player-x (* (- MAPSIZE 1) TILEGLOBAL))
                     (< player-y (* (- MAPSIZE 1) TILEGLOBAL))))
      (unless (SD_SoundPlaying)
        (SD_PlaySound HITWALLSND))
      (set! player-x (+ basex xmove))
      (set! player-y basey)
      (unless (TryMove player-x player-y)
        (set! player-x basex)
        (set! player-y (+ basey ymove))
        (unless (TryMove player-x player-y)
          (set! player-x basex)
          (set! player-y basey))))))

(define (Thrust angle speed)
  (when (and spear-mode (not (= speed 0)))
    (set! funnyticount 0))
  (set! thrustspeed (+ thrustspeed speed))
  (let ((limited (if (>= speed (* MINDIST 2)) (- (* MINDIST 2) 1) speed)))
    (let ((wrapped (- angle (* 360 (truncate (/ angle 360))))))
      (ClipMove (FixedByFrac limited (ref costable wrapped))
                (- (FixedByFrac limited (ref sintable wrapped))))))
  (set! player-tilex (tileof player-x))
  (set! player-tiley (tileof player-y))
  ;; C reads mapsegs[0] and subtracts AREATILE (WL_AGENT.C:912-913), which is out of range on a
  ;; door tile. `areaat` holds the door's neighbouring area there and is identical elsewhere.
  (set! player-areanumber (areaat player-tilex player-tiley))
  (when (= (maptile 1 (+ (* player-tiley MAPSIZE) player-tilex)) EXITTILE)
    (VictoryTile)))

(define (Turn units)
  (set! player-angle (- player-angle units))
  (when (>= player-angle 360) (set! player-angle (- player-angle 360)))
  (when (< player-angle 0) (set! player-angle (+ player-angle 360))))

(define (ControlMovement controlx controly)
  (set! thrustspeed 0)
  (let ((oldx player-x)
        (oldy player-y))
    (if (ref buttonstate bt_strafe)
        (cond ((> controlx 0)
               (let ((angle (- player-angle 90)))
                 (Thrust (if (< angle 0) (+ angle 360) angle) (* controlx MOVESCALE))))
              ((< controlx 0)
               (let ((angle (+ player-angle 90)))
                 (Thrust (if (>= angle 360) (- angle 360) angle) (* (- controlx) MOVESCALE)))))
        (begin
          (set! anglefrac (+ anglefrac controlx))
          (let ((angleunits (truncate (/ anglefrac ANGLESCALE))))
            (set! anglefrac (- anglefrac (* angleunits ANGLESCALE)))
            (Turn angleunits))))
    (when (> controly 0)
      (let ((angle (+ player-angle 180)))
        (Thrust (if (>= angle 360) (- angle 360) angle) (* controly BACKMOVESCALE))))
    (when (< controly 0)
      (Thrust player-angle (* (- controly) MOVESCALE)))
    (unless victoryflag
      (set! playerxmove (- player-x oldx))
      (set! playerymove (- player-y oldy)))))
