;;; WL_ACT2.C — enemies, bosses, ghosts, and projectiles

(define SPR_DEATHCAM 1)
(define SPR_GRD_S_1 50)
(define SPR_DOG_W1_1 99)
(define SPR_SS_S_1 138)
(define SPR_MUT_S_1 187)
(define SPR_OFC_S_1 238)

(define SPR_BLINKY_W1 288)
(define SPR_BLINKY_W2 289)
(define SPR_PINKY_W1 290)
(define SPR_PINKY_W2 291)
(define SPR_CLYDE_W1 292)
(define SPR_CLYDE_W2 293)
(define SPR_INKY_W1 294)
(define SPR_INKY_W2 295)

(define SPR_BOSS_W1 296)
(define SPR_SCHABB_W1 307)
(define SPR_FAKE_W1 321)
(define SPR_MECHA_W1 334)
(define SPR_HITLER_W1 345)
(define SPR_GIFT_W1 360)
(define SPR_ROCKET_1 370)
(define SPR_SMOKE_1 378)
(define SPR_BOOM_1 382)
(define SPR_GRETEL_W1 385)
(define SPR_FAT_W1 396)

;; WL_DEF.H:576-599
(define NUMENEMIES 22)
(define en_guard 0)
(define en_officer 1)
(define en_ss 2)
(define en_dog 3)
(define en_boss 4)
(define en_schabbs 5)
(define en_fake 6)
(define en_hitler 7)
(define en_mutant 8)
(define en_blinky 9)
(define en_clyde 10)
(define en_pinky 11)
(define en_inky 12)
(define en_gretel 13)
(define en_gift 14)
(define en_fat 15)

;; WL_DEF.H:505-536, the object classes the port distinguishes.
(define inertobj 2)
(define guardobj 3)
(define bossobj 7)
(define schabbobj 8)
(define fakeobj 9)
(define mechahitlerobj 10)
(define mutantobj 11)
(define needleobj 12)
(define fireobj 13)
(define bjobj 14)
(define ghostobj 15)
(define realhitlerobj 16)
(define gretelobj 17)
(define giftobj 18)
(define fatobj 19)
(define rocketobj 20)
(define hrocketobj 27)

(define (class-of which) (+ guardobj which))

(define MAXACTORS 150)
(define actorcount 0)
(define actor-tilex (make-vector MAXACTORS 0))
(define actor-tiley (make-vector MAXACTORS 0))
(define actor-x (make-vector MAXACTORS 0))
(define actor-y (make-vector MAXACTORS 0))
(define actor-dir (make-vector MAXACTORS 0))
(define actor-class (make-vector MAXACTORS 0))
(define actor-state (make-vector MAXACTORS #f))
(define actor-ticcount (make-vector MAXACTORS 0))
(define actor-speed (make-vector MAXACTORS 0))
(define actor-flags (make-vector MAXACTORS 0))
(define actor-distance (make-vector MAXACTORS 0))
(define actor-areanumber (make-vector MAXACTORS 0))
(define actor-temp1 (make-vector MAXACTORS 0))
(define actor-temp2 (make-vector MAXACTORS 0))
(define actor-active (make-vector MAXACTORS #f))
(define actor-hitpoints (make-vector MAXACTORS 0))
(define actor-viewx (make-vector MAXACTORS 0))
(define actor-transx (make-vector MAXACTORS 0))
(define actor-transy (make-vector MAXACTORS 0))
(define actor-order (make-vector MAXACTORS 0))
(define next-actor-order 0)

(define SPDPATROL 512)
(define SPDDOG 1500)

(define killcount 0)
(define killtotal 0)

;; WL_ACT2.C:41-152, four difficulty rows of NUMENEMIES entries.
(define starthitpoints
  (vector 25 50 100 1 850 850 200 800 45 25 25 25 25 850 850 850 5 1450 850 1050 950 1250
          25 50 100 1 950 950 300 950 55 25 25 25 25 950 950 950 10 1550 950 1150 1050 1350
          25 50 100 1 1050 1550 400 1050 55 25 25 25 25 1050 1050 1050 15 1650 1050 1250 1150 1450
          25 50 100 1 1200 2400 500 1200 65 25 25 25 25 1200 1200 1200 25 2000 1200 1400 1300 1600))

(define (start-hitpoints which)
  (ref starthitpoints (+ (* difficulty NUMENEMIES) which)))

(define actor-angle (make-vector MAXACTORS 0))

;; `new` is the slot the last spawn produced, standing in for C's global of the same name.
(define new 0)

(define AMBUSHTILE 106)

(define (stand-state which)
  (cond ((= which en_guard) s_grdstand)
        ((= which en_officer) s_ofcstand)
        ((= which en_ss) s_ssstand)
        (else s_mutstand)))

(define (path-state which)
  (cond ((= which en_guard) s_grdpath1)
        ((= which en_officer) s_ofcpath1)
        ((= which en_ss) s_sspath1)
        ((= which en_mutant) s_mutpath1)
        (else s_dogpath1)))

;; WL_ACT2.C:889-905, the last floor neighbour wins.
(define (ambush-area tilex tiley)
  (let ((neighbours (list (maptile 0 (+ (* tiley MAPSIZE) tilex 1))
                          (maptile 0 (+ (* (- tiley 1) MAPSIZE) tilex))
                          (maptile 0 (+ (* (+ tiley 1) MAPSIZE) tilex))
                          (maptile 0 (+ (* tiley MAPSIZE) (- tilex 1))))))
    (let loop ((rest neighbours) (area 0))
      (if (null? rest)
          area
          (loop (cdr rest)
                (if (>= (car rest) AREATILE) (- (car rest) AREATILE) area))))))

(define (SpawnAmbush tilex tiley)
  (when (= (maptile 0 (+ (* tiley MAPSIZE) tilex)) AMBUSHTILE)
    (tileset! tilex tiley 0)
    (let ((area (ambush-area tilex tiley)))
      (areaset! tilex tiley area)
      (setf! actor-areanumber new area))
    (setf! actor-flags new (bitwise-ior (ref actor-flags new) FL_AMBUSH))))

(define (SpawnStand which tilex tiley dir)
  (when (or (= which en_guard) (= which en_officer) (= which en_mutant) (= which en_ss))
    (SpawnNewObj tilex tiley (stand-state which))
    (setf! actor-speed new SPDPATROL)
    (unless loadedgame
      (set! killtotal (+ killtotal 1))))
  (SpawnAmbush tilex tiley)
  (setf! actor-class new (class-of which))
  (setf! actor-hitpoints new (start-hitpoints which))
  (setf! actor-dir new (* dir 2))
  (setf! actor-flags new (bitwise-ior (ref actor-flags new) FL_SHOOTABLE)))

(define (SpawnDeadGuard tilex tiley)
  (SpawnNewObj tilex tiley s_grddie4)
  (setf! actor-class new inertobj))

(define (spawn-boss tilex tiley state which class dir)
  (SpawnNewObj tilex tiley state)
  (setf! actor-speed new SPDPATROL)
  (setf! actor-class new class)
  (setf! actor-hitpoints new (start-hitpoints which))
  (setf! actor-dir new dir)
  (setf! actor-flags new (bitwise-ior (ref actor-flags new)
                                      (bitwise-ior FL_SHOOTABLE FL_AMBUSH)))
  (unless loadedgame
    (set! killtotal (+ killtotal 1))))

(define (SpawnBoss tilex tiley) (spawn-boss tilex tiley s_bossstand en_boss bossobj south))
(define (SpawnGretel tilex tiley) (spawn-boss tilex tiley s_gretelstand en_gretel gretelobj north))
(define (SpawnSchabbs tilex tiley)
  (setf! (ref s_schabbdie1 'next) 'tictime (if (= DigiMode sds_Off) 5 140))
  (spawn-boss tilex tiley s_schabbstand en_schabbs schabbobj south))
(define (SpawnGift tilex tiley)
  (setf! (ref s_giftdie1 'next) 'tictime (if (= DigiMode sds_Off) 5 140))
  (spawn-boss tilex tiley s_giftstand en_gift giftobj north))
(define (SpawnFat tilex tiley)
  (setf! (ref s_fatdie1 'next) 'tictime (if (= DigiMode sds_Off) 5 140))
  (spawn-boss tilex tiley s_fatstand en_fat fatobj south))
(define (SpawnFakeHitler tilex tiley)
  (setf! s_hitlerdie2 'tictime (if (= DigiMode sds_Off) 5 140))
  (spawn-boss tilex tiley s_fakestand en_fake fakeobj north))
(define (SpawnHitler tilex tiley)
  (setf! s_hitlerdie2 'tictime (if (= DigiMode sds_Off) 5 140))
  (spawn-boss tilex tiley s_mechastand en_hitler mechahitlerobj south))

(define (SpawnGhosts which tilex tiley)
  (SpawnNewObj tilex tiley (cond ((= which en_blinky) s_blinkychase1)
                                 ((= which en_clyde) s_clydechase1)
                                 ((= which en_pinky) s_pinkychase1)
                                 (else s_inkychase1)))
  (setf! actor-class new ghostobj)
  (setf! actor-speed new SPDDOG)
  (setf! actor-dir new east)
  (setf! actor-flags new (bitwise-ior (ref actor-flags new) FL_AMBUSH))
  (unless loadedgame
    (set! killtotal (+ killtotal 1))))

;; WL_ACT2.C:1030-1078. The spawn tile is released and the actor claims the tile ahead of it.
(define (SpawnPatrol which tilex tiley dir)
  (SpawnNewObj tilex tiley (path-state which))
  (setf! actor-speed new (if (= which en_dog) SPDDOG SPDPATROL))
  (unless loadedgame
    (set! killtotal (+ killtotal 1)))
  (setf! actor-class new (class-of which))
  (setf! actor-dir new (* dir 2))
  (setf! actor-hitpoints new (start-hitpoints which))
  (setf! actor-distance new TILEGLOBAL)
  (setf! actor-flags new (bitwise-ior (ref actor-flags new) FL_SHOOTABLE))
  (setf! actor-active new #t)
  (actorat-set! (ref actor-tilex new) (ref actor-tiley new) -1)
  (cond ((= dir 0) (setf! actor-tilex new (+ (ref actor-tilex new) 1)))
        ((= dir 1) (setf! actor-tiley new (- (ref actor-tiley new) 1)))
        ((= dir 2) (setf! actor-tilex new (- (ref actor-tilex new) 1)))
        ((= dir 3) (setf! actor-tiley new (+ (ref actor-tiley new) 1))))
  (actorat-set! (ref actor-tilex new) (ref actor-tiley new) new))

;; WL_ACT2.C:2280-2345 and :2930-2960. The projectile flies at the player's bearing.
(define (throw-at-player index state class speed sound flags)
  (let* ((deltax (- player-x (ref actor-x index)))
         (deltay (- (ref actor-y index) player-y))
         (angle (atan2 deltay deltax))
         (wrapped (if (< angle 0) (+ (* pi 2) angle) angle))
         (iangle (truncate (* (/ wrapped (* pi 2)) ANGLES)))
         (fromx (ref actor-x index))
         (fromy (ref actor-y index))
         (fromtilex (ref actor-tilex index))
         (fromtiley (ref actor-tiley index)))
    (SpawnNewObj fromtilex fromtiley state)
    (setf! actor-ticcount new 1)
    (setf! actor-x new fromx)
    (setf! actor-y new fromy)
    (setf! actor-class new class)
    (setf! actor-dir new nodir)
    (setf! actor-angle new iangle)
    (setf! actor-speed new speed)
    (setf! actor-flags new flags)
    (setf! actor-active new #t)
    (PlaySoundLocActor sound new)))

(define (T_SchabbThrow index tics)
  (throw-at-player index s_needle1 needleobj 8192 SCHABBSTHROWSND FL_NONMARK))

(define (T_GiftThrow index tics)
  (throw-at-player index s_rocket rocketobj 8192 MISSILEFIRESND FL_NONMARK))

(define (T_Gift index tics)
  (boss-chase index tics s_giftshoot1))

(define (T_Fat index tics)
  (boss-chase index tics s_fatshoot1))

(define (T_Schabb index tics)
  (let* ((dx (abs (- (ref actor-tilex index) player-tilex)))
         (dy (abs (- (ref actor-tiley index) player-tiley)))
         (dist (if (> dx dy) dx dy))
         (shot (CheckLine index))
         (attack (and shot (< (US_RndT) (arithmetic-shift tics 3))))
         (dodge shot)
         (select (lambda (actor)
                   (cond ((< dist 4) (SelectRunDir actor))
                         (dodge (SelectDodgeDir actor))
                         (else (SelectChaseDir actor))))))
    (if attack
        (NewState index s_schabbshoot1)
        (begin
          (when (= (ref actor-dir index) nodir)
            (if dodge (SelectDodgeDir index) (SelectChaseDir index)))
          (unless (= (ref actor-dir index) nodir)
            (walk-move index (* (ref actor-speed index) tics) select))))))

(define (T_FakeFire index tics)
  (throw-at-player index s_fire1 fireobj 4608 FLAMETHROWERSND FL_NEVERMARK))

(define (T_Stand index tics)
  (SightPlayer index tics))

(define (T_Path index tics)
  (unless (SightPlayer index tics)
    (when (= (ref actor-dir index) nodir)
      (SelectPathDir index))
    (unless (= (ref actor-dir index) nodir)
      (let ((select (lambda (actor)
                      (when (or (> (ref actor-tilex actor) MAPSIZE)
                                (> (ref actor-tiley actor) MAPSIZE))
                        (Quit (string-append "T_Path hit a wall at "
                                             (number->string (ref actor-tilex actor)) ","
                                             (number->string (ref actor-tiley actor)) ", dir "
                                             (number->string (ref actor-dir actor)))))
                      (SelectPathDir actor))))
        (walk-move index (* (ref actor-speed index) tics) select)))))

(define (SelectPathDir index)
  (let ((spot (- (maptile 1 (+ (* (ref actor-tiley index) MAPSIZE) (ref actor-tilex index)))
                 ICONARROWS)))
    (when (and (>= spot 0) (< spot 8))
      (setf! actor-dir index spot))
    (setf! actor-distance index TILEGLOBAL)
    (unless (TryWalk index)
      (setf! actor-dir index nodir))))

(define (T_DogChase index tics)
  (when (= (ref actor-dir index) nodir)
    (SelectDodgeDir index))
  (unless (= (ref actor-dir index) nodir)
    (let loop ((move (* (ref actor-speed index) tics)))
      (when (> move 0)
        (let ((dx (- (abs (- player-x (ref actor-x index))) move))
              (dy (- (abs (- player-y (ref actor-y index))) move)))
          (if (and (<= dx MINACTORDIST) (<= dy MINACTORDIST))
              (NewState index s_dogjump1)
              (if (< move (ref actor-distance index))
                  (MoveObj index move)
                  (let ((rest (- move (ref actor-distance index))))
                    (center-on-tile index)
                    (SelectDodgeDir index)
                    (unless (= (ref actor-dir index) nodir)
                      (loop rest))))))))))

(define (T_Ghosts index tics)
  (when (= (ref actor-dir index) nodir)
    (SelectChaseDir index))
  (unless (= (ref actor-dir index) nodir)
    (plain-walk index (* (ref actor-speed index) tics) SelectChaseDir)))

(define (T_Chase index tics)
  (unless victoryflag
    (let ((shot (CheckLine index)))
      (unless (and shot (chase-attack index tics))
        (let ((select (if shot SelectDodgeDir SelectChaseDir)))
          (when (= (ref actor-dir index) nodir)
            (select index))
          (unless (= (ref actor-dir index) nodir)
            (walk-move index (* (ref actor-speed index) tics) select)))))))

(define (T_Fake index tics)
  (if (and (CheckLine index) (< (US_RndT) (arithmetic-shift tics 1)))
      (NewState index s_fakeshoot1)
      (begin
        (when (= (ref actor-dir index) nodir)
          (SelectDodgeDir index))
        (unless (= (ref actor-dir index) nodir)
          (plain-walk index (* (ref actor-speed index) tics) SelectDodgeDir)))))

(define PROJSIZE 8192)
(define PROJECTILESIZE 49152)

(define (ProjectileTryMove index)
  (let ((xl (tileof (- (ref actor-x index) PROJSIZE)))
        (yl (tileof (- (ref actor-y index) PROJSIZE)))
        (xh (tileof (+ (ref actor-x index) PROJSIZE)))
        (yh (tileof (+ (ref actor-y index) PROJSIZE))))
    (let rows ((ty yl))
      (if (> ty yh)
          #t
          (let cols ((tx xl))
            (cond ((> tx xh) (rows (+ ty 1)))
                  ((or (solid-at tx ty) (= (actorat-at tx ty) MAXACTORS)) #f)
                  (else (cols (+ tx 1)))))))))

(define (T_Projectile index tics)
  (let* ((speed (* (ref actor-speed index) tics))
         (angle (ref actor-angle index))
         (deltax (min (FixedByFrac speed (ref costable angle)) 65536))
         (deltay (min (- (FixedByFrac speed (ref sintable angle))) 65536)))
    (setf! actor-x index (+ (ref actor-x index) deltax))
    (setf! actor-y index (+ (ref actor-y index) deltay))
    (let ((gapx (abs (- (ref actor-x index) player-x)))
          (gapy (abs (- (ref actor-y index) player-y)))
          (which (ref actor-class index)))
      (cond
        ((not (ProjectileTryMove index))
         (if (= which rocketobj)
             (begin
               (PlaySoundLocActor MISSILEHITSND index)
               (setf! actor-state index s_boom1))
             (RemoveObj index)))
        ((and (< gapx PROJECTILESIZE) (< gapy PROJECTILESIZE))
         (TakeDamage (cond ((= which needleobj) (+ (arithmetic-shift (US_RndT) -3) 20))
                           ((or (= which rocketobj) (= which hrocketobj))
                            (+ (arithmetic-shift (US_RndT) -3) 30))
                           (else (arithmetic-shift (US_RndT) -3)))
                     index)
         (RemoveObj index))
        (else
         (setf! actor-tilex index (tileof (ref actor-x index)))
         (setf! actor-tiley index (tileof (ref actor-y index))))))))

;; WL_ACT2.C:226-252
(define (A_Smoke index tics)
  (let ((fromx (ref actor-x index))
        (fromy (ref actor-y index))
        (fromtilex (ref actor-tilex index))
        (fromtiley (ref actor-tiley index)))
    (SpawnNewObj fromtilex fromtiley s_smoke1)
    (setf! actor-ticcount new 6)
    (setf! actor-x new fromx)
    (setf! actor-y new fromy)
    (setf! actor-class new inertobj)
    (setf! actor-active new #t)
    (setf! actor-flags new FL_NEVERMARK)))

(define (A_MechaSound index tics)
  (when (areabyplayer-at (ref actor-areanumber index))
    (PlaySoundLocActor MECHSTEPSND index)))

(define (A_Slurpie index tics)
  (SD_PlaySound SLURPIESND))

;; WL_ACT2.C:2886-2910
(define (A_HitlerMorph index tics)
  (let ((fromx (ref actor-x index))
        (fromy (ref actor-y index))
        (distance (ref actor-distance index))
        (dir (ref actor-dir index))
        (flags (ref actor-flags index))
        (hitpoints (ref morph-hitpoints difficulty)))
    (SpawnNewObj (ref actor-tilex index) (ref actor-tiley index) s_hitlerchase1)
    (setf! actor-speed new (* SPDPATROL 5))
    (setf! actor-x new fromx)
    (setf! actor-y new fromy)
    (setf! actor-distance new distance)
    (setf! actor-dir new dir)
    (setf! actor-flags new (bitwise-ior flags FL_SHOOTABLE))
    (setf! actor-class new realhitlerobj)
    (setf! actor-hitpoints new hitpoints)))

(define morph-hitpoints (vector 500 700 800 900))

(define (SpawnBJVictory)
  (SpawnNewObj player-tilex (+ player-tiley 1) s_bjrun1)
  (setf! actor-x new player-x)
  (setf! actor-y new player-y)
  (setf! actor-class new bjobj)
  (setf! actor-dir new north)
  (setf! actor-temp1 new 6))

(define (T_BJRun index tics)
  (let loop ((move (* 2048 tics)))
    (when (> move 0)
      (if (< move (ref actor-distance index))
          (MoveObj index move)
          (let ((distance (ref actor-distance index)))
            (center-on-tile index)
            (SelectPathDir index)
            (setf! actor-temp1 index (- (ref actor-temp1 index) 1))
            (if (= (ref actor-temp1 index) 0)
                (NewState index s_bjjump1)
                (loop (- move distance))))))))

(define (T_BJJump index tics)
  (MoveObj index (* 680 tics)))

(define (T_BJYell index tics)
  (PlaySoundLocActor YEAHSND index))

(define (T_BJDone index tics)
  (set! playstate ex_victorious))

(define lastsound -1)

(define (PlaySoundLocActor sound index)
  (set! lastsound sound)
  (PlaySoundLocGlobal sound (ref actor-x index) (ref actor-y index)))

(define deathscreams
  (vector DEATHSCREAM1SND DEATHSCREAM2SND DEATHSCREAM3SND DEATHSCREAM4SND
          DEATHSCREAM5SND DEATHSCREAM7SND DEATHSCREAM8SND DEATHSCREAM9SND))

;; WL_ACT2.C:1080-1160. The bosses are not positioned; C plays them flat.
(define (A_DeathScream index tics)
  (let ((which (ref actor-class index)))
    (cond
      ((and (= mapon 9) (= (US_RndT) 0)
            (or (= which mutantobj) (= which (class-of en_guard))
                (= which (class-of en_officer)) (= which (class-of en_ss))
                (= which (class-of en_dog))))
       (PlaySoundLocActor DEATHSCREAM6SND index))
      ((= which mutantobj) (PlaySoundLocActor AHHHGSND index))
      ((= which (class-of en_guard))
       (PlaySoundLocActor (ref deathscreams (modulo (US_RndT) 8)) index))
      ((= which (class-of en_officer)) (PlaySoundLocActor NEINSOVASSND index))
      ((= which (class-of en_ss)) (PlaySoundLocActor LEBENSND index))
      ((= which (class-of en_dog)) (PlaySoundLocActor DOGDEATHSND index))
      ((= which bossobj) (SD_PlaySound MUTTISND))
      ((= which schabbobj) (SD_PlaySound MEINGOTTSND))
      ((= which fakeobj) (SD_PlaySound HITLERHASND))
      ((= which mechahitlerobj) (SD_PlaySound SCHEISTSND))
      ((= which realhitlerobj) (SD_PlaySound EVASND))
      ((= which gretelobj) (SD_PlaySound MEINSND))
      ((= which giftobj) (SD_PlaySound DONNERSND))
      ((= which fatobj) (SD_PlaySound ROSESND)))))

;; WL_ACT2.C: T_Shoot.  C's global tics is irrelevant to this instant action.
(define (T_Shoot index tics)
  (when (and (areabyplayer-at (ref actor-areanumber index)) (CheckLine index))
    (let* ((dx (abs (- (ref actor-tilex index) player-tilex)))
           (dy (abs (- (ref actor-tiley index) player-tiley)))
           (base-dist (if (> dx dy) dx dy))
           (which (ref actor-class index))
           (dist (if (or (= which (class-of en_ss)) (= which bossobj))
                     (truncate (/ (* base-dist 2) 3)) base-dist))
           (visible (not (= 0 (bitwise-and (ref actor-flags index) FL_VISABLE))))
           (hitchance (if (>= thrustspeed RUNSPEED)
                          (- 160 (* dist (if visible 16 8)))
                          (- 256 (* dist (if visible 16 8))))))
      (when (< (US_RndT) hitchance)
        (TakeDamage (arithmetic-shift (US_RndT)
                                      (if (< dist 2) -2 (if (< dist 4) -3 -4))) index))
      (PlaySoundLocActor
       (cond ((= which (class-of en_ss)) SSFIRESND)
             ((or (= which giftobj) (= which fatobj)) MISSILEFIRESND)
             ((or (= which mechahitlerobj) (= which realhitlerobj) (= which bossobj)) BOSSFIRESND)
             ((= which schabbobj) SCHABBSTHROWSND)
             ((= which fakeobj) FLAMETHROWERSND)
             (else NAZIFIRESND))
       index))))

(define (T_Bite index tics)
  (PlaySoundLocActor DOGATTACKSND index)
  (let ((dx (- (abs (- player-x (ref actor-x index))) TILEGLOBAL)))
    (when (<= dx MINACTORDIST)
      (let ((dy (- (abs (- player-y (ref actor-y index))) TILEGLOBAL)))
        (when (and (<= dy MINACTORDIST) (< (US_RndT) 180))
          (TakeDamage (arithmetic-shift (US_RndT) -4) index))))))

(define (CheckPosition index)
  (let ((xl (tileof (- (ref actor-x index) PLAYERSIZE)))
        (yl (tileof (- (ref actor-y index) PLAYERSIZE)))
        (xh (tileof (+ (ref actor-x index) PLAYERSIZE)))
        (yh (tileof (+ (ref actor-y index) PLAYERSIZE))))
    (let rows ((y yl))
      (if (> y yh) #t
          (let columns ((x xl))
            (cond ((> x xh) (rows (+ y 1)))
                  ((or (solid-at x y) (= (actorat-at x y) MAXACTORS)) #f)
                  (else (columns (+ x 1)))))))))

(define (actor-visible index)
  (let ((tilex (ref actor-tilex index))
        (tiley (ref actor-tiley index)))
    (let ((own (spotvis-at tilex tiley)))
      (if (= own 1)
          #t
          (let neighbours ((dx -1) (found #f))
            (if (or found (> dx 1))
                found
                (neighbours (+ dx 1)
                            (let scan ((dy -1) (seen #f))
                              (if (or seen (> dy 1))
                                  seen
                                  (scan (+ dy 1)
                                        (let ((nx (+ tilex dx)) (ny (+ tiley dy)))
                                          (if (or (< nx 0) (>= nx MAPSIZE) (< ny 0) (>= ny MAPSIZE))
                                              seen
                                              (and (= 1 (spotvis-at nx ny))
                                                   (= 0 (tileat nx ny)))))))))))))))


