;;; WL_DRAW.C — wall raycaster, headless framebuffer

(define TILEGLOBAL 65536)
(define TILESHIFT 16)
(define MAPSIZE 64)
(define ANGLES 360)
(define FINEANGLES 3600)
(define ANG90 900)
(define ANG180 1800)
(define ANG270 2700)
(define ANG360 3600)
(define MINDIST 22528)
(define FOCALLENGTH 22272)
(define VIEWGLOBAL 65536)
(define AREATILE 107)

(define viewwidth 320)
(define viewheight 160)
(define viewleft 0)
(define viewtop 0)
(define screenwidth 320)
(define screenheight 200)

(define finetangent (make-vector 900 0))
(define sintable (make-vector 361 0))
(define costable (make-vector 361 0))
(define pixelangle (make-vector viewwidth 0))

(define pi 3.14159265358979)

(define (atan2 y x)
  (cond ((> x 0) (atan (/ y x)))
        ((< x 0) (if (< y 0) (- (atan (/ y x)) pi) (+ (atan (/ y x)) pi)))
        ((> y 0) (/ pi 2))
        ((< y 0) (- (/ pi 2)))
        (else 0)))

(define (FixedByFrac a b) (truncate (/ (* a b) 65536)))

(define (FixedMul left right)
  (* (arithmetic-shift left -8) (arithmetic-shift right -8)))

(define ACTORSIZE 16384)
(define centerx (- (/ viewwidth 2) 1))

(define (TransformTile tilex tiley)
  (let ((gx (- (+ (* tilex TILEGLOBAL) 32768) viewx))
        (gy (- (+ (* tiley TILEGLOBAL) 32768) viewy)))
    (let ((nx (- (- (FixedByFrac gx viewcos) (FixedByFrac gy viewsin)) 8192))
          (ny (+ (FixedByFrac gy viewcos) (FixedByFrac gx viewsin))))
      (if (< nx MINDIST)
          (list 0 0 #f)
          (list (+ centerx (truncate (/ (* ny scale) nx)))
                (truncate (/ heightnumerator (truncate (/ nx 256))))
                (and (< nx TILEGLOBAL)
                     (> ny (- (truncate (/ TILEGLOBAL 2))))
                     (< ny (truncate (/ TILEGLOBAL 2)))))))))

(define dirangle (vector 0 45 90 135 180 225 270 315 360))

(define (CalcRotate index screenx)
  (let ((viewangle (+ player-angle (truncate (/ (- centerx screenx) 8))))
        (which (ref actor-class index)))
    (let ((facing (if (or (= which rocketobj) (= which hrocketobj))
                      (ref actor-angle index)
                      (ref dirangle (ref actor-dir index)))))
      (let ((angle (+ (- (- viewangle 180) facing) 22)))
        (let ((wrapped (let wrap ((value angle))
                         (cond ((>= value 360) (wrap (- value 360)))
                               ((< value 0) (wrap (+ value 360)))
                               (else value)))))
          (if (eqv? (actor-rotates index) 2)
              (* 4 (truncate (/ wrapped 180)))
              (truncate (/ wrapped 45))))))))

(define (TransformActor index)
  (let ((gx (- (ref actor-x index) viewx))
        (gy (- (ref actor-y index) viewy)))
    (let ((nx (- (- (FixedByFrac gx viewcos) (FixedByFrac gy viewsin)) ACTORSIZE))
          (ny (+ (FixedByFrac gy viewcos) (FixedByFrac gx viewsin))))
      (setf! actor-transx index nx)
      (setf! actor-transy index ny)
      (if (< nx MINDIST)
          (list 0 0)
          (let ((screenx (+ centerx (truncate (/ (* ny scale) nx)))))
            (setf! actor-viewx index screenx)
            (list screenx (truncate (/ heightnumerator (truncate (/ nx 256))))))))))

(define (tileof value) (truncate (/ value TILEGLOBAL)))

(define (BuildTables)
  (let ((radtoint (/ (/ FINEANGLES 2) pi)))
    (let loop ((index 0))
      (when (< index (/ FINEANGLES 8))
        (let ((tang (tan (/ (+ index 0.5) radtoint))))
          (setf! finetangent index (truncate (* tang TILEGLOBAL)))
          (setf! finetangent (- (- (/ FINEANGLES 4) 1) index)
                 (truncate (* (/ 1 tang) TILEGLOBAL))))
        (loop (+ index 1)))))
  (let loop ((index 0))
    (when (<= index ANGLES)
      (let ((angle (* (/ index ANGLES) (* 2 pi))))
        (setf! sintable index (truncate (* TILEGLOBAL (sin angle)))))
      (loop (+ index 1))))
  (let loop ((index 0))
    (when (<= index ANGLES)
      (setf! costable index (ref sintable (modulo (+ index (/ ANGLES 4)) ANGLES)))
      (loop (+ index 1)))))

(define focallength 0)
(define facedist 0)
(define scale 0)
(define heightnumerator 0)
(define minheightdiv 0)
(define maxslope 0)

(define (CalcProjection focal)
  (set! focallength focal)
  (set! facedist (+ focal MINDIST))
  (let ((halfview (/ viewwidth 2))
        (radtoint (/ (/ FINEANGLES 2) pi)))
    (set! scale (truncate (/ (* halfview facedist) (/ VIEWGLOBAL 2))))
    (set! heightnumerator (truncate (/ (* TILEGLOBAL scale) 64)))
    (let loop ((index 0))
      (when (< index halfview)
        (let ((tang (/ (truncate (/ (* index VIEWGLOBAL) viewwidth)) facedist)))
          (let ((intang (truncate (* (atan tang) radtoint))))
            (setf! pixelangle (- (- halfview 1) index) intang)
            (setf! pixelangle (+ halfview index) (- intang))))
        (loop (+ index 1))))
    (set! minheightdiv (+ (truncate (/ heightnumerator #x7fff)) 1))
    (set! maxslope (arithmetic-shift (ref finetangent (ref pixelangle 0)) -8))))

(define tilemap (make-bytevector (* MAPSIZE MAPSIZE) 0))
(define NUMAREAS 37)
(define areamap (make-bytevector (* MAPSIZE MAPSIZE) 0))

(define (areaat x y) (ref areamap (+ (* x MAPSIZE) y)))

(define (areaset! x y value) (setf! areamap (+ (* x MAPSIZE) y) value))

(define (tileat x y) (ref tilemap (+ (* x MAPSIZE) y)))

(define (tileset! x y value) (setf! tilemap (+ (* x MAPSIZE) y) value))

(define MAXDOORS 64)
(define doorposition (make-vector MAXDOORS 0))
(define doorlock (make-vector MAXDOORS 0))
(define doorvertical (make-vector MAXDOORS #f))
(define doortilex (make-vector MAXDOORS 0))
(define doortiley (make-vector MAXDOORS 0))
(define doornum 0)

(define (SpawnDoors)
  (set! doornum 0)
  (let rows ((y 0))
    (when (< y MAPSIZE)
      (let cols ((x 0))
        (when (< x MAPSIZE)
          (let ((tile (maptile 0 (+ (* y MAPSIZE) x))))
            (when (and (>= tile 90) (<= tile 101))
              (if (= 0 (- tile (* 2 (truncate (/ tile 2)))))
                  (SpawnDoor x y #t (truncate (/ (- tile 90) 2)))
                  (SpawnDoor x y #f (truncate (/ (- tile 91) 2))))))
          (cols (+ x 1))))
      (rows (+ y 1)))))

(define (doorwall) (- PMSpriteStart 8))

(define (doorpage lock vertical)
  (let ((base (cond ((= lock 0) (doorwall))
                    ((= lock 5) (- PMSpriteStart 4))
                    (else (- PMSpriteStart 2)))))
    (if vertical (+ base 1) base)))

(define (halfstep step)
  (let ((half (/ step 2)))
    (if (< half 0) (- 0 (truncate (- 0 half))) (truncate half))))

(define episode 0)

(define player-x 0)
(define player-y 0)
(define player-angle 0)
(define player-tilex 0)
(define player-tiley 0)
(define player-areanumber 0)

(define SPR_DEMO 0)
(define SPR_KNIFEREADY 416)

(define weaponscale
  (vector SPR_KNIFEREADY (+ SPR_KNIFEREADY 5) (+ SPR_KNIFEREADY 10) (+ SPR_KNIFEREADY 15)))

(define (DrawPlayerWeapon)
  (if (and (not spear-mode) victoryflag)
      (when (and deathcam-active (> (bitwise-and TimeCount 32) 0))
        (SimpleScaleShape (quotient viewwidth 2) SPR_DEATHCAM (+ viewheight 1)))
      (begin
        (when (not (= weapon -1))
          (SimpleScaleShape (quotient viewwidth 2)
                            (+ (ref weaponscale weapon) weaponframe)
                            (+ viewheight 1)))
        (when (or demorecord demoplayback)
          (SimpleScaleShape (quotient viewwidth 2) SPR_DEMO (+ viewheight 1))))))

(define TickBase 70)
(define MAXTICS 10)
(define lasttimecount 0)
(define frameon 0)
(define fizzlein #f)

(define (CalcTics)
  (let* ((newtime (* (time-monotonic) TickBase))
         (elapsed (truncate (- newtime lasttimecount))))
    (set! tics (max 1 (min elapsed MAXTICS)))
    (set! lasttimecount newtime)))

;; WL_DRAW.C: FixOfs restores the displayed view into the draw page before
;; incremental drawing.  Page offsets become explicit source/destination RAM.
(define (FixOfs)
  (let rows ((y 0))
    (when (< y viewheight)
      (let columns ((x 0))
        (when (< x viewwidth)
          (let ((offset (+ (* (+ viewtop y) screenwidth) viewleft x)))
            (setf! framebuffer offset (ref displayframebuffer offset)))
          (columns (+ x 1))))
      (rows (+ y 1)))))

(define framebuffer (make-bytevector (* screenwidth screenheight) 0))
(define wallheight (make-vector viewwidth 0))
(define last-vertical-wall #f)
(define last-vertical-xtile 0)
(define last-vertical-tile 0)
(define last-vertical-texture 0)
(define last-horizontal-wall #f)
(define last-horizontal-ytile 0)
(define last-horizontal-tile 0)
(define last-horizontal-texture 0)
(define last-door #f)
(define last-door-number 0)
(define last-door-texture 0)
(define last-pwall #f)
(define last-pwall-tile 0)
(define last-pwall-texture 0)

;; WL_DRAW.C:947-956, low byte of each doubled word.
(define vgaCeiling
  (vector 29 29 29 29 29 29 29 29 29 191
          78 78 78 29 141 78 29 45 29 141
          29 29 29 29 29 45 221 29 29 152
          29 157 45 221 221 157 45 77 29 221
          125 29 45 45 221 215 29 29 29 45
          29 29 29 29 221 221 125 221 221 221))

(define FLOOR 25)

(define (ceiling-color)
  (ref vgaCeiling (+ (* episode 10) mapon)))

(define (ClearScreen)
  (VGAClearScreen))

(define (VGAClearScreen)
  (let ((top (ceiling-color))
        (half (truncate (/ viewheight 2))))
    (let rows ((y 0))
      (when (< y (* half 2))
        (let ((value (if (< y half) top FLOOR)))
          (let cols ((x 0))
            (when (< x viewwidth)
              (setf! framebuffer (+ (* (+ y viewtop) screenwidth) viewleft x) value)
              (cols (+ x 1)))))
        (rows (+ y 1))))))

(define viewx 0)
(define viewy 0)
(define viewsin 0)
(define viewcos 0)
(define focaltx 0)
(define focalty 0)
(define xpartialup 0)
(define xpartialdown 0)
(define ypartialup 0)
(define ypartialdown 0)

(define (CalcHeight xintercept yintercept)
  (let ((gx (- xintercept viewx))
        (gy (- yintercept viewy)))
    (let ((nx (- (FixedByFrac gx viewcos) (FixedByFrac gy viewsin))))
      (let ((dist (if (< nx MINDIST) MINDIST nx)))
        (truncate (/ heightnumerator (truncate (/ dist 256))))))))

(define maxscale 0)
(define stepbytwo 0)

(define (BadScale)
  (Quit "BadScale called!"))

(define (SetupScaling maxscaleheight)
  (set! maxscale (- (truncate (/ maxscaleheight 2)) 1))
  (set! stepbytwo (truncate (/ viewheight 2))))

(SetupScaling (truncate (* viewwidth 1.5)))

;; WL_SCALE.C:153. Direct pixel drawing replaces the generated scaler code;
;; its observable result is the scaler's quantized output-row count.
(define (BuildCompScale height finalspot)
  (scale-rows height))

;; WL_SCALE.C:249. Generated VGA scaler instructions are interpreted directly
;; by ScalePost in this port, so no separate line-command dispatch is needed.
(define (ScaleLine)
  #f)

;; WOLFHACK.C plane state.  The two 64x64 VSWAP pages replace only the VGA
;; planar storage representation; every span remains an explicit draw pass.
(define halfheight 0)
(define plane-floor 0)
(define plane-ceiling 0)

(define (SetPlaneViewSize)
  (set! halfheight (arithmetic-shift viewheight -1))
  (set! plane-floor (PM_GetPage 0))
  (set! plane-ceiling (PM_GetPage 1)))

;; WOLFHACK.C: DrawSpans.  Draw the mirrored ceiling/floor pair for each
;; unoccluded column in a distance row.
(define (DrawSpans x1 x2 height)
  (let* (
         (level (plus-distance-level height halfheight))
         (length (truncate (/ (* 32768 scale) height)))
         (xstep (truncate (/ (* viewsin 2) height)))
         (ystep (truncate (/ (* viewcos 2) height)))
         (startx (+ viewx (FixedMul length viewcos)))
         (starty (- viewy (FixedMul length viewsin)))
         (top (- halfheight 1 height)) (bottom (+ halfheight height)))
    (let columns ((x x1))
      (when (<= x x2)
        (when (< (arithmetic-shift (ref wallheight x) -3) height)
          (let* ((prestep (- (arithmetic-shift viewwidth -1) x))
                 (xf (- startx (arithmetic-shift (* xstep prestep) -2)))
                 (yf (- starty (arithmetic-shift (* ystep prestep) -2)))
                 (tex (+ (arithmetic-shift (bitwise-and yf #x3f0000) -10)
                         (arithmetic-shift (bitwise-and xf #x3f0000) -16))))
            (when (and (>= top 0) (< bottom viewheight))
              (let ((lit-level (plus-ao (plus-light-level level (bitwise-and (arithmetic-shift xf -16) 63)
                                                          (bitwise-and (arithmetic-shift yf -16) 63))
                                        xf yf)))
                (setf! framebuffer (+ (* (+ viewtop top) screenwidth) viewleft x)
                       (plus-color (ref plane-ceiling tex) (plus-dither lit-level x top)))
                (setf! framebuffer (+ (* (+ viewtop bottom) screenwidth) viewleft x)
                       (plus-color (ref plane-floor tex) (plus-dither lit-level x bottom)))))))
        (columns (+ x 1))))))

(define (DrawPlanes)
  (when (not (= halfheight (arithmetic-shift viewheight -1))) (SetPlaneViewSize))
  (let rows ((height 1))
    (when (< height halfheight)
      (DrawSpans 0 (- viewwidth 1) height)
      (rows (+ height 1)))))

(define (scale-rows height)
  (let* ((raw (truncate (/ height 8)))
         (scale (cond ((< raw 1) 1)
                      ((> raw maxscale) maxscale)
                      (else raw)))
         (scaled (if (< scale stepbytwo)
                     scale
                     (+ stepbytwo (* 3 (truncate (/ (- scale stepbytwo) 3)))))))
    (* 2 scaled)))

(define FIRSTDOOR 90)
(define MAXWALLTILES 64)

;; WL_DRAW.C owns these lookup tables.  SetupWalls fills them during InitGame;
;; retain the initialization writes instead of deriving their values at use sites.
(define horizwall-table (make-vector MAXWALLTILES 0))
(define vertwall-table (make-vector MAXWALLTILES 0))

(define (walltile tile) (bitwise-and tile 191))

(define (horizwall tile) (ref horizwall-table (walltile tile)))

(define (vertwall tile) (ref vertwall-table (walltile tile)))

(define (pwalltile tile) (bitwise-and tile 63))

(define (horizpwall tile) (* (- (pwalltile tile) 1) 2))

(define (vertpwall tile) (+ (* (- (pwalltile tile) 1) 2) 1))

(define (door-neighbor? x y)
  (and (>= x 0) (< x MAPSIZE) (>= y 0) (< y MAPSIZE) (>= (tileat x y) 128)))

(define (horizpage tile xinttile ytile ytilestep)
  (if (and (> (bitwise-and tile 64) 0)
           (door-neighbor? xinttile (- ytile ytilestep)))
      (+ (doorwall) 2)
      (horizwall tile)))

(define (vertpage tile xtile yinttile xtilestep)
  (if (and (> (bitwise-and tile 64) 0)
           (door-neighbor? (- xtile xtilestep) yinttile))
      (+ (doorwall) 3)
      (vertwall tile)))

(define (ScalePost pixx height page column tilex tiley)
  (let* ((rows (scale-rows height))
         (level (plus-light-level (plus-distance-level rows viewheight) tilex tiley))
         (top (truncate (/ (- viewheight rows) 2)))
         (texels (PM_GetPage page)))
    (let loop ((y (max top 0)) (limit (min (+ top rows) viewheight)))
      (when (< y limit)
        (setf! framebuffer (+ (* (+ y viewtop) screenwidth) viewleft pixx)
               (plus-color (ref texels (+ (* column 64) (truncate (/ (* (- y top) 64) rows)))) (plus-dither level column (truncate (/ (* (- y top) 64) rows)))))
        (loop (+ y 1) limit)))))

(define (FarScalePost pixx height page column tilex tiley)
  (ScalePost pixx height page column tilex tiley))

(define (HitVertWall pixx tile xtile yinttile xtilestep yintercept)
  (let ((hitx (+ (* xtile TILEGLOBAL) (if (= xtilestep -1) TILEGLOBAL 0)))
        (texture (bitwise-and (arithmetic-shift yintercept -4) 4032)))
    (let* ((column (quotient (if (= xtilestep -1) (- 4032 texture) texture) 64))
           (height (CalcHeight hitx yintercept))
           (same-wall (and last-vertical-wall
                           (= last-vertical-xtile xtile)
                           (= last-vertical-tile tile)
                           (= last-vertical-texture texture))))
      (setf! wallheight pixx (if same-wall (ref wallheight (- pixx 1)) height))
      (set! last-pwall #f)
      (set! last-door #f)
      (set! last-horizontal-wall #f)
      (set! last-vertical-wall #t)
      (set! last-vertical-xtile xtile)
      (set! last-vertical-tile tile)
      (set! last-vertical-texture texture)
      (ScalePost pixx (ref wallheight pixx) (vertpage tile xtile yinttile xtilestep) column
                 (- xtile xtilestep) yinttile))))

(define (HitHorizWall pixx tile xinttile ytile ytilestep xintercept)
  (set! last-vertical-wall #f)
  (let ((hity (+ (* ytile TILEGLOBAL) (if (= ytilestep -1) TILEGLOBAL 0)))
        (texture (bitwise-and (arithmetic-shift xintercept -4) 4032)))
    (let* ((column (quotient (if (= ytilestep -1) (- 4032 texture) texture) 64))
           (height (CalcHeight xintercept hity))
           (same-wall (and last-horizontal-wall
                           (= last-horizontal-ytile ytile)
                           (= last-horizontal-tile tile)
                           (= last-horizontal-texture texture))))
      (setf! wallheight pixx (if same-wall (ref wallheight (- pixx 1)) height))
      (set! last-pwall #f)
      (set! last-door #f)
      (set! last-horizontal-wall #t)
      (set! last-horizontal-ytile ytile)
      (set! last-horizontal-tile tile)
      (set! last-horizontal-texture texture)
      (ScalePost pixx (ref wallheight pixx) (horizpage tile xinttile ytile ytilestep) column
                 xinttile (- ytile ytilestep)))))

(define (HitHorizDoor pixx door xmid ytile)
  (set! last-vertical-wall #f)
  (set! last-horizontal-wall #f)
  (set! last-pwall #f)
  (let ((hity (+ (* ytile TILEGLOBAL) 32768))
        (texture (bitwise-and (arithmetic-shift (- xmid (ref doorposition door)) -4) 4032)))
    (let* ((column (quotient texture 64))
           (height (CalcHeight xmid hity))
           (same-door (and last-door (= last-door-number door) (= last-door-texture texture))))
      (setf! wallheight pixx (if same-door (ref wallheight (- pixx 1)) height))
      (set! last-door #t)
      (set! last-door-number door)
      (set! last-door-texture texture)
      (ScalePost pixx (ref wallheight pixx) (doorpage (ref doorlock door) #f) column
                 (ref doortilex door) ytile))))

(define (HitVertDoor pixx door ymid xtile)
  (set! last-vertical-wall #f)
  (set! last-horizontal-wall #f)
  (set! last-pwall #f)
  (let ((hitx (+ (* xtile TILEGLOBAL) 32768))
        (texture (bitwise-and (arithmetic-shift (- ymid (ref doorposition door)) -4) 4032)))
    (let* ((column (quotient texture 64))
           (height (CalcHeight hitx ymid))
           (same-door (and last-door (= last-door-number door) (= last-door-texture texture))))
      (setf! wallheight pixx (if same-door (ref wallheight (- pixx 1)) height))
      (set! last-door #t)
      (set! last-door-number door)
      (set! last-door-texture texture)
      (ScalePost pixx (ref wallheight pixx) (doorpage (ref doorlock door) #t) column
                 xtile (ref doortiley door)))))

(define (HitHorizPWall pixx tile xmid ytile ytilestep)
  (set! last-vertical-wall #f)
  (set! last-horizontal-wall #f)
  (set! last-door #f)
  (let* ((offset (* pwallpos 1024))
         (hity (+ (* ytile TILEGLOBAL) (if (= ytilestep -1) (- TILEGLOBAL offset) offset)))
         (texture (bitwise-and (arithmetic-shift xmid -4) 4032))
         (column (quotient (if (= ytilestep -1) texture (- 4032 texture)) 64))
         (height (CalcHeight xmid hity))
         (same-pwall (and last-pwall (= last-pwall-tile tile) (= last-pwall-texture texture))))
    (setf! wallheight pixx (if same-pwall (ref wallheight (- pixx 1)) height))
    (set! last-pwall #t)
    (set! last-pwall-tile tile)
    (set! last-pwall-texture texture)
    (ScalePost pixx (ref wallheight pixx) (horizpwall tile) column
               (bitwise-and (arithmetic-shift xmid -16) 63) (- ytile ytilestep))))

(define (HitVertPWall pixx tile ymid xtile xtilestep)
  (set! last-vertical-wall #f)
  (set! last-horizontal-wall #f)
  (set! last-door #f)
  (let* ((offset (* pwallpos 1024))
         (hitx (+ (* xtile TILEGLOBAL) (if (= xtilestep -1) (- TILEGLOBAL offset) offset)))
         (texture (bitwise-and (arithmetic-shift ymid -4) 4032))
         (column (quotient (if (= xtilestep -1) (- 4032 texture) texture) 64))
         (height (CalcHeight hitx ymid))
         (same-pwall (and last-pwall (= last-pwall-tile tile) (= last-pwall-texture texture))))
    (setf! wallheight pixx (if same-pwall (ref wallheight (- pixx 1)) height))
    (set! last-pwall #t)
    (set! last-pwall-tile tile)
    (set! last-pwall-texture texture)
    (ScalePost pixx (ref wallheight pixx) (vertpwall tile) column
               (- xtile xtilestep) (bitwise-and (arithmetic-shift ymid -16) 63))))

(define (CastColumn pixx)
  (let ((angl (+ (* player-angle 10) (ref pixelangle pixx))))
    (let ((angle (cond ((< angl 0) (+ angl FINEANGLES))
                       ((>= angl ANG360) (- angl FINEANGLES))
                       (else angl))))
      (let ((xtilestep 0) (ytilestep 0) (xstep 0) (ystep 0)
            (xpartial 0) (ypartial 0))
        (cond
          ((< angle ANG90)
           (set! xtilestep 1) (set! ytilestep -1)
           (set! xstep (ref finetangent (- (- ANG90 1) angle)))
           (set! ystep (- (ref finetangent angle)))
           (set! xpartial xpartialup) (set! ypartial ypartialdown))
          ((< angle ANG180)
           (set! xtilestep -1) (set! ytilestep -1)
           (set! xstep (- (ref finetangent (- angle ANG90))))
           (set! ystep (- (ref finetangent (- (- ANG180 1) angle))))
           (set! xpartial xpartialdown) (set! ypartial ypartialdown))
          ((< angle ANG270)
           (set! xtilestep -1) (set! ytilestep 1)
           (set! xstep (- (ref finetangent (- (- ANG270 1) angle))))
           (set! ystep (ref finetangent (- angle ANG180)))
           (set! xpartial xpartialdown) (set! ypartial ypartialup))
          (else
           (set! xtilestep 1) (set! ytilestep 1)
           (set! xstep (ref finetangent (- angle ANG270)))
           (set! ystep (ref finetangent (- (- ANG360 1) angle)))
           (set! xpartial xpartialup) (set! ypartial ypartialup)))
        (let loop ((xtile (+ focaltx xtilestep))
                   (ytile (+ focalty ytilestep))
                   (xintercept (+ (FixedByFrac xstep ypartial) viewx))
                   (yintercept (+ (FixedByFrac ystep xpartial) viewy))
                   (steps 0))
          (if (> steps 256)
              #f
              (let ((yinttile (tileof yintercept))
                    (xinttile (tileof xintercept)))
                (if (if (= ytilestep -1) (<= yinttile ytile) (>= yinttile ytile))
                    (let ((tile (if (and (>= xinttile 0) (< xinttile MAPSIZE)
                                         (>= ytile 0) (< ytile MAPSIZE))
                                    (tileat xinttile ytile)
                                    1)))
                      (if (> tile 0)
                          (if (and (>= tile 128) (> (bitwise-and tile 64) 0))
                              (let ((xmid (+ xintercept (truncate (/ (* xstep pwallpos) 64)))))
                                (if (not (= (tileof xmid) (tileof xintercept)))
                                    (begin
                                      (spotvis-mark xinttile ytile)
                                      (loop xtile (+ ytile ytilestep) (+ xintercept xstep) yintercept (+ steps 1)))
                                    (HitHorizPWall pixx tile xmid ytile ytilestep)))
                          (if (>= tile 128)
                              (let ((door (bitwise-and tile 127))
                                    (xmid (+ xintercept (halfstep xstep))))
                                (if (or (not (= (tileof xmid) (tileof xintercept)))
                                        (< (- xmid (* (tileof xmid) TILEGLOBAL))
                                           (ref doorposition (bitwise-and tile 127))))
                                    (begin
                                      (spotvis-mark xinttile ytile)
                                      (loop xtile (+ ytile ytilestep) (+ xintercept xstep) yintercept (+ steps 1)))
                                    (HitHorizDoor pixx door xmid ytile)))
                              (HitHorizWall pixx tile xinttile ytile ytilestep xintercept)))
                          (begin
                            (when (and (>= xinttile 0) (< xinttile MAPSIZE) (>= ytile 0) (< ytile MAPSIZE))
                              (spotvis-mark xinttile ytile))
                            (loop xtile (+ ytile ytilestep) (+ xintercept xstep) yintercept (+ steps 1)))))
                    (let ((tile (if (and (>= xtile 0) (< xtile MAPSIZE)
                                         (>= yinttile 0) (< yinttile MAPSIZE))
                                    (tileat xtile yinttile)
                                    1)))
                      (if (> tile 0)
                          (if (and (>= tile 128) (> (bitwise-and tile 64) 0))
                              (let ((ymid (+ yintercept (truncate (/ (* ystep pwallpos) 64)))))
                                (if (not (= (tileof ymid) (tileof yintercept)))
                                    (begin
                                      (spotvis-mark xtile yinttile)
                                      (loop (+ xtile xtilestep) ytile xintercept (+ yintercept ystep) (+ steps 1)))
                                    (HitVertPWall pixx tile ymid xtile xtilestep)))
                          (if (>= tile 128)
                              (let ((door (bitwise-and tile 127))
                                    (ymid (+ yintercept (halfstep ystep))))
                                (if (or (not (= (tileof ymid) (tileof yintercept)))
                                        (< (- ymid (* (tileof ymid) TILEGLOBAL))
                                           (ref doorposition (bitwise-and tile 127))))
                                    (begin
                                      (spotvis-mark xtile yinttile)
                                      (loop (+ xtile xtilestep) ytile xintercept (+ yintercept ystep) (+ steps 1)))
                                    (HitVertDoor pixx door ymid xtile)))
                              (HitVertWall pixx tile xtile yinttile xtilestep yintercept)))
                          (begin
                            (when (and (>= xtile 0) (< xtile MAPSIZE) (>= yinttile 0) (< yinttile MAPSIZE))
                              (spotvis-mark xtile yinttile))
                            (loop (+ xtile xtilestep) ytile xintercept (+ yintercept ystep) (+ steps 1)))))))))))))

(define (WallRefresh)
  (set! last-vertical-wall #f)
  (set! last-horizontal-wall #f)
  (set! last-door #f)
  (set! last-pwall #f)
  (set! viewsin (ref sintable player-angle))
  (set! viewcos (ref costable player-angle))
  (set! viewx (- player-x (FixedByFrac focallength viewcos)))
  (set! viewy (+ player-y (FixedByFrac focallength viewsin)))
  (set! focaltx (tileof viewx))
  (set! focalty (tileof viewy))
  (set! xpartialdown (- viewx (* focaltx TILEGLOBAL)))
  (set! xpartialup (- TILEGLOBAL xpartialdown))
  (set! ypartialdown (- viewy (* focalty TILEGLOBAL)))
  (set! ypartialup (- TILEGLOBAL ypartialdown))
  (let loop ((pixx 0))
    (when (< pixx viewwidth)
      (CastColumn pixx)
      (loop (+ pixx 1)))))

(define (DrawScaleds)
  (set! viscount 0)
  (place-statics)
  (place-actors)
  (let draw ((drawn 0))
    (when (< drawn viscount)
      (let pick ((index 0) (least 32000) (farthest 0))
        (if (< index viscount)
            (if (< (ref vis-height index) least)
                (pick (+ index 1) (ref vis-height index) index)
                (pick (+ index 1) least farthest))
            (begin
              (ScaleShape (ref vis-x farthest) (ref vis-shape farthest) (ref vis-height farthest)
                          (ref vis-tilex farthest) (ref vis-tiley farthest))
              (setf! vis-height farthest 32000))))
      (draw (+ drawn 1))))
  viscount)

(define (ThreeDRefresh)
  (let ((display (if fizzlein
                     (bytevector-copy framebuffer 0 (bytevector-length framebuffer))
                     #f)))
    (spotvis-clear)
    (VGAClearScreen)
    (WallRefresh)
    (when plus-enabled (plus-draw-planes))
    (DrawScaleds)
    (DrawPlayerWeapon)
    (when fizzlein
      (let ((rendered (bytevector-copy framebuffer 0 (bytevector-length framebuffer))))
        (bytevector-copy! framebuffer 0 display 0 (bytevector-length display))
        (FizzleFade rendered viewleft viewtop viewwidth viewheight 20 #f))
      (set! fizzlein #f)
      (set! lasttimecount 0)
      (set! TimeCount 0))
    ;; ThreeDRefresh presents its completed draw page, corresponding to the
    ;; reference page flip; the single host image receives an explicit copy.
    (bytevector-copy! displayframebuffer 0 framebuffer 0 (bytevector-length framebuffer))
    (set! frameon (+ frameon 1))
    (PM_NextFrame)))
