;;; WL_DEBUG.C — debug utilities

(define DebugOk #f)
(define singlestep #f)
(define extravbls 0)
(define VIEWTILEX 20)
(define VIEWTILEY 10)
(define MAXWALLTILES 64)
(define NUMBERCHARS 9)
(define maporgx 0)
(define maporgy 0)

(define (debug-message width height text)
  (US_CenterWindow width height)
  (US_PrintCentered text)
  (VW_UpdateScreen)
  (IN_Ack))

(define (debug-number width prompt)
  (US_CenterWindow width 3)
  (set! PrintY (+ PrintY 6))
  (US_Print prompt)
  (VW_UpdateScreen)
  (let ((text (US_LineInput px py #f #t 2 0)))
    (if text (string->number text) #f)))

(define (DebugMemory)
  (US_CenterWindow 16 7)
  (US_CPrint "Memory Usage")
  (US_CPrint "------------")
  ;; JetScheme has no DOS paragraph allocator; preserve C's report layout.
  (US_Print "Total     :n/a\nFree      :n/a\nWith purge:n/a\n")
  (VW_UpdateScreen)
  (IN_Ack))

(define (CountObjects)
  (let count ((index 0) (statics 0) (actors 0) (active 0))
    (if (< index (max statcount actorcount))
        (count (+ index 1)
               (if (and (< index statcount) (not (= (ref stat-shape index) -1)))
                   (+ statics 1)
                   statics)
               (if (and (< index actorcount) (ref actor-state index)) (+ actors 1) actors)
               (if (and (< index actorcount) (ref actor-state index) (ref actor-active index))
                   (+ active 1)
                   active))
        (begin
          (US_CenterWindow 16 7)
          (US_Print "Total statics :")
          (US_PrintUnsigned statcount)
          (US_Print "\nIn use statics:")
          (US_PrintUnsigned statics)
          (US_Print "\nDoors         :")
          (US_PrintUnsigned doornum)
          (US_Print "\nTotal actors  :")
          (US_PrintUnsigned actors)
          (US_Print "\nActive actors :")
          (US_PrintUnsigned active)
          (VW_UpdateScreen)
          (IN_Ack)))))

(define (PicturePause)
  (VL_ColorBorder 15)
  (FinishPaletteShifts)
  (set! LastScan sc_None)
  (if (not (= (IN_WaitForKey) sc_Enter))
      (VL_ColorBorder 0)
      (begin
        (VL_ColorBorder 1)
        (VL_SetPalette gamepal)
        (IN_Shutdown)
        (VL_WaitVBL 70)
        (IN_WaitForKey)
        (VL_WaitVBL 70)
        (Quit))))

(define (shape-page-kind page)
  (cond ((< page PMSpriteStart) " (Wall)")
        ((< page PMSoundStart) " (Sprite)")
        ((= page (- ChunksInFile 1)) " (Sound Info)")
        (else " (Sound)")))

(define (shape-page-count length)
  (quotient (+ length (- PMPageSize 1)) PMPageSize))

(define (shape-sound-info page)
  (if (= page (- ChunksInFile 1))
      (let total ((sound 0) (bytes 0) (pages 0))
        (if (= sound NumDigi)
            (begin
              (US_Print "\n\n Number of sounds: ")
              (US_PrintUnsigned NumDigi)
              (US_Print "\n Total bytes: ")
              (US_PrintUnsigned bytes)
              (US_Print "\n Total pages: ")
              (US_PrintUnsigned pages))
            (let ((length (ref DigiList (+ (* sound 2) 1))))
              (total (+ sound 1) (+ bytes length) (+ pages (shape-page-count length))))))
      (let find ((sound 0))
        (when (< sound NumDigi)
          (let ((start (+ PMSoundStart (ref DigiList (* sound 2))))
                (pages (shape-page-count (ref DigiList (+ (* sound 2) 1)))))
            (if (and (>= page start) (< page (+ start pages)))
                (begin
                  (US_Print "\n Sound #")
                  (US_PrintUnsigned sound)
                  (US_Print "\n Segment #")
                  (US_PrintUnsigned (- page start)))
                (find (+ sound 1))))))))

(define (draw-shape-page page)
  (cond ((< page PMSpriteStart)
         (let loop ((column 0))
           (when (< column 64)
             (FarScalePost (+ 128 column) 64 page column)
             (loop (+ column 1)))))
        ((< page PMSoundStart)
         (SimpleScaleShape 160 (- page PMSpriteStart) 64))
        ((< page (- ChunksInFile 1))
         (let ((data (PM_GetPage page))
               (baseline (+ WindowY WindowH -32)))
           (let loop ((index 0))
             (when (< index (bytevector-length data))
               (let ((value (truncate (/ (- (ref data index) 128) 4))))
                 (VWB_Vlin (min baseline (+ baseline value))
                           (max baseline (+ baseline value))
                           (+ WindowX 8 (quotient index 32)) 0))
               (loop (+ index 32))))))))

(define (ShapeTest)
  (US_CenterWindow 20 16)
  (VW_UpdateScreen)
  (let loop ((page 0))
    (US_ClearWindow)
    (US_Print " Page #")
    (US_PrintUnsigned page)
    (US_Print (shape-page-kind page))
    (let ((entry (ref PMPages page)))
      (US_Print "\n XMS: No")
      (US_Print "\n Main: ")
      (US_Print (if (ref pagecache page) "Bytevector" "No"))
      (US_Print "\n Last hit: ")
      (US_PrintUnsigned (ref entry 'lastHit))
      (US_Print "\n Length: ")
      (US_PrintUnsigned (ref entry 'length)))
    (when (>= page PMSoundStart)
      (shape-sound-info page))
    (draw-shape-page page)
    (VW_UpdateScreen)
    (set! LastScan sc_None)
    (let ((scan (IN_WaitForKey)))
      (IN_ClearKey scan)
      (cond ((= scan sc_Escape) (SD_StopDigitized))
            ((= scan sc_LeftArrow) (loop (max 0 (- page 1))))
            ((= scan sc_RightArrow) (loop (min (- ChunksInFile 1) (+ page 1))))
            ((= scan sc_W) (loop 0))
            ((= scan sc_S) (loop PMSpriteStart))
            ((= scan sc_D) (loop PMSoundStart))
            ((= scan sc_I) (loop (- ChunksInFile 1)))
            ((= scan sc_L)
             (let load ((index 0))
               (when (< index ChunksInFile)
                 (PM_GetPage index)
                 (load (+ index 1))))
             (loop page))
            ((= scan sc_Enter) (PM_GetPage page) (loop page))
            (else (loop page))))))

(define (DebugKeys)
  (cond
    ((ref Keyboard sc_B)
     (let ((level (debug-number 24 " Border color (0-15):")))
       (when (and level (>= level 0) (<= level 15)) (VL_ColorBorder level)))
     1)
    ((ref Keyboard sc_C) (CountObjects) 1)
    (else
     (when (ref Keyboard sc_E)
       (when tedlevel (Quit))
       (set! playstate ex_completed))
     (cond
       ((ref Keyboard sc_F)
        (US_CenterWindow 14 4)
        (US_Print "X:") (US_PrintUnsigned player-x)
        (US_Print "\nY:") (US_PrintUnsigned player-y)
        (US_Print "\nA:") (US_PrintUnsigned player-angle)
        (VW_UpdateScreen) (IN_Ack) 1)
       ((ref Keyboard sc_G)
        (debug-message 12 2 (if godmode "God mode OFF" "God mode ON"))
        (set! godmode (not godmode)) 1)
       ((ref Keyboard sc_H) (IN_ClearKeysDown) (TakeDamage 16 #f) 0)
       ((ref Keyboard sc_I)
        (US_CenterWindow 12 3)
        (US_PrintCentered "Free items!")
        (VW_UpdateScreen)
        (GivePoints 100000) (HealSelf 99)
        (when (< bestweapon wp_chaingun) (GiveWeapon (+ bestweapon 1)))
        (set! ammo (min 99 (+ ammo 50))) (DrawAmmo) (IN_Ack) 1)
       ((ref Keyboard sc_M) (DebugMemory) 1)
       ((and spear-mode (ref Keyboard sc_N))
        (set! noclip (not noclip))
        (debug-message 18 3 (if noclip "No clipping ON" "No clipping OFF")) 1)
       ((ref Keyboard sc_P) (PicturePause) 1)
       ((ref Keyboard sc_Q) (Quit) 0)
       ((ref Keyboard sc_S)
        (set! singlestep (not singlestep))
        (debug-message 18 3 (if singlestep "Slow motion ON" "Slow motion OFF")) 1)
       ((ref Keyboard sc_T) (ShapeTest) 1)
       ((ref Keyboard sc_V)
        (let ((level (debug-number 30 "  Add how many extra VBLs(0-8):")))
          (when (and level (>= level 0) (<= level 8)) (set! extravbls level))) 1)
       ((ref Keyboard sc_W)
        (let ((level (debug-number 26 "  Warp to which level(1-10):")))
          (when (and level (> level 0) (< level (if spear-mode 22 11)))
            (set! mapon (- level 1))
            (set! playstate ex_warped))) 1)
       ((ref Keyboard sc_X) (debug-message 12 3 "Extra stuff!") 1)
       (else 0)))))

(define (OverheadRefresh)
  (let rows ((y maporgy))
    (when (< y (+ maporgy VIEWTILEY))
      (let columns ((x maporgx))
        (when (< x (+ maporgx VIEWTILEX))
          (let ((screenx (* (- x maporgx) 16))
                (screeny (* (- y maporgy) 16))
                (tile (bitwise-and (actorat-at x y) 65535)))
            (if (< tile MAXWALLTILES)
                (VWB_Bar screenx screeny 16 16 tile)
                (begin
                  (VWB_DrawTile8 screenx screeny
                                 (+ NUMBERCHARS (bitwise-and (arithmetic-shift tile -12) 15)))
                  (VWB_DrawTile8 (+ screenx 8) screeny
                                 (+ NUMBERCHARS (bitwise-and (arithmetic-shift tile -8) 15)))
                  (VWB_DrawTile8 screenx (+ screeny 8)
                                 (+ NUMBERCHARS (bitwise-and (arithmetic-shift tile -4) 15)))
                  (VWB_DrawTile8 (+ screenx 8) (+ screeny 8)
                                 (+ NUMBERCHARS (bitwise-and tile 15)))))
            (columns (+ x 1)))))
      (rows (+ y 1)))))

(define (ViewMap)
  (set! maporgx (max 0 (min (- MAPSIZE VIEWTILEX)
                            (- player-tilex (quotient VIEWTILEX 2)))))
  (set! maporgy (max 0 (min (- MAPSIZE VIEWTILEY)
                            (- player-tiley (quotient VIEWTILEY 2)))))
  (let loop ()
    (PollControls)
    (when (and (< controlx 0) (> maporgx 0))
      (set! maporgx (- maporgx 1)))
    (when (and (> controlx 0) (< maporgx (- MAPSIZE VIEWTILEX)))
      (set! maporgx (+ maporgx 1)))
    (when (and (< controly 0) (> maporgy 0))
      (set! maporgy (- maporgy 1)))
    (when (and (> controly 0) (< maporgy (- MAPSIZE VIEWTILEY)))
      (set! maporgy (+ maporgy 1)))
    (OverheadRefresh)
    (unless (ref Keyboard sc_Escape)
      (when (IN_Yield)
        (loop))))
  (IN_ClearKeysDown))
