;;; WL_INTER.C — level completion and victory tallies

(define PAR_AMOUNT 500)
(define PERCENT100AMT 10000)

;; WL_INTER.C copy protection is compiled only for non-demo Spear releases.
;; The standard Wolf3D asset set has no associated quiz screens.
(define (CopyProtection)
  #f)

;; EndSpear is compiled only in the non-demo Spear of Destiny build.
(define (EndSpear)
  #f)

;; The Spear-only copy-protection backdoor is not exposed by Wolf3D.
(define (BackDoor text)
  #f)

(define (ClearSplitVWB)
  (let loop ((index 0))
    (when (< index (* UPDATEWIDE UPDATEHIGH))
      (setf! update index 0)
      (loop (+ index 1))))
  (set! WindowX 0)
  (set! WindowY 0)
  (set! WindowW 320)
  (set! WindowH 160))

(define (EndScreen palette screen)
  (CA_CacheScreen screen)
  (VW_UpdateScreen)
  (VL_FadeIn 0 255 (CA_CacheGrChunk palette) 30)
  (IN_ClearKeysDown)
  (IN_Ack)
  (VL_FadeOut 0 255 0 0 0 30))

(define L_GUYPIC 43)
(define L_COLONPIC 44)
(define L_NUM0PIC 45)
(define L_PERCENTPIC 55)
(define L_APIC 56)
(define L_EXPOINTPIC 82)
(define L_APOSTROPHEPIC 83)
(define L_GUY2PIC 84)
(define L_BJWINSPIC 85)

;; GFXV_WL6.H:46-48,97,99
(define LEVELEND_LUMP_START 43)
(define LEVELEND_LUMP_END 85)
(define C_TIMECODEPIC 37)
(define C_LEVELPIC 38)
(define C_NAMEPIC 39)
(define C_SCOREPIC 40)
(define PG13PIC 88)
(define HIGHSCORESPIC 90)
(define GETPSYCHEDPIC 134)

(define RATIOX 6)
(define RATIOY 14)
(define TIMEX 14)
(define TIMEY 8)
(define RATIOXX 37)

;; WL_INTER.C:656-706. The index is the character code less '0'; letters land above the digits
;; and the colon.
(define (letter-pic code)
  (let ((slot (- code (char->integer #\0))))
    (cond ((and (>= slot 0) (<= slot 9)) (+ L_NUM0PIC slot))
          ((= slot 10) L_COLONPIC)
          ((and (>= slot 17) (<= slot 42)) (+ L_APIC (- slot 17)))
          (else 0))))

(define (Write x y text)
  (let ((ox (* x 8)))
    (let loop ((index 0) (nx ox) (ny (* y 8)))
      (when (< index (string-length text))
        (let ((ch (string-ref text index)))
          (cond
            ((char=? ch #\newline) (loop (+ index 1) ox (+ ny 16)))
            ((char=? ch #\!)
             (VWB_DrawPic nx ny L_EXPOINTPIC)
             (loop (+ index 1) (+ nx 8) ny))
            ((char=? ch #\')
             (VWB_DrawPic nx ny L_APOSTROPHEPIC)
             (loop (+ index 1) (+ nx 8) ny))
            ((char=? ch #\:)
             (VWB_DrawPic nx ny L_COLONPIC)
             (loop (+ index 1) (+ nx 8) ny))
            ((char=? ch #\space) (loop (+ index 1) (+ nx 16) ny))
            ((char=? ch #\%)
             (VWB_DrawPic nx ny L_PERCENTPIC)
             (loop (+ index 1) (+ nx 16) ny))
            (else
             (let ((code (char->integer (char-upcase ch))))
               (VWB_DrawPic nx ny (letter-pic code)))
             (loop (+ index 1) (+ nx 16) ny))))))))

;; WL_INTER.C:451-553, minutes per level, zero where the level has no par time.
(define parTimes
  (vector 1.5 2 2 3.5 3 3 2.5 2.5 0 0
          1.5 3.5 3 2 4 6 1 3 0 0
          1.5 1.5 2.5 2.5 3.5 2.5 2 6 0 0
          2 2 1.5 1 4.5 3.5 2 4.5 0 0
          2.5 1.5 2.5 2.5 4 3 4.5 3.5 0 0
          6.5 4 4.5 6 5 5.5 5.5 8.5 0 0))

(define (par-time) (ref parTimes (+ (* episode 10) mapon)))

(define (two-digit value)
  (string-append (number->string (truncate (/ value 10)))
                 (number->string (- value (* 10 (truncate (/ value 10)))))))

(define (par-string minutes)
  (if (= minutes 0)
      "??:??"
      (let ((seconds (truncate (* minutes 60))))
        (string-append (two-digit (truncate (/ seconds 60)))
                       ":"
                       (two-digit (- seconds (* 60 (truncate (/ seconds 60)))))))))

(define (ratio-of count total)
  (if (= total 0)
      0
      (truncate (/ (* count 100) total))))

(define LevelRatios-kill (make-vector 10 0))
(define LevelRatios-secret (make-vector 10 0))
(define LevelRatios-treasure (make-vector 10 0))
(define LevelRatios-time (make-vector 10 0))

(define (right-write text y)
  (Write (- RATIOXX (* (string-length text) 2)) y text))

(define (draw-clock x y minutes seconds)
  (VWB_DrawPic x y (+ L_NUM0PIC (truncate (/ minutes 10))))
  (VWB_DrawPic (+ x 16) y (+ L_NUM0PIC (- minutes (* 10 (truncate (/ minutes 10))))))
  (Write (truncate (/ (+ x 32) 8)) (truncate (/ y 8)) ":")
  (VWB_DrawPic (+ x 40) y (+ L_NUM0PIC (truncate (/ seconds 10))))
  (VWB_DrawPic (+ x 56) y (+ L_NUM0PIC (- seconds (* 10 (truncate (/ seconds 10)))))))

(define bj-breathe-which 0)
(define bj-breathe-max 10)

(define (BJ_Breathe)
  (when (> TimeCount bj-breathe-max)
    (set! bj-breathe-which (- 1 bj-breathe-which))
    (VWB_DrawPic 0 16 (if (= bj-breathe-which 0) L_GUYPIC L_GUY2PIC))
    (VW_UpdateScreen)
    (set! TimeCount 0)
    (set! bj-breathe-max 35)))

(define (bonus-sound-wait)
  (VL_WaitVBL 1)
  (let wait ()
    (when (SD_SoundPlaying)
      (BJ_Breathe)
      (VL_WaitVBL 1)
      (wait))))

(define (breathe-ack)
  (IN_StartAck)
  (let wait ()
    (unless (IN_CheckAck)
      (BJ_Breathe)
      (when (IN_Yield)
        (wait)))))

;; WL_INTER.C:656-676
(define (count-up-bonus timeleft)
  (let loop ((count 0))
    (if (> count timeleft)
        #f
        (let ((text (number->string (* count PAR_AMOUNT))))
          (Write (- 36 (* (string-length text) 2)) 7 text)
          (when (= 0 (remainder count (truncate (/ PAR_AMOUNT 10))))
            (SD_PlaySound ENDBONUS1SND))
          (bonus-sound-wait)
          (if (IN_CheckAck)
              #t
              (loop (+ count 1)))))))

;; WL_INTER.C:692-706, the same loop for the kill, secret, and treasure ratios
(define (count-up-ratio ratio y)
  (let loop ((count 0))
    (if (> count ratio)
        #f
        (begin
          (right-write (number->string count) y)
          (when (= 0 (remainder count 10))
            (SD_PlaySound ENDBONUS1SND))
          (bonus-sound-wait)
          (if (IN_CheckAck)
              #t
              (loop (+ count 1)))))))

;; WL_INTER.C:708-726. The 100% row pays PERCENT100AMT and repaints the bonus before its sound.
(define (ratio-sound ratio paid)
  (cond ((= ratio 100)
         (VL_WaitVBL 30)
         (SD_StopSound)
         (let ((text (number->string paid)))
           (Write (- (- RATIOXX 1) (* (string-length text) 2)) 7 text))
         (VL_WaitVBL 1)
         (SD_PlaySound PERCENT100SND))
        ((= ratio 0) (SD_PlaySound NOBONUSSND))
        (else (SD_PlaySound ENDBONUS2SND)))
  (bonus-sound-wait)
  #f)

;; WL_INTER.C:557-895
(define (LevelCompleted)
  (CacheLump LEVELEND_LUMP_START LEVELEND_LUMP_END)
  (StartCPMusic 16)
  (IN_ClearKeysDown)
  (IN_StartAck)
  (ClearSplitVWB)
  (VWB_Bar 0 0 320 (- 200 STATUSLINES) 127)
  (VWB_DrawPic 0 16 L_GUYPIC)
  (let ((result (if (< mapon 8)
      (let* ((par (par-time))
             (elapsed (min (truncate (/ TimeCount 70)) (* 99 60)))
             (timeleft (if (< TimeCount (* par 4200))
                           (- (truncate (/ (* par 4200) 70)) elapsed)
                           0))
             (minutes (truncate (/ elapsed 60)))
             (seconds (- elapsed (* 60 (truncate (/ elapsed 60)))))
             (kr (ratio-of killcount killtotal))
             (sr (ratio-of secretcount secrettotal))
             (tr (ratio-of treasurecount treasuretotal))
             (bonus (+ (* timeleft PAR_AMOUNT)
                       (if (= kr 100) PERCENT100AMT 0)
                       (if (= sr 100) PERCENT100AMT 0)
                       (if (= tr 100) PERCENT100AMT 0))))
        (Write 14 2 "floor\ncompleted")
        (Write 14 7 "bonus     0")
        (Write 16 10 "time")
        (Write 16 12 " par")
        (Write 9 14 "kill ratio    %")
        (Write 5 16 "secret ratio    %")
        (Write 1 18 "treasure ratio    %")
        (Write 26 2 (number->string (+ mapon 1)))
        (Write 26 12 (par-string par))
        (draw-clock (* 26 8) (* 10 8) minutes seconds)
        (VW_UpdateScreen)
        (VL_FadeIn 0 255 gamepal 30)
        (or (and (> timeleft 0)
                 (or (count-up-bonus timeleft)
                     (begin (SD_PlaySound ENDBONUS2SND) (bonus-sound-wait) #f)))
            (count-up-ratio kr 14)
            (ratio-sound kr (+ (* timeleft PAR_AMOUNT)
                               (if (= kr 100) PERCENT100AMT 0)))
            (count-up-ratio sr 16)
            (ratio-sound sr (+ (* timeleft PAR_AMOUNT)
                               (if (= kr 100) PERCENT100AMT 0)
                               (if (= sr 100) PERCENT100AMT 0)))
            (count-up-ratio tr 18)
            (ratio-sound tr bonus))
        (right-write (number->string kr) 14)
        (right-write (number->string sr) 16)
        (right-write (number->string tr) 18)
        (GivePoints bonus)
        (let ((text (number->string bonus)))
          (Write (- 36 (* (string-length text) 2)) 7 text))
        (setf! LevelRatios-kill mapon kr)
        (setf! LevelRatios-secret mapon sr)
        (setf! LevelRatios-treasure mapon tr)
        (setf! LevelRatios-time mapon (+ (* minutes 60) seconds))
        (DrawScore)
        (set! TimeCount 0)
        (breathe-ack)
        (list bonus kr sr tr))
      (begin
        (Write 14 4 "secret floor\n completed!")
        (Write 10 16 "15000 bonus!")
        (VW_UpdateScreen)
        (VL_FadeIn 0 255 gamepal 30)
        (GivePoints 15000)
        (DrawScore)
        (set! TimeCount 0)
        (breathe-ack)
        (list 15000 0 0 0)))))
    (VL_FadeOut 0 255 0 0 0 30)
    (DrawPlayBorder)
    (UnCacheLump LEVELEND_LUMP_START LEVELEND_LUMP_END)
    result))

(define (PreloadUpdate current total)
  (let ((width (- WindowW 10))
        (x (+ WindowX 5))
        (y (+ WindowY WindowH -3)))
    (VWB_Bar x y width 2 0)
    (let ((filled (truncate (/ (* width current) total))))
      (when (> filled 0)
        (VWB_Bar x y filled 2 #x37)
        (VWB_Bar x y (- filled 1) 1 #x32)))
    (VW_UpdateScreen)
    #f))

(define (PreloadGraphics)
  (DrawLevel)
  (ClearSplitVWB)
  (VWB_Bar 0 0 320 (- 200 STATUSLINES) 127)
  (LatchDrawPic 6 56 GETPSYCHEDPIC)
  (set! WindowX 48)
  (set! WindowY 56)
  (set! WindowW 224)
  (set! WindowH 48)
  (VW_UpdateScreen)
  (VL_FadeIn 0 255 gamepal 30)
  (PM_Preload PreloadUpdate)
  (IN_UserInput 70)
  (VL_FadeOut 0 255 0 0 0 30)
  (DrawPlayBorder)
  (VW_UpdateScreen))

;; WL_INTER.C:1030-1176, the WL6 build
(define (DrawHighScores)
  (MM_SortMem)
  (ClearMScreen)
  (DrawStripes 10)
  (VWB_DrawPic 48 0 HIGHSCORESPIC)
  (VWB_DrawPic (* 4 8) 68 C_NAMEPIC)
  (VWB_DrawPic (* 20 8) 68 C_LEVELPIC)
  (VWB_DrawPic (* 28 8) 68 C_SCOREPIC)
  (set! fontnumber 0)
  (set! fontcolor 15)
  (set! backcolor BORDCOLOR)
  (let loop ((entry 0))
    (when (< entry MaxScores)
      (set! PrintY (+ 76 (* 16 entry)))
      (set! PrintX (* 4 8))
      (US_Print (ref score-name entry))

      (let ((level (fixed-codes (number->string (ref score-completed entry)))))
        (set! PrintX (- (* 22 8) (US_MeasureCodes level) 6))
        (US_Print "E")
        (US_Print (number->string (+ (ref score-episode entry) 1)))
        (US_Print "/L")
        (US_PrintCodes level))

      (let ((points (fixed-codes (number->string (ref score-points entry)))))
        (set! PrintX (- (* 34 8) 8 (US_MeasureCodes points)))
        (US_PrintCodes points))
      (loop (+ entry 1))))
  (VW_UpdateScreen))

(define (CheckHighScore points completed)
  (let ((slot (let scan ((entry 0) (found -1))
                (if (= entry MaxScores)
                    found
                    (scan (+ entry 1)
                          (if (and (< found 0)
                                   (or (> points (ref score-points entry))
                                       (and (= points (ref score-points entry))
                                            (> completed (ref score-completed entry)))))
                              entry
                              found))))))
    (when (>= slot 0)
      (let shift ((entry (- MaxScores 1)))
        (when (> entry slot)
          (setf! score-name entry (ref score-name (- entry 1)))
          (setf! score-points entry (ref score-points (- entry 1)))
          (setf! score-completed entry (ref score-completed (- entry 1)))
          (setf! score-episode entry (ref score-episode (- entry 1)))
          (shift (- entry 1))))
      (setf! score-name slot "")
      (setf! score-points slot points)
      (setf! score-completed slot completed)
      (setf! score-episode slot episode))

    (StartCPMusic 23)
    (DrawHighScores)
    (VL_FadeIn 0 255 gamepal 30)
    (if (>= slot 0)
        (begin
          (set! PrintY (+ 76 (* 16 slot)))
          (set! PrintX (* 4 8))
          (set! backcolor BORDCOLOR)
          (set! fontcolor 15)
          (let ((name (US_LineInput PrintX PrintY "" #t MaxHighName 100)))
            (when name
              (setf! score-name slot name))))
        (begin
          (IN_ClearKeysDown)
          (IN_UserInput 500)))
    #f))

(define (NonShareware)
  (VL_FadeOut 0 255 0 0 0 30)
  (ClearMScreen)
  (DrawStripes 10)
  (CA_CacheGrChunk (+ STARTFONT 1))
  (set! fontnumber 1)
  (set! fontcolor READHCOLOR)
  (set! backcolor BKGDCOLOR)
  (set! PrintX 110)
  (set! PrintY 15)
  (US_Print "Attention")
  (set! fontcolor HIGHLIGHT)
  (set! WindowX 40)
  (set! PrintX 40)
  (set! PrintY 60)
  (US_Print "This game is NOT shareware.\n")
  (US_Print "Please do not distribute it.\n")
  (US_Print "Thanks.\n\n")
  (US_Print "        Id Software\n")
  (VW_UpdateScreen)
  (VL_FadeIn 0 255 gamepal 30)
  (IN_Ack))

;; WL_INTER.C:310-323
(define (PG13)
  (VWB_Bar 0 0 320 200 130)
  (CA_CacheGrChunk PG13PIC)
  (VWB_DrawPic 216 110 PG13PIC)
  (VW_UpdateScreen)
  (VL_FadeIn 0 255 gamepal 30)
  (IN_UserInput (* TickBase 7))
  (VL_FadeOut 0 255 0 0 0 30))

;; WL_INTER.C:104-290, less the fade and the time-verification code.
(define (Victory)
  (StartCPMusic 24)
  (ClearSplitVWB)
  (VWB_Bar 0 0 320 200 127)
  (Write 18 2 "you win!")
  (Write TIMEX (- TIMEY 2) "total time")
  (Write 12 (- RATIOY 2) "averages")
  (Write (+ RATIOX 8) RATIOY "kill    %")
  (Write (+ RATIOX 4) (+ RATIOY 2) "secret    %")
  (Write RATIOX (+ RATIOY 4) "treasure    %")
  (VWB_DrawPic 8 4 L_BJWINSPIC)
  (let sum ((level 0) (seconds 0) (kills 0) (secrets 0) (treasure 0))
    (if (< level 8)
        (sum (+ level 1)
             (+ seconds (ref LevelRatios-time level))
             (+ kills (ref LevelRatios-kill level))
             (+ secrets (ref LevelRatios-secret level))
             (+ treasure (ref LevelRatios-treasure level)))
        (let* ((kr (truncate (/ kills 8)))
               (sr (truncate (/ secrets 8)))
               (tr (truncate (/ treasure 8)))
               ;; WL_INTER.C:331, min and sec both become 99 on overflow
               (over (> (truncate (/ seconds 60)) 99))
               (minutes (if over 99 (truncate (/ seconds 60))))
               (rest (if over 99 (- seconds (* 60 (truncate (/ seconds 60)))))))
          (draw-clock (+ (* TIMEX 8) 1) (* TIMEY 8) minutes rest)
          (Write (- (+ RATIOX 24) (* (string-length (number->string kr)) 2))
                 RATIOY (number->string kr))
          (Write (- (+ RATIOX 24) (* (string-length (number->string sr)) 2))
                 (+ RATIOY 2) (number->string sr))
          (Write (- (+ RATIOX 24) (* (string-length (number->string tr)) 2))
                 (+ RATIOY 4) (number->string tr))
          (when (>= difficulty gd_medium)
            (VWB_DrawPic (* 30 8) (* TIMEY 8) C_TIMECODEPIC)
            (set! fontnumber 0)
            (set! fontcolor READHCOLOR)
            (set! PrintX (+ (* 30 8) 1))
            (set! PrintY (+ (* TIMEY 8) 8))
            (let* ((minutes-tens (quotient minutes 10))
                   (minutes-ones (remainder minutes 10))
                   (seconds-tens (quotient rest 10))
                   (seconds-ones (remainder rest 10))
                   (first (+ (bitwise-xor (bitwise-xor minutes-tens minutes-ones) 10) 65))
                   (second (+ (bitwise-xor (bitwise-xor seconds-tens seconds-ones) 10) 65)))
              (US_Print (string-append (string (integer->char first))
                                       (string (integer->char second))
                                       (string (integer->char (+ (bitwise-xor first second) 65))))))
            (set! fontnumber 1))
          (VL_WaitVBL 1)
          (VL_FadeIn 0 255 gamepal 30)
          (IN_Ack)
          (VL_FadeOut 0 255 0 0 0 30)
          (EndText)
          (list kr sr tr)))))
