;;; WL_MENU.C — the control panel

;; WL_MENU.H:20,32
(define (MenuFadeOut)
  (VL_FadeOut 0 255 43 0 0 10))

(define (MenuFadeIn)
  (VL_FadeIn 0 255 gamepal 10))

(define (ShootSnd)
  (SD_PlaySound SHOOTSND))

(define (StartCPMusic song)
  (SD_MusicOff))

(define (FreeMusic)
  #f)

;; WL_MENU.H:16-30
(define BORDCOLOR 41)
(define BORD2COLOR 35)
(define BKGDCOLOR 45)
(define STRIPE 44)
(define DEACTIVE 43)
(define TEXTCOLOR 23)
(define HIGHLIGHT 19)
(define READCOLOR 74)
(define READHCOLOR 71)

;; WL_MENU.C:290. True once a level is running, which renames the last main menu row.
(define ingame #f)

;; WL_MENU.H:45-82
(define MENU_X 76)
(define MENU_Y 55)
(define MENU_W 178)
(define MENU_H 136)
(define SM_X 48)
(define SM_Y1 20)
(define SM_H1 45)
(define SM_Y2 85)
(define SM_H2 45)
(define SM_Y3 150)
(define SM_H3 32)
(define SM_W 250)
(define LSM_X 85)
(define LSM_Y 55)
(define LSM_W 175)
(define LSM_H 140)
(define LSA_X 96)
(define LSA_Y 80)
(define LSA_W 130)
(define LSA_H 42)
(define NM_X 50)
(define NM_Y 100)
(define NM_W 225)
(define NM_H 67)
(define NE_X 10)
(define NE_Y 23)
(define NE_W 300)
(define NE_H 154)
(define MENUSTEP 13)

;; WL_MENU.C:2969-2976
(define (ClearMScreen)
  (VWB_Bar 0 0 320 200 BORDCOLOR))

;; WL_MENU.C:3860-3869
(define (DrawStripes y)
  (VWB_Bar 0 y 320 24 0)
  (VWB_Hlin 0 319 (+ y 22) STRIPE))

;; WL_MENU.C:2984
;; WL_MENU.C:2882. The graphical port has no EMS/XMS allocator; show the
;; managed main-memory capacity and available input/audio devices.
(define (IntroScreen)
  (let ((memory (truncate (/ (+ 1023 (ref mminfo 'nearheap) (ref mminfo 'farheap)) 1024))))
    (let bars ((level 1))
      (when (<= level 10)
        (when (>= memory (* level 32))
          (VWB_Bar 49 (- 163 (* 8 (- level 1))) 6 5 (- #x6c (- level 1))))
        (bars (+ level 1)))))
  (when MousePresent (VWB_Bar 164 82 12 2 14))
  (when (or (ref JoysPresent 0) (ref JoysPresent 1)) (VWB_Bar 164 105 12 2 14))
  (when (and AdLibPresent (not SoundBlasterPresent)) (VWB_Bar 164 128 12 2 14))
  (when SoundBlasterPresent (VWB_Bar 164 151 12 2 14))
  (when SoundSourcePresent (VWB_Bar 164 174 12 2 14)))

(define (CacheLump lumpstart lumpend)
  (let loop ((chunk lumpstart))
    (when (<= chunk lumpend)
      (CA_CacheGrChunk chunk)
      (loop (+ chunk 1)))))

;; WL_MENU.C:2993
(define (UnCacheLump lumpstart lumpend)
  (let loop ((chunk lumpstart))
    (when (<= chunk lumpend)
      (unless (number? (ref grsegs chunk))
        (setf! grsegs chunk 0))
      (loop (+ chunk 1)))))

;; WL_MENU.C:3015-3021
(define (DrawOutline x y w h color1 color2)
  (VWB_Hlin x (+ x w) y color2)
  (VWB_Vlin y (+ y h) x color2)
  (VWB_Hlin x (+ x w) (+ y h) color1)
  (VWB_Vlin y (+ y h) (+ x w) color1))

;; WL_MENU.C:3008-3012
(define (DrawWindow x y w h color)
  (VWB_Bar x y w h color)
  (DrawOutline x y w h BORD2COLOR DEACTIVE))

;; WL_MENU.H:93-97. The five fields of CP_iteminfo.
(define (iteminfo x y amount curpos indent) (vector x y amount curpos indent))
(define (item-x items) (ref items 0))
(define (item-y items) (ref items 1))
(define (item-amount items) (ref items 2))
(define (item-curpos items) (ref items 3))
(define (item-indent items) (ref items 4))

;; WL_MENU.C:57-62
(define MainItems (iteminfo MENU_X MENU_Y 10 6 24))
(define SndItems (iteminfo SM_X SM_Y1 12 0 52))
(define LSItems (iteminfo LSM_X LSM_Y 10 0 24))
(define NewEitems (iteminfo NE_X NE_Y 11 0 88))
(define NewItems (iteminfo NM_X NM_Y 4 2 24))
(define CtlItems (iteminfo 24 70 6 0 56))

;; WL_MENU.C:63-96. Control stays inactive while joystick input is excluded.
(define main-active (vector 1 1 1 1 1 1 2 1 1 1))
(define main-text
  (vector "New Game" "Sound" "Control" "Load Game" "Save Game" "Change View"
          "Read This!" "View Scores" "Back to Demo" "Quit"))
(define main-routine
  (vector 'newgame 'sound 'control 'loadgame 'savegame 'changeview 'readthis 'viewscores 'back 'quit))

;; WL_MENU.C:103-132
(define sound-active (vector 1 1 1 0 0 1 0 1 0 0 1 1))
(define sound-text
  (vector "None" "PC Speaker" "AdLib/Sound Blaster" "" ""
          "None" "Disney Sound Source" "Sound Blaster" "" ""
          "None" "AdLib/Sound Blaster"))

;; WL_MENU.C:229-241
(define control-active (vector 1 0 0 0 1 1))
(define control-text
  (vector "Mouse Enabled" "" "" "" "Mouse Sensitivity" "Customize controls"))

(define CusItems (iteminfo 8 74 9 -1 0))
(define custom-active (vector 1 0 0 0 0 0 1 0 1))
(define custom-text (vector "" "" "" "" "" "" "" "" ""))

(define difficulty-active (vector 1 1 1 1))
(define difficulty-text
  (vector "Can I play, Daddy?" "Don't hurt me." "Bring 'em on!" "I am Death incarnate!"))

;; WL_MENU.C:156-227, one row per episode
(define episode-active (vector 1 0 3 0 3 0 3 0 3 0 3))
;; WL_MENU.C:3882. This port ships the six-episode WL6 data set, whose
;; extension and active episode rows are the startup defaults above.
(define (CheckForEpisodes)
  (set! extension "WL6")
  episode-active)

(define episode-text
  (vector "Episode 1\nEscape from Wolfenstein" ""
          "Episode 2\nOperation: Eisenfaust" ""
          "Episode 3\nDie, Fuhrer, Die!" ""
          "Episode 4\nA Dark Secret" ""
          "Episode 5\nTrail of the Madman" ""
          "Episode 6\nConfrontation"))

(define CORNER_MUS 0)
(define MENUSONG 14)
(define ROSTER_MUS 23)

(define StartGame #f)
(define startgame #f)
(define loadedgame #f)
(define pickquick #f)
(define quick-slot 0)
(define SaveGameNames (make-vector 10 ""))

;; WL_MENU.C:273-285
(define color_hlite (vector DEACTIVE HIGHLIGHT READHCOLOR 103))
(define color_norml (vector DEACTIVE TEXTCOLOR READCOLOR 107))

;; WL_MENU.C:3457-3463
(define (SetTextColor active hlight)
  (set! fontcolor (if hlight (ref color_hlite active) (ref color_norml active)))
  (set! backcolor BKGDCOLOR))

;; WL_MENU.C:3489
(define (ReadAnyControl)
  (IN_ReadControl 0)
  (when mouseenabled
    (let ((delta (INL_GetMouseDelta)))
      (let ((mousex (ref delta 0)) (mousey (ref delta 1)))
        (cond ((< mousey -60) (set! in-dir dir_North))
              ((> mousey 60) (set! in-dir dir_South)))
        (cond ((< mousex -60) (set! in-dir dir_West))
              ((> mousex 60) (set! in-dir dir_East)))))
    (let ((buttons (INL_GetMouseButtons)))
      (when (not (= buttons 0))
        (set! in-button0 (not (= 0 (bitwise-and buttons 1))))
        (set! in-button1 (not (= 0 (bitwise-and buttons 2))))
        (set! in-button2 (not (= 0 (bitwise-and buttons 4))))
        (set! in-button3 #f))))
  (vector in-x in-y in-xaxis in-yaxis in-button0 in-button1 in-button2 in-button3 in-dir))

(define (WaitKeyUp)
  (let wait ()
    (ReadAnyControl)
    (when (or in-button0 in-button1 in-button2 in-button3
              (ref Keyboard sc_Space) (ref Keyboard sc_Enter) (ref Keyboard sc_Escape))
      (when (IN_Yield)
        (wait)))))

(define SoundStatus 0)

;; WL_MENU.C:3821
(define (CheckPause)
  (when Paused
    (if (= SoundStatus 0) (SD_MusicOn) (SD_MusicOff))
    (set! SoundStatus (bitwise-xor SoundStatus 1))
    (VL_WaitVBL 3)
    (IN_ClearKeysDown)
    (set! Paused #f)))

(define (TicDelay count)
  (set! TimeCount 0)
  (let delay ()
    (IN_ReadControl 0)
    (when (and (< TimeCount count) (not (= in-dir dir_None)))
      (when (IN_Yield)
        (delay)))))

;; WL_MENU.C:3423-3448
(define (DrawMenu items active text)
  (set! WindowX (+ (item-x items) (item-indent items)))
  (set! WindowY (item-y items))
  (set! WindowW 320)
  (set! WindowH 200)
  (let loop ((item 0))
    (when (< item (item-amount items))
      (SetTextColor (ref active item) (= item (item-curpos items)))
      (set! PrintX WindowX)
      (set! PrintY (+ (item-y items) (* item MENUSTEP)))
      (US_Print (ref text item))
      (loop (+ item 1))))
  (SetTextColor 1 #f))

;; WL_MENU.C:3352-3362
(define (EraseGun items active text x y which)
  (VWB_Bar (- x 1) y 25 16 BKGDCOLOR)
  (SetTextColor (ref active which) #f)
  (set! PrintX (+ (item-x items) (item-indent items)))
  (set! PrintY (+ (item-y items) (* which MENUSTEP)))
  (US_Print (ref text which))
  (VW_UpdateScreen))

(define (DrawHalfStep x y)
  (VWB_DrawPic x y C_CURSOR1PIC)
  (VW_UpdateScreen)
  (SD_PlaySound MOVEGUN1SND)
  (set! TimeCount 0)
  (let wait ()
    (when (< TimeCount 8)
      (when (IN_Yield)
        (wait)))))

;; WL_MENU.C:3381-3405
(define (DrawGun items active text x y which basey routine)
  (VWB_Bar (- x 1) y 25 16 BKGDCOLOR)
  (let ((next-y (+ basey (* which MENUSTEP))))
    (VWB_DrawPic x next-y C_CURSOR1PIC)
    (SetTextColor (ref active which) #t)
    (set! PrintX (+ (item-x items) (item-indent items)))
    (set! PrintY (+ (item-y items) (* which MENUSTEP)))
    (US_Print (ref text which))
    (when routine
      (routine which))
    (VW_UpdateScreen)
    (SD_PlaySound MOVEGUN2SND)))

;; WL_MENU.C:3844
(define (DrawMenuGun items)
  (VWB_DrawPic (item-x items)
               (+ (item-y items) (* (item-curpos items) MENUSTEP) -2)
               C_CURSOR1PIC))

;; WL_MENU.C:3223-3272, the skip over inactive rows
(define (menu-step items active step)
  (let loop ((next (+ (item-curpos items) step)))
    (let ((wrapped (cond ((< next 0) (- (item-amount items) 1))
                         ((>= next (item-amount items)) 0)
                         (else next))))
      (if (= (ref active wrapped) 0)
          (loop (+ wrapped step))
          (setf! items 3 wrapped)))))

;; WL_MENU.C:3170-3211. Two scans, after the cursor then before it; the cursor row is never tested.
(define (menu-matches? active text entry code)
  (and (not (= 0 (ref active entry)))
       (> (string-length (ref text entry)) 0)
       (char=? (char-downcase (string-ref (ref text entry) 0))
               (char-downcase (integer->char code)))))

(define (menu-letter items active text code)
  (let ((which (item-curpos items)))
    (let after ((entry (+ which 1)))
      (cond ((< entry (item-amount items))
             (if (menu-matches? active text entry code)
                 (setf! items 3 entry)
                 (after (+ entry 1))))
            (else
             (let before ((entry 0))
               (when (< entry which)
                 (if (menu-matches? active text entry code)
                     (setf! items 3 entry)
                     (before (+ entry 1))))))))))

;; WL_MENU.C:3300-3342
(define (finish-menu items active text x y which result)
  (IN_ClearKeysDown)
  (VWB_Bar (- x 1) y 25 16 BKGDCOLOR)
  (SetTextColor (ref active which) #f)
  (set! PrintX (+ (item-x items) (item-indent items)))
  (set! PrintY (+ (item-y items) (* which MENUSTEP)))
  (US_Print (ref text which))
  (VW_UpdateScreen)
  (setf! items 3 which)
  result)

;; WL_MENU.C:3106-3351
(define (HandleMenu items active text routine)
  (let ((x (- (item-x items) (remainder (item-x items) 8)))
        (basey (- (item-y items) 2)))
    (DrawMenu items active text)
    (VWB_DrawPic x (+ basey (* (item-curpos items) MENUSTEP)) C_CURSOR1PIC)
    (SetTextColor (ref active (item-curpos items)) #t)
    (set! PrintX (+ (item-x items) (item-indent items)))
    (set! PrintY (+ (item-y items) (* (item-curpos items) MENUSTEP)))
    (US_Print (ref text (item-curpos items)))
    (when routine
      (routine (item-curpos items)))
    (VW_UpdateScreen)
    (IN_ClearKeysDown)
    (set! TimeCount 0)
    (let frame ((shape C_CURSOR1PIC) (timer 8) (last TimeCount))
      (let ((y (+ basey (* (item-curpos items) MENUSTEP))))
        (if (not (IN_Yield))
            -1
            (let* ((ignored (ReadAnyControl))
                   (scan LastScan)
                   (code LastASCII)
                  (which (item-curpos items)))
              (set! LastScan sc_None)
              (set! LastASCII key_None)
              (cond
                ((or (= in-dir dir_North) (= in-dir dir_South))
                 (EraseGun items active text x y which)
                 (let ((step (if (= in-dir dir_North) -1 1)))
                   (let ((neighbor (+ which step)))
                     (when (and (>= neighbor 0) (< neighbor (item-amount items))
                                (not (= 0 (ref active neighbor))))
                       (DrawHalfStep x (+ y (* step 6)))))
                   (menu-step items active step))
                 (DrawGun items active text x y (item-curpos items) basey routine)
                 (TicDelay 20)
                 (frame C_CURSOR1PIC 8 TimeCount))
                ((or (= scan sc_Return) (= scan sc_Space) in-button0)
                 (SD_PlaySound SHOOTSND)
                 (finish-menu items active text x y which which))
                ((or (= scan sc_Escape) in-button1)
                 (SD_PlaySound ESCPRESSEDSND)
                 (finish-menu items active text x y which -1))
                ((> code 0)
                 (EraseGun items active text x y which)
                 (menu-letter items active text code)
                 (DrawGun items active text x y (item-curpos items) basey routine)
                 (frame C_CURSOR1PIC 8 TimeCount))
                ((> (- TimeCount last) timer)
                 (let ((next (if (= shape C_CURSOR1PIC) C_CURSOR2PIC C_CURSOR1PIC)))
                   (VWB_DrawPic x (+ basey (* which MENUSTEP)) next)
                   (when routine
                     (routine which))
                   (frame next (if (= next C_CURSOR2PIC) 8 70) TimeCount)))
                (else (frame shape timer last)))))))))

(define (Message text)
  (CA_CacheGrChunk (+ STARTFONT 1))
  (set! fontnumber 1)
  (let ((font (VH_Font)))
    (let measure ((index 0) (height (font-height font)) (width 0) (max-width 0))
      (if (= index (string-length text))
          (let ((max-width (max max-width (+ width 10))))
            (set! PrintY (- (quotient WindowH 2) (quotient height 2)))
            (set! PrintX (- 160 (quotient max-width 2)))
            (set! WindowX PrintX)
            (DrawWindow (- WindowX 5) (- PrintY 5) (+ max-width 10) (+ height 10) TEXTCOLOR)
            (DrawOutline (- WindowX 5) (- PrintY 5) (+ max-width 10) (+ height 10) 0 HIGHLIGHT)
            (set! fontcolor 0)
            (set! backcolor TEXTCOLOR)
            (US_Print text)
            (VW_UpdateScreen))
          (let ((character (string-ref text index)))
            (if (char=? character #\newline)
                (measure (+ index 1) (+ height (font-height font)) 0 (max max-width width))
                (measure (+ index 1) height (+ width (font-width font (char->integer character)))
                         max-width)))))))

(define (Confirm text)
  (Message text)
  (IN_ClearKeysDown)
  (let ((x PrintX) (y PrintY))
    (set! TimeCount 0)
    (let frame ((tick 0))
      (if (not (IN_Yield))
          #f
          (let ((next-tick tick))
            (when (>= TimeCount 10)
              (if (= tick 0)
                  (VWB_Bar x y 8 13 TEXTCOLOR)
                  (begin (set! PrintX x) (set! PrintY y) (US_Print "_")))
              (VW_UpdateScreen)
              (set! next-tick (bitwise-xor tick 1))
              (set! TimeCount 0))
            (when (and (ref Keyboard sc_Tab) (ref Keyboard sc_P) (MS_CheckParm "goobers"))
              (PicturePause))
            (let ((scan LastScan))
              (set! LastScan sc_None)
              (cond ((or (= scan sc_Y) (ref Keyboard sc_Y))
                     (ShootSnd)
                     (WaitKeyUp)
                     (IN_ClearKeysDown)
                     (SD_PlaySound SHOOTSND)
                     #t)
                    ((or (= scan sc_N) (= scan sc_Escape) (ref Keyboard sc_N)
                         (ref Keyboard sc_Escape))
                     (WaitKeyUp)
                     (IN_ClearKeysDown)
                     (SD_PlaySound ESCPRESSEDSND)
                     #f)
                    (else (frame next-tick)))))))))

(define (GetYorN x y pic)
  (CA_CacheGrChunk pic)
  (VWB_DrawPic (* x 8) (* y 8) pic)
  (UnCacheLump pic pic)
  (VW_UpdateScreen)
  (IN_ClearKeysDown)
  (let wait ()
    (if (not (IN_Yield))
        #f
        (begin
          (when (and (ref Keyboard sc_Tab) (ref Keyboard sc_P) (MS_CheckParm "goobers"))
            (PicturePause))
          (let ((scan LastScan))
            (set! LastScan sc_None)
            (cond ((or (= scan sc_Y) (ref Keyboard sc_Y))
                   (ShootSnd)
                   (WaitKeyUp)
                   (IN_ClearKeysDown)
                   (SD_PlaySound SHOOTSND)
                   #t)
                  ((or (= scan sc_N) (= scan sc_Escape) (ref Keyboard sc_N)
                       (ref Keyboard sc_Escape))
                   (WaitKeyUp)
                   (IN_ClearKeysDown)
                   (SD_PlaySound ESCPRESSEDSND)
                   #f)
                  (else (wait))))))))

(define (DrawSoundMenu)
  (ClearMScreen)
  (VWB_DrawPic 112 184 C_MOUSELBACKPIC)
  (DrawWindow (- SM_X 8) (- SM_Y1 3) SM_W SM_H1 BKGDCOLOR)
  (DrawWindow (- SM_X 8) (- SM_Y2 3) SM_W SM_H2 BKGDCOLOR)
  (DrawWindow (- SM_X 8) (- SM_Y3 3) SM_W SM_H3 BKGDCOLOR)
  (DrawMenu SndItems sound-active sound-text)
  (VWB_DrawPic 100 (- SM_Y1 20) C_FXTITLEPIC)
  (VWB_DrawPic 100 (- SM_Y2 20) C_DIGITITLEPIC)
  (VWB_DrawPic 100 (- SM_Y3 20) C_MUSICTITLEPIC)
  (let loop ((item 0))
    (when (< item (item-amount SndItems))
      (when (> (string-length (ref sound-text item)) 0)
        (let ((selected
               (cond ((= item 0) (= SoundMode sdm_Off))
                     ((= item 1) (= SoundMode sdm_PC))
                     ((= item 2) (= SoundMode sdm_AdLib))
                     ((= item 5) (= DigiMode sds_Off))
                     ((= item 7) (= DigiMode sds_SoundBlaster))
                     ((= item 10) (= MusicMode smm_Off))
                     ((= item 11) (= MusicMode smm_AdLib))
                     (else #f))))
          (VWB_DrawPic (+ SM_X 24) (+ SM_Y1 (* item MENUSTEP) 2)
                       (if selected C_SELECTEDPIC C_NOTSELECTEDPIC))))
      (loop (+ item 1))))
  (VW_UpdateScreen)
  (MenuFadeIn))

;; WL_MENU.C:1135-1240, for the two devices this port drives
(define (CP_Sound)
  (DrawSoundMenu)
  (WaitKeyUp)
  (let ((which (HandleMenu SndItems sound-active sound-text #f)))
    (cond ((= which 0) (SD_SetSoundMode sdm_Off) (CP_Sound))
          ((= which 1)
           (if (= SoundMode sdm_PC)
               (CP_Sound)
               (begin
                 (SD_SetSoundMode sdm_PC)
                 (CA_LoadAllSounds)
                 (SD_PlaySound SHOOTSND)
                 (CP_Sound))))
          ((= which 2)
           (SD_SetSoundMode sdm_AdLib)
           (CA_LoadAllSounds)
           (SD_PlaySound SHOOTSND)
           (CP_Sound))
          ((= which 5) (SD_SetDigiDevice sds_Off) (CP_Sound))
          ((= which 7)
           (if (= DigiMode sds_SoundBlaster)
               (CP_Sound)
               (begin
                 (SD_SetDigiDevice sds_SoundBlaster)
                 (SD_PlaySound SHOOTSND)
                 (CP_Sound))))
          ((= which 10) (SD_SetMusicMode smm_Off) (CP_Sound))
          ((= which 11) (SD_SetMusicMode smm_AdLib) (StartCPMusic MENUSONG) (CP_Sound))
          (else (MenuFadeOut) #f))))

;; WL_MENU.C:1761-1829. Joystick and gamepad choices are inactive because the
;; configured input backend exposes neither device.
(define (CP_Control)
  (DrawCtlScreen)
  (WaitKeyUp)
  (let loop ()
    (let ((which (HandleMenu CtlItems control-active control-text #f)))
      (cond ((= which 0)
             (set! mouseenabled (not mouseenabled))
             (DrawCtlScreen)
             (ShootSnd)
             (loop))
            ((= which 4)
             (MouseSensitivity)
             (DrawCtlScreen)
             (WaitKeyUp)
             (loop))
            ((= which 5)
             (CustomControls)
             (DrawCtlScreen)
             (WaitKeyUp)
             (loop))
            (else
             (MenuFadeOut)
             #f)))))

(define (DrawMouseSens)
  (ClearMScreen)
  (VWB_DrawPic 112 184 C_MOUSELBACKPIC)
  (DrawWindow 10 80 300 30 BKGDCOLOR)
  (set! WindowX 0)
  (set! WindowW 320)
  (set! PrintY 82)
  (set! fontcolor READCOLOR)
  (set! backcolor BKGDCOLOR)
  (US_CPrint "Adjust Mouse Sensitivity")
  (set! fontcolor TEXTCOLOR)
  (set! PrintX 14)
  (set! PrintY 95)
  (US_Print "Slow")
  (set! PrintX 269)
  (US_Print "Fast")
  (VWB_Bar 60 97 200 10 TEXTCOLOR)
  (DrawOutline 60 97 200 10 0 HIGHLIGHT)
  (DrawOutline (+ 60 (* 20 mouseadjustment)) 97 20 10 0 READCOLOR)
  (VWB_Bar (+ 61 (* 20 mouseadjustment)) 98 19 9 READHCOLOR)
  (VW_UpdateScreen)
  (MenuFadeIn))

(define (MouseSensitivity)
  (let ((old mouseadjustment))
    (define (redraw value)
      (VWB_Bar 60 97 200 10 TEXTCOLOR)
      (DrawOutline 60 97 200 10 0 HIGHLIGHT)
      (DrawOutline (+ 60 (* 20 value)) 97 20 10 0 READCOLOR)
      (VWB_Bar (+ 61 (* 20 value)) 98 19 9 READHCOLOR)
      (VW_UpdateScreen))
    (DrawMouseSens)
    (let adjust ((value mouseadjustment))
      (set! mouseadjustment value)
      (if (not (IN_Yield))
          #f
          (let ((scan LastScan))
            (set! LastScan sc_None)
            (cond ((or (= scan sc_LeftArrow) (= scan sc_UpArrow))
                   (let ((next (max 0 (- value 1))))
                     (unless (= next value) (redraw next) (SD_PlaySound MOVEGUN1SND))
                     (adjust next)))
                  ((or (= scan sc_RightArrow) (= scan sc_DownArrow))
                   (let ((next (min 9 (+ value 1))))
                     (unless (= next value) (redraw next) (SD_PlaySound MOVEGUN1SND))
                     (adjust next)))
                  ((= scan sc_Return) (SD_PlaySound SHOOTSND) (MenuFadeOut) #t)
                  ((= scan sc_Escape) (set! mouseadjustment old) (SD_PlaySound ESCPRESSEDSND) (MenuFadeOut) #f)
                  (else (adjust value))))))))

(define (DefineMouseBtns)
  (EnterCtrlData 2 (vector 0 1 1 1) DrawCustMouse PrintCustMouse 'mouse))

(define (DefineJoyBtns)
  #f)

(define (DefineKeyBtns)
  (EnterCtrlData 8 (vector 1 1 1 1) DrawCustKeybd PrintCustKeybd 'keyboard-buttons))

(define (DefineKeyMove)
  (EnterCtrlData 10 (vector 1 1 1 1) DrawCustKeys PrintCustKeys 'keyboard-move))

(define (CustomControls)
  (DrawCustomScreen)
  (let loop ()
    (let ((which (HandleMenu CusItems custom-active custom-text FixupCustom)))
      (cond ((= which 0) (DefineMouseBtns) (DrawCustMouse #t) (loop))
            ((= which 6) (DefineKeyBtns) (DrawCustKeybd #f) (loop))
            ((= which 8) (DefineKeyMove) (DrawCustKeys #f) (loop))
            (else (MenuFadeOut))))))

(define (EnterCtrlData index allowed draw print type)
  (let ((print-y (+ 48 (* 13 index))))
    (define (first-allowed action)
    (if (ref allowed action)
        action
        (first-allowed (+ action 1))))
  (define (draw-choice action)
    (let ((x (+ 60 (* 60 action))))
      (DrawWindow 5 (- print-y 1) 310 13 BKGDCOLOR)
      (draw #t)
      (DrawWindow (- x 2) print-y 60 11 TEXTCOLOR)
      (DrawOutline (- x 2) print-y 60 11 0 HIGHLIGHT)
      (set! fontcolor 0)
      (set! backcolor TEXTCOLOR)
      (print action)
      (set! PrintX x)
      (set! fontcolor TEXTCOLOR)
      (set! backcolor BKGDCOLOR)
      (VW_UpdateScreen)
      (WaitKeyUp)))
  (define (store-mouse action)
    (let ((physical (cond (in-button0 0) (in-button1 1) (in-button2 2) (in-button3 3) (else -1))))
      (when (>= physical 0)
        (let ((wanted (ref (vector bt_run bt_use bt_attack bt_strafe) action)))
          (let clear ((slot 0))
            (when (< slot 4)
              (if (= (ref buttonmouse slot) wanted)
                  (setf! buttonmouse slot bt_nobutton)
                  (clear (+ slot 1)))))
          (setf! buttonmouse physical wanted)
          (SD_PlaySound SHOOTDOORSND)
          #t))))
  (define (store-key action)
    (if (= LastScan sc_None)
        #f
        (begin
          (cond ((eq? type 'keyboard-buttons)
                 (setf! buttonscan (ref (vector bt_run bt_use bt_attack bt_strafe) action) LastScan))
                ((eq? type 'keyboard-move)
                 (setf! dirscan (ref (vector 3 1 0 2) action) LastScan)))
          (ShootSnd)
          (IN_ClearKeysDown)
          #t)))
  (define (capture action x)
    (let wait ((tick 0))
      (if (not (IN_Yield))
          #f
          (begin
            (when (> TimeCount 10)
              (if (= tick 0)
                  (VWB_Bar x (+ print-y 1) 58 10 TEXTCOLOR)
                  (begin (set! PrintX x) (US_Print "?") (SD_PlaySound HITWALLSND)))
              (set! TimeCount 0))
            (ReadAnyControl)
            (cond ((IN_KeyDown sc_Escape) #t)
                  ((eq? type 'mouse) (or (store-mouse action) (wait (bitwise-xor tick 1))))
                  (else (or (store-key action) (wait (bitwise-xor tick 1)))))))))
  (define (next-action action step)
    (let ((candidate (modulo (+ action step) 4)))
      (if (ref allowed candidate)
          candidate
          (next-action candidate step))))
    (ShootSnd)
    (IN_ClearKeysDown)
    (let loop ((action (first-allowed 0)) (redraw #t))
      (when redraw
        (draw-choice action))
      (if (not (IN_Yield))
          #f
          (begin
            (ReadAnyControl)
            (cond ((or in-button0 in-button1 in-button2 in-button3
                       (and (not (eq? type 'mouse)) (= LastScan sc_Enter)))
                   (IN_ClearKeysDown)
                   (set! TimeCount 0)
                   (capture action (+ 60 (* 60 action)))
                   (WaitKeyUp)
                   (loop action #t))
                  ((or in-button1 (IN_KeyDown sc_Escape))
                   (SD_PlaySound ESCPRESSEDSND)
                   (WaitKeyUp)
                   (DrawWindow 5 (- print-y 1) 310 13 BKGDCOLOR))
                  ((= in-dir dir_West)
                   (SD_PlaySound MOVEGUN1SND)
                   (IN_ClearKeysDown)
                   (loop (next-action action -1) #t))
                  ((= in-dir dir_East)
                   (SD_PlaySound MOVEGUN1SND)
                   (IN_ClearKeysDown)
                   (loop (next-action action 1) #t))
                  ((or (= in-dir dir_North) (= in-dir dir_South))
                   (SD_PlaySound ESCPRESSEDSND)
                   (WaitKeyUp)
                   (DrawWindow 5 (- print-y 1) 310 13 BKGDCOLOR))
                  (else (loop action #f))))))))

(define custom-last -1)
(define (FixupCustom which)
  (define (draw-lines row)
    (let ((y (+ 74 (* row 13))))
      (VWB_Hlin 7 32 (- y 1) DEACTIVE)
      (VWB_Hlin 7 32 (+ y 12) BORD2COLOR)
      (VWB_Hlin 7 32 (- y 2) BORDCOLOR)
      (VWB_Hlin 7 32 (+ y 13) BORDCOLOR)))
  (draw-lines which)
  (cond ((= which 0) (DrawCustMouse #t))
        ((= which 3) (DrawCustJoy #t))
        ((= which 6) (DrawCustKeybd #t))
        ((= which 8) (DrawCustKeys #t)))
  (when (>= custom-last 0)
    (draw-lines custom-last)
    (when (not (= custom-last which))
      (cond ((= custom-last 0) (DrawCustMouse #f))
            ((= custom-last 3) (DrawCustJoy #f))
            ((= custom-last 6) (DrawCustKeybd #f))
            ((= custom-last 8) (DrawCustKeys #f)))))
  (set! custom-last which))

(define (DrawCustomScreen)
  (ClearMScreen)
  (set! WindowX 0)
  (set! WindowW 320)
  (VWB_DrawPic 112 184 C_MOUSELBACKPIC)
  (DrawStripes 10)
  (VWB_DrawPic 80 0 C_CUSTOMIZEPIC)

  (set! fontcolor READCOLOR)
  (set! backcolor BKGDCOLOR)
  (set! PrintY 48)
  (US_CPrint "Mouse\n")
  (set! fontcolor TEXTCOLOR)
  (set! PrintX 60)
  (US_Print "Run")
  (set! PrintX 120)
  (US_Print "Open")
  (set! PrintX 180)
  (US_Print "Fire")
  (set! PrintX 240)
  (US_Print "Strafe\n")
  (DrawWindow 5 (- PrintY 1) 310 13 BKGDCOLOR)
  (DrawCustMouse #f)
  (US_Print "\n")

  (set! fontcolor READCOLOR)
  (US_CPrint "Joystick/Gravis GamePad\n")
  (set! fontcolor TEXTCOLOR)
  (set! PrintX 60)
  (US_Print "Run")
  (set! PrintX 120)
  (US_Print "Open")
  (set! PrintX 180)
  (US_Print "Fire")
  (set! PrintX 240)
  (US_Print "Strafe\n")
  (DrawWindow 5 (- PrintY 1) 310 13 BKGDCOLOR)
  (DrawCustJoy #f)
  (US_Print "\n")

  (set! fontcolor READCOLOR)
  (US_CPrint "Keyboard\n")
  (set! fontcolor TEXTCOLOR)
  (set! PrintX 60)
  (US_Print "Run")
  (set! PrintX 120)
  (US_Print "Open")
  (set! PrintX 180)
  (US_Print "Fire")
  (set! PrintX 240)
  (US_Print "Strafe\n")
  (DrawWindow 5 (- PrintY 1) 310 13 BKGDCOLOR)
  (DrawCustKeybd #f)
  (US_Print "\n")

  (set! fontcolor TEXTCOLOR)
  (set! PrintX 60)
  (US_Print "Left")
  (set! PrintX 120)
  (US_Print "Right")
  (set! PrintX 180)
  (US_Print "Frwd")
  (set! PrintX 240)
  (US_Print "Bkwrd\n")
  (DrawWindow 5 (- PrintY 1) 310 13 BKGDCOLOR)
  (DrawCustKeys #f)

  (when (< (item-curpos CusItems) 0)
    (let find ((row 0))
      (when (< row (item-amount CusItems))
        (if (not (= 0 (ref custom-active row)))
            (setf! CusItems 3 row)
            (find (+ row 1))))))
  (VW_UpdateScreen)
  (MenuFadeIn))

;; WL_MENU.C:2615
(define (PrintCustMouse action)
  (when (and (>= action 0) (< action 4))
    (let ((wanted (ref (vector bt_run bt_use bt_attack bt_strafe) action)))
      (let find ((physical 0))
        (cond ((>= physical 4) #f)
              ((= (ref buttonmouse physical) wanted)
               (set! PrintX (+ 60 (* 60 action)))
               (US_Print (string-append "b" (number->string physical))))
              (else (find (+ physical 1))))))))

;; WL_MENU.C:2628
(define (DrawCustMouse highlight)
  (set! fontcolor (if highlight HIGHLIGHT TEXTCOLOR))
  (set! backcolor BKGDCOLOR)
  (setf! custom-active 0 (if mouseenabled 1 0))
  (when (not mouseenabled)
    (set! fontcolor DEACTIVE))
  (set! PrintY 74)
  (let draw ((action 0))
    (when (< action 4)
      (PrintCustMouse action)
      (draw (+ action 1)))))

;; WL_MENU.C:2651. Joystick bindings are unavailable in this port.
(define (PrintCustJoy action)
  #f)

;; WL_MENU.C:2664. No joystick customization pane is shown.
(define (DrawCustJoy highlight)
  #f)

;; WL_MENU.C:2688
(define (PrintCustKeybd action)
  (when (and (>= action 0) (< action 4))
    (let ((wanted (ref (vector bt_run bt_use bt_attack bt_strafe) action)))
      (set! PrintX (+ 60 (* 60 action)))
      (US_Print (IN_GetScanName (ref buttonscan wanted))))))

;; WL_MENU.C:2694
(define (DrawCustKeybd highlight)
  (set! fontcolor (if highlight HIGHLIGHT TEXTCOLOR))
  (set! backcolor BKGDCOLOR)
  (set! PrintY 152)
  (let draw ((action 0))
    (when (< action 4)
      (PrintCustKeybd action)
      (draw (+ action 1)))))

;; WL_MENU.C:2709
(define (PrintCustKeys direction)
  (when (and (>= direction 0) (< direction 4))
    (let ((wanted (ref (vector 3 1 0 2) direction)))
      (set! PrintX (+ 60 (* 60 direction)))
      (US_Print (IN_GetScanName (ref dirscan wanted))))))

;; WL_MENU.C:2715
(define (DrawCustKeys highlight)
  (set! fontcolor (if highlight HIGHLIGHT TEXTCOLOR))
  (set! backcolor BKGDCOLOR)
  (set! PrintY 178)
  (let draw ((direction 0))
    (when (< direction 4)
      (PrintCustKeys direction)
      (draw (+ direction 1)))))

(define (DrawCtlScreen)
  (ClearMScreen)
  (DrawStripes 10)
  (VWB_DrawPic 80 0 C_CONTROLPIC)
  (VWB_DrawPic 112 184 C_MOUSELBACKPIC)
  (DrawWindow 16 65 284 84 BKGDCOLOR)
  (set! WindowX 0)
  (set! WindowW 320)
  (set! fontcolor TEXTCOLOR)
  (set! backcolor BKGDCOLOR)
  (setf! control-active 0 (if MousePresent 1 0))
  (setf! control-active 4 (if mouseenabled 1 0))
  (when (or (< (item-curpos CtlItems) 0)
            (= (ref control-active (item-curpos CtlItems)) 0))
    (setf! CtlItems 3 0))
  (DrawMenu CtlItems control-active control-text)
  (VWB_DrawPic (+ (item-x CtlItems) (item-indent CtlItems) -24) (+ (item-y CtlItems) 3)
               (if mouseenabled C_SELECTEDPIC C_NOTSELECTEDPIC))
  (DrawMenuGun CtlItems)
  (VW_UpdateScreen))

;; The graphical runtime has no joystick calibration API; joystick rows remain
;; inactive, matching an unavailable device.
(define (CalibrateJoystick)
  #f)

(define (CP_Control)
  (DrawCtlScreen)
  (MenuFadeIn)
  (WaitKeyUp)
  (let loop ()
    (let ((which (HandleMenu CtlItems control-active control-text #f)))
      (cond ((= which 0) (set! mouseenabled (not mouseenabled)) (DrawCtlScreen) (ShootSnd) (loop))
            ((= which 4) (MouseSensitivity) (DrawCtlScreen) (MenuFadeIn) (WaitKeyUp) (loop))
            ((= which 5) (CustomControls) (DrawCtlScreen) (MenuFadeIn) (WaitKeyUp) (loop))
            (else (MenuFadeOut))))))

(define (DrawNewEpisode)
  (ClearMScreen)
  (VWB_DrawPic 112 184 C_MOUSELBACKPIC)
  (DrawWindow (- NE_X 4) (- NE_Y 4) (+ NE_W 8) (+ NE_H 8) BKGDCOLOR)
  (set! fontcolor READHCOLOR)
  (set! backcolor BKGDCOLOR)
  (set! PrintY 2)
  (set! WindowX 0)
  (US_CPrint "Which episode to play?")
  (DrawMenu NewEitems episode-active episode-text)
  (let loop ((episode 0))
    (when (< episode 6)
      (VWB_DrawPic (+ NE_X 32) (+ NE_Y (* episode 26)) (+ C_EPISODE1PIC episode))
      (loop (+ episode 1))))
  (VW_UpdateScreen)
  (MenuFadeIn)
  (WaitKeyUp))

(define (DrawNewGameDiff difficulty)
  (VWB_DrawPic (+ NM_X 185) (+ NM_Y 7) (+ C_BABYMODEPIC difficulty)))

(define (DrawNewGame)
  (ClearMScreen)
  (VWB_DrawPic 112 184 C_MOUSELBACKPIC)
  (set! fontcolor READHCOLOR)
  (set! backcolor BKGDCOLOR)
  (set! PrintX (+ NM_X 20))
  (set! PrintY (- NM_Y 32))
  (US_Print "How tough are you?")
  (DrawWindow (- NM_X 5) (- NM_Y 10) NM_W NM_H BKGDCOLOR)
  (DrawMenu NewItems difficulty-active difficulty-text)
  (DrawNewGameDiff (item-curpos NewItems))
  (VW_UpdateScreen)
  (MenuFadeIn)
  (WaitKeyUp))

(define (CP_EndGame)
  (if (not (Confirm "Are you sure you want to\nend the game you\nare playing? (Y or N):"))
      #f
      (begin
        (set! pickquick #f)
        (set! lives 0)
        (set! playstate ex_died)
        (setf! main-active 4 0)
        (setf! main-routine 7 'viewscores)
        (setf! main-text 7 "View Scores")
        #t)))

(define (CP_NewGame)
  (let choose-episode ()
    (DrawNewEpisode)
    (let ((which (HandleMenu NewEitems episode-active episode-text #f)))
      (if (< which 0)
          (MenuFadeOut)
          (let ((chapter (truncate (/ which 2))))
            (ShootSnd)
            (if (and ingame (not (Confirm "You are currently in\na game. Continuing will\nerase old game. Ok?")))
              (MenuFadeOut)
              (begin
                (MenuFadeOut)
                (DrawNewGame)
                (let ((chosen (HandleMenu NewItems difficulty-active difficulty-text DrawNewGameDiff)))
                  (if (< chosen 0)
                      (begin
                        (MenuFadeOut)
                        (choose-episode))
                      (begin
                        (ShootSnd)
                        (NewGame chosen chapter)
                        (set! StartGame #t)
                        (setf! main-active 6 1)
                        (set! pickquick #f)
                        (MenuFadeOut)))))))))))

;; WL_MENU.C:893-918
(define (CP_ViewScores)
  (set! fontnumber 0)
  (StartCPMusic ROSTER_MUS)
  (DrawHighScores)
  (VW_UpdateScreen)
  (MenuFadeIn)
  (set! fontnumber 1)
  (IN_Ack)
  (StartCPMusic MENUSONG)
  (MenuFadeOut))

;; WL_MENU.C:619-628
(define (CP_ReadThis)
  (StartCPMusic CORNER_MUS)
  (HelpScreens)
  (StartCPMusic MENUSONG))

;; The DOS text-mode shell has no equivalent in the graphical port; suspend
;; gameplay audio until Escape, then restore it.
(define (BossKey)
  (SD_MusicOff #t)
  (IN_ClearKeysDown)
  (let wait ()
    (unless (= LastScan sc_Escape)
      (IN_Yield)
      (wait)))
  (IN_ClearKeysDown)
  (SD_MusicOn)
  (VL_SetVGAPlaneMode)
  (VL_TestPaletteSet)
  (VL_SetPalette gamepal)
  (LoadLatchMem))

;; WL_MENU.C:2844-2867
(define endstrings
  (vector "Dost thou wish to\nleave with such hasty\nabandon?"
          "Chickening out...\nalready?"
          "Press N for more carnage.\nPress Y to be a weenie."
          "So, you think you can\nquit this easily, huh?"
          "Press N to save the world.\nPress Y to abandon it in\nits hour of need."
          "Press N if you are brave.\nPress Y to cower in shame."
          "Heroes, press N.\nWimps, press Y."
          "You are at an intersection.\nA sign says, 'Press Y to quit.'\n>"
          "For guns and glory, press N.\nFor work and worry, press Y."))

(define (CP_Quit)
  (let ((which (bitwise-and (US_RndT) (+ 7 (bitwise-and (US_RndT) 1)))))
    (when (Confirm (ref endstrings which))
      (VW_UpdateScreen)
      (SD_MusicOff)
      (SD_StopSound)
      (MenuFadeOut)
      (let clear ((register 1))
        (when (<= register #xf5)
          (alOut register 0)
          (clear (+ register 1))))
      (Quit))))

(define (save-slot-text slot)
  (let ((name (ref SaveGameNames slot)))
    (if (string=? name "") "      - empty -" name)))

;; WL_MENU.C:3029-3078, the save file scan
(define (SetupSaveGames)
  (let loop ((slot 0))
    (when (< slot 10)
      (setf! SaveGameNames slot (ReadSaveName slot))
      (loop (+ slot 1)))))

(define (PrintLSEntry slot color)
  (set! fontcolor color)
  (set! backcolor BKGDCOLOR)
  (DrawOutline (+ LSM_X (item-indent LSItems)) (+ LSM_Y (* slot MENUSTEP))
               (- LSM_W (item-indent LSItems) 15) 11 color color)
  (set! PrintX (+ LSM_X (item-indent LSItems) 2))
  (set! PrintY (+ LSM_Y (* slot MENUSTEP) 1))
  (set! fontnumber 0)
  (US_Print (save-slot-text slot))
  (set! fontnumber 1))

(define lastgameon 0)

(define (TrackWhichGame selected)
  (PrintLSEntry lastgameon TEXTCOLOR)
  (PrintLSEntry selected HIGHLIGHT)
  (set! lastgameon selected))

(define (DrawLSAction saving)
  (DrawWindow LSA_X LSA_Y LSA_W LSA_H TEXTCOLOR)
  (DrawOutline LSA_X LSA_Y LSA_W LSA_H 0 HIGHLIGHT)
  (VWB_DrawPic (+ LSA_X 8) (+ LSA_Y 5) C_DISKLOADING1PIC)
  (set! fontnumber 1)
  (set! fontcolor 0)
  (set! backcolor TEXTCOLOR)
  (set! PrintX (+ LSA_X 46))
  (set! PrintY (+ LSA_Y 13))
  (US_Print (if saving "Saving..." "Loading..."))
  (VW_UpdateScreen))

(define (DrawLoadSaveScreen saving)
  (ClearMScreen)
  (set! fontnumber 1)
  (DrawWindow (- LSM_X 10) (- LSM_Y 5) LSM_W LSM_H BKGDCOLOR)
  (VWB_DrawPic 112 184 C_MOUSELBACKPIC)
  (DrawStripes 10)
  (VWB_DrawPic 60 0 (if saving C_SAVEGAMEPIC C_LOADGAMEPIC))
  (let loop ((slot 0))
    (when (< slot 10)
      (PrintLSEntry slot TEXTCOLOR)
      (loop (+ slot 1))))
  (DrawMenu LSItems (make-vector 10 1) (make-vector 10 ""))
  (VW_UpdateScreen)
  (MenuFadeIn)
  (WaitKeyUp))

;; WL_MENU.C:1373-1452
(define (CP_LoadGame)
  (let choose ()
    (DrawLoadSaveScreen #f)
    (let* ((active (make-vector 10 1))
           (which (HandleMenu LSItems active (make-vector 10 "") TrackWhichGame)))
      (when (>= which 0)
        (if (string=? (ref SaveGameNames which) "")
            (choose)
            (begin
              (SD_PlaySound SHOOTSND)
              (DrawLSAction #f)
              (set! loadedgame #t)
              (LoadTheGame which (+ LSA_X 8) (+ LSA_Y 5))
              (SD_PlaySound SHOOTSND)
              (setf! LSItems 3 which)
              (set! quick-slot which)
              (set! pickquick #t)
              (setf! main-active 6 1)
              (set! StartGame #t)))))))

;; WL_MENU.C:1538-1648
(define (CP_SaveGame)
  (let choose ()
    (DrawLoadSaveScreen #t)
    (let* ((active (make-vector 10 1))
           (which (HandleMenu LSItems active (make-vector 10 "") TrackWhichGame)))
      (when (>= which 0)
        (if (and (not (string=? (ref SaveGameNames which) ""))
                 (not (Confirm "There's already a game\nsaved at this position.\n      Overwrite?")))
            (choose)
            (begin
              (SD_PlaySound SHOOTSND)
              (DrawWindow (- LSM_X 8) (- LSM_Y 3) LSM_W LSM_H BKGDCOLOR)
              (set! backcolor BKGDCOLOR)
              (set! fontcolor TEXTCOLOR)
              (set! PrintX (+ LSM_X (item-indent LSItems) 2))
              (set! PrintY (+ LSM_Y (* which MENUSTEP) 1))
              (let ((name (US_LineInput PrintX PrintY (ref SaveGameNames which) #t 31
                                        (- LSM_W (item-indent LSItems) 30))))
                (when name
                  (DrawLSAction #t)
                  (SaveTheGame which name (+ LSA_X 8) (+ LSA_Y 5))
                  (SD_PlaySound SHOOTSND)
                  (setf! LSItems 3 which)
                  (set! quick-slot which)
                  (set! pickquick #t)
                  (setf! SaveGameNames which name))))))))
  (MenuFadeOut))

(define (CP_EndGame)
  (if (Confirm "Are you sure you want\nto end the game you\nare playing? (Y or N):")
      (begin
        (set! pickquick #f)
        (set! lives 0)
        (set! playstate ex_died)
        (setf! main-active 4 0)
        (setf! main-text 7 "View Scores")
        (setf! main-routine 7 'viewscores)
        #t)
      #f))

(define VIEWCOLOR 127)

(define (DrawChangeView size)
  (VWB_Bar 0 160 320 40 VIEWCOLOR)
  (ShowViewSize size)
  (set! PrintY 161)
  (set! WindowX 0)
  (set! WindowY 320)
  (set! WindowW 320)
  (set! fontcolor HIGHLIGHT)
  (set! backcolor BKGDCOLOR)
  (US_CPrint "Use arrows to size\n")
  (US_CPrint "ENTER to accept\n")
  (US_CPrint "ESC to cancel")
  (VW_UpdateScreen)
  (MenuFadeIn))

(define (CP_ChangeView)
  (set! WindowX 0)
  (set! WindowY 0)
  (set! WindowW 320)
  (set! WindowH 200)
  (let ((old (truncate (/ viewwidth 16))))
    (DrawChangeView old)
    (let choose ((size old))
      (if (not (IN_Yield))
          #f
          (let ((scan LastScan))
            (set! LastScan sc_None)
            (IN_ReadControl 0)
            (when (and (ref Keyboard sc_Tab) (ref Keyboard sc_P) (MS_CheckParm "goobers"))
              (PicturePause))
            (cond ((or (= in-dir dir_South) (= in-dir dir_West))
                   (let ((next (max 4 (- size 1))))
                     (ShowViewSize next)
                     (VW_UpdateScreen)
                     (SD_PlaySound HITWALLSND)
                     (TicDelay 10)
                     (choose next)))
                  ((or (= in-dir dir_North) (= in-dir dir_East))
                   (let ((next (min 19 (+ size 1))))
                     (ShowViewSize next)
                     (VW_UpdateScreen)
                     (SD_PlaySound HITWALLSND)
                     (TicDelay 10)
                     (choose next)))
                  ((or in-button0 (= scan sc_Return))
                   (unless (= old size)
                     (SD_PlaySound SHOOTSND)
                     (Message "Thinking...")
                     (NewViewSize size))
                   (ShootSnd)
                   (MenuFadeOut)
                   #t)
                  ((or in-button1 (= scan sc_Escape))
                   (set! viewwidth (* old 16))
                   (SD_PlaySound ESCPRESSEDSND)
                   (MenuFadeOut)
                   #f)
                  (else (choose size))))))))

(define (run-menu-routine routine)
  (cond ((eq? routine 'newgame) (CP_NewGame))
        ((eq? routine 'sound) (CP_Sound))
        ((eq? routine 'control) (CP_Control))
        ((eq? routine 'loadgame) (CP_LoadGame))
        ((eq? routine 'savegame) (CP_SaveGame))
        ((eq? routine 'changeview) (CP_ChangeView))
        ((eq? routine 'readthis) (CP_ReadThis))
        ((eq? routine 'viewscores) (CP_ViewScores))
        ((eq? routine 'endgame) (when (CP_EndGame) (set! StartGame #t)))
        ((eq? routine 'back) (set! StartGame #t))
        ((eq? routine 'quit) (CP_Quit))
        (else #f)))

;; GFXV_WL6.H:18-26
(define C_OPTIONSPIC 10)
(define C_CURSOR1PIC 11)
(define C_CURSOR2PIC 12)
(define C_MOUSELBACKPIC 18)
(define C_BABYMODEPIC 19)
(define C_EPISODE1PIC 30)
(define C_NOTSELECTEDPIC 13)
(define C_SELECTEDPIC 14)
(define C_FXTITLEPIC 15)
(define C_DIGITITLEPIC 16)
(define C_MUSICTITLEPIC 17)
(define C_DISKLOADING1PIC 24)
(define CONTROLS_LUMP_START C_OPTIONSPIC)
(define CONTROLS_LUMP_END C_DISKLOADING1PIC)
(define C_CONTROLPIC 26)
(define C_CUSTOMIZEPIC 27)
(define C_LOADGAMEPIC 28)
(define C_SAVEGAMEPIC 29)

;; WL_MENU.C:539-601
(define (DrawMainMenu)
  (ClearMScreen)
  (VWB_DrawPic 112 184 C_MOUSELBACKPIC)
  (DrawStripes 10)
  (VWB_DrawPic 84 0 C_OPTIONSPIC)
  (DrawWindow (- MENU_X 8) (- MENU_Y 3) MENU_W MENU_H BKGDCOLOR)
  (setf! main-text 7 (if ingame "End Game" "View Scores"))
  (setf! main-routine 7 (if ingame 'endgame 'viewscores))
  (setf! main-text 8 (if ingame "Back to Game" "Back to Demo"))
  (setf! main-active 8 (if ingame 2 1))
  (DrawMenu MainItems main-active main-text)
  (VW_UpdateScreen))

;; WL_MENU.C:3029-3098
(define (SetupControlPanel)
  (CA_CacheGrChunk (+ STARTFONT 1))
  (CacheLump CONTROLS_LUMP_START CONTROLS_LUMP_END)
  (set! fontcolor TEXTCOLOR)
  (set! backcolor BKGDCOLOR)
  (set! fontnumber 1)
  (set! WindowH 200)
  (unless ingame
    (CA_LoadAllSounds))
  (setf! main-active 4 (if ingame 1 0))
  (SetupSaveGames)
  (IN_ClearKeysDown)
  (DrawMainMenu))

(define (CleanupControlPanel)
  (UnCacheLump CONTROLS_LUMP_START CONTROLS_LUMP_END)
  (set! fontnumber 0))

(define (CP_CheckQuick scan)
  (cond ((= scan sc_F7)
         (when (CP_EndGame)
           (set! pickquick #f)
           (set! lives 0)
           (set! playstate ex_died))
         (DrawAllPlayBorder)
         (setf! main-active 4 0)
         #t)
        ((= scan sc_F8)
         (let ((slot (item-curpos LSItems)))
           (if (and pickquick (not (string=? (ref SaveGameNames slot) "")))
               (begin
                 (Message "Saving...")
                 (SaveTheGame slot (ref SaveGameNames slot) 0 0))
               (CP_SaveGame)))
         #t)
        ((= scan sc_F9)
         (let ((slot (item-curpos LSItems)))
           (if (and pickquick
                    (not (string=? (ref SaveGameNames slot) ""))
                    (Confirm (string-append "Load " (ref SaveGameNames slot) "?")))
               (begin
                 (set! loadedgame #t)
                 (LoadTheGame slot 0 0)
                 (set! StartGame #t))
               (CP_LoadGame)))
         #t)
        ((= scan sc_F10) (CP_Quit) #t)
        (else #f)))

;; WL_MENU.C:332-538
(define (US_ControlPanel scan)
  (set! StartGame #f)
  (unless (and ingame (CP_CheckQuick scan))
    (StartCPMusic MENUSONG)
    (SetupControlPanel)
    (cond ((= scan sc_F1) (CP_ReadThis))
          ((= scan sc_F2) (CP_SaveGame))
          ((= scan sc_F3) (CP_LoadGame))
          ((= scan sc_F4) (CP_Sound))
          ((= scan sc_F5) (CP_ChangeView))
          ((= scan sc_F6) (CP_Control))
          (else
           (DrawMainMenu)
           (MenuFadeIn)
           (let panel ()
             (let ((which (HandleMenu MainItems main-active main-text #f)))
               (cond ((< which 0)
                      (CP_Quit)
                      (DrawMainMenu)
                      (MenuFadeIn)
                      (panel))
                     (else
                      (let ((routine (ref main-routine which)))
                        (when routine
                          (MenuFadeOut)
                          (run-menu-routine routine))
                        (unless StartGame
                          (DrawMainMenu)
                          (MenuFadeIn)
                          (panel))))))))
    (CleanupControlPanel))))
