;;; WL_MAIN.C — configuration file

(define MaxHighName 57)
(define MaxScores 7)
(define SCOREENTRY 66)
(define SCORESIZE (* MaxScores SCOREENTRY))
(define CONFIGSIZE 522)

(define configname "CONFIG.")
(define configpath "/tmp/CONFIG.WL6")

(define score-name (make-vector MaxScores ""))
(define score-points (make-vector MaxScores 0))
(define score-completed (make-vector MaxScores 0))
(define score-episode (make-vector MaxScores 0))

(define config 0)

(define viewsize 15)
(define mouseadjustment 5)
(define mouseenabled #f)
(define joystickenabled #f)
(define joypadenabled #f)
(define joystickprogressive #f)
(define joystickport 0)
(define diskflop-which 0)

(define (DiskFlopAnim x y)
  (unless (and (= x 0) (= y 0))
    (VWB_DrawPic x y (+ C_DISKLOADING1PIC diskflop-which))
    (VW_UpdateScreen)
    (set! diskflop-which (- 1 diskflop-which))))

(define (Patch386)
  #f)

;; WL_MAIN.C: SetupWalls.  Keep the reference's table population rather than
;; replacing it with an arithmetic lookup in the renderer.
(define (SetupWalls)
  (let loop ((index 1))
    (when (< index MAXWALLTILES)
      (setf! horizwall-table index (* (- index 1) 2))
      (setf! vertwall-table index (+ (* (- index 1) 2) 1))
      (loop (+ index 1)))))

(define (MS_CheckParm check)
  (let scan ((index 1))
    (if (>= index (vector-length argv))
        #f
        (let* ((argument (ref argv index))
               (start (let skip ((offset 0))
                        (if (and (< offset (string-length argument))
                                 (not (char-alphabetic? (string-ref argument offset))))
                            (skip (+ offset 1))
                            offset))))
          (if (and (= (- (string-length argument) start) (string-length check))
                   (string=? (ascii-downcase (substring argument start (string-length argument)))
                        (ascii-downcase check)))
              #t
              (scan (+ index 1)))))))

(define (config-string bytes offset limit)
  (let loop ((index 0) (name ""))
    (if (or (= index limit) (= 0 (ref bytes (+ offset index))))
        name
        (loop (+ index 1)
              (string-append name (string (integer->char (ref bytes (+ offset index)))))))))

(define (ReadConfig)
  (let ((port (or (open-input-file/maybe configpath)
                  (open-input-file (datafile configname)))))
    (set! config (read-bytes/all port))
    (close-input-port port))
  (let loop ((entry 0))
    (when (< entry MaxScores)
      (let ((base (* entry SCOREENTRY)))
        (setf! score-name entry (config-string config base MaxHighName))
        (setf! score-points entry (readu32 config (+ base 58)))
        (setf! score-completed entry (readu16 config (+ base 62)))
        (setf! score-episode entry (readu16 config (+ base 64))))
      (loop (+ entry 1))))
  (SD_SetSoundMode (readu16 config SCORESIZE))
  (SD_SetMusicMode (readu16 config (+ SCORESIZE 2)))
  (SD_SetDigiDevice (readu16 config (+ SCORESIZE 4)))
  (set! mouseenabled (= 1 (readu16 config (+ SCORESIZE 6))))
  (set! joystickenabled (= 1 (readu16 config (+ SCORESIZE 8))))
  (set! joypadenabled (= 1 (readu16 config (+ SCORESIZE 10))))
  (set! joystickprogressive (= 1 (readu16 config (+ SCORESIZE 12))))
  (set! joystickport (readu16 config (+ SCORESIZE 14)))
  (let controls ((index 0))
    (when (< index 4)
      (setf! dirscan index (readu16 config (+ 478 (* index 2))))
      (let ((button (readu16 config (+ 494 (* index 2)))))
        (setf! buttonmouse index (if (= button 65535) -1 button)))
      (setf! buttonjoy index (readu16 config (+ 502 (* index 2))))
      (controls (+ index 1))))
  (let buttons ((index 0))
    (when (< index NUMBUTTONS)
      (setf! buttonscan index (readu16 config (+ 486 (* index 2))))
      (buttons (+ index 1))))
  (set! viewsize (readu16 config (- CONFIGSIZE 4)))
  (set! mouseadjustment (readu16 config (- CONFIGSIZE 2))))

(define (WriteConfig)
  (let loop ((entry 0))
    (when (< entry MaxScores)
      (let ((base (* entry SCOREENTRY))
            (name (ref score-name entry)))
        (let chars ((index 0))
          (when (< index MaxHighName)
            (setf! config (+ base index)
                   (if (< index (string-length name))
                       (char->integer (string-ref name index))
                       0))
            (chars (+ index 1))))
        (setf! config (+ base MaxHighName) 0)
        (setu16! config (+ base 58) (bitwise-and (ref score-points entry) 65535))
        (setu16! config (+ base 60) (arithmetic-shift (ref score-points entry) -16))
        (setu16! config (+ base 62) (ref score-completed entry))
        (setu16! config (+ base 64) (ref score-episode entry)))
      (loop (+ entry 1))))
  (setu16! config SCORESIZE SoundMode)
  (setu16! config (+ SCORESIZE 2) MusicMode)
  (setu16! config (+ SCORESIZE 4) DigiMode)
  (setu16! config (+ SCORESIZE 6) (if mouseenabled 1 0))
  (setu16! config (+ SCORESIZE 8) (if joystickenabled 1 0))
  (setu16! config (+ SCORESIZE 10) (if joypadenabled 1 0))
  (setu16! config (+ SCORESIZE 12) (if joystickprogressive 1 0))
  (setu16! config (+ SCORESIZE 14) joystickport)
  (let controls ((index 0))
    (when (< index 4)
      (setu16! config (+ 478 (* index 2)) (ref dirscan index))
      (setu16! config (+ 494 (* index 2)) (ref buttonmouse index))
      (setu16! config (+ 502 (* index 2)) (ref buttonjoy index))
      (controls (+ index 1))))
  (let buttons ((index 0))
    (when (< index NUMBUTTONS)
      (setu16! config (+ 486 (* index 2)) (ref buttonscan index))
      (buttons (+ index 1))))
  (setu16! config (- CONFIGSIZE 4) viewsize)
  (setu16! config (- CONFIGSIZE 2) mouseadjustment)
  (let ((port (open-output-file configpath)))
    (write-bytes config port)
    (close-output-port port)))

(define (SetViewSize width height)
  (set! viewwidth (* 16 (truncate (/ width 16))))
  (set! viewheight (* 2 (truncate (/ height 2))))
  (set! viewleft (truncate (/ (- screenwidth viewwidth) 2)))
  (set! viewtop (truncate (/ (- (- screenheight STATUSLINES) viewheight) 2)))
  (set! centerx (- (truncate (/ viewwidth 2)) 1))
  (set! shootdelta (truncate (/ viewwidth 10)))
  (CalcProjection FOCALLENGTH)
  (SetupScaling (truncate (* viewwidth 1.5)))
  #t)

(define (NewViewSize width)
  (CA_UpLevel)
  (MM_SortMem)
  (set! viewsize width)
  (SetViewSize (* width 16) (* width 8))
  (CA_DownLevel))

(define (ShowViewSize size)
  (let ((old-width viewwidth)
        (old-height viewheight)
        (old-left viewleft)
        (old-top viewtop))
    (set! viewwidth (* size 16))
    (set! viewheight (* size 8))
    (set! viewleft (truncate (/ (- screenwidth viewwidth) 2)))
    (set! viewtop (truncate (/ (- (- screenheight STATUSLINES) viewheight) 2)))
    (DrawPlayBorder)
    (set! viewwidth old-width)
    (set! viewheight old-height)
    (set! viewleft old-left)
    (set! viewtop old-top)))

;; WL_MAIN.C: SignonScreen.  The original linked `signon` bitmap is accepted
;; as signon.bin when supplied beside the port; retain its munging and blit.
(define (SignonScreen)
  (VL_SetVGAPlaneMode)
  (VL_TestPaletteSet)
  (VL_LoadPalette)
  (let ((signon (or (CA_LoadFile "signon.bin")
                    (make-bytevector (* 320 200) 0))))
    (VL_MungePic signon 320 200)
    (VL_MemToScreen signon 320 200 0 0)
    (bytevector-copy! displayframebuffer 0 framebuffer 0
                      (bytevector-length framebuffer))))

(define (DoJukebox)
  (Message "Jukebox needs music playback.")
  (IN_ClearKeysDown)
  (IN_Ack)
  #f)

(define (FinishSignon)
  (VWB_Bar 0 189 300 11 BKGDCOLOR)
  (set! WindowX 0)
  (set! WindowW 320)
  (set! PrintY 190)
  (set! fontcolor 14)
  (set! backcolor BKGDCOLOR)
  (VWB_Bar 0 189 300 11 BKGDCOLOR)
  (set! PrintY 190)
  (set! fontcolor 10)
  (US_CPrint "Working...")
  (set! fontcolor 0)
  (set! backcolor 15))

(define (InitGame)
  (MM_Startup)
  (SignonScreen)
  (VL_Startup)
  (IN_Startup)
  (PM_Startup)
  (SD_Startup)
  (CA_Startup)
  (InitDigiMap)
  (SD_SetDigiDevice sds_SoundBlaster)
  ;; Every sound without a digitized version, which is every pickup, plays on the speaker.
  (SD_SetSoundMode sdm_PC)
  (ReadConfig)
  (CA_CacheGrChunk STARTFONT)
  (LoadLatchMem)
  (BuildTables)
  (SetupWalls)
  (NewViewSize viewsize)
  (VL_LoadPalette)
  (InitRedShifts)
  (FinishSignon))

(define (NewGame chosen chapter)
  (set! startgame #t)
  (set! oldscore 0)
  (set! secretcount 0)
  (set! treasurecount 0)
  (set! killcount 0)
  (set! secrettotal 0)
  (set! treasuretotal 0)
  (set! killtotal 0)
  (set! killx 0)
  (set! killy 0)
  (set! attackframe 0)
  (set! attackcount 0)
  (set! weaponframe 0)
  (set! faceframe 0)
  (set! difficulty chosen)
  (set! episode chapter)
  (set! mapon 0)
  (set! weapon wp_pistol)
  (set! bestweapon wp_pistol)
  (set! chosenweapon wp_pistol)
  (set! health 100)
  (set! ammo STARTAMMO)
  (set! lives 3)
  (set! score 0)
  (set! nextextra EXTRAPOINTS)
  (set! keys 0)
  (set! victoryflag #f)
  (set! TimeCount 0))

(define (ShutdownId)
  (US_Shutdown)
  (SD_Shutdown)
  (PM_Shutdown)
  (IN_Shutdown)
  (VL_Shutdown)
  (CA_Shutdown)
  (MM_Shutdown))

(define Quit
  (lambda errors
    (let ((error (if (pair? errors) (car errors) "")))
      (ClearMemory)
      (if (string=? error "")
          (begin
            (WriteConfig)
            (ShutdownId)
            (exit 0))
          (begin
            (ShutdownId)
            (display error)
            (newline)
            (exit 1))))))

;;; WL_MAIN.C:304-536 — save and load

;; C writes its own structs. This port has no such structs, so the file holds the port's arrays in
;; the order C writes them, behind a 32-byte name and in front of the same trailing checksum.
(define SAVEBUFFER 262144)
(define SAVENAMELEN 32)
(define save-buffer (make-bytevector SAVEBUFFER 0))
(define save-at 0)

(define (save-path slot)
  (string-append "SAVEGAM" (number->string slot) ".WL6"))

(define (put-byte value)
  (setf! save-buffer save-at (bitwise-and value 255))
  (set! save-at (+ save-at 1)))

(define (put-i32 value)
  (let ((bits (if (< value 0) (+ value 4294967296) value)))
    (put-byte bits)
    (put-byte (arithmetic-shift bits -8))
    (put-byte (arithmetic-shift bits -16))
    (put-byte (arithmetic-shift bits -24))))

(define (get-byte)
  (let ((value (ref save-buffer save-at)))
    (set! save-at (+ save-at 1))
    value))

(define (get-i32)
  (let ((bits (readu32 save-buffer save-at)))
    (set! save-at (+ save-at 4))
    (if (>= bits 2147483648) (- bits 4294967296) bits)))

;; A slot can hold a number, #f, or #t.
(define (put-num value)
  (cond ((eq? value #f) (put-i32 -2147483647))
        ((eq? value #t) (put-i32 -2147483646))
        (else (put-i32 (truncate value)))))

(define (get-num)
  (let ((value (get-i32)))
    (cond ((= value -2147483647) #f)
          ((= value -2147483646) #t)
          (else value))))

(define (put-vector source count)
  (let loop ((index 0))
    (when (< index count)
      (put-num (ref source index))
      (loop (+ index 1)))))

(define (get-vector target count)
  (let loop ((index 0))
    (when (< index count)
      (setf! target index (get-num))
      (loop (+ index 1)))))

(define (put-bytevector source count)
  (let loop ((index 0))
    (when (< index count)
      (put-byte (ref source index))
      (loop (+ index 1)))))

(define (get-bytevector target count)
  (let loop ((index 0))
    (when (< index count)
      (setf! target index (get-byte))
      (loop (+ index 1)))))

(define (put-name name)
  (let loop ((index 0))
    (when (< index SAVENAMELEN)
      (put-byte (if (< index (string-length name))
                    (char->integer (string-ref name index))
                    0))
      (loop (+ index 1)))))

;; WL_MAIN.C:304-311. C runs this over one field or array at a time, so the sum never crosses a
;; section boundary; save-section records those boundaries.
(define save-sections '())
(define section-start 0)

(define (DoChecksum start end sum)
  (let loop ((index start) (total sum))
    (if (>= index (- end 1))
        (if (>= total 2147483648) (- total 4294967296) total)
        (loop (+ index 1)
              (bitwise-and (+ total (bitwise-xor (ref save-buffer index) (ref save-buffer (+ index 1))))
                           4294967295)))))

(define (start-sections)
  (set! save-sections '())
  (set! section-start SAVENAMELEN))

(define (end-section)
  (set! save-sections (cons (list section-start save-at) save-sections))
  (set! section-start save-at))

(define (sections-checksum)
  (let loop ((rest (reverse save-sections)) (sum 0))
    (if (null? rest)
        sum
        (loop (cdr rest) (DoChecksum (first (car rest)) (second (car rest)) sum)))))

(define (save-play-fields)
  (put-num difficulty)
  (put-num episode)
  (put-num mapon)
  (put-num playstate)
  (put-num health)
  (put-num ammo)
  (put-num weapon)
  (put-num bestweapon)
  (put-num chosenweapon)
  (put-num weaponframe)
  (put-num attackframe)
  (put-num attackcount)
  (put-num keys)
  (put-num score)
  (put-num oldscore)
  (put-num nextextra)
  (put-num lives)
  (put-num godmode)
  (put-num victoryflag)
  (put-num TimeCount)
  (put-num killcount)
  (put-num killtotal)
  (put-num secretcount)
  (put-num secrettotal)
  (put-num treasurecount)
  (put-num treasuretotal)
  (put-num player-x)
  (put-num player-y)
  (put-num player-angle)
  (put-num player-tilex)
  (put-num player-tiley)
  (put-num statcount)
  (put-num doornum)
  (put-num pwallstate)
  (put-num pwallpos)
  (put-num pwallx)
  (put-num pwally)
  (put-num pwalldir))

(define (load-play-fields)
  (set! difficulty (get-num))
  (set! episode (get-num))
  (set! mapon (get-num))
  (set! playstate (get-num))
  (set! health (get-num))
  (set! ammo (get-num))
  (set! weapon (get-num))
  (set! bestweapon (get-num))
  (set! chosenweapon (get-num))
  (set! weaponframe (get-num))
  (set! attackframe (get-num))
  (set! attackcount (get-num))
  (set! keys (get-num))
  (set! score (get-num))
  (set! oldscore (get-num))
  (set! nextextra (get-num))
  (set! lives (get-num))
  (set! godmode (get-num))
  (set! victoryflag (get-num))
  (set! TimeCount (get-num))
  (set! killcount (get-num))
  (set! killtotal (get-num))
  (set! secretcount (get-num))
  (set! secrettotal (get-num))
  (set! treasurecount (get-num))
  (set! treasuretotal (get-num))
  (set! player-x (get-num))
  (set! player-y (get-num))
  (set! player-angle (get-num))
  (set! player-tilex (get-num))
  (set! player-tiley (get-num))
  (set! statcount (get-num))
  (set! doornum (get-num))
  (set! pwallstate (get-num))
  (set! pwallpos (get-num))
  (set! pwallx (get-num))
  (set! pwally (get-num))
  (set! pwalldir (get-num)))

(define (save-actors x y)
  (let loop ((index 0))
    (when (< index MAXACTORS)
      (when (ref actor-state index)
        (DiskFlopAnim x y))
      (put-num (state-id (ref actor-state index)))
      (put-num (ref actor-tilex index))
      (put-num (ref actor-tiley index))
      (put-num (ref actor-x index))
      (put-num (ref actor-y index))
      (put-num (ref actor-dir index))
      (put-num (ref actor-class index))
      (put-num (ref actor-ticcount index))
      (put-num (ref actor-speed index))
      (put-num (ref actor-flags index))
      (put-num (ref actor-distance index))
      (put-num (ref actor-areanumber index))
      (put-num (ref actor-temp1 index))
      (put-num (ref actor-temp2 index))
      (put-num (ref actor-active index))
      (put-num (ref actor-hitpoints index))
      (put-num (ref actor-viewx index))
      (put-num (ref actor-transx index))
      (put-num (ref actor-angle index))
      (loop (+ index 1)))))

(define (load-actors x y)
  (let loop ((index 0))
    (when (< index MAXACTORS)
      (setf! actor-state index (state-by-id (get-num)))
      (setf! actor-tilex index (get-num))
      (setf! actor-tiley index (get-num))
      (setf! actor-x index (get-num))
      (setf! actor-y index (get-num))
      (setf! actor-dir index (get-num))
      (setf! actor-class index (get-num))
      (setf! actor-ticcount index (get-num))
      (setf! actor-speed index (get-num))
      (setf! actor-flags index (get-num))
      (setf! actor-distance index (get-num))
      (setf! actor-areanumber index (get-num))
      (setf! actor-temp1 index (get-num))
      (setf! actor-temp2 index (get-num))
      (setf! actor-active index (get-num))
      (setf! actor-hitpoints index (get-num))
      (setf! actor-viewx index (get-num))
      (setf! actor-transx index (get-num))
      (setf! actor-angle index (get-num))
      (when (ref actor-state index)
        (DiskFlopAnim x y))
      (loop (+ index 1)))))

;; WL_MAIN.C:323-427
(define (SaveTheGame slot name x y)
  (set! save-at 0)
  (put-name name)
  (start-sections)
  (DiskFlopAnim x y)
  (save-play-fields)
  (end-section)
  (DiskFlopAnim x y)
  (put-vector LevelRatios-kill 8)
  (put-vector LevelRatios-secret 8)
  (put-vector LevelRatios-treasure 8)
  (put-vector LevelRatios-time 8)
  (end-section)
  (DiskFlopAnim x y)
  (put-bytevector tilemap (* MAPSIZE MAPSIZE))
  (end-section)
  (DiskFlopAnim x y)
  (put-vector actorat (* MAPSIZE MAPSIZE))
  (end-section)
  (put-vector areamap (* MAPSIZE MAPSIZE))
  (put-vector areaconnect (* NUMAREAS NUMAREAS))
  (put-vector areabyplayer NUMAREAS)
  (save-actors x y)
  (DiskFlopAnim x y)
  (end-section)
  (DiskFlopAnim x y)
  (put-vector stat-tilex MAXSTATS)
  (put-vector stat-tiley MAXSTATS)
  (put-vector stat-shape MAXSTATS)
  (put-vector stat-flags MAXSTATS)
  (put-vector stat-item MAXSTATS)
  (end-section)
  (DiskFlopAnim x y)
  (put-vector doorposition MAXDOORS)
  (put-vector dooraction MAXDOORS)
  (put-vector doorlock MAXDOORS)
  (put-vector doorvertical MAXDOORS)
  (put-vector doortilex MAXDOORS)
  (put-vector doortiley MAXDOORS)
  (end-section)
  (put-i32 (sections-checksum))
  (let ((port (open-output-file (save-path slot))))
    (write-bytes (bytevector-copy save-buffer 0 save-at) port)
    (close-output-port port))
  #t)

;; WL_MAIN.C:443-536
(define (LoadTheGame slot x y)
  (let ((port (open-input-file (save-path slot))))
    (set! save-buffer (read-bytes/all port))
    (close-input-port port))
  (set! save-at SAVENAMELEN)
  (DiskFlopAnim x y)
  (load-play-fields)
  (get-vector LevelRatios-kill 8)
  (get-vector LevelRatios-secret 8)
  (get-vector LevelRatios-treasure 8)
  (get-vector LevelRatios-time 8)
  (DiskFlopAnim x y)
  (SetupGameLevel)
  (set! save-at SAVENAMELEN)
  (start-sections)
  (load-play-fields)
  (end-section)
  (get-vector LevelRatios-kill 8)
  (get-vector LevelRatios-secret 8)
  (get-vector LevelRatios-treasure 8)
  (get-vector LevelRatios-time 8)
  (end-section)
  (DiskFlopAnim x y)
  (get-bytevector tilemap (* MAPSIZE MAPSIZE))
  (end-section)
  (DiskFlopAnim x y)
  (get-vector actorat (* MAPSIZE MAPSIZE))
  (end-section)
  (get-vector areamap (* MAPSIZE MAPSIZE))
  (get-vector areaconnect (* NUMAREAS NUMAREAS))
  (get-vector areabyplayer NUMAREAS)
  (load-actors x y)
  (DiskFlopAnim x y)
  (end-section)
  (DiskFlopAnim x y)
  (get-vector stat-tilex MAXSTATS)
  (get-vector stat-tiley MAXSTATS)
  (get-vector stat-shape MAXSTATS)
  (get-vector stat-flags MAXSTATS)
  (get-vector stat-item MAXSTATS)
  (end-section)
  (DiskFlopAnim x y)
  (DiskFlopAnim x y)
  (get-vector doorposition MAXDOORS)
  (get-vector dooraction MAXDOORS)
  (get-vector doorlock MAXDOORS)
  (get-vector doorvertical MAXDOORS)
  (get-vector doortilex MAXDOORS)
  (get-vector doortiley MAXDOORS)
  (end-section)
  (DiskFlopAnim x y)
  (DiskFlopAnim x y)
  (let* ((stored (get-i32))
         (matches (= stored (sections-checksum))))
    (set! save-buffer (make-bytevector SAVEBUFFER 0))
    (unless matches
      (Message "Your Save Game file is,\nshall we say, \"corrupted\".\nBut I'll let you go on and\nplay anyway....")
      (IN_ClearKeysDown)
      (IN_Ack)
      (set! score 0)
      (set! lives 1)
      (set! weapon wp_pistol)
      (set! chosenweapon wp_pistol)
      (set! bestweapon wp_pistol)
      (set! ammo 8))
    #t))

(define (ReadSaveName slot)
  (let ((port (open-input-file/maybe (save-path slot))))
    (if port
        (let ((bytes (read-bytes/all port)))
          (close-input-port port)
          (config-string bytes 0 SAVENAMELEN))
        "")))

(define (start-level)
  (set! startgame #f)
  (set! score oldscore)
  (DrawScore)
  (SetupGameLevel)
  (StartMusic)
  (DrawLevel)
  (set! playstate ex_stillplaying))

(define (show-screen)
  (VL_WaitVBL 1)
  (IN_UserInput 350))

(define (game-step)
  (unless (= playstate ex_stillplaying)
    (StopMusic))
  (cond ((= playstate ex_stillplaying)
         (PlayLoop)
         #f)
        ((or (= playstate ex_completed) (= playstate ex_secretlevel))
         (set! keys 0)
         (DrawKeys)
         (VL_FadeOut 0 255 0 0 0 30)
         (LevelCompleted)
         (show-screen)
         (set! oldscore score)
         (next-map)
         (start-level)
         #f)
        ((= playstate ex_died)
         (Died)
         (if (> lives -1)
             (begin (start-level) #f)
             (begin (CheckHighScore score (+ mapon 1)) #t)))
        ((or (= playstate ex_resetgame) (= playstate ex_loadedgame))
         (if (= playstate ex_loadedgame)
             (begin
               (StartMusic)
               (DrawLevel)
               (set! playstate ex_stillplaying))
             (start-level))
         #f)
        ((= playstate ex_victorious)
         (Victory)
         (show-screen)
         (CheckHighScore score (+ mapon 1))
         #t)
        (else #t)))

(define TITLEPIC 87)
(define CREDITSPIC 89)
(define T_DEMO0 139)

(define INTROSONG 7)

(define (attract-screen pic delay)
  (VL_FadeOut 0 255 0 0 0 30)
  (VWB_DrawPic 0 0 pic)
  (VL_FadeIn 0 255 gamepal 30)
  (IN_UserInput delay))

(define (argument? wanted)
  (let loop ((index 0))
    (and (< index (vector-length argv))
         (or (string=? (ref argv index) wanted) (loop (+ index 1))))))

(define (DemoLoop)
  (let attract ((demo 0))
    (if (or (attract-screen TITLEPIC (* TickBase 15))
            (attract-screen CREDITSPIC (* TickBase 10))
            (begin
              (VL_FadeOut 0 255 0 0 0 30)
              (DrawHighScores)
              (VL_FadeIn 0 255 gamepal 30)
              (IN_UserInput (* TickBase 10))))
        (begin
          (VL_FadeOut 0 255 0 0 0 30)
          (if (and (ref Keyboard sc_Tab) (MS_CheckParm "goobers"))
              (RecordDemo)
              (US_ControlPanel sc_None))
          (if (or startgame loadedgame)
              #t
              (attract demo)))
        (begin
          (PlayDemo (CA_CacheGrChunk (+ T_DEMO0 demo)))
          (if (= playstate ex_abort)
              #t
              (begin
                (StartCPMusic INTROSONG)
                (attract (- (+ demo 1) (* 4 (truncate (/ (+ demo 1) 4)))))))))))
