;;; WL_STATE.C — enemy states, sighting, and tile movement

(define east 0)
(define northeast 1)
(define north 2)
(define northwest 3)
(define west 4)
(define southwest 5)
(define south 6)
(define southeast 7)
(define nodir 8)

(define opposite (vector 4 5 6 7 0 1 2 3 8))
(define dirdx (vector 1 1 0 -1 -1 -1 0 1 0))
(define dirdy (vector 0 -1 -1 -1 0 1 1 1 0))

(define diagonal
  (vector 8 8 1 8 8 8 7 8 8
          8 8 8 8 8 8 8 8 8
          1 8 8 8 3 8 8 8 8
          8 8 8 8 8 8 8 8 8
          8 8 3 8 8 8 5 8 8
          8 8 8 8 8 8 8 8 8
          7 8 8 8 5 8 8 8 8
          8 8 8 8 8 8 8 8 8
          8 8 8 8 8 8 8 8 8))

(define MINSIGHT 98304)
(define MINACTORDIST 65536)
(define ICONARROWS 90)

(define FL_SHOOTABLE 1)
(define FL_NEVERMARK 4)
(define FL_VISABLE 8)
(define FL_ATTACKMODE 16)
(define FL_FIRSTATTACK 32)
(define FL_AMBUSH 64)
(define FL_NONMARK 128)

(define madenoise #f)

(define actorat (make-vector (* MAPSIZE MAPSIZE) -1))

(define (actorat-at x y) (ref actorat (+ (* x MAPSIZE) y)))

(define (actorat-set! x y index) (setf! actorat (+ (* x MAPSIZE) y) index))

;; WL_STATE.C:778-802
(define (DropItem itemtype tilex tiley)
  (if (< (actorat-at tilex tiley) 0)
      (begin (PlaceItemType itemtype tilex tiley) #t)
      (let xscan ((x (max 0 (- tilex 1))))
        (if (> x (min (- MAPSIZE 1) (+ tilex 1)))
            #f
            (let yscan ((y (max 0 (- tiley 1))))
              (cond ((> y (min (- MAPSIZE 1) (+ tiley 1))) (xscan (+ x 1)))
                    ((< (actorat-at x y) 0)
                     (PlaceItemType itemtype x y)
                     #t)
                    (else (yscan (+ y 1)))))))))

(define (actorat-clear)
  (let loop ((index 0))
    (when (< index (* MAPSIZE MAPSIZE))
      (setf! actorat index -1)
      (loop (+ index 1)))))

(define statetype (struct 'statetype '(rotate shapenum tictime think action next)))

;; A save file cannot hold a state object, so every state carries an index in this registry.
(define state-registry (make-vector 512 #f))
(define state-count 0)

(define (mkstate rotate shapenum tictime think action)
  (let ((state (statetype rotate shapenum tictime think action #f)))
    (setf! state-registry state-count state)
    (set! state-count (+ state-count 1))
    state))

(define (state-id state)
  (if state
      (let scan ((index 0))
        (cond ((= index state-count) -1)
              ((eq? (ref state-registry index) state) index)
              (else (scan (+ index 1)))))
      -1))

(define (state-by-id id)
  (if (< id 0)
      #f
      (ref state-registry id)))

(define (SpawnNewObj tilex tiley state)
  (GetNewActor)
  (let ((index new))
    (setf! actor-state index state)
    (setf! actor-ticcount index (if (= (ref state 'tictime) 0) 0
                                     (remainder (US_RndT) (ref state 'tictime))))
    (setf! actor-tilex index tilex)
    (setf! actor-tiley index tiley)
    (setf! actor-x index (+ (* tilex TILEGLOBAL) (truncate (/ TILEGLOBAL 2))))
    (setf! actor-y index (+ (* tiley TILEGLOBAL) (truncate (/ TILEGLOBAL 2))))
    (setf! actor-dir index nodir)
    (actorat-set! tilex tiley index)
    (setf! actor-areanumber index (areaat tilex tiley))
    index))

(define (NewState index state)
  (setf! actor-state index state)
  (setf! actor-ticcount index (ref state 'tictime)))

(define (actor-rotates index)
  (let ((state (ref actor-state index)))
    (if state (ref state 'rotate) #t)))

(define (blocked-diag x y)
  (let ((tile (tileat x y)))
    (cond ((>= tile 128) #t)
          ((> (bitwise-and tile 63) 0) #t)
          ((>= (actorat-at x y) 0) #t)
          (else #f))))

(define (blocked-side x y)
  (let ((tile (tileat x y)))
    (cond ((>= tile 128) (bitwise-and tile 63))
          ((> (bitwise-and tile 63) 0) -2)
          ((>= (actorat-at x y) 0) -2)
          (else -1))))

(define (TryWalk index)
  (let ((dir (ref actor-dir index)))
    (cond ((= dir nodir) #f)
          ((or (< dir east) (> dir southeast)) (Quit "Walk: Bad dir"))
          (else
           (let ((tilex (ref actor-tilex index))
              (tiley (ref actor-tiley index))
              (dx (ref dirdx dir))
              (dy (ref dirdy dir)))
          (let ((doorway
                 (cond ((= (ref actor-class index) inertobj) -1)
                       ((and (not (= dx 0)) (not (= dy 0)))
                        (if (or (blocked-diag (+ tilex dx) (+ tiley dy))
                                (blocked-diag (+ tilex dx) tiley)
                                (blocked-diag tilex (+ tiley dy)))
                            -2
                            -1))
                       ((or (= (ref actor-class index) (class-of en_dog))
                            (= (ref actor-class index) fakeobj))
                        (if (blocked-diag (+ tilex dx) (+ tiley dy)) -2 -1))
                       (else (blocked-side (+ tilex dx) (+ tiley dy))))))
            (if (= doorway -2)
                #f
                (begin
                  (setf! actor-tilex index (+ tilex dx))
                  (setf! actor-tiley index (+ tiley dy))
                  (if (>= doorway 0)
                      (begin
                        (OpenDoor doorway)
                        (setf! actor-distance index (- (- doorway) 1)))
                      (begin
                        (setf! actor-areanumber index (areaat (+ tilex dx) (+ tiley dy)))
                        (setf! actor-distance index TILEGLOBAL)))
                  #t))))))))

(define (try-dir index dir)
  (setf! actor-dir index dir)
  (TryWalk index))

(define (SelectChaseDir index)
  (let ((olddir (ref actor-dir index))
        (deltax (- player-tilex (ref actor-tilex index)))
        (deltay (- player-tiley (ref actor-tiley index))))
    (let ((turnaround (ref opposite olddir))
          (xdir (cond ((> deltax 0) east) ((< deltax 0) west) (else nodir)))
          (ydir (cond ((> deltay 0) south) ((< deltay 0) north) (else nodir))))
      (let ((swap (> (abs deltay) (abs deltax))))
        (let ((first (if swap ydir xdir))
              (second (if swap xdir ydir)))
          (let ((d1 (if (= first turnaround) nodir first))
                (d2 (if (= second turnaround) nodir second)))
            (cond
              ((and (not (= d1 nodir)) (try-dir index d1)) #t)
              ((and (not (= d2 nodir)) (try-dir index d2)) #t)
              ((and (not (= olddir nodir)) (try-dir index olddir)) #t)
              (else
               (let ((found
                      (if (> (US_RndT) 128)
                          (let up ((tdir north))
                            (cond ((> tdir west) #f)
                                  ((and (not (= tdir turnaround)) (try-dir index tdir)) #t)
                                  (else (up (+ tdir 1)))))
                          (let down ((tdir west))
                            (cond ((< tdir north) #f)
                                  ((and (not (= tdir turnaround)) (try-dir index tdir)) #t)
                                  (else (down (- tdir 1))))))))
                 (cond (found #t)
                       ((and (not (= turnaround nodir)) (try-dir index turnaround)) #t)
                       (else (setf! actor-dir index nodir) #f)))))))))))

(define (SelectDodgeDir index)
  (let ((turnaround
         (if (> (bitwise-and (ref actor-flags index) FL_FIRSTATTACK) 0)
             (begin
               (setf! actor-flags index (- (ref actor-flags index) FL_FIRSTATTACK))
               nodir)
             (ref opposite (ref actor-dir index))))
        (deltax (- player-tilex (ref actor-tilex index)))
        (deltay (- player-tiley (ref actor-tiley index))))
    (let* ((d1 (if (> deltax 0) east west))
           (d3 (if (> deltax 0) west east))
           (d2 (if (> deltay 0) south north))
           (d4 (if (> deltay 0) north south))
           (wide (> (abs deltax) (abs deltay)))
           (p1 (if wide d2 d1))
           (p2 (if wide d1 d2))
           (p3 (if wide d4 d3))
           (p4 (if wide d3 d4))
           (shuffle (< (US_RndT) 128))
           (q1 (if shuffle p2 p1))
           (q2 (if shuffle p1 p2))
           (q3 (if shuffle p4 p3))
           (q4 (if shuffle p3 p4))
           (q0 (ref diagonal (+ (* q1 9) q2))))
      (let loop ((tries (list q0 q1 q2 q3 q4)))
        (cond ((null? tries)
               (if (and (not (= turnaround nodir)) (try-dir index turnaround))
                   #t
                   (begin (setf! actor-dir index nodir) #f)))
              ((or (= (car tries) nodir) (= (car tries) turnaround)) (loop (cdr tries)))
              ((try-dir index (car tries)) #t)
              (else (loop (cdr tries))))))))

;; WL_STATE.C:600-660
(define (SelectRunDir index)
  (let* ((deltax (- player-tilex (ref actor-tilex index)))
         (deltay (- player-tiley (ref actor-tiley index)))
         (first (if (< deltax 0) east west))
         (second (if (< deltay 0) south north))
         (swap (> (abs deltay) (abs deltax)))
         (d1 (if swap second first))
         (d2 (if swap first second)))
    (unless (or (try-dir index d1) (try-dir index d2))
      (let ((forward (> (US_RndT) 128)))
        (let scan ((tdir (if forward north west)))
          (cond ((if forward (> tdir west) (< tdir north))
                 (setf! actor-dir index nodir))
                ((try-dir index tdir) #t)
                (else (scan (if forward (+ tdir 1) (- tdir 1))))))))))

(define (MoveObj index move)
  (let ((dir (ref actor-dir index)))
    (cond ((= dir nodir) #f)
          ((or (< dir east) (> dir southeast)) (Quit "MoveObj: bad dir!"))
          (else
           (let ((dx (* (ref dirdx dir) move))
            (dy (* (ref dirdy dir) move)))
        (setf! actor-x index (+ (ref actor-x index) dx))
        (setf! actor-y index (+ (ref actor-y index) dy))
        (if (and (areabyplayer-at (ref actor-areanumber index))
                 (<= (abs (- (ref actor-x index) player-x)) MINACTORDIST)
                 (<= (abs (- (ref actor-y index) player-y)) MINACTORDIST))
            (begin
              (when (= (ref actor-class index) ghostobj)
                (TakeDamage (* tics 2) index))
              (setf! actor-x index (- (ref actor-x index) dx))
              (setf! actor-y index (- (ref actor-y index) dy)))
            (setf! actor-distance index (- (ref actor-distance index) move))))))))

(define (door-blocks door intercept)
  (> (bitwise-and intercept 65535) (ref doorposition door)))

(define (line-clear-x x1 y1 x2 y2 xt1 xt2)
  (let ((forward (> xt2 xt1)))
    (let ((partial (if forward (- 256 (bitwise-and x1 255)) (bitwise-and x1 255)))
          (xstep (if forward 1 -1))
          (deltafrac (abs (- x2 x1)))
          (delta (- y2 y1)))
      (let ((ltemp (truncate (/ (arithmetic-shift delta 8) deltafrac))))
        (let ((ystep (cond ((> ltemp 32767) 32767) ((< ltemp -32767) -32767) (else ltemp))))
          (let loop ((x (+ xt1 xstep))
                     (yfrac (+ y1 (arithmetic-shift (* ystep partial) -8)))
                     (limit (+ xt2 xstep)))
            (let ((y (arithmetic-shift yfrac -8)))
              (let ((value (tileat x y))
                    (nextfrac (+ yfrac ystep))
                    (nextx (+ x xstep)))
                (cond
                  ((= value 0) (if (= nextx limit) #t (loop nextx nextfrac limit)))
                  ((or (< value 128) (> value 256)) #f)
                  ((door-blocks (bitwise-and value 127) (- nextfrac (truncate (/ ystep 2)))) #f)
                  (else (if (= nextx limit) #t (loop nextx nextfrac limit))))))))))))

(define (line-clear-y x1 y1 x2 y2 yt1 yt2)
  (let ((forward (> yt2 yt1)))
    (let ((partial (if forward (- 256 (bitwise-and y1 255)) (bitwise-and y1 255)))
          (ystep (if forward 1 -1))
          (deltafrac (abs (- y2 y1)))
          (delta (- x2 x1)))
      (let ((ltemp (truncate (/ (arithmetic-shift delta 8) deltafrac))))
        (let ((xstep (cond ((> ltemp 32767) 32767) ((< ltemp -32767) -32767) (else ltemp))))
          (let loop ((y (+ yt1 ystep))
                     (xfrac (+ x1 (arithmetic-shift (* xstep partial) -8)))
                     (limit (+ yt2 ystep)))
            (let ((x (arithmetic-shift xfrac -8)))
              (let ((value (tileat x y))
                    (nextfrac (+ xfrac xstep))
                    (nexty (+ y ystep)))
                (cond
                  ((= value 0) (if (= nexty limit) #t (loop nexty nextfrac limit)))
                  ((or (< value 128) (> value 256)) #f)
                  ((door-blocks (bitwise-and value 127) (- nextfrac (truncate (/ xstep 2)))) #f)
                  (else (if (= nexty limit) #t (loop nexty nextfrac limit))))))))))))

(define (CheckLine index)
  (let ((x1 (arithmetic-shift (ref actor-x index) -8))
        (y1 (arithmetic-shift (ref actor-y index) -8))
        (x2 (arithmetic-shift player-x -8))
        (y2 (arithmetic-shift player-y -8)))
    (let ((xt1 (arithmetic-shift x1 -8))
          (yt1 (arithmetic-shift y1 -8)))
      (and (or (= xt1 player-tilex) (line-clear-x x1 y1 x2 y2 xt1 player-tilex))
           (or (= yt1 player-tiley) (line-clear-y x1 y1 x2 y2 yt1 player-tiley))))))

(define (CheckSight index)
  (if (not (areabyplayer-at (ref actor-areanumber index)))
      #f
      (let ((deltax (- player-x (ref actor-x index)))
            (deltay (- player-y (ref actor-y index)))
            (dir (ref actor-dir index)))
        (if (and (> deltax (- MINSIGHT)) (< deltax MINSIGHT)
                 (> deltay (- MINSIGHT)) (< deltay MINSIGHT))
            #t
            (cond ((and (= dir north) (> deltay 0)) #f)
                  ((and (= dir east) (< deltax 0)) #f)
                  ((and (= dir south) (< deltay 0)) #f)
                  ((and (= dir west) (> deltax 0)) #f)
                  (else (CheckLine index)))))))

(define (shoot-state which)
  (cond ((= which guardobj) s_grdshoot1)
        ((= which (class-of en_officer)) s_ofcshoot1)
        ((= which (class-of en_ss)) s_ssshoot1)
        ((= which mutantobj) s_mutshoot1)
        ((= which bossobj) s_bossshoot1)
        ((= which gretelobj) s_gretelshoot1)
        ((= which mechahitlerobj) s_mechashoot1)
        ((= which realhitlerobj) s_hitlershoot1)
        (else #f)))

;; WL_STATE.C:1253-1386
(define (FirstSighting index)
  (let ((which (ref actor-class index))
        (speed (ref actor-speed index)))
    (cond
      ((= which guardobj)
       (PlaySoundLocActor HALTSND index)
       (NewState index s_grdchase1)
       (setf! actor-speed index (* speed 3)))
      ((= which (class-of en_officer))
       (PlaySoundLocActor SPIONSND index)
       (NewState index s_ofcchase1)
       (setf! actor-speed index (* speed 5)))
      ((= which mutantobj)
       (NewState index s_mutchase1)
       (setf! actor-speed index (* speed 3)))
      ((= which (class-of en_ss))
       (PlaySoundLocActor SCHUTZADSND index)
       (NewState index s_sschase1)
       (setf! actor-speed index (* speed 4)))
      ((= which (class-of en_dog))
       (PlaySoundLocActor DOGBARKSND index)
       (NewState index s_dogchase1)
       (setf! actor-speed index (* speed 2)))
      ((= which bossobj)
       (SD_PlaySound GUTENTAGSND)
       (NewState index s_bosschase1)
       (setf! actor-speed index (* SPDPATROL 3)))
      ((= which gretelobj)
       (SD_PlaySound KEINSND)
       (NewState index s_gretelchase1)
       (setf! actor-speed index (* speed 3)))
      ((= which giftobj)
       (SD_PlaySound EINESND)
       (NewState index s_giftchase1)
       (setf! actor-speed index (* speed 3)))
      ((= which fatobj)
       (SD_PlaySound ERLAUBENSND)
       (NewState index s_fatchase1)
       (setf! actor-speed index (* speed 3)))
      ((= which schabbobj)
       (SD_PlaySound SCHABBSHASND)
       (NewState index s_schabbchase1)
       (setf! actor-speed index (* speed 3)))
      ((= which fakeobj)
       (SD_PlaySound TOT_HUNDSND)
       (NewState index s_fakechase1)
       (setf! actor-speed index (* speed 3)))
      ((= which mechahitlerobj)
       (SD_PlaySound DIESND)
       (NewState index s_mechachase1)
       (setf! actor-speed index (* speed 3)))
      ((= which realhitlerobj)
       (SD_PlaySound DIESND)
       (NewState index s_hitlerchase1)
       (setf! actor-speed index (* speed 5)))
      ((= which ghostobj)
       (NewState index s_blinkychase1)
       (setf! actor-speed index (* speed 2)))))
  (when (< (ref actor-distance index) 0)
    (setf! actor-distance index 0))
  (setf! actor-flags index
         (bitwise-ior (ref actor-flags index) (bitwise-ior FL_ATTACKMODE FL_FIRSTATTACK))))

;; WL_STATE.C:1434-1470
(define (reaction-delay index)
  (let ((which (ref actor-class index)))
    (cond ((= which guardobj) (+ 1 (truncate (/ (US_RndT) 4))))
          ((= which (class-of en_officer)) 2)
          ((= which mutantobj) (+ 1 (truncate (/ (US_RndT) 6))))
          ((= which (class-of en_ss)) (+ 1 (truncate (/ (US_RndT) 6))))
          ((= which (class-of en_dog)) (+ 1 (truncate (/ (US_RndT) 8))))
          (else 1))))

(define (SightPlayer index tics)
  (when (> (bitwise-and (ref actor-flags index) FL_ATTACKMODE) 0)
    (Quit "An actor in ATTACKMODE called SightPlayer!"))
  (if (> (ref actor-temp2 index) 0)
      (begin
        (setf! actor-temp2 index (- (ref actor-temp2 index) tics))
        (if (> (ref actor-temp2 index) 0)
            #f
            (begin
              (setf! actor-temp2 index 0)
              (FirstSighting index)
              #t)))
      (if (not (areabyplayer-at (ref actor-areanumber index)))
          #f
          (let ((ambush (> (bitwise-and (ref actor-flags index) FL_AMBUSH) 0)))
            (if (not (or (and (not ambush) madenoise) (CheckSight index)))
                #f
                (begin
                  (when ambush
                    (setf! actor-flags index (- (ref actor-flags index) FL_AMBUSH)))
                  (setf! actor-temp2 index (reaction-delay index))
                  #f))))))

(define (center-on-tile index)
  (setf! actor-x index (+ (* (ref actor-tilex index) TILEGLOBAL) 32768))
  (setf! actor-y index (+ (* (ref actor-tiley index) TILEGLOBAL) 32768)))

(define (walk-move index move select)
  (let loop ((left move))
    (when (> left 0)
      (if (< (ref actor-distance index) 0)
          (let ((door (- (- (ref actor-distance index)) 1)))
            (OpenDoor door)
            (when (= (ref dooraction door) dr_open)
              (setf! actor-distance index TILEGLOBAL)
              (loop left)))
          (if (< left (ref actor-distance index))
              (MoveObj index left)
              (let ((rest (- left (ref actor-distance index))))
                (center-on-tile index)
                (select index)
                (unless (= (ref actor-dir index) nodir)
                  (loop rest))))))))

(define (chase-attack index tics)
  (let ((dx (abs (- (ref actor-tilex index) player-tilex)))
        (dy (abs (- (ref actor-tiley index) player-tiley))))
    (let ((dist (if (> dx dy) dx dy)))
      (let ((chance (if (or (= dist 0)
                            (and (= dist 1) (< (ref actor-distance index) 16384)))
                        300
                        (truncate (/ (arithmetic-shift tics 4) dist))))
            (roll (US_RndT))
            (state (shoot-state (ref actor-class index))))
        (if (and state (< roll chance))
            (begin (NewState index state) #t)
            #f)))))

(define (T_Shoot index tics)
  (when (and (areabyplayer-at (ref actor-areanumber index)) (CheckLine index))
    (plus-flash-at (ref actor-tilex index) (ref actor-tiley index))
    (let ((dx (abs (- (ref actor-tilex index) player-tilex)))
          (dy (abs (- (ref actor-tiley index) player-tiley))))
      (let ((spread (if (> dx dy) dx dy)))
        (let ((dist (if (or (= (ref actor-class index) (class-of en_ss))
                            (= (ref actor-class index) bossobj))
                        (truncate (/ (* spread 2) 3))
                        spread))
              (visible (> (bitwise-and (ref actor-flags index) FL_VISABLE) 0)))
          (let ((hitchance (if (>= thrustspeed RUNSPEED)
                               (if visible (- 160 (* dist 16)) (- 160 (* dist 8)))
                               (if visible (- 256 (* dist 16)) (- 256 (* dist 8))))))
            (when (< (US_RndT) hitchance)
              (TakeDamage (cond ((< dist 2) (arithmetic-shift (US_RndT) -2))
                                ((< dist 4) (arithmetic-shift (US_RndT) -3))
                                (else (arithmetic-shift (US_RndT) -4)))
                          index))
            (PlaySoundLocActor
             (cond ((= (ref actor-class index) (class-of en_ss)) SSFIRESND)
                   ((or (= (ref actor-class index) giftobj)
                        (= (ref actor-class index) fatobj))
                    MISSILEFIRESND)
                   ((or (= (ref actor-class index) mechahitlerobj)
                        (= (ref actor-class index) realhitlerobj)
                        (= (ref actor-class index) bossobj))
                    BOSSFIRESND)
                   ((= (ref actor-class index) schabbobj) SCHABBSTHROWSND)
                   ((= (ref actor-class index) fakeobj) FLAMETHROWERSND)
                   (else NAZIFIRESND))
             index)))))))

(define (T_Bite index tics)
  (PlaySoundLocActor DOGATTACKSND index)
  (let ((dx (- (abs (- player-x (ref actor-x index))) TILEGLOBAL)))
    (when (<= dx MINACTORDIST)
      (let ((dy (- (abs (- player-y (ref actor-y index))) TILEGLOBAL)))
        (when (and (<= dy MINACTORDIST) (< (US_RndT) 180))
          (TakeDamage (arithmetic-shift (US_RndT) -4) index))))))

(define SPR_GRD_W1_1 (+ SPR_GRD_S_1 8))
(define SPR_GRD_W2_1 (+ SPR_GRD_S_1 16))
(define SPR_GRD_W3_1 (+ SPR_GRD_S_1 24))
(define SPR_GRD_W4_1 (+ SPR_GRD_S_1 32))
(define SPR_GRD_PAIN_1 (+ SPR_GRD_S_1 40))
(define SPR_GRD_DIE_1 (+ SPR_GRD_S_1 41))
(define SPR_GRD_DIE_2 (+ SPR_GRD_S_1 42))
(define SPR_GRD_DIE_3 (+ SPR_GRD_S_1 43))
(define SPR_GRD_PAIN_2 (+ SPR_GRD_S_1 44))
(define SPR_GRD_DEAD (+ SPR_GRD_S_1 45))
(define SPR_GRD_SHOOT1 (+ SPR_GRD_S_1 46))
(define SPR_GRD_SHOOT2 (+ SPR_GRD_S_1 47))
(define SPR_GRD_SHOOT3 (+ SPR_GRD_S_1 48))

(define SPR_DOG_W2_1 (+ SPR_DOG_W1_1 8))
(define SPR_DOG_W3_1 (+ SPR_DOG_W1_1 16))
(define SPR_DOG_W4_1 (+ SPR_DOG_W1_1 24))
(define SPR_DOG_DIE_1 (+ SPR_DOG_W1_1 32))
(define SPR_DOG_DIE_2 (+ SPR_DOG_W1_1 33))
(define SPR_DOG_DIE_3 (+ SPR_DOG_W1_1 34))
(define SPR_DOG_DEAD (+ SPR_DOG_W1_1 35))
(define SPR_DOG_JUMP1 (+ SPR_DOG_W1_1 36))
(define SPR_DOG_JUMP2 (+ SPR_DOG_W1_1 37))
(define SPR_DOG_JUMP3 (+ SPR_DOG_W1_1 38))

(define s_grdstand (mkstate #t SPR_GRD_S_1 0 T_Stand #f))

(define s_grdpath1 (mkstate #t SPR_GRD_W1_1 20 T_Path #f))
(define s_grdpath1s (mkstate #t SPR_GRD_W1_1 5 #f #f))
(define s_grdpath2 (mkstate #t SPR_GRD_W2_1 15 T_Path #f))
(define s_grdpath3 (mkstate #t SPR_GRD_W3_1 20 T_Path #f))
(define s_grdpath3s (mkstate #t SPR_GRD_W3_1 5 #f #f))
(define s_grdpath4 (mkstate #t SPR_GRD_W4_1 15 T_Path #f))

(define s_grdchase1 (mkstate #t SPR_GRD_W1_1 10 T_Chase #f))
(define s_grdchase1s (mkstate #t SPR_GRD_W1_1 3 #f #f))
(define s_grdchase2 (mkstate #t SPR_GRD_W2_1 8 T_Chase #f))
(define s_grdchase3 (mkstate #t SPR_GRD_W3_1 10 T_Chase #f))
(define s_grdchase3s (mkstate #t SPR_GRD_W3_1 3 #f #f))
(define s_grdchase4 (mkstate #t SPR_GRD_W4_1 8 T_Chase #f))

(define s_grdshoot1 (mkstate #f SPR_GRD_SHOOT1 20 #f #f))
(define s_grdshoot2 (mkstate #f SPR_GRD_SHOOT2 20 #f T_Shoot))
(define s_grdshoot3 (mkstate #f SPR_GRD_SHOOT3 20 #f #f))

(define s_grdpain (mkstate 2 SPR_GRD_PAIN_1 10 #f #f))
(define s_grdpain1 (mkstate 2 SPR_GRD_PAIN_2 10 #f #f))
(define s_grddie1 (mkstate #f SPR_GRD_DIE_1 15 #f A_DeathScream))
(define s_grddie2 (mkstate #f SPR_GRD_DIE_2 15 #f #f))
(define s_grddie3 (mkstate #f SPR_GRD_DIE_3 15 #f #f))
(define s_grddie4 (mkstate #f SPR_GRD_DEAD 0 #f #f))

(define SPR_OFC_W1_1 (+ SPR_OFC_S_1 8))
(define SPR_OFC_W2_1 (+ SPR_OFC_S_1 16))
(define SPR_OFC_W3_1 (+ SPR_OFC_S_1 24))
(define SPR_OFC_W4_1 (+ SPR_OFC_S_1 32))
(define SPR_OFC_PAIN_1 (+ SPR_OFC_S_1 40))
(define SPR_OFC_DIE_1 (+ SPR_OFC_S_1 41))
(define SPR_OFC_DIE_2 (+ SPR_OFC_S_1 42))
(define SPR_OFC_DIE_3 (+ SPR_OFC_S_1 43))
(define SPR_OFC_PAIN_2 (+ SPR_OFC_S_1 44))
(define SPR_OFC_DIE_4 (+ SPR_OFC_S_1 45))
(define SPR_OFC_DEAD (+ SPR_OFC_S_1 46))
(define SPR_OFC_SHOOT1 (+ SPR_OFC_S_1 47))
(define SPR_OFC_SHOOT2 (+ SPR_OFC_S_1 48))
(define SPR_OFC_SHOOT3 (+ SPR_OFC_S_1 49))

(define SPR_SS_W1_1 (+ SPR_SS_S_1 8))
(define SPR_SS_W2_1 (+ SPR_SS_S_1 16))
(define SPR_SS_W3_1 (+ SPR_SS_S_1 24))
(define SPR_SS_W4_1 (+ SPR_SS_S_1 32))
(define SPR_SS_PAIN_1 (+ SPR_SS_S_1 40))
(define SPR_SS_DIE_1 (+ SPR_SS_S_1 41))
(define SPR_SS_DIE_2 (+ SPR_SS_S_1 42))
(define SPR_SS_DIE_3 (+ SPR_SS_S_1 43))
(define SPR_SS_PAIN_2 (+ SPR_SS_S_1 44))
(define SPR_SS_DEAD (+ SPR_SS_S_1 45))
(define SPR_SS_SHOOT1 (+ SPR_SS_S_1 46))
(define SPR_SS_SHOOT2 (+ SPR_SS_S_1 47))
(define SPR_SS_SHOOT3 (+ SPR_SS_S_1 48))

(define SPR_MUT_W1_1 (+ SPR_MUT_S_1 8))
(define SPR_MUT_W2_1 (+ SPR_MUT_S_1 16))
(define SPR_MUT_W3_1 (+ SPR_MUT_S_1 24))
(define SPR_MUT_W4_1 (+ SPR_MUT_S_1 32))
(define SPR_MUT_PAIN_1 (+ SPR_MUT_S_1 40))
(define SPR_MUT_DIE_1 (+ SPR_MUT_S_1 41))
(define SPR_MUT_DIE_2 (+ SPR_MUT_S_1 42))
(define SPR_MUT_DIE_3 (+ SPR_MUT_S_1 43))
(define SPR_MUT_PAIN_2 (+ SPR_MUT_S_1 44))
(define SPR_MUT_DIE_4 (+ SPR_MUT_S_1 45))
(define SPR_MUT_DEAD (+ SPR_MUT_S_1 46))
(define SPR_MUT_SHOOT1 (+ SPR_MUT_S_1 47))
(define SPR_MUT_SHOOT2 (+ SPR_MUT_S_1 48))
(define SPR_MUT_SHOOT3 (+ SPR_MUT_S_1 49))
(define SPR_MUT_SHOOT4 (+ SPR_MUT_S_1 50))

(define s_ofcstand (mkstate #t SPR_OFC_S_1 0 T_Stand #f))
(define s_ofcpath1 (mkstate #t SPR_OFC_W1_1 20 T_Path #f))
(define s_ofcpath1s (mkstate #t SPR_OFC_W1_1 5 #f #f))
(define s_ofcpath2 (mkstate #t SPR_OFC_W2_1 15 T_Path #f))
(define s_ofcpath3 (mkstate #t SPR_OFC_W3_1 20 T_Path #f))
(define s_ofcpath3s (mkstate #t SPR_OFC_W3_1 5 #f #f))
(define s_ofcpath4 (mkstate #t SPR_OFC_W4_1 15 T_Path #f))
(define s_ofcshoot1 (mkstate #f SPR_OFC_SHOOT1 6 #f #f))
(define s_ofcshoot2 (mkstate #f SPR_OFC_SHOOT2 20 #f T_Shoot))
(define s_ofcshoot3 (mkstate #f SPR_OFC_SHOOT3 10 #f #f))
(define s_ofcchase1 (mkstate #t SPR_OFC_W1_1 10 T_Chase #f))
(define s_ofcchase1s (mkstate #t SPR_OFC_W1_1 3 #f #f))
(define s_ofcchase2 (mkstate #t SPR_OFC_W2_1 8 T_Chase #f))
(define s_ofcchase3 (mkstate #t SPR_OFC_W3_1 10 T_Chase #f))
(define s_ofcchase3s (mkstate #t SPR_OFC_W3_1 3 #f #f))
(define s_ofcchase4 (mkstate #t SPR_OFC_W4_1 8 T_Chase #f))
(define s_ofcpain (mkstate 2 SPR_OFC_PAIN_1 10 #f #f))
(define s_ofcpain1 (mkstate 2 SPR_OFC_PAIN_2 10 #f #f))
(define s_ofcdie1 (mkstate #f SPR_OFC_DIE_1 11 #f A_DeathScream))
(define s_ofcdie2 (mkstate #f SPR_OFC_DIE_2 11 #f #f))
(define s_ofcdie3 (mkstate #f SPR_OFC_DIE_3 11 #f #f))
(define s_ofcdie4 (mkstate #f SPR_OFC_DIE_4 11 #f #f))
(define s_ofcdie5 (mkstate #f SPR_OFC_DEAD 0 #f #f))

(define s_ssstand (mkstate #t SPR_SS_S_1 0 T_Stand #f))
(define s_sspath1 (mkstate #t SPR_SS_W1_1 20 T_Path #f))
(define s_sspath1s (mkstate #t SPR_SS_W1_1 5 #f #f))
(define s_sspath2 (mkstate #t SPR_SS_W2_1 15 T_Path #f))
(define s_sspath3 (mkstate #t SPR_SS_W3_1 20 T_Path #f))
(define s_sspath3s (mkstate #t SPR_SS_W3_1 5 #f #f))
(define s_sspath4 (mkstate #t SPR_SS_W4_1 15 T_Path #f))
(define s_ssshoot1 (mkstate #f SPR_SS_SHOOT1 20 #f #f))
(define s_ssshoot2 (mkstate #f SPR_SS_SHOOT2 20 #f T_Shoot))
(define s_ssshoot3 (mkstate #f SPR_SS_SHOOT3 10 #f #f))
(define s_ssshoot4 (mkstate #f SPR_SS_SHOOT2 10 #f T_Shoot))
(define s_ssshoot5 (mkstate #f SPR_SS_SHOOT3 10 #f #f))
(define s_ssshoot6 (mkstate #f SPR_SS_SHOOT2 10 #f T_Shoot))
(define s_ssshoot7 (mkstate #f SPR_SS_SHOOT3 10 #f #f))
(define s_ssshoot8 (mkstate #f SPR_SS_SHOOT2 10 #f T_Shoot))
(define s_ssshoot9 (mkstate #f SPR_SS_SHOOT3 10 #f #f))
(define s_sschase1 (mkstate #t SPR_SS_W1_1 10 T_Chase #f))
(define s_sschase1s (mkstate #t SPR_SS_W1_1 3 #f #f))
(define s_sschase2 (mkstate #t SPR_SS_W2_1 8 T_Chase #f))
(define s_sschase3 (mkstate #t SPR_SS_W3_1 10 T_Chase #f))
(define s_sschase3s (mkstate #t SPR_SS_W3_1 3 #f #f))
(define s_sschase4 (mkstate #t SPR_SS_W4_1 8 T_Chase #f))
(define s_sspain (mkstate 2 SPR_SS_PAIN_1 10 #f #f))
(define s_sspain1 (mkstate 2 SPR_SS_PAIN_2 10 #f #f))
(define s_ssdie1 (mkstate #f SPR_SS_DIE_1 15 #f A_DeathScream))
(define s_ssdie2 (mkstate #f SPR_SS_DIE_2 15 #f #f))
(define s_ssdie3 (mkstate #f SPR_SS_DIE_3 15 #f #f))
(define s_ssdie4 (mkstate #f SPR_SS_DEAD 0 #f #f))

(define s_mutstand (mkstate #t SPR_MUT_S_1 0 T_Stand #f))
(define s_mutpath1 (mkstate #t SPR_MUT_W1_1 20 T_Path #f))
(define s_mutpath1s (mkstate #t SPR_MUT_W1_1 5 #f #f))
(define s_mutpath2 (mkstate #t SPR_MUT_W2_1 15 T_Path #f))
(define s_mutpath3 (mkstate #t SPR_MUT_W3_1 20 T_Path #f))
(define s_mutpath3s (mkstate #t SPR_MUT_W3_1 5 #f #f))
(define s_mutpath4 (mkstate #t SPR_MUT_W4_1 15 T_Path #f))
(define s_mutshoot1 (mkstate #f SPR_MUT_SHOOT1 6 #f T_Shoot))
(define s_mutshoot2 (mkstate #f SPR_MUT_SHOOT2 20 #f #f))
(define s_mutshoot3 (mkstate #f SPR_MUT_SHOOT3 10 #f T_Shoot))
(define s_mutshoot4 (mkstate #f SPR_MUT_SHOOT4 20 #f #f))
(define s_mutchase1 (mkstate #t SPR_MUT_W1_1 10 T_Chase #f))
(define s_mutchase1s (mkstate #t SPR_MUT_W1_1 3 #f #f))
(define s_mutchase2 (mkstate #t SPR_MUT_W2_1 8 T_Chase #f))
(define s_mutchase3 (mkstate #t SPR_MUT_W3_1 10 T_Chase #f))
(define s_mutchase3s (mkstate #t SPR_MUT_W3_1 3 #f #f))
(define s_mutchase4 (mkstate #t SPR_MUT_W4_1 8 T_Chase #f))
(define s_mutpain (mkstate 2 SPR_MUT_PAIN_1 10 #f #f))
(define s_mutpain1 (mkstate 2 SPR_MUT_PAIN_2 10 #f #f))
(define s_mutdie1 (mkstate #f SPR_MUT_DIE_1 7 #f A_DeathScream))
(define s_mutdie2 (mkstate #f SPR_MUT_DIE_2 7 #f #f))
(define s_mutdie3 (mkstate #f SPR_MUT_DIE_3 7 #f #f))
(define s_mutdie4 (mkstate #f SPR_MUT_DIE_4 7 #f #f))
(define s_mutdie5 (mkstate #f SPR_MUT_DEAD 0 #f #f))

(define s_dogpath1 (mkstate #t SPR_DOG_W1_1 20 T_Path #f))
(define s_dogpath1s (mkstate #t SPR_DOG_W1_1 5 #f #f))
(define s_dogpath2 (mkstate #t SPR_DOG_W2_1 15 T_Path #f))
(define s_dogpath3 (mkstate #t SPR_DOG_W3_1 20 T_Path #f))
(define s_dogpath3s (mkstate #t SPR_DOG_W3_1 5 #f #f))
(define s_dogpath4 (mkstate #t SPR_DOG_W4_1 15 T_Path #f))

(define s_dogjump1 (mkstate #f SPR_DOG_JUMP1 10 #f #f))
(define s_dogjump2 (mkstate #f SPR_DOG_JUMP2 10 #f T_Bite))
(define s_dogjump3 (mkstate #f SPR_DOG_JUMP3 10 #f #f))
(define s_dogjump4 (mkstate #f SPR_DOG_JUMP1 10 #f #f))
(define s_dogjump5 (mkstate #f SPR_DOG_W1_1 10 #f #f))

(define s_dogchase1 (mkstate #t SPR_DOG_W1_1 10 T_DogChase #f))
(define s_dogchase1s (mkstate #t SPR_DOG_W1_1 3 #f #f))
(define s_dogchase2 (mkstate #t SPR_DOG_W2_1 8 T_DogChase #f))
(define s_dogchase3 (mkstate #t SPR_DOG_W3_1 10 T_DogChase #f))
(define s_dogchase3s (mkstate #t SPR_DOG_W3_1 3 #f #f))
(define s_dogchase4 (mkstate #t SPR_DOG_W4_1 8 T_DogChase #f))

(define s_dogdie1 (mkstate #f SPR_DOG_DIE_1 15 #f A_DeathScream))
(define s_dogdie2 (mkstate #f SPR_DOG_DIE_2 15 #f #f))
(define s_dogdie3 (mkstate #f SPR_DOG_DIE_3 15 #f #f))
(define s_dogdead (mkstate #f SPR_DOG_DEAD 15 #f #f))

(setf! s_grdstand 'next s_grdstand)

(setf! s_grdpath1 'next s_grdpath1s)
(setf! s_grdpath1s 'next s_grdpath2)
(setf! s_grdpath2 'next s_grdpath3)
(setf! s_grdpath3 'next s_grdpath3s)
(setf! s_grdpath3s 'next s_grdpath4)
(setf! s_grdpath4 'next s_grdpath1)

(setf! s_grdchase1 'next s_grdchase1s)
(setf! s_grdchase1s 'next s_grdchase2)
(setf! s_grdchase2 'next s_grdchase3)
(setf! s_grdchase3 'next s_grdchase3s)
(setf! s_grdchase3s 'next s_grdchase4)
(setf! s_grdchase4 'next s_grdchase1)

(setf! s_grdshoot1 'next s_grdshoot2)
(setf! s_grdshoot2 'next s_grdshoot3)
(setf! s_grdshoot3 'next s_grdchase1)

(setf! s_grdpain 'next s_grdchase1)
(setf! s_grdpain1 'next s_grdchase1)
(setf! s_grddie1 'next s_grddie2)
(setf! s_grddie2 'next s_grddie3)
(setf! s_grddie3 'next s_grddie4)
(setf! s_grddie4 'next s_grddie4)

(setf! s_dogpath1 'next s_dogpath1s)
(setf! s_dogpath1s 'next s_dogpath2)
(setf! s_dogpath2 'next s_dogpath3)
(setf! s_dogpath3 'next s_dogpath3s)
(setf! s_dogpath3s 'next s_dogpath4)
(setf! s_dogpath4 'next s_dogpath1)

(setf! s_dogjump1 'next s_dogjump2)
(setf! s_dogjump2 'next s_dogjump3)
(setf! s_dogjump3 'next s_dogjump4)
(setf! s_dogjump4 'next s_dogjump5)
(setf! s_dogjump5 'next s_dogchase1)

(setf! s_dogchase1 'next s_dogchase1s)
(setf! s_dogchase1s 'next s_dogchase2)
(setf! s_dogchase2 'next s_dogchase3)
(setf! s_dogchase3 'next s_dogchase3s)
(setf! s_dogchase3s 'next s_dogchase4)
(setf! s_dogchase4 'next s_dogchase1)

(setf! s_dogdie1 'next s_dogdie2)
(setf! s_dogdie2 'next s_dogdie3)
(setf! s_dogdie3 'next s_dogdead)
(setf! s_dogdead 'next s_dogdead)

(setf! s_ofcstand 'next s_ofcstand)
(setf! s_ofcpath1 'next s_ofcpath1s)
(setf! s_ofcpath1s 'next s_ofcpath2)
(setf! s_ofcpath2 'next s_ofcpath3)
(setf! s_ofcpath3 'next s_ofcpath3s)
(setf! s_ofcpath3s 'next s_ofcpath4)
(setf! s_ofcpath4 'next s_ofcpath1)
(setf! s_ofcshoot1 'next s_ofcshoot2)
(setf! s_ofcshoot2 'next s_ofcshoot3)
(setf! s_ofcshoot3 'next s_ofcchase1)
(setf! s_ofcchase1 'next s_ofcchase1s)
(setf! s_ofcchase1s 'next s_ofcchase2)
(setf! s_ofcchase2 'next s_ofcchase3)
(setf! s_ofcchase3 'next s_ofcchase3s)
(setf! s_ofcchase3s 'next s_ofcchase4)
(setf! s_ofcchase4 'next s_ofcchase1)
(setf! s_ofcpain 'next s_ofcchase1)
(setf! s_ofcpain1 'next s_ofcchase1)
(setf! s_ofcdie1 'next s_ofcdie2)
(setf! s_ofcdie2 'next s_ofcdie3)
(setf! s_ofcdie3 'next s_ofcdie4)
(setf! s_ofcdie4 'next s_ofcdie5)
(setf! s_ofcdie5 'next s_ofcdie5)

(setf! s_ssstand 'next s_ssstand)
(setf! s_sspath1 'next s_sspath1s)
(setf! s_sspath1s 'next s_sspath2)
(setf! s_sspath2 'next s_sspath3)
(setf! s_sspath3 'next s_sspath3s)
(setf! s_sspath3s 'next s_sspath4)
(setf! s_sspath4 'next s_sspath1)
(setf! s_ssshoot1 'next s_ssshoot2)
(setf! s_ssshoot2 'next s_ssshoot3)
(setf! s_ssshoot3 'next s_ssshoot4)
(setf! s_ssshoot4 'next s_ssshoot5)
(setf! s_ssshoot5 'next s_ssshoot6)
(setf! s_ssshoot6 'next s_ssshoot7)
(setf! s_ssshoot7 'next s_ssshoot8)
(setf! s_ssshoot8 'next s_ssshoot9)
(setf! s_ssshoot9 'next s_sschase1)
(setf! s_sschase1 'next s_sschase1s)
(setf! s_sschase1s 'next s_sschase2)
(setf! s_sschase2 'next s_sschase3)
(setf! s_sschase3 'next s_sschase3s)
(setf! s_sschase3s 'next s_sschase4)
(setf! s_sschase4 'next s_sschase1)
(setf! s_sspain 'next s_sschase1)
(setf! s_sspain1 'next s_sschase1)
(setf! s_ssdie1 'next s_ssdie2)
(setf! s_ssdie2 'next s_ssdie3)
(setf! s_ssdie3 'next s_ssdie4)
(setf! s_ssdie4 'next s_ssdie4)

(setf! s_mutstand 'next s_mutstand)
(setf! s_mutpath1 'next s_mutpath1s)
(setf! s_mutpath1s 'next s_mutpath2)
(setf! s_mutpath2 'next s_mutpath3)
(setf! s_mutpath3 'next s_mutpath3s)
(setf! s_mutpath3s 'next s_mutpath4)
(setf! s_mutpath4 'next s_mutpath1)
(setf! s_mutshoot1 'next s_mutshoot2)
(setf! s_mutshoot2 'next s_mutshoot3)
(setf! s_mutshoot3 'next s_mutshoot4)
(setf! s_mutshoot4 'next s_mutchase1)
(setf! s_mutchase1 'next s_mutchase1s)
(setf! s_mutchase1s 'next s_mutchase2)
(setf! s_mutchase2 'next s_mutchase3)
(setf! s_mutchase3 'next s_mutchase3s)
(setf! s_mutchase3s 'next s_mutchase4)
(setf! s_mutchase4 'next s_mutchase1)
(setf! s_mutpain 'next s_mutchase1)
(setf! s_mutpain1 'next s_mutchase1)
(setf! s_mutdie1 'next s_mutdie2)
(setf! s_mutdie2 'next s_mutdie3)
(setf! s_mutdie3 'next s_mutdie4)
(setf! s_mutdie4 'next s_mutdie5)
(setf! s_mutdie5 'next s_mutdie5)

;;; WL_ACT2.C:175-183, 2058-2200, 2530-2812 — bosses, ghosts, and projectiles

(define SPR_BOSS_SHOOT1 (+ SPR_BOSS_W1 4))
(define SPR_BOSS_DEAD (+ SPR_BOSS_W1 7))
(define SPR_BOSS_DIE1 (+ SPR_BOSS_W1 8))
(define SPR_SCHABB_SHOOT1 (+ SPR_SCHABB_W1 4))
(define SPR_SCHABB_DIE1 (+ SPR_SCHABB_W1 6))
(define SPR_SCHABB_DEAD (+ SPR_SCHABB_W1 9))
(define SPR_HYPO1 (+ SPR_SCHABB_W1 10))
(define SPR_FAKE_SHOOT (+ SPR_FAKE_W1 4))
(define SPR_FIRE1 (+ SPR_FAKE_W1 5))
(define SPR_FIRE2 (+ SPR_FAKE_W1 6))
(define SPR_FAKE_DIE1 (+ SPR_FAKE_W1 7))
(define SPR_FAKE_DEAD (+ SPR_FAKE_W1 12))
(define SPR_MECHA_SHOOT1 (+ SPR_MECHA_W1 4))
(define SPR_MECHA_DEAD (+ SPR_MECHA_W1 7))
(define SPR_MECHA_DIE1 (+ SPR_MECHA_W1 8))
(define SPR_HITLER_SHOOT1 (+ SPR_HITLER_W1 4))
(define SPR_HITLER_DEAD (+ SPR_HITLER_W1 7))
(define SPR_HITLER_DIE1 (+ SPR_HITLER_W1 8))
(define SPR_GIFT_SHOOT1 (+ SPR_GIFT_W1 4))
(define SPR_GIFT_DIE1 (+ SPR_GIFT_W1 6))
(define SPR_GIFT_DEAD (+ SPR_GIFT_W1 9))
(define SPR_GRETEL_SHOOT1 (+ SPR_GRETEL_W1 4))
(define SPR_GRETEL_DEAD (+ SPR_GRETEL_W1 7))
(define SPR_GRETEL_DIE1 (+ SPR_GRETEL_W1 8))
(define SPR_FAT_SHOOT1 (+ SPR_FAT_W1 4))
(define SPR_FAT_DIE1 (+ SPR_FAT_W1 8))
(define SPR_FAT_DEAD (+ SPR_FAT_W1 11))

(define (deathcam-position-open? x y)
  (let ((xl (tileof (- x PLAYERSIZE)))
        (yl (tileof (- y PLAYERSIZE)))
        (xh (tileof (+ x PLAYERSIZE)))
        (yh (tileof (+ y PLAYERSIZE))))
    (let rows ((tile-y yl))
      (if (> tile-y yh)
          #t
          (let columns ((tile-x xl))
            (cond ((> tile-x xh) (rows (+ tile-y 1)))
                  ((solid-at tile-x tile-y) #f)
                  (else (columns (+ tile-x 1)))))))))

;; WL_ACT2.C:3765-3819
(define (A_StartDeathCam index tics)
  (FinishPaletteShifts)
  (VL_WaitVBL 100)
  (if victoryflag
      (set! playstate ex_victorious)
      (begin
        (set! victoryflag #t)
        (set! deathcam-active #t)
        (FizzleFade (fizzle-source 0 0 320 (- 200 STATUSLINES) 127)
                    0 0 320 (- 200 STATUSLINES) 70 #f)
        (Write 0 7 "let's see that again!")
        (VL_WaitVBL 1)
        (IN_UserInput 300)
        (set! player-x killx)
        (set! player-y killy)
        (let* ((dx (- (ref actor-x index) player-x))
               (dy (- player-y (ref actor-y index)))
               (angle (atan2 dy dx))
               (wrapped (if (< angle 0) (+ (* pi 2) angle) angle)))
          (set! player-angle (truncate (* (/ wrapped (* pi 2)) ANGLES))))
        (let position ((dist 81920))
          (let ((x (- (ref actor-x index) (FixedByFrac dist (ref costable player-angle))))
                (y (+ (ref actor-y index) (FixedByFrac dist (ref sintable player-angle)))))
            (if (deathcam-position-open? x y)
                (begin
                  (set! player-x x)
                  (set! player-y y)
                  (set! player-tilex (tileof x))
                  (set! player-tiley (tileof y)))
                (position (+ dist 4096)))))
        (DrawPlayBorder)
        (let ((which (ref actor-class index)))
          (cond ((= which schabbobj) (NewState index s_schabbdeathcam))
                ((= which realhitlerobj) (NewState index s_hitlerdeathcam))
                ((= which giftobj) (NewState index s_giftdeathcam))
                ((= which fatobj) (NewState index s_fatdeathcam)))))))

;; WL_ACT2.C:2996-3026, the walk loop without the door wait the other bosses have.
(define (plain-walk index move select)
  (let loop ((left move))
    (when (> left 0)
      (if (< left (ref actor-distance index))
          (MoveObj index left)
          (let ((rest (- left (ref actor-distance index))))
            (center-on-tile index)
            (select index)
            (unless (= (ref actor-dir index) nodir)
              (loop rest)))))))

;; A boss walks toward the player, dodges when it has a shot, and runs a path when it is close.
(define (boss-walk index tics dodge dist)
  (let ((select (lambda (which)
                  (cond ((< dist 4) (SelectRunDir which))
                        (dodge (SelectDodgeDir which))
                        (else (SelectChaseDir which))))))
    (when (= (ref actor-dir index) nodir)
      (if dodge (SelectDodgeDir index) (SelectChaseDir index)))
    (unless (= (ref actor-dir index) nodir)
      (walk-move index (* (ref actor-speed index) tics) select))))

(define (boss-chase index tics shootstate)
  (let* ((dx (abs (- (ref actor-tilex index) player-tilex)))
         (dy (abs (- (ref actor-tiley index) player-tiley)))
         (dist (if (> dx dy) dx dy))
         (shot (CheckLine index)))
    (if (and shot (< (US_RndT) (arithmetic-shift tics 3)))
        (NewState index shootstate)
        (boss-walk index tics shot dist))))

(define s_rocket (mkstate #t SPR_ROCKET_1 3 T_Projectile A_Smoke))
(define s_smoke1 (mkstate #f SPR_SMOKE_1 3 #f #f))
(define s_smoke2 (mkstate #f (+ SPR_SMOKE_1 1) 3 #f #f))
(define s_smoke3 (mkstate #f (+ SPR_SMOKE_1 2) 3 #f #f))
(define s_smoke4 (mkstate #f (+ SPR_SMOKE_1 3) 3 #f #f))
(define s_boom1 (mkstate #f SPR_BOOM_1 6 #f #f))
(define s_boom2 (mkstate #f (+ SPR_BOOM_1 1) 6 #f #f))
(define s_boom3 (mkstate #f (+ SPR_BOOM_1 2) 6 #f #f))

(setf! s_rocket 'next s_rocket)
(setf! s_smoke1 'next s_smoke2)
(setf! s_smoke2 'next s_smoke3)
(setf! s_smoke3 'next s_smoke4)
(setf! s_boom1 'next s_boom2)
(setf! s_boom2 'next s_boom3)

(define s_needle1 (mkstate #f SPR_HYPO1 6 T_Projectile #f))
(define s_needle2 (mkstate #f (+ SPR_HYPO1 1) 6 T_Projectile #f))
(define s_needle3 (mkstate #f (+ SPR_HYPO1 2) 6 T_Projectile #f))
(define s_needle4 (mkstate #f (+ SPR_HYPO1 3) 6 T_Projectile #f))
(setf! s_needle1 'next s_needle2)
(setf! s_needle2 'next s_needle3)
(setf! s_needle3 'next s_needle4)
(setf! s_needle4 'next s_needle1)

(define s_fire1 (mkstate #f SPR_FIRE1 6 #f T_Projectile))
(define s_fire2 (mkstate #f SPR_FIRE2 6 #f T_Projectile))
(setf! s_fire1 'next s_fire2)
(setf! s_fire2 'next s_fire1)

(define s_blinkychase1 (mkstate #f SPR_BLINKY_W1 10 T_Ghosts #f))
(define s_blinkychase2 (mkstate #f SPR_BLINKY_W2 10 T_Ghosts #f))
(define s_inkychase1 (mkstate #f SPR_INKY_W1 10 T_Ghosts #f))
(define s_inkychase2 (mkstate #f SPR_INKY_W2 10 T_Ghosts #f))
(define s_pinkychase1 (mkstate #f SPR_PINKY_W1 10 T_Ghosts #f))
(define s_pinkychase2 (mkstate #f SPR_PINKY_W2 10 T_Ghosts #f))
(define s_clydechase1 (mkstate #f SPR_CLYDE_W1 10 T_Ghosts #f))
(define s_clydechase2 (mkstate #f SPR_CLYDE_W2 10 T_Ghosts #f))
(setf! s_blinkychase1 'next s_blinkychase2)
(setf! s_blinkychase2 'next s_blinkychase1)
(setf! s_inkychase1 'next s_inkychase2)
(setf! s_inkychase2 'next s_inkychase1)
(setf! s_pinkychase1 'next s_pinkychase2)
(setf! s_pinkychase2 'next s_pinkychase1)
(setf! s_clydechase1 'next s_clydechase2)
(setf! s_clydechase2 'next s_clydechase1)

;; Hans and Gretel share one shape: four walk frames, three shoot frames, three death frames.
(define (make-big-boss base shoot dead die1 chase-think)
  (let ((stand (mkstate #f base 0 T_Stand #f))
        (chase1 (mkstate #f base 10 chase-think #f))
        (chase1s (mkstate #f base 3 #f #f))
        (chase2 (mkstate #f (+ base 1) 8 chase-think #f))
        (chase3 (mkstate #f (+ base 2) 10 chase-think #f))
        (chase3s (mkstate #f (+ base 2) 3 #f #f))
        (chase4 (mkstate #f (+ base 3) 8 chase-think #f))
        (d1 (mkstate #f die1 15 #f A_DeathScream))
        (d2 (mkstate #f (+ die1 1) 15 #f #f))
        (d3 (mkstate #f (+ die1 2) 15 #f #f))
        (d4 (mkstate #f dead 0 #f #f))
        (s1 (mkstate #f shoot 30 #f #f))
        (s2 (mkstate #f (+ shoot 1) 10 #f T_Shoot))
        (s3 (mkstate #f (+ shoot 2) 10 #f T_Shoot))
        (s4 (mkstate #f (+ shoot 1) 10 #f T_Shoot))
        (s5 (mkstate #f (+ shoot 2) 10 #f T_Shoot))
        (s6 (mkstate #f (+ shoot 1) 10 #f T_Shoot))
        (s7 (mkstate #f (+ shoot 2) 10 #f T_Shoot))
        (s8 (mkstate #f shoot 10 #f #f)))
    (setf! stand 'next stand)
    (setf! chase1 'next chase1s)
    (setf! chase1s 'next chase2)
    (setf! chase2 'next chase3)
    (setf! chase3 'next chase3s)
    (setf! chase3s 'next chase4)
    (setf! chase4 'next chase1)
    (setf! d1 'next d2)
    (setf! d2 'next d3)
    (setf! d3 'next d4)
    (setf! d4 'next d4)
    (setf! s1 'next s2)
    (setf! s2 'next s3)
    (setf! s3 'next s4)
    (setf! s4 'next s5)
    (setf! s5 'next s6)
    (setf! s6 'next s7)
    (setf! s7 'next s8)
    (setf! s8 'next chase1)
    (list stand chase1 d1 s1)))

(define boss-states (make-big-boss SPR_BOSS_W1 SPR_BOSS_SHOOT1 SPR_BOSS_DEAD SPR_BOSS_DIE1 T_Chase))
(define s_bossstand (car boss-states))
(define s_bosschase1 (cadr boss-states))
(define s_bossdie1 (caddr boss-states))
(define s_bossshoot1 (cadr (cddr boss-states)))

(define gretel-states
  (make-big-boss SPR_GRETEL_W1 SPR_GRETEL_SHOOT1 SPR_GRETEL_DEAD SPR_GRETEL_DIE1 T_Chase))
(define s_gretelstand (car gretel-states))
(define s_gretelchase1 (cadr gretel-states))
(define s_greteldie1 (caddr gretel-states))
(define s_gretelshoot1 (cadr (cddr gretel-states)))

;; Schabbs, Giftmacher, and Fat Face share the two-frame throw and the six-step death.
(define (make-throw-boss base shoot die1 dead chase-think throw)
  (let ((stand (mkstate #f base 0 T_Stand #f))
        (chase1 (mkstate #f base 10 chase-think #f))
        (chase1s (mkstate #f base 3 #f #f))
        (chase2 (mkstate #f (+ base 1) 8 chase-think #f))
        (chase3 (mkstate #f (+ base 2) 10 chase-think #f))
        (chase3s (mkstate #f (+ base 2) 3 #f #f))
        (chase4 (mkstate #f (+ base 3) 8 chase-think #f))
        (cam (mkstate #f base 1 #f #f))
        (d1 (mkstate #f base 10 #f A_DeathScream))
        (d2 (mkstate #f base 10 #f #f))
        (d3 (mkstate #f die1 10 #f #f))
        (d4 (mkstate #f (+ die1 1) 10 #f #f))
        (d5 (mkstate #f (+ die1 2) 10 #f #f))
        (d6 (mkstate #f dead 20 #f A_StartDeathCam))
        (s1 (mkstate #f shoot 30 #f #f))
        (s2 (mkstate #f (+ shoot 1) 10 #f throw)))
    (setf! stand 'next stand)
    (setf! chase1 'next chase1s)
    (setf! chase1s 'next chase2)
    (setf! chase2 'next chase3)
    (setf! chase3 'next chase3s)
    (setf! chase3s 'next chase4)
    (setf! chase4 'next chase1)
    (setf! cam 'next d1)
    (setf! d1 'next d2)
    (setf! d2 'next d3)
    (setf! d3 'next d4)
    (setf! d4 'next d5)
    (setf! d5 'next d6)
    (setf! d6 'next d6)
    (setf! s1 'next s2)
    (setf! s2 'next chase1)
    (list stand chase1 d1 s1 cam s2)))

(define schabb-states
  (make-throw-boss SPR_SCHABB_W1 SPR_SCHABB_SHOOT1 SPR_SCHABB_DIE1 SPR_SCHABB_DEAD
                   T_Schabb T_SchabbThrow))
(define s_schabbstand (car schabb-states))
(define s_schabbchase1 (cadr schabb-states))
(define s_schabbdie1 (caddr schabb-states))
(define s_schabbshoot1 (cadr (cddr schabb-states)))
(define s_schabbdeathcam (caddr (cddr schabb-states)))

(define gift-states
  (make-throw-boss SPR_GIFT_W1 SPR_GIFT_SHOOT1 SPR_GIFT_DIE1 SPR_GIFT_DEAD T_Gift T_GiftThrow))
(define s_giftstand (car gift-states))
(define s_giftchase1 (cadr gift-states))
(define s_giftdie1 (caddr gift-states))
(define s_giftshoot1 (cadr (cddr gift-states)))
(define s_giftdeathcam (caddr (cddr gift-states)))

;; Fat Face throws once, then fires four shots (WL_ACT2.C:2196-2201).
(define fat-states
  (make-throw-boss SPR_FAT_W1 SPR_FAT_SHOOT1 SPR_FAT_DIE1 SPR_FAT_DEAD T_Fat T_GiftThrow))
(define s_fatstand (car fat-states))
(define s_fatchase1 (cadr fat-states))
(define s_fatdie1 (caddr fat-states))
(define s_fatshoot1 (cadr (cddr fat-states)))
(define s_fatdeathcam (caddr (cddr fat-states)))
(define s_fatshoot2 (car (cddr (cddr fat-states))))
(define s_fatshoot3 (mkstate #f (+ SPR_FAT_SHOOT1 2) 10 #f T_Shoot))
(define s_fatshoot4 (mkstate #f (+ SPR_FAT_SHOOT1 3) 10 #f T_Shoot))
(define s_fatshoot5 (mkstate #f (+ SPR_FAT_SHOOT1 2) 10 #f T_Shoot))
(define s_fatshoot6 (mkstate #f (+ SPR_FAT_SHOOT1 3) 10 #f T_Shoot))
(setf! s_fatshoot2 'next s_fatshoot3)
(setf! s_fatshoot3 'next s_fatshoot4)
(setf! s_fatshoot4 'next s_fatshoot5)
(setf! s_fatshoot5 'next s_fatshoot6)
(setf! s_fatshoot6 'next s_fatchase1)

(define s_fakestand (mkstate #f SPR_FAKE_W1 0 T_Stand #f))
(define s_fakechase1 (mkstate #f SPR_FAKE_W1 10 T_Fake #f))
(define s_fakechase1s (mkstate #f SPR_FAKE_W1 3 #f #f))
(define s_fakechase2 (mkstate #f (+ SPR_FAKE_W1 1) 8 T_Fake #f))
(define s_fakechase3 (mkstate #f (+ SPR_FAKE_W1 2) 10 T_Fake #f))
(define s_fakechase3s (mkstate #f (+ SPR_FAKE_W1 2) 3 #f #f))
(define s_fakechase4 (mkstate #f (+ SPR_FAKE_W1 3) 8 T_Fake #f))
(define s_fakedie1 (mkstate #f SPR_FAKE_DIE1 10 #f A_DeathScream))
(define s_fakedie2 (mkstate #f (+ SPR_FAKE_DIE1 1) 10 #f #f))
(define s_fakedie3 (mkstate #f (+ SPR_FAKE_DIE1 2) 10 #f #f))
(define s_fakedie4 (mkstate #f (+ SPR_FAKE_DIE1 3) 10 #f #f))
(define s_fakedie5 (mkstate #f (+ SPR_FAKE_DIE1 4) 10 #f #f))
(define s_fakedie6 (mkstate #f SPR_FAKE_DEAD 0 #f #f))
(define s_fakeshoot1 (mkstate #f SPR_FAKE_SHOOT 8 #f T_FakeFire))
(define s_fakeshoot2 (mkstate #f SPR_FAKE_SHOOT 8 #f T_FakeFire))
(define s_fakeshoot3 (mkstate #f SPR_FAKE_SHOOT 8 #f T_FakeFire))
(define s_fakeshoot4 (mkstate #f SPR_FAKE_SHOOT 8 #f T_FakeFire))
(define s_fakeshoot5 (mkstate #f SPR_FAKE_SHOOT 8 #f T_FakeFire))
(define s_fakeshoot6 (mkstate #f SPR_FAKE_SHOOT 8 #f T_FakeFire))
(define s_fakeshoot7 (mkstate #f SPR_FAKE_SHOOT 8 #f T_FakeFire))
(define s_fakeshoot8 (mkstate #f SPR_FAKE_SHOOT 8 #f T_FakeFire))
(define s_fakeshoot9 (mkstate #f SPR_FAKE_SHOOT 8 #f #f))
(setf! s_fakestand 'next s_fakestand)
(setf! s_fakechase1 'next s_fakechase1s)
(setf! s_fakechase1s 'next s_fakechase2)
(setf! s_fakechase2 'next s_fakechase3)
(setf! s_fakechase3 'next s_fakechase3s)
(setf! s_fakechase3s 'next s_fakechase4)
(setf! s_fakechase4 'next s_fakechase1)
(setf! s_fakedie1 'next s_fakedie2)
(setf! s_fakedie2 'next s_fakedie3)
(setf! s_fakedie3 'next s_fakedie4)
(setf! s_fakedie4 'next s_fakedie5)
(setf! s_fakedie5 'next s_fakedie6)
(setf! s_fakedie6 'next s_fakedie6)
(setf! s_fakeshoot1 'next s_fakeshoot2)
(setf! s_fakeshoot2 'next s_fakeshoot3)
(setf! s_fakeshoot3 'next s_fakeshoot4)
(setf! s_fakeshoot4 'next s_fakeshoot5)
(setf! s_fakeshoot5 'next s_fakeshoot6)
(setf! s_fakeshoot6 'next s_fakeshoot7)
(setf! s_fakeshoot7 'next s_fakeshoot8)
(setf! s_fakeshoot8 'next s_fakeshoot9)
(setf! s_fakeshoot9 'next s_fakechase1)

(define s_mechastand (mkstate #f SPR_MECHA_W1 0 T_Stand #f))
(define s_mechachase1 (mkstate #f SPR_MECHA_W1 10 T_Chase A_MechaSound))
(define s_mechachase1s (mkstate #f SPR_MECHA_W1 6 #f #f))
(define s_mechachase2 (mkstate #f (+ SPR_MECHA_W1 1) 8 T_Chase #f))
(define s_mechachase3 (mkstate #f (+ SPR_MECHA_W1 2) 10 T_Chase A_MechaSound))
(define s_mechachase3s (mkstate #f (+ SPR_MECHA_W1 2) 6 #f #f))
(define s_mechachase4 (mkstate #f (+ SPR_MECHA_W1 3) 8 T_Chase #f))
(define s_mechadie1 (mkstate #f SPR_MECHA_DIE1 10 #f A_DeathScream))
(define s_mechadie2 (mkstate #f (+ SPR_MECHA_DIE1 1) 10 #f #f))
(define s_mechadie3 (mkstate #f (+ SPR_MECHA_DIE1 2) 10 #f A_HitlerMorph))
(define s_mechadie4 (mkstate #f SPR_MECHA_DEAD 0 #f #f))
(define s_mechashoot1 (mkstate #f SPR_MECHA_SHOOT1 30 #f #f))
(define s_mechashoot2 (mkstate #f (+ SPR_MECHA_SHOOT1 1) 10 #f T_Shoot))
(define s_mechashoot3 (mkstate #f (+ SPR_MECHA_SHOOT1 2) 10 #f T_Shoot))
(define s_mechashoot4 (mkstate #f (+ SPR_MECHA_SHOOT1 1) 10 #f T_Shoot))
(define s_mechashoot5 (mkstate #f (+ SPR_MECHA_SHOOT1 2) 10 #f T_Shoot))
(define s_mechashoot6 (mkstate #f (+ SPR_MECHA_SHOOT1 1) 10 #f T_Shoot))
(setf! s_mechastand 'next s_mechastand)
(setf! s_mechachase1 'next s_mechachase1s)
(setf! s_mechachase1s 'next s_mechachase2)
(setf! s_mechachase2 'next s_mechachase3)
(setf! s_mechachase3 'next s_mechachase3s)
(setf! s_mechachase3s 'next s_mechachase4)
(setf! s_mechachase4 'next s_mechachase1)
(setf! s_mechadie1 'next s_mechadie2)
(setf! s_mechadie2 'next s_mechadie3)
(setf! s_mechadie3 'next s_mechadie4)
(setf! s_mechadie4 'next s_mechadie4)
(setf! s_mechashoot1 'next s_mechashoot2)
(setf! s_mechashoot2 'next s_mechashoot3)
(setf! s_mechashoot3 'next s_mechashoot4)
(setf! s_mechashoot4 'next s_mechashoot5)
(setf! s_mechashoot5 'next s_mechashoot6)
(setf! s_mechashoot6 'next s_mechachase1)

(define s_hitlerchase1 (mkstate #f SPR_HITLER_W1 6 T_Chase #f))
(define s_hitlerchase1s (mkstate #f SPR_HITLER_W1 4 #f #f))
(define s_hitlerchase2 (mkstate #f (+ SPR_HITLER_W1 1) 2 T_Chase #f))
(define s_hitlerchase3 (mkstate #f (+ SPR_HITLER_W1 2) 6 T_Chase #f))
(define s_hitlerchase3s (mkstate #f (+ SPR_HITLER_W1 2) 4 #f #f))
(define s_hitlerchase4 (mkstate #f (+ SPR_HITLER_W1 3) 2 T_Chase #f))
(define s_hitlerdeathcam (mkstate #f SPR_HITLER_W1 10 #f #f))
(define s_hitlerdie1 (mkstate #f SPR_HITLER_W1 1 #f A_DeathScream))
(define s_hitlerdie2 (mkstate #f SPR_HITLER_W1 10 #f #f))
(define s_hitlerdie3 (mkstate #f SPR_HITLER_DIE1 10 #f A_Slurpie))
(define s_hitlerdie4 (mkstate #f (+ SPR_HITLER_DIE1 1) 10 #f #f))
(define s_hitlerdie5 (mkstate #f (+ SPR_HITLER_DIE1 2) 10 #f #f))
(define s_hitlerdie6 (mkstate #f (+ SPR_HITLER_DIE1 3) 10 #f #f))
(define s_hitlerdie7 (mkstate #f (+ SPR_HITLER_DIE1 4) 10 #f #f))
(define s_hitlerdie8 (mkstate #f (+ SPR_HITLER_DIE1 5) 10 #f #f))
(define s_hitlerdie9 (mkstate #f (+ SPR_HITLER_DIE1 6) 10 #f #f))
(define s_hitlerdie10 (mkstate #f SPR_HITLER_DEAD 20 #f A_StartDeathCam))
(define s_hitlershoot1 (mkstate #f SPR_HITLER_SHOOT1 30 #f #f))
(define s_hitlershoot2 (mkstate #f (+ SPR_HITLER_SHOOT1 1) 10 #f T_Shoot))
(define s_hitlershoot3 (mkstate #f (+ SPR_HITLER_SHOOT1 2) 10 #f T_Shoot))
(define s_hitlershoot4 (mkstate #f (+ SPR_HITLER_SHOOT1 1) 10 #f T_Shoot))
(define s_hitlershoot5 (mkstate #f (+ SPR_HITLER_SHOOT1 2) 10 #f T_Shoot))
(define s_hitlershoot6 (mkstate #f (+ SPR_HITLER_SHOOT1 1) 10 #f T_Shoot))
(setf! s_hitlerchase1 'next s_hitlerchase1s)
(setf! s_hitlerchase1s 'next s_hitlerchase2)
(setf! s_hitlerchase2 'next s_hitlerchase3)
(setf! s_hitlerchase3 'next s_hitlerchase3s)
(setf! s_hitlerchase3s 'next s_hitlerchase4)
(setf! s_hitlerchase4 'next s_hitlerchase1)
(setf! s_hitlerdeathcam 'next s_hitlerdie1)
(setf! s_hitlerdie1 'next s_hitlerdie2)
(setf! s_hitlerdie2 'next s_hitlerdie3)
(setf! s_hitlerdie3 'next s_hitlerdie4)
(setf! s_hitlerdie4 'next s_hitlerdie5)
(setf! s_hitlerdie5 'next s_hitlerdie6)
(setf! s_hitlerdie6 'next s_hitlerdie7)
(setf! s_hitlerdie7 'next s_hitlerdie8)
(setf! s_hitlerdie8 'next s_hitlerdie9)
(setf! s_hitlerdie9 'next s_hitlerdie10)
(setf! s_hitlerdie10 'next s_hitlerdie10)
(setf! s_hitlershoot1 'next s_hitlershoot2)
(setf! s_hitlershoot2 'next s_hitlershoot3)
(setf! s_hitlershoot3 'next s_hitlershoot4)
(setf! s_hitlershoot4 'next s_hitlershoot5)
(setf! s_hitlershoot5 'next s_hitlershoot6)
(setf! s_hitlershoot6 'next s_hitlerchase1)

;;; WL_ACT2.C:3576-3716 — BJ's run to the exit

(define BJRUNSPEED 2048)
(define BJJUMPSPEED 680)

(define SPR_BJ_W1 408)
(define SPR_BJ_W2 409)
(define SPR_BJ_W3 410)
(define SPR_BJ_W4 411)
(define SPR_BJ_JUMP1 412)
(define SPR_BJ_JUMP2 413)
(define SPR_BJ_JUMP3 414)
(define SPR_BJ_JUMP4 415)

(define (T_BJRun index tics)
  (let loop ((move (* BJRUNSPEED tics)))
    (when (> move 0)
      (if (< move (ref actor-distance index))
          (MoveObj index move)
          (let ((rest (- move (ref actor-distance index))))
            (center-on-tile index)
            (SelectPathDir index)
            (setf! actor-temp1 index (- (ref actor-temp1 index) 1))
            (if (= (ref actor-temp1 index) 0)
                (NewState index s_bjjump1)
                (loop rest)))))))

(define (T_BJJump index tics)
  (MoveObj index (* BJJUMPSPEED tics)))

(define (T_BJYell index tics)
  (PlaySoundLocActor YEAHSND index))

(define (T_BJDone index tics)
  (set! playstate ex_victorious))

(define s_bjrun1 (mkstate #f SPR_BJ_W1 12 T_BJRun #f))
(define s_bjrun1s (mkstate #f SPR_BJ_W1 3 #f #f))
(define s_bjrun2 (mkstate #f SPR_BJ_W2 8 T_BJRun #f))
(define s_bjrun3 (mkstate #f SPR_BJ_W3 12 T_BJRun #f))
(define s_bjrun3s (mkstate #f SPR_BJ_W3 3 #f #f))
(define s_bjrun4 (mkstate #f SPR_BJ_W4 8 T_BJRun #f))

(define s_bjjump1 (mkstate #f SPR_BJ_JUMP1 14 T_BJJump #f))
(define s_bjjump2 (mkstate #f SPR_BJ_JUMP2 14 T_BJJump T_BJYell))
(define s_bjjump3 (mkstate #f SPR_BJ_JUMP3 14 T_BJJump #f))
(define s_bjjump4 (mkstate #f SPR_BJ_JUMP4 300 #f T_BJDone))

(setf! s_bjrun1 'next s_bjrun1s)
(setf! s_bjrun1s 'next s_bjrun2)
(setf! s_bjrun2 'next s_bjrun3)
(setf! s_bjrun3 'next s_bjrun3s)
(setf! s_bjrun3s 'next s_bjrun4)
(setf! s_bjrun4 'next s_bjrun1)
(setf! s_bjjump1 'next s_bjjump2)
(setf! s_bjjump2 'next s_bjjump3)
(setf! s_bjjump3 'next s_bjjump4)
(setf! s_bjjump4 'next s_bjjump4)

;; WL_STATE.C:1500-1620
(define (kill-reward index tilex tiley)
  (let ((which (ref actor-class index)))
    (cond
      ((= which guardobj)
       (GivePoints 100) (NewState index s_grddie1) (PlaceItemType bo_clip2 tilex tiley))
      ((= which (class-of en_officer))
       (GivePoints 400) (NewState index s_ofcdie1) (PlaceItemType bo_clip2 tilex tiley))
      ((= which mutantobj)
       (GivePoints 700) (NewState index s_mutdie1) (PlaceItemType bo_clip2 tilex tiley))
      ((= which (class-of en_ss))
       (GivePoints 500)
       (NewState index s_ssdie1)
       (if (< bestweapon wp_machinegun)
           (PlaceItemType bo_machinegun tilex tiley)
           (PlaceItemType bo_clip2 tilex tiley)))
      ((= which (class-of en_dog))
       (GivePoints 200) (NewState index s_dogdie1))
      ((= which bossobj)
       (GivePoints 5000) (NewState index s_bossdie1) (PlaceItemType bo_key1 tilex tiley))
      ((= which gretelobj)
       (GivePoints 5000) (NewState index s_greteldie1) (PlaceItemType bo_key1 tilex tiley))
      ((= which giftobj)
       (GivePoints 5000) (set! killx player-x) (set! killy player-y)
       (NewState index s_giftdie1))
      ((= which fatobj)
       (GivePoints 5000) (set! killx player-x) (set! killy player-y)
       (NewState index s_fatdie1))
      ((= which schabbobj)
       (GivePoints 5000) (set! killx player-x) (set! killy player-y)
       (NewState index s_schabbdie1) (A_DeathScream index 0))
      ((= which fakeobj)
       (GivePoints 2000) (NewState index s_fakedie1))
      ((= which mechahitlerobj)
       (GivePoints 5000) (NewState index s_mechadie1))
      ((= which realhitlerobj)
       (GivePoints 5000) (set! killx player-x) (set! killy player-y)
       (NewState index s_hitlerdie1) (A_DeathScream index 0)))))

(define (KillActor index)
  (let ((tilex (tileof (ref actor-x index)))
        (tiley (tileof (ref actor-y index))))
    (setf! actor-tilex index tilex)
    (setf! actor-tiley index tiley)
    (kill-reward index tilex tiley)
    (set! killcount (+ killcount 1))
    (setf! actor-flags index (bitwise-and (ref actor-flags index) (- 255 FL_SHOOTABLE)))
    (actorat-set! (ref actor-tilex index) (ref actor-tiley index) -1)
    (setf! actor-flags index (bitwise-ior (ref actor-flags index) FL_NONMARK))))

;; WL_STATE.C:1625-1690. Only the four rank-and-file classes have a pain frame.
(define (pain-state which hitpoints)
  (let ((odd (> (bitwise-and hitpoints 1) 0)))
    (cond ((= which guardobj) (if odd s_grdpain s_grdpain1))
          ((= which (class-of en_officer)) (if odd s_ofcpain s_ofcpain1))
          ((= which mutantobj) (if odd s_mutpain s_mutpain1))
          ((= which (class-of en_ss)) (if odd s_sspain s_sspain1))
          (else #f))))

(define (DamageActor index damage)
  (set! madenoise #t)
  (let ((attacking (> (bitwise-and (ref actor-flags index) FL_ATTACKMODE) 0)))
    (setf! actor-hitpoints index
           (- (ref actor-hitpoints index) (if attacking damage (arithmetic-shift damage 1))))
    (if (<= (ref actor-hitpoints index) 0)
        (KillActor index)
        (begin
          (unless attacking
            (FirstSighting index))
          (let ((state (pain-state (ref actor-class index) (ref actor-hitpoints index))))
            (when state
              (NewState index state)))))))

(define (run-think index tics)
  (when (ref actor-state index)
    (let ((think (ref (ref actor-state index) 'think)))
      (when think
        (think index tics)))))

;; C's end-of-state action reads the global `tics`, so it gets the same value the think does.
(define (advance-states index tics)
  (let loop ()
    (when (and (ref actor-state index) (<= (ref actor-ticcount index) 0))
      (let ((action (ref (ref actor-state index) 'action)))
        (when action
          (action index tics)))
      (when (ref actor-state index)
        (let ((next (ref (ref actor-state index) 'next)))
          (if next
              (begin
                (setf! actor-state index next)
                (if (= (ref next 'tictime) 0)
                    (setf! actor-ticcount index 0)
                    (begin
                      (setf! actor-ticcount index
                             (+ (ref actor-ticcount index) (ref next 'tictime)))
                      (loop))))
              (RemoveObj index)))))))

(define (mark-actor index)
  (let ((flags (ref actor-flags index))
        (tilex (ref actor-tilex index))
        (tiley (ref actor-tiley index)))
    (when (= 0 (bitwise-and flags FL_NEVERMARK))
      (unless (and (> (bitwise-and flags FL_NONMARK) 0) (>= (actorat-at tilex tiley) 0))
        (actorat-set! tilex tiley index)))))

(define (DoActor index tics)
  (when (and (ref actor-state index)
             (or (ref actor-active index)
                 (areabyplayer-at (ref actor-areanumber index))))
    (when (= 0 (bitwise-and (ref actor-flags index) (bitwise-ior FL_NONMARK FL_NEVERMARK)))
      (actorat-set! (ref actor-tilex index) (ref actor-tiley index) -1))
    (unless (= (ref actor-ticcount index) 0)
      (setf! actor-ticcount index (- (ref actor-ticcount index) tics))
      (advance-states index tics))
    (run-think index tics)
    (when (ref actor-state index)
      (mark-actor index))))

(define (MoveActors tics)
  (ConnectAreas)
  (let loop ((index 0))
    (when (< index actorcount)
      (DoActor index tics)
      (loop (+ index 1)))))

;;; WL_PLAY.C:1054-1236 — palette shifting

(define NUMREDSHIFTS 6)
(define REDSTEPS 8)
(define NUMWHITESHIFTS 3)
(define WHITESTEPS 20)
(define WHITETICS 6)

(define redshifts (make-vector NUMREDSHIFTS 0))
(define whiteshifts (make-vector NUMWHITESHIFTS 0))
(define damagecount 0)
(define bonuscount 0)
(define palshifted #f)

(define (shift-toward shifts count red green blue steps)
  (let shift ((index 1))
    (when (<= index count)
      (let ((work (make-bytevector PALETTEBYTES 0))
            (target (vector red green blue)))
        (let colors ((color 0))
          (when (<= color 255)
            (let channels ((channel 0))
              (when (< channel 3)
                (let* ((slot (+ (* color 3) channel))
                       (base (ref gamepal slot))
                       (delta (- (ref target channel) base)))
                  (setf! work slot (+ base (truncate (/ (* delta index) steps)))))
                (channels (+ channel 1))))
            (colors (+ color 1))))
        (setf! shifts (- index 1) work))
      (shift (+ index 1)))))

(define (InitRedShifts)
  (shift-toward redshifts NUMREDSHIFTS 64 0 0 REDSTEPS)
  (shift-toward whiteshifts NUMWHITESHIFTS 64 62 0 WHITESTEPS))

(define (ClearPaletteShifts)
  (set! bonuscount 0)
  (set! damagecount 0))

(define (StartBonusFlash)
  (set! bonuscount (* NUMWHITESHIFTS WHITETICS)))

(define (StartDamageFlash damage)
  (set! damagecount (+ damagecount damage)))

(define (UpdatePaletteShifts)
  (let ((white (if (= bonuscount 0)
                   0
                   (let ((shade (min (+ (truncate (/ bonuscount WHITETICS)) 1) NUMWHITESHIFTS)))
                     (set! bonuscount (max (- bonuscount tics) 0))
                     shade)))
        (red (if (= damagecount 0)
                 0
                 (let ((shade (min (+ (truncate (/ damagecount 10)) 1) NUMREDSHIFTS)))
                   (set! damagecount (max (- damagecount tics) 0))
                   shade))))
    (cond ((> red 0)
           (VL_SetPalette (ref redshifts (- red 1)))
           (set! palshifted #t))
          ((> white 0)
           (VL_SetPalette (ref whiteshifts (- white 1)))
           (set! palshifted #t))
          (palshifted
           (VL_SetPalette gamepal)
           (set! palshifted #f)))))

(define (FinishPaletteShifts)
  (when palshifted
    (set! palshifted #f)
    (VL_SetPalette gamepal)))

(define NUMBUTTONS 8)
(define bt_attack 0)
(define bt_strafe 1)
(define bt_run 2)
(define bt_use 3)
(define bt_readyknife 4)
(define bt_readypistol 5)
(define bt_readymachinegun 6)
(define bt_readychaingun 7)
(define bt_nobutton -1)

(define dirscan (vector sc_UpArrow sc_RightArrow sc_DownArrow sc_LeftArrow))
(define buttonscan (vector sc_Control sc_Alt sc_RShift sc_Space 2 3 4 5))
(define buttonmouse (vector bt_attack bt_strafe bt_use bt_nobutton))
(define buttonjoy (vector bt_attack bt_strafe bt_use bt_run))

(define buttonstate (make-vector NUMBUTTONS #f))
(define buttonheld (make-vector NUMBUTTONS #f))
(define controlx 0)
(define controly 0)
(define tics 1)
(define control-input #f)
(define demoplayback #f)
(define demorecord #f)
(define demo-buffer #f)
(define demo-pointer 0)
(define demo-end 0)
(define demo-lasttimecount 0)
(define DEMOTICS 4)

(define (demo-byte value)
  (if (> value 127) (- value 256) value))

(define (demo-buttons)
  (let loop ((button (- NUMBUTTONS 1)) (bits 0))
    (if (< button 0)
        bits
        (loop (- button 1) (+ (* bits 2) (if (ref buttonstate button) 1 0))))))

(define (demo-play-controls)
  (let ((bits (ref demo-buffer demo-pointer)))
    (let buttons ((button 0) (remaining bits))
      (when (< button NUMBUTTONS)
        (setf! buttonstate button (= (bitwise-and remaining 1) 1))
        (buttons (+ button 1) (arithmetic-shift remaining -1))))
    (set! controlx (* (demo-byte (ref demo-buffer (+ demo-pointer 1))) tics))
    (set! controly (* (demo-byte (ref demo-buffer (+ demo-pointer 2))) tics))
    (set! demo-pointer (+ demo-pointer 3))
    (when (= demo-pointer demo-end)
      (set! playstate ex_completed))))

(define (demo-record-controls)
  (let ((x (truncate (/ controlx tics)))
        (y (truncate (/ controly tics))))
    (setf! demo-buffer demo-pointer (demo-buttons))
    (setf! demo-buffer (+ demo-pointer 1) (bitwise-and x 255))
    (setf! demo-buffer (+ demo-pointer 2) (bitwise-and y 255))
    (set! demo-pointer (+ demo-pointer 3))
    (when (>= demo-pointer demo-end)
      (Quit "Demo buffer overflowed!"))))

(define (PollKeyboardButtons)
  (let buttons ((button 0))
    (when (< button NUMBUTTONS)
      (when (ref Keyboard (ref buttonscan button))
        (setf! buttonstate button #t))
      (buttons (+ button 1)))))

(define (PollKeyboardMove)
  (let ((step (* (if (ref buttonstate bt_run) 70 35) tics)))
    (when (ref Keyboard (ref dirscan 0)) (set! controly (- controly step)))
    (when (ref Keyboard (ref dirscan 2)) (set! controly (+ controly step)))
    (when (ref Keyboard (ref dirscan 3)) (set! controlx (- controlx step)))
    (when (ref Keyboard (ref dirscan 1)) (set! controlx (+ controlx step)))))

(define (PollKeyboardControls)
  (PollKeyboardButtons)
  (PollKeyboardMove))

(define (InitActorList)
  (set! actorcount 0)
  (set! killcount 0)
  (set! killtotal 0)
  (actorat-clear))

(define (GetNewActor)
  (let scan ((index 0))
    (cond ((= index actorcount)
           (when (>= actorcount MAXACTORS)
             (Quit "GetNewActor: No free spots in objlist!"))
           (set! actorcount (+ actorcount 1))
           (set! new index))
          ((ref actor-state index) (scan (+ index 1)))
          (else (set! new index))))
  (setf! actor-tilex new 0)
  (setf! actor-tiley new 0)
  (setf! actor-x new 0)
  (setf! actor-y new 0)
  (setf! actor-dir new 0)
  (setf! actor-class new 0)
  (setf! actor-state new #f)
  (setf! actor-ticcount new 0)
  (setf! actor-speed new 0)
  (setf! actor-flags new 0)
  (setf! actor-distance new 0)
  (setf! actor-areanumber new 0)
  (setf! actor-temp1 new 0)
  (setf! actor-temp2 new 0)
  (setf! actor-active new #f)
  (setf! actor-hitpoints new 0)
  (setf! actor-viewx new 0)
  (setf! actor-transx new 0)
  (setf! actor-transy new 0)
  (setf! actor-angle new 0)
  (setf! actor-order new next-actor-order)
  (set! next-actor-order (+ next-actor-order 1))
  new)

(define (RemoveObj index)
  (setf! actor-state index #f))

(define (CenterWindow width height)
  (FixOfs)
  (US_CenterWindow width height))

;; WL_PLAY.C:303. The graphical port has no joystick device to poll.
(define (PollJoystickButtons)
  #f)

;; WL_PLAY.C:398. The graphical runtime has no joystick axis source.
(define (PollJoystickMove)
  #f)

(define (PollMouseButtons)
  (let loop ((index 0) (names (list 'left 'right 'middle)))
    (when (< index 3)
      (let ((button (ref buttonmouse index)))
        (when (and (>= button 0) (dos:mouse-button-down? (car names)))
          (setf! buttonstate button #t)))
      (loop (+ index 1) (cdr names)))))

(define (PollMouseMove)
  (set! controlx (+ controlx
                    (truncate (/ (* (dos:get-mouse-motion-x) 10) (- 13 mouseadjustment)))))
  (set! controly (+ controly
                    (truncate (/ (* (dos:get-mouse-motion-y) 20) (- 13 mouseadjustment))))))

(define (wait-demo-tics)
  (let wait ()
    (when (< TimeCount (+ demo-lasttimecount DEMOTICS))
      (when (IN_Yield)
        (wait))))
  (set! TimeCount (+ demo-lasttimecount DEMOTICS))
  (set! demo-lasttimecount (+ demo-lasttimecount DEMOTICS))
  (set! tics DEMOTICS))

(define (PollControls)
  (set! controlx 0)
  (set! controly 0)
  (let loop ((button 0))
    (when (< button NUMBUTTONS)
      (setf! buttonheld button (ref buttonstate button))
      (setf! buttonstate button #f)
      (loop (+ button 1))))
  (if demoplayback
      (begin
        (wait-demo-tics)
        (demo-play-controls))
      (begin
        (if demorecord
            (wait-demo-tics)
            (CalcTics))
        (PollKeyboardControls)
        (when control-input
          (control-input))
        (when mouseenabled
          (PollMouseButtons)
          (PollMouseMove))
        (let ((limit (* 100 tics)))
          (when (> controlx limit) (set! controlx limit))
          (when (< controlx (- limit)) (set! controlx (- limit)))
          (when (> controly limit) (set! controly limit))
          (when (< controly (- limit)) (set! controly (- limit))))
        (when demorecord
          (demo-record-controls)))))

;; GFXV_WL6.H:143
(define PAUSEDPIC 133)

;; WL_PLAY.C:613-833.
(define (CheckKeys)
  (unless (or screenfaded demoplayback)
    (when (and (ref Keyboard sc_M) (ref Keyboard sc_L) (ref Keyboard sc_I))
      (set! health 100)
      (set! ammo 99)
      (set! keys 3)
      (set! score 0)
      (set! TimeCount (+ TimeCount 42000))
      (GiveWeapon wp_chaingun)
      (DrawHealth)
      (DrawKeys)
      (DrawAmmo)
      (DrawScore)
      (ClearMemory)
      (Message (string-append
                "You now have 100% Health,\n"
                "99 Ammo and both Keys!\n\n"
                "Note that you have basically\n"
                "eliminated your chances of\n"
                "getting a high score!"))
      (IN_ClearKeysDown)
      (IN_Ack)
      (DrawAllPlayBorder))
    (when (and (ref Keyboard sc_BackSpace) (ref Keyboard sc_LShift) (ref Keyboard sc_Alt)
               (MS_CheckParm "goobers"))
      (ClearMemory)
      (Message "Debugging keys are\nnow available!")
      (IN_ClearKeysDown)
      (IN_Ack)
      (DrawAllPlayBorderSides)
      (set! DebugOk #t))
    (when (and (ref Keyboard sc_B) (ref Keyboard sc_A) (ref Keyboard sc_T))
      (ClearMemory)
      (Message (string-append
                "Commander Keen is also\n"
                "available from Apogee, but\n"
                "then, you already know\n"
                "that - right, Cheatmeister?!"))
      (IN_ClearKeysDown)
      (IN_Ack)
      (DrawAllPlayBorder))
    (if Paused
        (begin
          (VWB_DrawPic 128 64 PAUSEDPIC)
          (SD_MusicOff)
          (IN_Ack)
          (IN_ClearKeysDown)
          (SD_MusicOn)
          (set! Paused #f))
        (let ((scan LastScan))
          (if (or (and (>= scan sc_F1) (<= scan sc_F10)) (= scan sc_Escape))
              (begin
                (set! LastScan sc_None)
                (set! ingame #t)
                (StopMusic)
                (US_ControlPanel scan)
                (DrawPlayScreen)
                (cond (loadedgame (set! playstate ex_loadedgame))
                      (startgame (set! playstate ex_resetgame))
                      (else (StartMusic))))
              (when (and (ref Keyboard sc_Tab) DebugOk)
                (CA_CacheGrChunk STARTFONT)
                (set! fontnumber 0)
                (set! fontcolor 0)
                (DebugKeys)))))))

(define (PlayLoop)
  (PollControls)
  (set! madenoise #f)
  (MoveDoors tics)
  (MovePWalls tics)
  (if player-attacking
      (T_Attack controlx controly tics)
      (T_Player controlx controly tics))
  (MoveActors tics)
  (UpdatePaletteShifts)
  (ThreeDRefresh)
  (SD_Poll)
  (UpdateSoundLoc)
  (when screenfaded
    (VL_FadeIn 0 255 gamepal 30))
  (CheckKeys)
  (unless (= playstate ex_stillplaying)
    (unless (= playstate ex_died)
      (FinishPaletteShifts))))
