;;; WL_TEXT.C — article layout and text screens

(define BACKCOLOR 17)
(define FONTHEIGHT 10)
(define TOPMARGIN 16)
(define BOTTOMMARGIN 32)
(define LEFTMARGIN 16)
(define RIGHTMARGIN 16)
(define PICMARGIN 8)
(define SPACEWIDTH 7)
(define SCREENPIXWIDTH 320)
(define SCREENMID 160)
(define TEXTROWS 15)
(define WORDLIMIT 80)

(define H_TOPWINDOWPIC 6)
(define H_LEFTWINDOWPIC 7)
(define H_RIGHTWINDOWPIC 8)
(define H_BOTTOMINFOPIC 9)
(define T_HELPART 138)
(define T_ENDART1 143)

(define text 0)
(define textpos 0)
(define pagenum 0)
(define numpages 0)
(define rowon 0)
(define layoutdone #f)
(define picx 0)
(define picy 0)
(define picnum 0)
(define leftmargin (make-vector TEXTROWS 0))
(define rightmargin (make-vector TEXTROWS 0))

(define (textbyte offset)
  (if (and (>= offset 0) (< offset (bytevector-length text)))
      (ref text offset)
      (Quit "Article layout command exceeds cached text")))

(define (text-char) (textbyte textpos))

(define (RipToEOL)
  (let loop ()
    (let ((ch (text-char)))
      (set! textpos (+ textpos 1))
      (unless (= ch 10)
        (loop)))))

(define (digit? ch) (and (>= ch 48) (<= ch 57)))

(define (ParseNumber)
  (let skip ()
    (unless (digit? (text-char))
      (set! textpos (+ textpos 1))
      (skip)))
  (let take ((value 0))
    (if (digit? (text-char))
        (let ((digit (- (text-char) 48)))
          (set! textpos (+ textpos 1))
          (take (+ (* value 10) digit)))
        value)))

(define (ParsePicCommand)
  (set! picy (ParseNumber))
  (set! picx (ParseNumber))
  (set! picnum (ParseNumber))
  (RipToEOL))

(define picdelay 0)

(define (ParseTimedCommand)
  (set! picy (ParseNumber))
  (set! picx (ParseNumber))
  (set! picnum (ParseNumber))
  (set! picdelay (ParseNumber))
  (RipToEOL))

(define (TimedPicCommand)
  (ParseTimedCommand)
  (VW_UpdateScreen)
  (set! TimeCount 0)
  (let wait ()
    (when (and (< TimeCount picdelay) (IN_Yield))
      (wait)))
  (VWB_DrawPic (bitwise-and picx 65528) picy picnum))

(define (upcase ch)
  (if (and (>= ch 97) (<= ch 122)) (- ch 32) ch))

(define (hexvalue ch)
  (cond ((digit? ch) (- ch 48))
        ((and (>= ch 65) (<= ch 70)) (+ 10 (- ch 65)))
        (else 0)))

(define (pic-margins)
  (let ((width (ref (ref pictable (- picnum STARTPICS)) 'width))
        (height (ref (ref pictable (- picnum STARTPICS)) 'height)))
    (let ((picmid (+ picx (truncate (/ width 2)))))
      (let ((margin (if (> picmid SCREENMID)
                        (- picx PICMARGIN)
                        (+ picx width PICMARGIN)))
            (top (let ((row (truncate (/ (- picy TOPMARGIN) FONTHEIGHT))))
                   (if (< row 0) 0 row)))
            (bottom (let ((row (truncate (/ (- (+ picy height) TOPMARGIN) FONTHEIGHT))))
                      (if (>= row TEXTROWS) (- TEXTROWS 1) row))))
        (let loop ((row top))
          (when (<= row bottom)
            (if (> picmid SCREENMID)
                (setf! rightmargin row margin)
                (setf! leftmargin row margin))
            (loop (+ row 1))))
        (when (< px (ref leftmargin rowon))
          (set! px (ref leftmargin rowon)))))))

(define (HandleCommand)
  (set! textpos (+ textpos 1))
  (let ((command (upcase (text-char))))
    (cond
      ((= command 66)
       (set! picy (ParseNumber))
       (set! picx (ParseNumber))
       (let ((width (ParseNumber)) (height (ParseNumber)))
         (VWB_Bar picx picy width height BACKCOLOR))
       (RipToEOL))
      ((= command 59) (RipToEOL))
      ((or (= command 80) (= command 69))
       (set! layoutdone #t)
       (set! textpos (- textpos 1)))
      ((= command 67)
       (set! textpos (+ textpos 1))
       (let ((high (hexvalue (upcase (text-char)))))
         (set! textpos (+ textpos 1))
         (set! fontcolor (+ (* high 16) (hexvalue (upcase (text-char))))))
       (set! textpos (+ textpos 1)))
      ((= command 62)
       (set! px 160)
       (set! textpos (+ textpos 1)))
      ((= command 76)
       (set! py (ParseNumber))
       (set! rowon (truncate (/ (- py TOPMARGIN) FONTHEIGHT)))
       (set! py (+ TOPMARGIN (* rowon FONTHEIGHT)))
       (set! px (ParseNumber))
       (RipToEOL))
      ((= command 71)
       (ParsePicCommand)
       (VWB_DrawPic (bitwise-and picx 65528) picy picnum)
       (pic-margins))
      ;; WL_TEXT.C:134-175
      ((= command 84)
       (TimedPicCommand))
      (else (RipToEOL)))))

(define (skip-to-page-break)
  (let loop ()
    (if (= (text-char) 94)
        (let ((next (upcase (textbyte (+ textpos 1)))))
          (unless (or (= next 69) (= next 80))
            (set! textpos (+ textpos 1))
            (loop)))
        (begin
          (set! textpos (+ textpos 1))
          (loop)))))

(define (NewLine)
  (set! rowon (+ rowon 1))
  (if (= rowon TEXTROWS)
      (begin
        (set! layoutdone #t)
        (skip-to-page-break))
      (begin
        (set! px (ref leftmargin rowon))
        (set! py (+ py FONTHEIGHT)))))

(define (HandleCtrls)
  (let ((ch (text-char)))
    (set! textpos (+ textpos 1))
    (when (= ch 10)
      (NewLine))))

(define (next-word)
  (let loop ((word (string (integer->char (text-char)))) (length 1))
    (set! textpos (+ textpos 1))
    (if (> (text-char) 32)
        (begin
          (when (>= length (- WORDLIMIT 1))
            (Quit "PageLayout: Word limit exceeded"))
          (loop (string-append word (string (integer->char (text-char)))) (+ length 1)))
        word)))

(define (HandleWord)
  (let ((word (next-word)))
    (let ((width (car (VW_MeasurePropString word))))
      (let fit ()
        (when (and (> (+ px width) (ref rightmargin rowon)) (not layoutdone))
          (NewLine)
          (fit)))
      (unless layoutdone
        (let ((newpos (+ px width)))
          (VW_DrawPropString word)
          (set! px newpos))
        (let spaces ()
          (when (= (text-char) 32)
            (set! px (+ px SPACEWIDTH))
            (set! textpos (+ textpos 1))
            (spaces)))))))

(define (PageLayout shownumber)
  (let ((oldcolor fontcolor))
    (set! fontcolor 0)
    (VWB_Bar 0 0 320 200 BACKCOLOR)
    (VWB_DrawPic 0 0 H_TOPWINDOWPIC)
    (VWB_DrawPic 0 8 H_LEFTWINDOWPIC)
    (VWB_DrawPic 312 8 H_RIGHTWINDOWPIC)
    (VWB_DrawPic 8 176 H_BOTTOMINFOPIC)
    (let loop ((row 0))
      (when (< row TEXTROWS)
        (setf! leftmargin row LEFTMARGIN)
        (setf! rightmargin row (- SCREENPIXWIDTH RIGHTMARGIN))
        (loop (+ row 1))))
    (set! px LEFTMARGIN)
    (set! py TOPMARGIN)
    (set! rowon 0)
    (set! layoutdone #f)
    (let skip ()
      (when (<= (text-char) 32)
        (set! textpos (+ textpos 1))
        (skip)))
    (unless (and (= (text-char) 94)
                 (= (upcase (textbyte (+ textpos 1))) 80))
      (Quit "PageLayout: Text not headed with ^P"))
    (set! textpos (+ textpos 2))
    (RipToEOL)
    (let loop ()
      (let ((ch (text-char)))
        (cond ((= ch 94) (HandleCommand))
              ((= ch 9) (set! px (bitwise-and (+ px 8) 248)) (set! textpos (+ textpos 1)))
              ((<= ch 32) (HandleCtrls))
              (else (HandleWord))))
      (unless layoutdone
        (loop)))
    (set! pagenum (+ pagenum 1))
    ;; WL_TEXT.C:478-500
    (when shownumber
      (set! py 183)
      (set! px 213)
      (set! fontcolor 79)
      (VW_DrawPropString (string-append "pg " (number->string pagenum)
                                        " of " (number->string numpages))))
    (set! fontcolor oldcolor)))

(define (CacheLayoutGraphics)
  (let ((start textpos) (limit (bytevector-length text)))
    (set! numpages 0)
    (set! pagenum 0)
    (let loop ()
      (when (>= textpos limit)
        (Quit "CacheLayoutGraphics: No ^E to terminate file!"))
      (if (= (text-char) 94)
          (let ((command (upcase (textbyte (+ textpos 1)))))
            (set! textpos (+ textpos 1))
            (cond ((= command 80) (set! numpages (+ numpages 1)) (loop))
                  ((= command 69)
                   (for-each CA_CacheGrChunk
                             (list H_TOPWINDOWPIC H_LEFTWINDOWPIC
                                   H_RIGHTWINDOWPIC H_BOTTOMINFOPIC))
                   (set! textpos start))
                  ((= command 71) (ParsePicCommand) (CA_CacheGrChunk picnum) (loop))
                  ((= command 84) (ParseTimedCommand) (CA_CacheGrChunk picnum) (loop))
                  (else (loop))))
          (begin (set! textpos (+ textpos 1)) (loop))))))

(define (CountPages)
  (CacheLayoutGraphics))

;; WL_TEXT.C:518-527
(define (BackPage)
  (set! pagenum (- pagenum 1))
  (let loop ()
    (set! textpos (- textpos 1))
    (unless (and (= (textbyte textpos) 94)
                 (= (upcase (textbyte (+ textpos 1))) 80))
      (loop))))

;; WL_TEXT.C:599-722. A headless script installs no yield, so the loop ends after the first page.
(define (ShowArticle chunk)
  (let ((oldfont fontnumber))
    (set! text (CA_CacheGrChunk chunk))
    (set! textpos 0)
    (set! fontnumber 0)
    (CA_CacheGrChunk STARTFONT)
    (VWB_Bar 0 0 320 200 BACKCOLOR)
    (CountPages)
    (let page ((newpage #t) (firstpage #t) (running #t))
      (when newpage
        (PageLayout #t)
        (VW_UpdateScreen)
        (when firstpage
          (VL_FadeIn 0 255 gamepal 10)))
      (set! LastScan sc_None)
      (if (not (IN_Yield))
          #f
          (let ((scan LastScan))
            (cond ((= scan sc_Escape)
                   (set! LastScan sc_None)
                   #f)
                  ((or (= scan sc_UpArrow) (= scan sc_PgUp) (= scan sc_LeftArrow))
                   (set! LastScan sc_None)
                   (if (> pagenum 1)
                       (begin (BackPage) (BackPage) (page #t #f running))
                       (page #f #f running)))
                  ((or (= scan sc_Return) (= scan sc_DownArrow)
                       (= scan sc_PgDn) (= scan sc_RightArrow))
                   (set! LastScan sc_None)
                   (page (< pagenum numpages) #f running))
                  (else (page #f firstpage running))))))
    (IN_ClearKeysDown)
    (set! fontnumber oldfont)
    pagenum))

(define (HelpScreens)
  (ShowArticle T_HELPART)
  (VL_FadeOut 0 255 0 0 0 30)
  (FreeMusic))

;; WL_TEXT.C:800-812, one end article per episode
(define (EndText)
  (ClearMemory)
  (ShowArticle (+ T_ENDART1 episode))
  (VL_FadeOut 0 255 0 0 0 30)
  (set! fontcolor 0)
  (set! backcolor 15)
  (IN_ClearKeysDown)
  (INL_GetMouseDelta)
  (FreeMusic))
