;; SPDX-License-Identifier: Apache-2.0
;; Copyright 2011 Google Inc.
;; Havlak loop recognition over a synthetic control-flow graph.

(define UNVISITED 2147483647)
(define MAX-NON-BACK-PREDS (* 32 1024))
(define NONHEADER 1)
(define REDUCIBLE 2)
(define SELF 3)
(define IRREDUCIBLE 4)
(define DEAD 5)

(define block (struct 'block '(name in out)))
(define cfg (struct 'cfg '(blocks start)))
(define loop-data
  (struct 'loop '(id header reducible parent children child-ids blocks nesting depth)))
(define loop-graph (struct 'loop-graph '(root loops)))
(define union-node (struct 'union-node '(parent block number loop)))
(define finder
  (struct 'finder '(cfg loops non-back back number header kind last nodes)))

(define (make-cfg) (cfg (vector) #f))

(define (cfg-node graph name)
  (let ((blocks (ref graph 'blocks)))
    (if (= name (vector-length blocks))
        (let ((value (block name (vector) (vector))))
          (vector-push! blocks value)
          (if (not (ref graph 'start)) (setf! graph 'start value))
          value)
        (ref blocks name))))

(define (cfg-connect! graph source target)
  (let ((from (cfg-node graph source))
        (to (cfg-node graph target)))
    (vector-push! (ref from 'out) (ref to 'name))
    (vector-push! (ref to 'in) (ref from 'name))))

(define (make-loop id header reducible)
  (loop-data id header reducible #f (vector) (hashset) (hashset) 0 0))

(define (loop-add-child! parent child)
  (let ((id (ref child 'id)))
    (if (not (ref parent 'child-ids id))
        (begin
          (setf! (ref parent 'child-ids) id #t)
          (vector-push! (ref parent 'children) child)))))

(define (loop-set-parent! child parent)
  (setf! child 'parent parent)
  (loop-add-child! parent child))

(define (make-loop-graph)
  (let ((root (make-loop 0 #f #t)))
    (loop-graph root (vector root))))

(define (new-loop! graph header reducible)
  (let* ((loops (ref graph 'loops))
         (value (make-loop (vector-length loops) header reducible)))
    (vector-push! loops value)
    value))

(define (calculate-loop! value depth)
  (setf! value 'depth depth)
  (let ((children (ref value 'children)))
    (let visit ((i 0))
      (if (< i (vector-length children))
          (let ((child (ref children i)))
            (calculate-loop! child (+ depth 1))
            (setf! value 'nesting
                   (max (ref value 'nesting) (+ (ref child 'nesting) 1)))
            (visit (+ i 1)))))))

(define (calculate-nesting! graph)
  (let ((loops (ref graph 'loops)))
    (let visit ((i 1))
      (if (< i (vector-length loops))
          (let ((value (ref loops i)))
            (if (not (ref value 'parent))
                (loop-set-parent! value (ref graph 'root)))
            (visit (+ i 1))))))
  (calculate-loop! (ref graph 'root) 0))

(define (make-finder graph loops)
  (finder graph loops (vector) (vector) (hashmap) (vector) (vector) (vector) (vector)))

(define (find-set state number)
  (let find ((current number) (path '()))
    (let ((parent (ref state 'nodes current 'parent)))
      (if (= parent current)
          (begin
            (let compress ((path path))
              (if (pair? path)
                  (begin
                    (setf! (ref state 'nodes (car path)) 'parent current)
                    (compress (cdr path)))))
            current)
          (find parent (cons current path))))))

(define (dfs! state block-id number)
  (let ((nodes (ref state 'nodes))
        (numbers (ref state 'number))
        (lasts (ref state 'last)))
    (setf! nodes number (union-node number block-id number #f))
    (setf! numbers block-id number)
    (let ((targets (ref state 'cfg 'blocks block-id 'out)))
      (let visit ((i 0) (last number))
        (if (< i (vector-length targets))
            (let ((target (ref targets i)))
              (if (= (ref numbers target) UNVISITED)
                  (visit (+ i 1) (dfs! state target (+ last 1)))
                  (visit (+ i 1) last)))
            (begin
              (setf! lasts number last)
              last))))))

(define (find-loops! state)
  (let* ((graph (ref state 'cfg))
         (blocks (ref graph 'blocks))
         (size (vector-length blocks))
         (non-back (make-vector size #f))
         (back (make-vector size #f))
         (numbers (hashmap))
         (headers (make-vector size 0))
         (kinds (make-vector size NONHEADER))
         (lasts (make-vector size 0))
         (nodes (make-vector size #f)))
    (setf! state 'non-back non-back)
    (setf! state 'back back)
    (setf! state 'number numbers)
    (setf! state 'header headers)
    (setf! state 'kind kinds)
    (setf! state 'last lasts)
    (setf! state 'nodes nodes)
    (let initialize ((i 0))
      (if (< i size)
          (begin
            (setf! non-back i (hashset))
            (setf! back i (vector))
            (setf! numbers (ref blocks i 'name) UNVISITED)
            (initialize (+ i 1)))))
    (dfs! state (ref graph 'start 'name) 0)

    (let identify ((w 0))
      (if (< w size)
          (let ((node (ref nodes w)))
            (if (not node)
                (setf! kinds w DEAD)
                (let ((incoming (ref blocks (ref node 'block) 'in)))
                  (let edges ((i 0))
                    (if (< i (vector-length incoming))
                        (let* ((source (ref incoming i))
                               (v (ref numbers source)))
                          (if (not (= v UNVISITED))
                              (if (and (<= w v) (<= v (ref lasts w)))
                                  (vector-push! (ref back w) v)
                                  (setf! (ref non-back w) v #t)))
                          (edges (+ i 1)))))))
            (identify (+ w 1)))))

    (setf! headers 0 0)
    (let headers-loop ((w (- size 1)))
      (if (>= w 0)
          (let ((node-w (ref nodes w))
                (pool (vector))
                (pool-ids (hashset)))
            (if node-w
                (begin
                  (let step-d ((i 0) (preds (ref back w)))
                    (if (< i (vector-length preds))
                        (let ((v (ref preds i)))
                          (if (= v w)
                              (setf! kinds w SELF)
                              (let ((root (find-set state v)))
                                (if (not (ref pool-ids root))
                                    (begin
                                      (setf! pool-ids root #t)
                                      (vector-push! pool root)))))
                          (step-d (+ i 1) preds))))
                  (if (> (vector-length pool) 0) (setf! kinds w REDUCIBLE))
                  (let step-e ((at 0))
                    (if (< at (vector-length pool))
                        (let* ((x (ref pool at))
                               (x-number (ref nodes x 'number))
                               (pred-set (ref non-back x-number)))
                          (if (> (hashset-length pred-set) MAX-NON-BACK-PREDS)
                              (begin (displayn "too many non-back predecessors") (exit 1)))
                          (let visit-preds ((cursor (%iter pred-set)))
                            (%if/next! ((pred) cursor) (let* ((root (find-set state pred))
                                     (root-number (ref nodes root 'number)))
                                (if (not (and (<= w root-number)
                                              (<= root-number (ref lasts w))))
                                    (begin
                                      (setf! kinds w IRREDUCIBLE)
                                      (setf! (ref non-back w) root-number #t))
                                    (if (and (not (= root w))
                                             (not (ref pool-ids root)))
                                        (begin
                                          (setf! pool-ids root #t)
                                          (vector-push! pool root))))
                                (visit-preds cursor))))
                          (step-e (+ at 1)))))))
            (if (or (> (vector-length pool) 0) (= (ref kinds w) SELF))
                (let ((value (new-loop! (ref state 'loops)
                                        (ref node-w 'block)
                                        (not (= (ref kinds w) IRREDUCIBLE)))))
                  (setf! (ref value 'blocks) (ref node-w 'block) #t)
                  (setf! (ref nodes w) 'loop value)
                  (let collapse ((i 0))
                    (if (< i (vector-length pool))
                        (let* ((number (ref pool i))
                               (node (ref nodes number)))
                          (setf! headers (ref node 'number) w)
                          (setf! node 'parent w)
                          (if (ref node 'loop)
                              (loop-set-parent! (ref node 'loop) value)
                              (setf! (ref value 'blocks) (ref node 'block) #t))
                          (collapse (+ i 1)))))))
            (headers-loop (- w 1)))))))

(define (build-diamond! graph start)
  (cfg-connect! graph start (+ start 1))
  (cfg-connect! graph start (+ start 2))
  (cfg-connect! graph (+ start 1) (+ start 3))
  (cfg-connect! graph (+ start 2) (+ start 3))
  (+ start 3))

(define (build-straight! graph start length)
  (let loop ((offset 0))
    (if (< offset length)
        (begin
          (cfg-connect! graph (+ start offset) (+ start offset 1))
          (loop (+ offset 1)))
        (+ start length))))

(define (build-base-loop! graph start)
  (let* ((header (build-straight! graph start 1))
         (diamond1 (build-diamond! graph header))
         (middle (build-straight! graph diamond1 1))
         (diamond2 (build-diamond! graph middle))
         (footer (build-straight! graph diamond2 1)))
    (cfg-connect! graph diamond2 middle)
    (cfg-connect! graph diamond1 header)
    (cfg-connect! graph footer start)
    (build-straight! graph footer 1)))

(define (run)
  (let ((graph (make-cfg))
        (loops (make-loop-graph)))
    (cfg-node graph 0)
    (build-base-loop! graph 0)
    (cfg-node graph 1)
    (cfg-connect! graph 0 2)
    (find-loops! (make-finder graph loops))
    (let outer ((i 0) (n 2))
      (if (< i 10)
          (begin
            (cfg-node graph (+ n 1))
            (cfg-connect! graph 2 (+ n 1))
            (let middle ((j 0) (n (+ n 1)))
              (if (< j 10)
                  (let ((top n)
                        (n (build-straight! graph n 1)))
                    (let inner ((k 0) (n n))
                      (if (< k 5)
                          (inner (+ k 1) (build-base-loop! graph n))
                          (let ((bottom (build-straight! graph n 1)))
                            (cfg-connect! graph n top)
                            (middle (+ j 1) bottom)))))
                  (begin
                    (cfg-connect! graph n 1)
                    (outer (+ i 1) n)))))))
    (find-loops! (make-finder graph loops))
    (let repeat ((i 0))
      (if (< i 50)
          (begin
            (find-loops! (make-finder graph (make-loop-graph)))
            (repeat (+ i 1)))))
    (calculate-nesting! loops)
    (vector (vector-length (ref loops 'loops))
            (vector-length (ref graph 'blocks)))))

(let ((result (run)))
  (if (and (= (ref result 0) 1605) (= (ref result 1) 5213))
      (displayn "ok")
      (begin
        (display "verify failed: ")
        (displayn result)
        (exit 1))))
